### ISSUE TITLE
This tutorial requires the Azure Tools extension

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-dev-docs#10]
One of the requirements of this tutorial is using the Azure Tools VSCode extension but it's not listed as one of the tools to install.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6a3f99-4725-7f93-301e-da4ba69d4986
* Version Independent ID: 3477aa24-7135-e6e9-3791-17d66052589e
* Content: [Create and deploy serverless Azure Functions in Python with Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-01#azure-subscription)
* Content Source: [python/tutorial-vs-code-serverless-python-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-vs-code-serverless-python-01.md)
* Service: **azure-functions**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@FISHMANPET Well, the Azure Tools extension pack isn't technically required: it's a collection of all the other Azure extensions. For the Functions walkthrough, you need only the Azure Functions extension, which is what's listed. Are you saying that another Azure extension is needed? 

In any case, I'll add a note that Azure Functions is included with the Azure Tools extension pack.

**Comment by kraigb** [comment]
It does sound like a reload of VS Code issue, because that icon should appear after installing any of the individual Azure extensions (Functions, App Service, Storage, etc.). Do try it fresh and let me know what you find.

**Comment by FISHMANPET** [comment]
I played around with this just now.  Here's what I did:
1) Removed `%AppData%\Code`
2) Removed `%UserProfile\.vscode`
3) Launched Code
4) Installed Python Extension and Azure Functions extension as explained in the tutorial (which automatically installed Azure Account for login)
At this point the Azure icon appeared as expected in the Activity bar, and I was signed into Azure (not sure why, my local session was logged in with `az login` and/or `Connect-AzAccount`).  I used the  Command Palette and Azure: Sign Out to sign out, which I think would place me in the state of a brand new user who had just installed VSCode and installed the extensions.  At that point my window looks like this:
![image](https://user-images.githubusercontent.com/7810151/66079764-55a87000-e52a-11e9-890f-b7a0c45027bb.png)
Which is slightly different from what's show in the screenshot.  If I install another extension then my screen starts to look like the screenshots in the Tutorial.  So it appears that if you have only one Azure extension installed, there's no "Azure" heading, there's just a (in my case) "Azure Functions".  The screenshots were taken with the full Azure Tools (or at least an additional Azure) extension installed, which changes the UI from what someone would see if they've just installed only the extensions given in the tutorial.

I probably never would have noticed this if my Extension installation had worked without requiring a reload, and I'm not sure if it would add more confusion to change the screenshots and/or include a lot of extra wording about how the UI may be slightly different.  I was able to navigate the UI just fine, and I would expect anyone who's at the level of developing Azure Functions should be able to figure out slight tweaks to the UI.

**Comment by kraigb** [comment]
Thanks for checking the details! Yes, I know that having one extension installed shows a UI with Azure Functions or Azure Storage or Azure App Service, and that the UI shown is what you see with multiple extensions installed. It ends up that way because I'm using a shared piece of docs source for the sign-in part across multiple tutorials, and it's simpler to keep them all the same rather than have screenshots for each variation (and having to explain those variations). I'm glad you confirmed that it's not confusing. :) Developers are smart people and I figured they'd work it out!

**Comment by Rodrigossz** [comment]
Close and Open VS Code, and it will work. :)
