### ISSUE TITLE
Example for Managed Identities needs improvement

### ISSUE THREAD

**Issue by mleidecker** [MicrosoftDocs/azure-dev-docs#100]
Hi,

die example for the Managed Identites has a typo.

It should be:
"for resource_group in client.resource_groups.list():"

instead of:
"for resource_group in resource_client.resource_groups.list():"

It would also be great if you give an example how to reference the Managed Identity as it can be passed in the constructor of:

# Create MSI Authentication
credentials = MSIAuthentication()

like:
# Create MSI Authentication
credentials = MSIAuthentication(client_id = '')

best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef339a7-5fdc-2ab4-fcf4-00faa27c54b9
* Version Independent ID: 664eb028-888d-a543-cd8a-b3254f919da2
* Content: [Authenticate apps using the Azure management libraries for Python](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-authenticate#feedback)
* Content Source: [python/python-sdk-azure-authenticate.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/python-sdk-azure-authenticate.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@mleidecker Thanks for the details; I'm working on a revision to that article. No definite ETA yet, though.

**Comment by kraigb** [comment]
@mleidecker Update: I have the revised article in review, which actually removes the MSIAuthentication code in favor of using DefaultAzureCredential. Here's what the code in that section looks like (using a Key Vault SecretClient for the example, which is taken from a longer walkthrough that I'm working on):

> import os
> from azure.identity import DefaultAzureCredential
> from azure.keyvault.secrets import SecretClient
> 
> # Obtain the Managed Identity credential object
> credential = DefaultAzureCredential()
> 
> # Create the client object to access Key Vault secrets. Instantiating the object
> # fails if the service principal is not authorized to access the Key Vault.
> vault_url = os.environ["KEY_VAULT_URL"]
> secret_client = SecretClient(vault_url=vault_url, credential=credential)
> 
> # Retrieve a secret value. The operation fails if the service principal is not
> # further authorized for the operation in question.
> retrieved_secret = client.get_secret("secret-name-01")
> 

I'll let you know when the new article is published, at which point I'll be closing this issue.

**Comment by kraigb** [comment]
Auth article has been updated now on https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=bash, covering Managed Identity among other things.
