### ISSUE TITLE
Confused about the two steps.

### ISSUE THREAD

**Issue by CapitaineNemo** [MicrosoftDocs/azure-dev-docs#1001]
![image](https://user-images.githubusercontent.com/25415402/209896050-539f4de9-8b0b-4043-a6d5-78fccdc94570.png)

What are the two step differences?
One is "Run the function locally" and one is "Execute the function locally"

**Comment by KarlErickson** [comment]
@diberry this is for <https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-azure-cloud-python-etl-02-get-data>

**Comment by diberry** [comment]
@CapitaineNemo A PR is in progress now. 

Step 3: Start the function app locally in Visual Studio Code by pressing `F5` or the play icon.
Step 4: Call the API from Visual Studio Code.
Step 5: Add the API body by entering the request message body value `{ "name": "<YOUR_NAME>"}` and press Enter.

Does this clarify the steps?

**Comment by diberry** [comment]
This article series has been refreshed for clarity, including this step. The updates will be available within 24 hours. If, after reviewing the updated information, you are still unsure of the correct step in this issue, please reopen this issue.
