### ISSUE TITLE
Confused about wording "Open the folder msdocs-cloud-python-etl-proj created by the Azure Function Core Tools in Visual Studio Code."

### ISSUE THREAD

**Issue by CapitaineNemo** [MicrosoftDocs/azure-dev-docs#1002]
![image](https://user-images.githubusercontent.com/25415402/209913505-29826000-5c5c-4307-b07f-e23c21d3f8c9.png)
In the sample code  key_vault_secret.py is stored in the shared folder that created manually. 

Can it be more clear in the guide?

**Comment by KarlErickson** [comment]
@diberry this is for <https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-azure-cloud-python-etl-02-get-data>

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
This article series has been refreshed for clarity, including this step. The updates will be available within 24 hours. If, after reviewing the updated information, you are still unsure of the correct step in this issue, please reopen this issue.
