### ISSUE TITLE
Confused about the step in Tutorial "Process data using Python Azure Function"

### ISSUE THREAD

**Issue by CapitaineNemo** [MicrosoftDocs/azure-dev-docs#1006]
https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-azure-cloud-python-etl-03-process-data

![image](https://user-images.githubusercontent.com/25415402/210176464-1733fe3a-159c-4cd5-a9b2-9db26ac1bbe4.png)
Actually in my VSCode screen, I cannot find function. 
![image](https://user-images.githubusercontent.com/25415402/210176498-d36ccffc-6a5c-41f9-9d26-224ed5bce517.png)
If it is a key I need to choose, which key ?

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
This article series has been refreshed for clarity, including this step. The updates will be available within 24 hours. If, after reviewing the updated information, you are still unsure of the correct step in this issue, please reopen this issue.

**Comment by CapitaineNemo** [comment]
@diberry  I still cannot get it.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/25415402/210753615-8defbea7-d732-41ad-bc1d-9fa9f88b5ea6.png">
