### ISSUE TITLE
Deprecated Terraform resource in Azure VMSS example: azurerm_virtual_machine_scale_set

### ISSUE THREAD

**Issue by akiskips** [MicrosoftDocs/azure-dev-docs#1007]
The azurerm_virtual_machine_scale_set resource used in this example has been deprecated in favour of the [azurerm_linux_virtual_machine_scale_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set) and [azurerm_windows_virtual_machine_scale_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine_scale_set) resources. W

Link to Terraform registry: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 560d5902-d21c-a085-86a2-3189dde5d76c
* Version Independent ID: 7c19fad6-c65a-847d-a98c-0f9c9e4c6217
* Content: [Create an Azure virtual machine scale set using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-hcl?source=docs)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-scaleset-network-disks-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
