### ISSUE TITLE
Missing configuration for output destination in application.properties

### ISSUE THREAD

**Issue by JMayrbaeurl** [MicrosoftDocs/azure-dev-docs#101]
Spring Boot configuration in 'application.properties' is missing the following line (otherwise crashes on context creation):

spring.cloud.stream.bindings.output.destination=wingtiptoyshub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f82b124-deb4-9ae4-21de-8d0e5f8ca302
* Version Independent ID: 515ca402-b5bb-85a7-99c1-1459e2ac4871
* Content: [How to create a Spring Cloud Stream Binder application with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub#feedback)
* Content Source: [java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@seanli1988 - Sean would you please forward to the appropriate contact and assign? Adding @KarlErickson for editorial support. Thanks.

**Comment by KarlErickson** [comment]
Thanks @JMayrbaeurl - I've just merged this fix.
