### ISSUE TITLE
Code Sample is OutDated

### ISSUE THREAD

**Issue by PraveenGangula1392** [MicrosoftDocs/azure-dev-docs#1012]
[Enter feedback here]

Hi Team,
Can you provide code sample for current version of flutter. The are compile time issues with kotlin versions.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94b0eeab-4627-9795-8d11-16187ea82d6c
* Version Independent ID: 963a4858-9631-c1a7-b4ef-e74f74bf95e6
* Content: [Send push notifications to Flutter apps using Azure Notification Hubs via a backend service](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-flutter)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-flutter.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-flutter.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
