### ISSUE TITLE
Docs recommend using a github action deprecated before the latest update

### ISSUE THREAD

**Issue by fuzzzerd** [MicrosoftDocs/azure-dev-docs#1017]
Action deprecated in September 2022: https://github.com/microsoft/variable-substitution/commit/5d24b045312c1e1773f86f35c1f6b80401c0f221#comments with no replacement specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f48a84-dcf9-e852-3f3c-703382971875
* Version Independent ID: ffe51d31-19c8-f4c3-0d31-dc154e414a59
* Content: [Use variable substitution with GitHub Actions for Azure](https://learn.microsoft.com/en-us/azure/developer/github/github-variable-substitution)
* Content Source: [articles/github/github-variable-substitution.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-variable-substitution.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thank you for reporting this. Unfortunately there's no alternative action currently. I'll work on retiring the article.
