### ISSUE TITLE
terraform fails 

### ISSUE THREAD

**Issue by rjain15** [MicrosoftDocs/azure-dev-docs#1018]
Error

╷
│ Error: Invalid function argument
│ 
│   on main.tf line 55, in resource "azurerm_kubernetes_cluster" "k8s":
│   55:       key_data = file(var.ssh_public_key)
│     ├────────────────
│     │ while calling file(path)
│     │ var.ssh_public_key is "id_rsa.pub"
│ 
│ Invalid value for "path" parameter: no file exists at "id_rsa.pub"; this function works only with files that are distributed as part of the configuration source code, so if this file
│ will be created by a resource in this configuration you must instead obtain this result from an attribute of that resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Quickstart: Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@rjain15 I've rewritten this code sample and it will publish next week.
