### ISSUE TITLE
[Bug Report] Docker --password-stdin command doesn't work

### ISSUE THREAD

**Issue by glaucia86** [MicrosoftDocs/azure-dev-docs#102]
**Link:** [https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-docker-node-02](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-docker-node-02 )

In the step 7 asked to use the command:

**> docker login .azurecr.io -u --password-stdin** 

![image](https://user-images.githubusercontent.com/1631477/77378186-12e68880-6d54-11ea-8ea0-cc365e190d12.png)

But using the other script (that is not too much secure – works fine): 

**> docker login .azurecr.io -u -p**

![image](https://user-images.githubusercontent.com/1631477/77378173-06fac680-6d54-11ea-9098-515e3f8532ba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861f9ddd-e95f-8025-b312-7a3c6a97dfe3
* Version Independent ID: cec6249d-6aec-c15c-9cc6-76b0518203dc
* Content: [Use a container registry from Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-docker-node-02)
* Content Source: [javascript/tutorial-vscode-docker-node-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-docker-node-02.md)
* Product: **azure-nodejs**
* GitHub Login: @btholt
* Microsoft Alias: **brholt**

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
@glaucia86 I don't see step 7 or the exact mention of docker login. Are you sure this is the page you mean to reference or was VSCode having an issue that you determined was the under the covers docker login?

**Comment by diberry** [comment]
Found [doc](https://docs.microsoft.com/en-us/azure/developer/javascript/node-howto-e2e). Testing now.

**Comment by diberry** [comment]
@glaucia86  When using --stdin, you do not also pass in the password directly after, as part of the single docker login command. The secure behavior is to not pass in a password. You can have the same goal when you only pass in user name, because you will be prompted for the password. 

As you have discovered, you can also send in the password with the command. 

Closing this issue for now. #please-close
