### ISSUE TITLE
Performing terraform plan and access_key 

### ISSUE THREAD

**Issue by ZerNox** [MicrosoftDocs/azure-dev-docs#1021]
There are some references to ARM_ACCESS_KEY and that this needs to be done manually to be able to access the remote state
But when perform `az login` it seems to be enough to execute terraform commands  

`terraform init`
`terraform plan`

With the prerequisite is that it is defined in backend "azurerm"
This means that I have never set the storage key this is sorted in azure somehow...

How does this work? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Store Terraform state in Azure Storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ZerNox Thanks for your question. Here's a link to an article detailing [authenticating to Azure](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs).
