### ISSUE TITLE
[Java/Spring Cloud][Docs] AAD docs example no longer works with Spring Boot 3

### ISSUE THREAD

**Issue by anno1985** [MicrosoftDocs/azure-dev-docs#1026]
The [Spring Boot Starter for Azure Active Directory developer's guide](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md#protect-a-resource-serverapi) ([live](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide#protect-a-resource-serverapi)) uses `AadResourceServerWebSecurityConfigurerAdapter` in an example (step 3), which [extends](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/AadResourceServerWebSecurityConfigurerAdapter.java#L27) `WebSecurityConfigurerAdapter`.

`WebSecurityConfigurerAdapter` was removed in [Spring Boot 3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes#third-party-library-upgrades)/[Spring Security 6.0](https://docs.spring.io/spring-security/reference/whats-new.html) ([gh-11923](https://github.com/spring-projects/spring-security/pull/11923)).

Migration guides:
* https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#_publish_a_securityfilterchain_bean
* https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
* https://www.baeldung.com/spring-deprecated-websecurityconfigureradapter

Could you please provide an updated example that's compatible with Spring Boot 3.x?

**Comment by moarychan** [comment]
Hi @anno1985 , thanks for your feedback!

We have started to support the Spring Boot 3 with beta support, the latest version is [6.0.0-beta.4](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-dependencies/6.0.0-beta.4) and the [changelog ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#600-beta4-2022-12-07). 

We change the major version number from `6` to `5`, the 5.0.0 GA version is coming this week, but the Spring Security support may have breaking changes in the future and is not ready to announce the GA, so the doc and samples are not updated in sync. You can temporarily refer to [the sample](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure-v6.0.0-beta.4/aad/spring-cloud-azure-starter-active-directory/aad-web-application-and-resource-server/src/main/java/com/azure/spring/sample/aad/security/AadWebApplicationAndResourceServerConfig.java#L21) to use it. In 5.0.0, some class paths should be changed in your application.

**Comment by anno1985** [comment]
Hi @moarychan, thank you for your prompt reply and the example! 

Quick question, though: what do you mean by "some class paths should be changed"? Aren't maven/gradle going to take care of that? Or do you mean imports, because packages in Spring and/or spring-azure-cloud change? :-)

**Comment by fangjian0423** [comment]
@anno1985 Some packages in Spring Cloud Azure changed in 5.0 major version, see the [change log](https://github.com/Azure/azure-sdk-for-java/blob/release/spring-cloud-azure-6.0.0/sdk/spring/CHANGELOG.md#600-2023-01-10) (as @moarychan mentioned before, the version number in change log will change from 6 and 5).

**Comment by anno1985** [comment]
Thanks, @fangjian0423. Is there an ETA (days/weeks/months) for the Spring Security support? Or a way to get notified once it's available? :-)

**Comment by moarychan** [comment]
@anno1985 , no, the ETA has not been specified yet, you can follow the [release history ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md) or [developer guide](https://aka.ms/spring/msdocs/developer-guide) to get notified.

Although we are not ready for Spring Security GA support, the auto-configure function of Spring Security is still available in 5.0.0, but there will be more breaking changes in the future.

**Comment by anno1985** [comment]
The package I was waiting for showed up on mvnrepository's search about a day after my last comment (and the main package's release), so I got everything I need. Thanks! :-)
@KarlErickson  how does this work? Do I simply close the ticket, or do you still need it until the docs are eventually updated?

**Comment by KarlErickson** [comment]
@anno1985 I'll close it. Thanks!
