### ISSUE TITLE
Support for SQL Managed Instance

### ISSUE THREAD

**Issue by shanchatterjee** [MicrosoftDocs/azure-dev-docs#1033]
Does this documentation apply to Azure Managed Instance ?
I am not able to use GitHub action to deploy to Azure SQL MI.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53b5e33c-f80d-a9b9-b8d9-39e53f1b46ad
* Version Independent ID: c9fa279e-f6d0-534e-3fec-032c1d06697b
* Content: [Deploy databases from GitHub to Azure](https://learn.microsoft.com/en-us/azure/developer/github/database-actions-deploy)
* Content Source: [articles/github/database-actions-deploy.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/database-actions-deploy.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I'm not able to connect to Azure Managed Instance either. I always get the message, `Error: Unable to get details of SQL server server-name. No SQL servers were found in the subscription.` I'll add a note to the article.
