### ISSUE TITLE
Information missing regarding azuread_group

### ISSUE THREAD

**Issue by acarrere184** [MicrosoftDocs/azure-dev-docs#1036]
The documentation propose to add the following block into the `output.tf` file:

    output "AVD_user_groupname" {
      description = "Azure Active Directory Group for AVD users"
      value       = azuread_group.aad_group.display_name
    }

But there is no mention of `azuread_group` in the `main.tf` file. And there is no information on how to assign a user or a group to a `azurerm_virtual_desktop_application_group`

Just copy pasting the example will result in an error: `Reference to undeclared resource`

**Comment by TomArcherMsft** [comment]
@acarrere184 The content information that identifies the article was lost in your GitHub Issue. Which AVD article are you referring to?

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
