### ISSUE TITLE
.app.config.tsx does not exist

### ISSUE THREAD

**Issue by rdick** [MicrosoftDocs/azure-dev-docs#1037]
I am running through the tutorial for Azure Notification Hub but when I follow this 

After updating the scripts with

` "configure": "cp .app.config.tsx src/config/AppConfig.tsx"`

I run this
`yarn configure`

And get this error
`cp: .app.config.tsx: No such file or directory`

Where do I get .app.config.tsx?

I feel like this should be more bullet proof?

**Comment by diberry** [comment]
@rdick - can you provide a link to the doc?

**Comment by KarlErickson** [comment]
Looks like it's *mobile-apps\includes\notification-hubs-backend-service-sample-app-react-native.md*.

**Comment by KarlErickson** [comment]
@mikeparker104 this include file is used by *mobile-apps\notification-hubs-backend-service-react-native.md*.

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
