### ISSUE TITLE
Incomplete documentation about storage account access 

### ISSUE THREAD

**Issue by TUSHPATT** [MicrosoftDocs/azure-dev-docs#1038]
It doesn't tell if someone wants to access using SAS token. It also doesn't tell how to construct sign-in string to connect to storage account. Simply account key is not working, it is complaining sign in string do not match 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [Spring Cloud Stream with Azure Event Hubs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi @yiliuTo, please help to handle this issue.

**Comment by yiliuTo** [comment]
Hi @TUSHPATT thanks for reporting this issue. We will fix the doc soon by adding the missing content about how to use kinds of credentials for Storage connection. And currently, you can refer to our [reference doc](https://learn.microsoft.com/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#sending-and-receiving-messages-fromto-event-hubs) for how to establish the connection.

**Comment by KarlErickson** [comment]
Doc has been updated.
