### ISSUE TITLE
Error after the Plan Command

### ISSUE THREAD

**Issue by adrobson** [MicrosoftDocs/azure-dev-docs#1039]
I get the following error after the plan command:

Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14080c3b-027f-93e1-fd0f-4bea971f51b0
* Version Independent ID: 5894d6ec-4347-153c-fa9a-203d41275153
* Content: [Install the Azure Terraform Visual Studio Code extension](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-vs-code-extension-for-terraform?tabs=azure-cli)
* Content Source: [articles/terraform/configure-vs-code-extension-for-terraform.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-vs-code-extension-for-terraform.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@arob98 Thanks for the feedback! Apologies for this issue taking so long to resolve. We're in the process of implementing a new testing pipeline, so issues like this will be caught much quicker going forward. I've updated the article and it should go live by tomorrow afternoon (PST).
