### ISSUE TITLE
terraform plan Error: Insufficient features blocks

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/azure-dev-docs#1040]
This $ terraform plan fails with below error :
╷
│ Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.

Probably you need to add 

provider "azurerm" {
   features {}
}

into the main.tf file?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14080c3b-027f-93e1-fd0f-4bea971f51b0
* Version Independent ID: 5894d6ec-4347-153c-fa9a-203d41275153
* Content: [Install the Azure Terraform Visual Studio Code extension](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-vs-code-extension-for-terraform?source=recommendations&tabs=azure-cli)
* Content Source: [articles/terraform/configure-vs-code-extension-for-terraform.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-vs-code-extension-for-terraform.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Thanks @ctahok. This article has been updated and should publish by tomorrow afternoon (PST).
