### ISSUE TITLE
Error: Missing required argument on main.tf line 14, in module "network":

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/azure-dev-docs#1041]
$ terraform plan -out main.tfplan
╷
│ Error: Missing required argument
│
│   on main.tf line 14, in module "network":
│   14: module "network" {
│
│ The argument "use_for_each" is required, but no definition was found.
╵

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df42c6c6-f4e0-072f-3fca-e3d97ccfe261
* Version Independent ID: da6a6e53-0803-3692-85cb-9a77fc231946
* Content: [Configure an Azure VM cluster using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-module)
* Content Source: [articles/terraform/create-vm-cluster-module.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-cluster-module.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ctahok Thanks for the feedback! I've rewritten this sample and the article should publish early next week.
