### ISSUE TITLE
"allow_blob_public_access" variable should be renamed to "allow_nested_items_to_be_public" (in "azurerm_storage_account" resource example)

### ISSUE THREAD

**Issue by kantorv** [MicrosoftDocs/azure-dev-docs#1052]
Current version, which uses `allow_blob_public_access` (in "2. Configure remote state storage account" section), throwing an error  while performing `terraform plan`.
As mentioned here: [https://www.hashicorp.com/blog/terraform-azurerm-3-0-brings-enhanced-azure-function-support](https://www.hashicorp.com/blog/terraform-azurerm-3-0-brings-enhanced-azure-function-support)
it should be renamed  to `allow_nested_items_to_be_public`,
```bash
$ terraform plan
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 18, in resource "azurerm_storage_account" "tfstate":
│   18:   allow_blob_public_access = false
│ 
│ An argument named "allow_blob_public_access" is not expected here.
```

provider version:

```hcl
terraform {
  required_version = "~>1.3.7"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.42.0"
    }
  }
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Store Terraform state in Azure Storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=terraform)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
