### ISSUE TITLE
Error: Reference to undeclared resource

### ISSUE THREAD

**Issue by ctahok** [MicrosoftDocs/azure-dev-docs#1054]
Error: Reference to undeclared resource
│
│   on output.tf line 28, in output "AVD_user_groupname":
│   28:   value       = azuread_group.aad_group.display_name
│
│ A managed resource "azuread_group" "aad_group" has not been declared in the root module.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0a97cf-1514-889c-edbc-9c10bd566231
* Version Independent ID: 3a0a97cf-1514-889c-edbc-9c10bd566231
* Content: [Configure Azure Virtual Desktop using Terraform - Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop)
* Content Source: [articles/terraform/configure-azure-virtual-desktop.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-azure-virtual-desktop.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close

**Comment by ctahok** [comment]
The more feedbacks I give the more they don't get closed without resolution. 
I will not give any more feedbacks as they are pointless.
