### ISSUE TITLE
Error: Insufficient features blocks

### ISSUE THREAD

**Issue by faustinopalma** [MicrosoftDocs/azure-dev-docs#1055]
The terraform example in this documentation, used with the current Terraform version, gives the error:
```
│ Error: Insufficient features blocks
│ 
│   on <empty> line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
```

This issue is solved by adding a **providers.tf** file with the following code:

```
terraform {

  required_version = ">=0.12"
  
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.97.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

This snippet is taken from another example on the Azure documentation (namely the example on Application Gateway v2).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14080c3b-027f-93e1-fd0f-4bea971f51b0
* Version Independent ID: 5894d6ec-4347-153c-fa9a-203d41275153
* Content: [Install the Azure Terraform Visual Studio Code extension](https://learn.microsoft.com/en-us/azure/developer/terraform/configure-vs-code-extension-for-terraform?tabs=azure-cli)
* Content Source: [articles/terraform/configure-vs-code-extension-for-terraform.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-vs-code-extension-for-terraform.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@faustinopalma Thanks for the feedback! I've added the missing file and the article should republish tomorrow.
