### ISSUE TITLE
Really good ! But missing just one parameter in the application.yaml (connection-string) to be just perfect ! 

### ISSUE THREAD

**Issue by antaramad** [MicrosoftDocs/azure-dev-docs#1069]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25596474-8a16-dcf6-e9a9-09ca23c905a9
* Version Independent ID: 9c1525d4-c8fe-f585-8f27-667291a58fd0
* Content: [Spring Cloud Stream with Azure Service Bus](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus#fd)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **seal**

**Comment by KarlErickson** [comment]
@seanli1988 can you take a look? Thanks!

**Comment by yiliuTo** [comment]
Hi @antaramad , thanks for reaching us! We will fix it soon.
Besides, this article is designed to recommand connecting to Service Bus in a passwordless way, so we don't intend to document how to configure connection-string as the credential, instead, we will introduce using the local credential in your Azure CLI environment to establish the connection.
Before our fix gets released, you can try the passwordless connection by applying the following step:
1. run `az login` in your terminal to setup your account permissions locally.
2. replace the property `spring.cloud.azure.servicebus.connection-string` with `spring.cloud.azure.servicebus.namespace`
3. assign the [Azure Service Bus Data Sender](https://review.learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles.md#azure-service-bus-data-sender) and [Azure Service Bus Data Receiver](https://review.learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles.md#azure-service-bus-data-receiver) roles to the Azure AD account you're currently using. See [Assign Azure roles using the Azure portal](https://review.learn.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal).

**Comment by antaramad** [comment]
Yes I tried it to and it's working too. Thanks for your recommendations.
