### ISSUE TITLE
Can't find where to configure partition key in code example?

### ISSUE THREAD

**Issue by JonnewDev-blip** [MicrosoftDocs/azure-dev-docs#107]
When I run the example it fails with error,

Gremlin Query Execution Error: Cannot add a vertex where the partition key property has value 'null'
Seems I need to configure a partition key somewhere but I can't find where to do it or set up Cosmos Db without a partition key which is a deprecated setup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 027365fa-060a-d121-194a-d0b7d308e49c
* Version Independent ID: 70952df9-d97e-7d22-671e-917021b78835
* Content: [How to use the Spring Data Gremlin Starter with the Azure Cosmos DB SQL API](https://docs.microsoft.com/en-US/azure/java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db#feedback)
* Content Source: [java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-data-gremlin-java-app-with-cosmos-db.md)
* Service: **cosmos-db**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@selvasingh - Would you please forward to the appropriate contact.

cc: KarlErickson

**Comment by JonnewDev-blip** [comment]
Perhaps this could be related to my issue, https://github.com/microsoft/spring-data-gremlin/issues/232

**Comment by KarlErickson** [comment]
@JonnewDev-blip the topic has now been updated. Thanks again for the feedback!
