### ISSUE TITLE
invalid terraform code Fails to compile

### ISSUE THREAD

**Issue by sekhemrekhutawysobekhotep** [MicrosoftDocs/azure-dev-docs#1070]
you have duplicate resource names in outline for file

variables.tf

current bad  _____________________________________

variable "resource_group_name" {
   description = "Name of the resource group in which the Packer image  will be created"
   default     = "myPackerImages"
}

variable "resource_group_name" {
   description = "Name of the resource group in which the resources will be created"
   default     = "myResourceGroup"
}

above fails during `terraform plan` ...   instead it should be __________________________________________

variable "managed_image_resource_group_name" {
   description = "Name of the resource group in which the Packer image  will be created"
   default     = "myPackerImages"
}

variable "resource_group_name" {
   description = "Name of the resource group in which the resources will be created"
   default     = "myResourceGroup"
}

Please fix this bug

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4371abd-f9cc-1ee9-1ed3-a5f0488740ce
* Version Independent ID: 14c6cf0f-ec32-15ed-cb38-8eb5860d858e
* Content: [Create an Azure virtual machine scale set from a Packer custom image by using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-using-packer-hcl?source=docs)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sekhemrekhutawysobekhotep Thanks for the feedback. I've removed the dupe from the variables.tf file. Once the product group merges the fix, it will go live (sometime next week).
