### ISSUE TITLE
Stop presenting use of Terraform legacy splat expressions

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/azure-dev-docs#1080]
On this page, and perhaps others too, there are Terraform code examples which use the legacy splat expressions.
Those uses are also reported by [tflint ](https://github.com/terraform-linters/tflint).

For example

```hcl
virtual_machine_id         = azurerm_windows_virtual_machine.avd_vm.*.id[count.index]
```

like in this snippet

```hcl
resource "azurerm_virtual_machine_extension" "domain_join" {
  count                      = var.rdsh_count
  name                       = "${var.prefix}-${count.index + 1}-domainJoin"
  virtual_machine_id         = azurerm_windows_virtual_machine.avd_vm.*.id[count.index]
...
```

It would be helpful if those examples are updated to use current and recommended syntax.

### References

- https://developer.hashicorp.com/terraform/language/expressions/splat#legacy-attribute-only-splat-expressions
- https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md#splat-operators
- https://github.com/terraform-linters/tflint-ruleset-terraform/blob/main/docs/rules/terraform_deprecated_index.md

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 954f37c7-64b8-759a-6f67-20d7847a9a85
* Version Independent ID: 954f37c7-64b8-759a-6f67-20d7847a9a85
* Content: [Configure Azure Virtual Desktop Session Hosts using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host)
* Content Source: [articles/terraform/create-avd-session-host.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-avd-session-host.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@mloskot Thanks for the feedback. We are currently implementing an e2e testing pipeline for Terraform samples to minimize breaking changes introduced with new Terraform releases. As part of that rollout, we are fixing issues like the one you mention ("splatting") across all the samples.

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
