### ISSUE TITLE
Java code in doc:Use Spring Data JDBC with Azure Database for MySQL is not correct.

### ISSUE THREAD

**Issue by backwind1233** [MicrosoftDocs/azure-dev-docs#1082]
[Enter feedback here]
The three pages have the same issue,
1. [Use Spring Data JDBC with Azure Database for MySQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless&pivots=mysql-passwordless-flexible-server)
2. [Use Spring Data JDBC with Azure Database for PostgreSQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless&pivots=postgresql-passwordless-flexible-server)
3. [Use Spring Data JDBC with Azure SQL Database](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server?tabs=passwordless)

Use this doc: [Use Spring Data JDBC with Azure Database for MySQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless&pivots=mysql-passwordless-flexible-server) to describe the issue.

In the section: [configure-spring-boot-to-use-azure-database-for-mysql ](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless&pivots=mysql-passwordless-flexible-server#configure-spring-boot-to-use-azure-database-for-mysql)

<img width="769" alt="image" src="https://user-images.githubusercontent.com/4465723/222615513-f1e06e2c-9bc4-41f2-91f9-981f03fd311d.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d253625-4caa-d771-7bee-fee6efe49bb8
* Version Independent ID: 342215bb-0060-4702-cb78-e1821a133242
* Content: [Use Spring Data JDBC with Azure Database for MySQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless&pivots=mysql-passwordless-flexible-server)
* Content Source: [articles/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql.md)
* Service: **mysql**
* GitHub Login: @KarlErickson
* Microsoft Alias: **v-yonghuiye**

**Comment by KarlErickson** [comment]
@backwind1233 thanks for letting us know about these problems!

@hui1110 I've added the missing quote and the missing "r". Could you please determine the correct fix for the "toList" issue, and file a PR to make the update? Thanks!

**Comment by hui1110** [comment]
@KarlErickson Fixing changes have been added to this [PR](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4216/commits/f58497e7fd057357761816691a38e01d17153afb).

**Comment by KarlErickson** [comment]
@backwind1233 @hui1110 closing. The PR that includes the code fix is in the editorial queue, ETA 3/17.
