### ISSUE TITLE
An example with a controller classs

### ISSUE THREAD

**Issue by Barbieri1981** [MicrosoftDocs/azure-dev-docs#1085]
Hi,

Do you have an example using a controller?
So, I can execute some endpoint and produce some events inside de event broken. 

regards,
Santiago

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [Spring Cloud Stream with Azure Event Hubs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub?toc=%2Fazure%2Fevent-hubs%2FTOC.json)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@chenrujun do you have any suggestions? Thanks!

**Comment by Barbieri1981** [comment]
Yes, If you want you can check my project 
https://github.com/Barbieri1981/azure_event_hubs/tree/main/ms-producer
It is based on Microsoft documentation.

**Comment by chenrujun** [comment]
Hi, @Barbieri1981 
Thanks for reaching out. We will look into it soon.

**Comment by saragluna** [comment]
Thanks for the suggestion, but for now we will keep the doc as is to better illustrate the core part of messaging processing. You can refer to https://aka.ms/spring/samples for more samples.

**Comment by saragluna** [comment]
#please-close
