### ISSUE TITLE
Casing for configurationsetting is wrong 

### ISSUE THREAD

**Issue by jkommeren** [MicrosoftDocs/azure-dev-docs#1089]
"AzureAD" in settings json should be "AzureAd". This gave me issues on azure app service for Linux (AzureAD__ClientId did not work, AzureAd__ClientId did)
This Ad casing is also in the documentation.

Please adjust! 

Other than that great tutorial!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Version Independent ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Content: [Add authentication to your .NET MAUI app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication?pivots=vs2022-windows)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Thanks for the report - PR in progress to fix this.

**Comment by adrianhall** [comment]
PR merged and will be in the next docs release.

#please-close
