### ISSUE TITLE
Outdated "Add federated credentials (preview)" section for Azure CLI

### ISSUE THREAD

**Issue by mderriey** [MicrosoftDocs/azure-dev-docs#1090]
The page currently resorts to `az rest` to add the federated credential.

At the time of raising this, Azure CLI (2.45.0) has native support for this through the [`az ad app federated-credential create` command](https://learn.microsoft.com/en-us/cli/azure/ad/app/federated-credential?view=azure-cli-latest#az-ad-app-federated-credential-create).
Using the [sample from the official docs](https://learn.microsoft.com/en-us/cli/azure/ad/app/federated-credential?view=azure-cli-latest#az-ad-app-federated-credential-create-examples) would be good to show how to do this.

We didn't do it through an external JSON file as the payload was dynamic, and we had to deal with escaping quotes, which you may not want to get into in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#add-federated-credentials-preview)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks, this is now updated. 

#please-close
