### ISSUE TITLE
Completar los tutoriales y hacer demostraciones

### ISSUE THREAD

**Issue by santiago-cortes-ortiz** [MicrosoftDocs/azure-dev-docs#1098]
Seria bueno mostrar los tutoriales muchos mas completos porque se queda corto, por ejemplo el tutorial de Survey, comienza chevere pero se queda sin poder probar con un token al backend API. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8424d3f-b681-56b5-8384-b3cdfd5f2585
* Version Independent ID: a8424d3f-b681-56b5-8384-b3cdfd5f2585
* Content: [Secure your REST API using Spring Cloud Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/secure-your-restful-api-using-spring-cloud-azure)
* Content Source: [articles/java/spring-framework/secure-your-restful-api-using-spring-cloud-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/secure-your-restful-api-using-spring-cloud-azure.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi, @santiago-cortes-ortiz 
Thanks for reaching out. We will consider to update the doc.
For now, you can refer to this sample: https://github.com/Azure-Samples/azure-spring-boot-samples/blob/d65ab5cd33374e7d11f8fcd421bb5f465fd4a05a/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-resource-server/README.md
