### ISSUE TITLE
Should func.request be func.HttpRequest?

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/azure-dev-docs#11]
The text says the main function receives an object of type func.request but looking at the code and the links about more information it appears to be of type func.HttpRequest.

I'm guessing since there can be other triggers they would have different types and maybe they're generally of type func.request (though the func.HttpRequest documentation doesn't seem to indicate any kind of parent class of func.request).

If this is supposed to be func.HtppRequest it should be updated.  If func.request is a real object type it should be clarified here somehow because "func.reqest" doesn't show up anywhere in the auto generated code I'm looking at.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7556d3d-8a73-692e-1754-90e2fe7ff806
* Version Independent ID: 637221f8-9585-0771-619b-8866ead7584d
* Content: [Examine the Python code files for Azure Functions in Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-03)
* Content Source: [python/tutorial-vs-code-serverless-python-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-vs-code-serverless-python-03.md)
* Service: **azure-functions**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@FISHMANPET Yes, thanks for pointing out that glitch. It should be func.HttpRequest, and I'll get it fixed.
