### ISSUE TITLE
Typo:   - name: Ceate second virtual network

### ISSUE THREAD

**Issue by timmyreilly** [MicrosoftDocs/azure-dev-docs#110]
Typo in Ansible script here: https://docs.microsoft.com/en-us/azure/developer/ansible/virtual-network-peering-configure#create-the-second-virtual-network 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009c3b43-b54e-fce3-2ad2-74d8dee95a6e
* Version Independent ID: f529513c-24ed-2092-7590-5fe89e811009
* Content: [Tutorial - Configure Azure virtual network peering using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/virtual-network-peering-configure#create-the-second-virtual-network)
* Content Source: [articles/ansible/virtual-network-peering-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/virtual-network-peering-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@timmyreilly Thanks for the heads-up. The typo has been fixed and should be live by Friday afternoon (PST).
