### ISSUE TITLE
'downgit' deemed harmful by Safari (Google Safe Browsing)

### ISSUE THREAD

**Issue by Bouke** [MicrosoftDocs/azure-dev-docs#1101]
> Example code and resources: Using the DownGit tool, download from GitHub the [integration-testing project](https://downgit.github.io/#/home?url=https://github.com/Azure/terraform/tree/master/samples/integration-testing) and unzip into a new directory to contain the example code. This directory is referred to as the example directory.

```
https://downgit.github.io/#/home?url=https://github.com/Azure/terraform/tree/master/samples/integration-testing
```

![image](https://user-images.githubusercontent.com/235882/226725520-56c68321-a03d-4f3c-8333-8ab3ef32717d.png)

See also: https://transparencyreport.google.com/safe-browsing/search?url=downgit.github.io&hl=en-GB

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1572ea-d197-2543-b3ea-07b5bf7e8483
* Version Independent ID: 6651e0a0-be7d-6a50-43ff-83760f9fa380
* Content: [Implement integration testing with Terraform and Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/best-practices-integration-testing)
* Content Source: [articles/terraform/best-practices-integration-testing.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/best-practices-integration-testing.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Bouke Thanks for bringing this issue to our attention. I'm doing some research and update soon.
