### ISSUE TITLE
Support for TLS/mTLS in azure cloud springboot?

### ISSUE THREAD

**Issue by MarcelTemp** [MicrosoftDocs/azure-dev-docs#1104]
It states that TLS is not supported on the server side in version 4.x, but you are already on 5.x. Why is support still not added. I am using an extremely outdated 3.14 library. New vulnerabilities get found every day. Why is this support still not added.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f76c16f-4898-d212-cec3-463f1d5a3912
* Version Independent ID: 10e24fd2-aa87-b300-d4ce-1a4377f4f2fc
* Content: [Enable HTTPS in Spring Boot with Azure Key Vault certificates](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.md)
* Service: **key-vault**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by chenrujun** [comment]
Hi, @MarcelTemp .
Thanks for reaching out. We will consider add this feature. But for now, there is no ETA.

**Comment by chenrujun** [comment]
Hi, @KarlErickson .
Could you please help to close current issue? Because current issue is tracked by this issue: https://github.com/Azure/azure-sdk-for-java/issues/28243

**Comment by chenrujun** [comment]
Hi, @MarcelTemp 
The requests in GitHub does not have high priority. 
If this requirement is urgent in your company, please contact Microsoft Support team for help. 
Your colleague who created related Azure resources should know how to contact Microsoft Support team.
