### ISSUE TITLE
.Net is not a language

### ISSUE THREAD

**Issue by mash-qbe** [MicrosoftDocs/azure-dev-docs#1107]
In the Currently supported/planned languages table, its marked as .Net being a supported language. .Net isn't a langage > C# is being mainly used in the templates and not F# for example which are both part of .net

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da63649f-5dd6-83c7-8d42-46b4b1291e47
* Version Independent ID: da63649f-5dd6-83c7-8d42-46b4b1291e47
* Content: [What is the Azure Developer CLI (preview)?](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/overview)
* Content Source: [articles/azure-developer-cli/overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/overview.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
#please-close
