### ISSUE TITLE
Why is the Grant Admin Consent screenshot there

### ISSUE THREAD

**Issue by nicksc423** [MicrosoftDocs/azure-dev-docs#111]
Under step 5 for "Add an application registration for your Spring Boot app" there is a screenshot that appears to be telling you to click Grant Admin consent for your App Registration, but there is no text telling you to do this?  

This is super confusing, I have no idea if I am supposed to do this or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c3e00f-bdf2-cdb9-53a3-d672e0a1196d
* Version Independent ID: 3bd15057-0071-7aee-cf46-4c50a3061fbb
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @panli
* Microsoft Alias: **panli**

**Comment by KarlErickson** [comment]
@nicksc423 thanks for the feedback! We'll look into this.
@seanli1988 can you comment here? Thanks!

**Comment by KarlErickson** [comment]
@nicksc423 this is fixed now. Thanks again for the feedback!
