### ISSUE TITLE
the corresponding TOC entry in wrong

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-dev-docs#1111]
it says "managed identity to connect MySQL" but it actually describes connecting to multiple DB engines

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 594cedfc-c0a7-3650-7126-f891460b8ae5
* Version Independent ID: 594cedfc-c0a7-3650-7126-f891460b8ae5
* Content: [Deploy to Azure Spring Apps with passwordless connection to Azure database](https://learn.microsoft.com/en-au/azure/developer/java/spring-framework/deploy-passwordless-spring-database-app?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json&tabs=mysql)
* Content Source: [articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/deploy-passwordless-spring-database-app.md)
* Service: **spring-apps**
* GitHub Login: @KarlErickson
* Microsoft Alias: **xiada**

**Comment by KarlErickson** [comment]
Thanks, @ciufudean !
