### ISSUE TITLE
Spring Data R2DBC with Managed Identity

### ISSUE THREAD

**Issue by janchristian-haddorp** [MicrosoftDocs/azure-dev-docs#1112]
There are samples for using Spring Data R2DBC with Azure PostgreSQL/MySQL and for migrating JPA applications to use passwordless connections (managed identity).

https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-postgresql.md
https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/migrate-postgresql-to-passwordless-connection.md

But there are no docs or sample applications showing how Spring Data R2DBC can work with managed identity. Would be great if example apps can be extended.

**Comment by chenrujun** [comment]
Hi, @janchristian-haddorp 
Thanks for reaching out. We will consider update this sample: https://github.com/Azure-Samples/quickstart-spring-data-r2dbc-postgresql

**Comment by chenrujun** [comment]
Hi, @janchristian-haddorp 
Thanks for reaching out.
Now passwordless connections (managed-identity) is supported JDBC, not supported in R2DBC. 
And not we do not have ETA for this feature.

**Comment by janchristian-haddorp** [comment]
@chenrujun, thanks for your feedback.

Regarding passwordless connections it would be great if besides `managed-identity` also support for `workload-identity` could be added to Spring Data R2DBC libs.
 
https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity
