### ISSUE TITLE
Could not find artifact com.azure.spring:spring-cloud-azure-starter-keyvault

### ISSUE THREAD

**Issue by Tudor281** [MicrosoftDocs/azure-dev-docs#1119]
Hello,

I'm following the tutorial https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault and cannot import the second dependency, which also has a missing version.

Googling the artifact doesn't find it either.

**Comment by backwind1233** [comment]
Hi @Tudor281 
Thanks for reaching out, "the second dependency", do you mean [spring-cloud-azure-starter-keyvault](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-keyvault)?
<img width="590" alt="image" src="https://user-images.githubusercontent.com/4465723/231922989-3c4c15b0-bab1-49b4-adc3-e95588a7e71c.png">

It worked in my local machine:
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/4465723/231926408-d5dd0943-9787-4cc1-a3fd-3434ac2eaf69.png">

did you add the pom dependencies in your pom.xml file?
<img width="722" alt="image" src="https://user-images.githubusercontent.com/4465723/231926561-329a1433-b912-49f5-9447-5ddb0f3bd2c4.png">

**Comment by Tudor281** [comment]
Hi @backwind1233 ,

Thanks for your feedback, indeed, it is my fault. I was adding the first dependency as a normal dependency. 

Within <dependencyManagement> now it works.
