### ISSUE TITLE
azure_rm.py link broken

### ISSUE THREAD

**Issue by 36roentgen** [MicrosoftDocs/azure-dev-docs#112]
&gt; GET /ansible/ansible/blob/devel/contrib/inventory/azure_rm.py HTTP/1.1
&gt; Host: github.com
&gt; User-Agent: curl/7.64.1
&gt; Accept: */*
&gt;
&lt; HTTP/1.1 404 Not Found
&lt; server: GitHub.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059a1972-09ee-02a7-8159-07ba04a2c763
* Version Independent ID: 4323aa16-062c-1b11-fb73-11777c34f88e
* Content: [Tutorial - Configure dynamic inventories of your Azure resources using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure#feedback)
* Content Source: [articles/ansible/dynamic-inventory-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/dynamic-inventory-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by muratcabuk** [comment]
is there any update? it is still not working.

**Comment by f3rdy** [comment]
You can go for the script up to stable-2.9 but keep in mind, that the contributed scripts are deprecated in favor of the inventory plugin.

https://github.com/ansible/ansible/blob/stable-2.7/contrib/inventory/azure_rm.py

**Comment by TomArcherMsft** [comment]
@36roentgen The links have been updated and the article will be republished Monday.
