### ISSUE TITLE
Reference to deprecated github action

### ISSUE THREAD

**Issue by polinaouk** [MicrosoftDocs/azure-dev-docs#1120]
[Enter feedback here]

---
#### Document Details
the doc is referencing [get-keyvault-secrets](https://github.com/Azure/get-keyvault-secrets) action which is deprecated. 

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae689e10-62a4-f724-7705-9273801217aa
* Version Independent ID: 2fa43bd0-223b-5f6e-1fca-e823d5b92ef5
* Content: [Quickstart -  Use Azure Key Vault secrets in GitHub Actions workflows](https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault#add-the-key-vault-action)
* Content Source: [articles/github/github-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-key-vault.md)
* Service: **key-vault**
* Sub-service: **secrets**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Closing out this issue because the article is now retired. 

#please-close
