### ISSUE TITLE
The code sample connects to the DB with username and password, not passwordless

### ISSUE THREAD

**Issue by ciufudean** [MicrosoftDocs/azure-dev-docs#1122]
It is very confusing for me whether a passwordless connection is used or not:
1. if one follows the documentation, command `az spring connection create sql` will create property `spring.datasource.url` on the service connection (so not exactly an app configuration as the page says)
2. but if one looks at the code, `application.properties` contains these 3 lines
```
spring.datasource.url=jdbc:sqlserver://$AZ_DATABASE_NAME.database.windows.net:1433;database=demo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=spring@$AZ_DATABASE_NAME
spring.datasource.password=$AZ_SQL_SERVER_PASSWORD
```
So which `spring.datasource.url` one is being used? Is it really the one on the service connection? If yes, how come?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 594cedfc-c0a7-3650-7126-f891460b8ae5
* Version Independent ID: 594cedfc-c0a7-3650-7126-f891460b8ae5
* Content: [Tutorial: Deploy to Azure Spring Apps with passwordless connection to Azure database](https://learn.microsoft.com/en-au/azure/developer/java/spring-framework/deploy-passwordless-spring-database-app?toc=%2Fazure%2Fspring-apps%2Ftoc.json&bc=%2Fazure%2Fspring-apps%2Fbreadcrumb%2Ftoc.json&tabs=mysql)
* Content Source: [articles/java/spring-framework/deploy-passwordless-spring-database-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/deploy-passwordless-spring-database-app.md)
* Service: **spring-apps**
* GitHub Login: @KarlErickson
* Microsoft Alias: **xiada**

**Comment by KarlErickson** [comment]
@saragluna can you comment here? Thanks!

**Comment by backwind1233** [comment]
Hi @ciufudean, thanks for reaching out.

This step in the doc will override the value in `application.properties`.
So there should be only one `spring.datasource.url` which is configured by service connector.
<img width="890" alt="image" src="https://user-images.githubusercontent.com/4465723/231929081-cce28fd4-9470-41aa-89f1-89aeb327f4a0.png">

**Comment by KarlErickson** [comment]
No further reply - closing.
