### ISSUE TITLE
@TimeToLive 

### ISSUE THREAD

**Issue by jayanthpatki91** [MicrosoftDocs/azure-dev-docs#1124]
looks like @TimeToLive doesnt work with azure redis cache spring webflux. any comments on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2985bd1-1292-408a-ed6c-2b5ca73d113e
* Version Independent ID: b9dc82b9-a34a-9fc8-8dc7-ae405e05e5b8
* Content: [use Azure Redis Cache in Spring](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache)
* Content Source: [articles/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md)
* Service: **cache**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by moarychan** [comment]
Hi @jayanthpatki91 ,

Thank you for reporting this issue. We have received your submission and will take it into consideration. We appreciate your input and will review this matter as soon as possible.
We'll keep you updated on the progress of our review.
Thank you for your contribution to improving our project.

**Comment by KarlErickson** [comment]
@moarychan any update on this? Can we close this issue? Thanks.

**Comment by moarychan** [comment]
@Netyyyy please help take a look at this scenario, thanks.

**Comment by saragluna** [comment]
This is more like a spring-data-redis issue or Azure Redis server issue. And there should be no doc impact. Is it possible to monitor the command sent from the client just like this https://github.com/spring-projects/spring-data-redis/issues/1764? So we can identify the issue.

**Comment by KarlErickson** [comment]
Thanks, @saragluna. Since there's no response, and it's not a doc issue, I'm closing it.
@jayanthpatki91 if this is still an issue for you, please ask again at the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site or file an issue at <https://github.com/spring-projects/spring-data-redis/issues>. Thanks!
