### ISSUE TITLE
Typo in resource name

### ISSUE THREAD

**Issue by yury-dubinin** [MicrosoftDocs/azure-dev-docs#1125]
Typo in `resource "random_string" "rando"`, missing `m`.

Latter used like:
```
resource "azurerm_shared_image_gallery" "sig" {
  name                = "sig${random_string.random.id}"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7c2a01d4-b03a-9ce1-d47b-a8de986ee167
* Version Independent ID: 7c2a01d4-b03a-9ce1-d47b-a8de986ee167
* Content: [Configure Azure Compute Gallery using Terraform - Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-azure-compute-image-gallery)
* Content Source: [articles/terraform/create-avd-azure-compute-image-gallery.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-avd-azure-compute-image-gallery.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@yury-dubinin Thanks for the feedback! I've fixed the instances where the name was misspelled. I've submitted the change to the engineering team, so the article should be updated later this week.
