### ISSUE TITLE
Parameter specification misleading

### ISSUE THREAD

**Issue by jaumecen** [MicrosoftDocs/azure-dev-docs#1131]
Hi, while using the api mentioned in this document: https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/2022-08-01-preview/scheduledqueryrules?pivots=deployment-language-arm-template I found that the parameter mentioned [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/2022-08-01-preview/scheduledqueryrules?pivots=deployment-language-arm-template#:~:text=The%20list%20of%20resource%20id%27s%20that%20this%20scheduled%20query%20rule%20is%20scoped%20to.) didn't work as expected.

It states that "Scopes" is a list that accepts multiples resourcesId but it throws this error: 

`{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidRequestContent\",\r\n    \"message\": \"The request content was invalid and could not be deserialized: 'Scopes list should contain exactly 1 resource Id'\"\r\n  }\r\n}"}]}`

Please fix it so people don't have to lose time with this.

**Comment by KarlErickson** [comment]
Hi @jaumecen - thanks for the feedback, but the content you're referring to is not in this repository. Please use the feedback mechanism on that content page to provide your input so that it will be routed to the people who can address it. Thanks!
