### ISSUE TITLE
Terraform Azure module version out of date

### ISSUE THREAD

**Issue by Freshchris01** [MicrosoftDocs/azure-dev-docs#1132]
Hello, I followed this article to [use Azure Blob Storage as Terraform Backend](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli).

With the provided Code, I could not run `terraform plan` successfully. I got the following error: 
`Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure sending request: StatusCode=0 -- Original Error: context canceled`

Updating the Azure module version solved the issue for me:

```
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.53.0"
    }
```

Does it make sense to open a PR to fix the module version in a single place? Or should this be part of a bigger refactoring?

**Comment by TomArcherMsft** [comment]
@Freshchris01 I also recommend running `terraform init --upgrade`. Using the `--upgrade` switch is another change we're making across the Terraform samples.

**Comment by TomArcherMsft** [comment]
@Freshchris01 Thank you for your patience.  I have made the changes to the article and they should be published later today.
