### ISSUE TITLE
Wrong variable name in example

### ISSUE THREAD

**Issue by sandman-battelle** [MicrosoftDocs/azure-dev-docs#1133]
The example declared `tokenCredential` but the client consumes `credentials`.

```js
...
// Acquire credential
const tokenCredential = DefaultAzureCredential();

async function listSubscriptions() {
  try {

    // use credential to authenticate with Azure SDKs
    const client = new SubscriptionClient(credentials);
...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfeae622-1391-1fac-ca16-e8566d406413
* Version Independent ID: dfeae622-1391-1fac-ca16-e8566d406413
* Content: [Local dev: Auth JS apps to Azure services with service principal - Azure](https://learn.microsoft.com/en-us/azure/developer/javascript/sdk/authentication/local-development-environment-service-principal?tabs=azure-portal)
* Content Source: [articles/javascript/sdk/authentication/local-development-environment-service-principal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/sdk/authentication/local-development-environment-service-principal.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
#in-progress
