### ISSUE TITLE
ActiveDirectoryServicePrincipal authentication with sql server reactive driver

### ISSUE THREAD

**Issue by jbkervyn** [MicrosoftDocs/azure-dev-docs#1136]
Are other form of authentication supported by the reactive driver. I'm especially thinking of the one available on the "standard" driver ActiveDirectoryServicePrincipal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c05b955d-5688-f2c3-5c7e-30d269fc6f48
* Version Independent ID: 83b6c7bf-8693-71c0-c933-b36610f7b4c2
* Content: [Use Spring Data R2DBC with Azure SQL Database](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server)
* Content Source: [articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server.md)
* Service: **sql-database**
* GitHub Login: @KarlErickson
* Microsoft Alias: **bbenz**

**Comment by KarlErickson** [comment]
Hi @jbkervyn - you might want to ask your question at <https://learn.microsoft.com/en-us/answers/questions/> as well, since this issues list is primarily for documentation feedback. Thanks!

**Comment by MashaMSFT** [comment]
Hi @jbkervyn , thanks for contacting Microsoft! As your question is about the product, we'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
