### ISSUE TITLE
MI with Federated Identity for GH Actions

### ISSUE THREAD

**Issue by lindacmsheard** [MicrosoftDocs/azure-dev-docs#1141]
I found this resource in the public domain, and am wondering why this pattern (MI  with Federated identity) is not explicitly referenced in this page - please could you explain?

https://yourazurecoach.com/2022/12/29/use-github-actions-with-user-assigned-managed-identity/

I suspect that there is some implicit equivalency with the second scenario, but I think it would be helpful to explain when you would choose an app registration vs a MI. 

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @MoChilia
* Microsoft Alias: **shiyingchen**

**Comment by MoChilia** [comment]
Hi @lindacmsheard! Sorry for the late response. This doc is outdated and lacks some information. Thanks for contacting us. We will update it soon.

**Comment by juliakm** [comment]
Closing as this is on the product team's list for future updates. 

#please-close
