### ISSUE TITLE
cloud-init jenkins gpg key install commands outdated

### ISSUE THREAD

**Issue by ehcmke** [MicrosoftDocs/azure-dev-docs#1151]
The commands provided in this tutorial are outdated. Here are the commands from jenkins.io's Debian/Ubuntu install guide that worked for me. Prior to that I was getting expired keys and errors.

https://www.jenkins.io/doc/book/installing/linux/#debianubuntu

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Get Started - Install Jenkins on an Azure Linux VM](https://learn.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ehcmke Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
