### ISSUE TITLE
Need install additional package "pwsh"

### ISSUE THREAD

**Issue by xinlaoda** [MicrosoftDocs/azure-dev-docs#1154]
[Enter feedback here]
To execute azd command, it also needs to install additional package "pwsh", which be used in "azd up" command.
The document needs to describe this dependency.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Version Independent ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Content: [Install the Azure Developer CLI (preview)](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux)
* Content Source: [articles/azure-developer-cli/install-azd.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/install-azd.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thank you, this was removed as a dependency.

#please-close
