### ISSUE TITLE
Role/group setup is not working and the description is confusing

### ISSUE THREAD

**Issue by vvoinov** [MicrosoftDocs/azure-dev-docs#116]
Have followed all the steps from the example and authentication part (sign in) works for me. However, authorization part (role/group) access is not working - I don't get role setup in AD inside Spring Boot App - my authenticated user has 'ROLE_USER' authorization.
The documentation around role/group is bit misleading since the group name in AD is 'users' however the value in Spring Boot App is 'Users'. It's not clear is it the convention, is it case sensitive or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf5423d-6c4c-26a8-89bb-7686794716d0
* Version Independent ID: 998d0369-045c-d32c-d07e-ff7d4352e878
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory#configure-and-compile-your-app)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@vvoinov thanks for the feedback! We'll investigate and update the topic to clear things up.
@seanli1988 can you comment here? Thanks!
