### ISSUE TITLE
Tomcat using JCA client is serving leaf SSL cert but not the rest of the chain

### ISSUE THREAD

**Issue by Trailbear** [MicrosoftDocs/azure-dev-docs#1164]
Our site is using the AKV-Tomcat code to deploy SSL certs when they get renewed in Key Vault.  However, the site is only serving up the leaf certificate, and not the rest of the certificate chain.  In particular many visitors who don't have the intermediary certificate installed get an untrusted site error.   

Each time the certificate is renewed in AKV, it gets some new intermediary TLS certificate, and the client machines that don't have that certificate are broken, while the ones who were broken are often resolved because they have the other intermediary.  

Is there some configuration we should be setting to ensure the entire chain is sent to the clients?  Or is there some other way that the server is supposed to be set up to send the other certificates in the chain?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0ecfefd-142b-e06f-a42d-7f466984d6cc
* Version Independent ID: e0ecfefd-142b-e06f-a42d-7f466984d6cc
* Content: [Use Azure Key Vault to deliver TLS/SSL certificates to Apache Tomcat](https://learn.microsoft.com/en-us/azure/developer/java/fundamentals/java-azure-keyvault-tomcat-integration?tabs=windows)
* Content Source: [articles/java/fundamentals/java-azure-keyvault-tomcat-integration.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/fundamentals/java-azure-keyvault-tomcat-integration.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **manriem**

**Comment by KarlErickson** [comment]
@mnriem can you reply here? Thanks!

@Trailbear you might also want to ask your question on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site, since this issues list is primarily for documentation feedback. Thanks!

**Comment by mnriem** [comment]
@stliu Can you confirm this is the case?

**Comment by saragluna** [comment]
Hi @Trailbear, sorry for the late reply. This feature is still in our backlog, please vote to help us prioritize.

**Comment by Trailbear** [comment]
@KarlErickson starting in what release should I look for this change?

**Comment by KarlErickson** [comment]
@Trailbear it sounds like this change hasn't been scheduled yet, but it might be prioritized if enough people vote for it. I suggest adding a comment to https://github.com/Azure/azure-sdk-for-java/issues/20591. 

@saragluna is there a better way to vote for prioritization?

**Comment by Trailbear** [comment]
This code is pointless unless it serves up the entire certificate chain.  Folks who start using it are assuming it will serve up the whole chain but after a lot of troubleshooting will find out that there is no recourse but to use other code.  That drives a lot of dissatisfaction and leaves these folks out in the cold.

**Comment by KarlErickson** [comment]
@Trailbear could you add your comment to https://github.com/Azure/azure-sdk-for-java/issues/20591 so that the product team will see it directly? Comments at the current location are for documentation feedback. Thanks!

**Comment by Trailbear** [comment]
Added both places… 😉  Thanks

Frank Long
Voice or Text: 206-390-5861
