### ISSUE TITLE
variables.tf has duplicated variables

### ISSUE THREAD

**Issue by aadesola** [MicrosoftDocs/azure-dev-docs#1165]
[Enter feedback here]
Kindly review the variables.tf as resource_group_name was repeated twice resulting in the error below.
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/25845446/155849cd-6dcb-4b06-a58d-836c5d5591da)

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Duplicate variable declaration
│ 
│   on variables.tf line 16:
│   16: variable "resource_group_name" {
│ 
│ A variable named "resource_group_name" was already declared at variables.tf:11,1-31. Variable names must be unique within a module.
╵

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4371abd-f9cc-1ee9-1ed3-a5f0488740ce
* Version Independent ID: 14c6cf0f-ec32-15ed-cb38-8eb5860d858e
* Content: [Create an Azure virtual machine scale set from a Packer custom image by using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-using-packer-hcl)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
