### ISSUE TITLE
Unsupported Argument

### ISSUE THREAD

**Issue by kargajopep** [MicrosoftDocs/azure-dev-docs#1167]
Remote storage account terraform configuration contains outdated argument:

```
Error: Unsupported argument

  on create-remote-storage.tf line 31, in resource "azurerm_storage_account" "tfstate":
  31:   allow_blob_public_access = false

An argument named "allow_blob_public_access" is not expected here.
```

Either provider's version should be downgraded or the unsupported argument should be replaced following https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide and the following guides. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Store Terraform state in Azure Storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=terraform)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
