### ISSUE TITLE
Association of LB with VMs

### ISSUE THREAD

**Issue by umesh001** [MicrosoftDocs/azure-dev-docs#1168]
Association of LB with VMs is not specified in the terraform code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aef91226-6c89-f8f1-3400-28d633cd1791
* Version Independent ID: 19ea3aee-2e71-0764-110c-fadf241c377f
* Content: [Quickstart: Create an Azure Linux VM cluster with Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-with-infrastructure?tabs=azure-cli)
* Content Source: [articles/terraform/create-vm-cluster-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-cluster-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
