### ISSUE TITLE
The referenced action is deprecated with no mention of what can be used in it's place

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/azure-dev-docs#1169]
This page references a deprecated action with no indication (that I can see anyway) on how to do it going forward. Any chance this can be updated to the preferred method for variable substitution in github actions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f48a84-dcf9-e852-3f3c-703382971875
* Version Independent ID: ffe51d31-19c8-f4c3-0d31-dc154e414a59
* Content: [Use variable substitution with GitHub Actions for Azure](https://learn.microsoft.com/en-us/azure/developer/github/github-variable-substitution)
* Content Source: [articles/github/github-variable-substitution.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-variable-substitution.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@giwleb The action is no longer supported and unfortunately there is not an alternative. We recommend using the built-in `env` variable support in GitHub Actions ([GitHub doc](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow)). 

This article should be retired in the next day.

**Comment by juliakm** [comment]
#please-close
