### ISSUE TITLE
Update VS Uninstall

### ISSUE THREAD

**Issue by gablans** [MicrosoftDocs/azure-dev-docs#1172]
Both update and uninstall have the same instruction (uninstall).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Version Independent ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Content: [Install the Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux)
* Content Source: [articles/azure-developer-cli/install-azd.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/install-azd.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
This was resolved but the issue was left open.

#please-close
