### ISSUE TITLE
repository 'https://github.com/Azure-Samples/emplate/' not found

### ISSUE THREAD

**Issue by borgetx** [MicrosoftDocs/azure-dev-docs#1176]
When I execute
azd init --template todo-nodejs-mongo

I get the error message below

C:\Users\borget\source\repos\azdquickstart>azd init -template todo-nodejs-mongo

Initializing a new project (azd init)

  |      =| Downloading template code to: C:\Users\borget\source\repos\azdquickstartinfo: please complete authentication in your browser...
  (✓) Done: Downloading template code to: C:\Users\borget\source\repos\azdquickstart

ERROR: init from template repository: fetching template: failed to clone repository https://github.com/Azure-Samples/emplate: exit code: 128, stdout: , stderr: Cloning into 'C:\Users\borget\AppData\Local\Temp\az-dev-template982246579'...
remote: Repository not found.
fatal: repository 'https://github.com/Azure-Samples/emplate/' not found

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Version Independent ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Content: [Get started using Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=localinstall&pivots=programming-language-nodejs)
* Content Source: [articles/azure-developer-cli/get-started.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/get-started.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thanks for the feedback, it appears this error is caused by running `azd init -template todo-nodejs-mongo` instead of `azd init --template todo-nodejs-mongo` (missing a hyphen on the first command). I have tested the init code on the linked document and it works correctly when both hyphens are there.

**Comment by alexwolfmsft** [comment]
#please-close
