### ISSUE TITLE
Spring Cloud Function

### ISSUE THREAD

**Issue by snodnipper** [MicrosoftDocs/azure-dev-docs#1181]
Whilst I appreciate the documentation, honestly, I cannot get this to build in a short amount of time.  Others are complaining too: https://learn.microsoft.com/en-us/answers/questions/1166331/spring-autowiring-not-working-for-spring-azure-fun

My @Autowired is not working (injected items are null).

```shell
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.966 s - in com.microsoft.azure.functions.worker.functional.tests.SimpleParamReturnTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FunctionEnvironmentReloadRequestHandlerTest.SetEnv_Succeeds:27 » InaccessibleObject
[INFO] 
[ERROR] Tests run: 61, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Spring Cloud Function in Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
@jdubois do you have a solution?

**Comment by jdubois** [comment]
It does work using the sample https://github.com/Azure-Samples/hello-spring-function-azure 
Let me check if we can update the Learn module that is mentioned here, as it may be out of date (there was several updates both in Azure Functions and Spring Functions, so something could have been broken here).
For the record: this is in the process of being simplified a lot by the Spring team, so this will need to be rewritten soon anyway.

**Comment by snodnipper** [comment]
Thank you both for looking into it.

I have since updated my azure functions core tools* and got the following example working, which was updated ~5 days ago: https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-azure.

I have asked the spring folks if they could provide a gradle version of that project as we are using the `com.microsoft.azure.azurefunctions` gradle plugin.

I appreciate that there are some sizeable upcoming changes and that it might be best to update the documentation in one go.

\* _brew install azure-functions-core-tools@4_

**Comment by jdubois** [comment]
Thanks for the update @snodnipper ! Can you point to where the documentation or the sample was wrong or misleading?
On our side, @mkheck volunteered to update the doc, so any help is always good!

**Comment by jdubois** [comment]
Hello,

I've just tested:

- https://github.com/Azure-Samples/hello-spring-function-azure with the current version ( https://github.com/Azure-Samples/hello-spring-function-azure/tree/3137be8cc91ce2a54ac957f957081e54ec820870 to be exact )
- With the current version of Azure Functions Core Tools ( 4.0.5348 )
- And the current version of Java ( java version "20.0.2" 2023-07-18 )

Running `mvn clean test` works:

```
2023-09-13T12:24:32.159+02:00  INFO 2821 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Starting ForkedBooter v2.22.2 using Java 20.0.2 with PID 2821 (started by julien in /Users/julien/workspace/hello-spring-function-azure)
2023-09-13T12:24:32.160+02:00  INFO 2821 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : No active profile set, falling back to 1 default profile: "default"
2023-09-13T12:24:32.322+02:00  INFO 2821 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Started ForkedBooter in 0.291 seconds (process running for 0.864)
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.462 s - in com.example.HelloTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.386 s
[INFO] Finished at: 2023-09-13T12:24:32+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by KarlErickson** [comment]
Thanks, @jdubois ! I'll go ahead and close. @snodnipper if you're still encountering problems, please open a new issue and provide details about where the documentation or the sample is wrong or misleading. Thanks!
