### ISSUE TITLE
Clarification of Implicit Push

### ISSUE THREAD

**Issue by ryanlpoconnell** [MicrosoftDocs/azure-dev-docs#1187]
Re Implicit Push...
I have observed that yes, PullAsync will result in an implicit Push if this table has pending operations... but will only push operations for the table being 'Pulled' without further optional parameters supplied. 

Therefore, I think where documentation says "executes a push on the sync context", it would be clearer if it continued to clarify that "pending operations for other tables will NOT be implicitly pushed unless specified in the optional PullOptions parameter".  

I think this is useful information because I believe the default behaviour is different compared with the older Azure sync library and it guarantees any Sync Errors received in `Microsoft.Datasync.Client.Offline.PushFailedException` will be related directly to the table being 'pulled' and no other tables, potentially simplifying error handling.

Code to prove this:
https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/src/Microsoft.Datasync.Client/Offline/SyncContext.cs#L306
https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/src/Microsoft.Datasync.Client/Offline/SyncContext.cs#LL318C13-L320C23
`string[] relatedTables = options.PushOtherTables ? null : new string[] { tableName };
...
            if (await TableIsDirtyAsync(tableName, cancellationToken).ConfigureAwait(false))
            {
                await PushContext.PushItemsAsync(relatedTables, cancellationToken).ConfigureAwait(false);
...
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8c7a315-62a7-2c82-1c76-205698d24171
* Version Independent ID: a4ade2b3-73f3-f192-a945-dbdc0b17d960
* Content: [Offline data sync for mobile apps](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/data-sync?source=docs#implicit-push)
* Content Source: [articles/mobile-apps/azure-mobile-apps/howto/data-sync.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/howto/data-sync.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
I've just submitted some improvements to the data-sync.md, and fixed this issue in the process.  It's currently going through the publication / review process, and should be available soon.

#please-close
