### ISSUE TITLE
architecture for migrating spring boot apps to azure spring apps

### ISSUE THREAD

**Issue by hemas2022** [MicrosoftDocs/azure-dev-docs#1188]
[Enter feedback here]
I am looking for architecture diagram on the infra services that are used in the app consolidation and migration of spring boot apps to azure spring apps. i have gone through the azure spring apps standard and enterprise architecture already.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09d9c752-ab9b-2ec1-5ad8-5730e9068762
* Version Independent ID: 09d9c752-ab9b-2ec1-5ad8-5730e9068762
* Content: [Migrate Spring Boot applications to run on Azure Container Apps](https://learn.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-container-apps)
* Content Source: [articles/java/migration/migrate-spring-boot-to-azure-container-apps.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migrate-spring-boot-to-azure-container-apps.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **manriem**

**Comment by KarlErickson** [comment]
Hi @hemas2022 - I'm not aware of any ASA architecture diagrams besides the ones you've already seen. You might be able to find something on the [Apps on Azure](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/bg-p/AppsonAzureBlog/label-name/Azure%20Spring%20Apps) blog, or you can ask for help on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site. I hope this helps!
