### ISSUE TITLE
Azure Spring Cloud - Event Hub & Schema Registry SDK & Documentation

### ISSUE THREAD

**Issue by vksatish-lab** [MicrosoftDocs/azure-dev-docs#1192]
Hello Team,

I have recently started adopted azure apps into my projects. Especially focused on leveraging event hub and schema registry.  Current documentation is helpful but pretty basic. Can you point to me any documentation where I can understand how do we register schema registry and use them to deserlize incoming message stream.

I found a solution here - https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/schemaregistry/azure-data-schemaregistry-apacheavro/src/samples/java/com/azure/data/schemaregistry/apacheavro/SchemaRegistryWithEventHubs.java

Wondering if there is one which is could be done using sprint cloud stream and azure apps. 

Thanks
Satish  
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [Spring Cloud Stream with Azure Event Hubs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by Netyyyy** [comment]
Hi @vksatish-lab , Thanks for your reporting, we haven't had a relevant doc yet and will take it into consideration.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
