### ISSUE TITLE
How to setup with proxy

### ISSUE THREAD

**Issue by Pymann** [MicrosoftDocs/azure-dev-docs#1193]
Hi guys,

I need login to azure via ntlm proxy...
so how to tell your client to use a proxy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0512b7d6-3f16-303f-44dc-4e1595d5ca62
* Version Independent ID: 43cd9aca-e5ee-31f7-7c34-497c54ff9487
* Content: [Azure authentication with the Azure Identity module for Go](https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash#azureCLI)
* Content Source: [articles/go/azure-sdk-authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/azure-sdk-authentication.md)
* Service: **azure**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by KarlErickson** [comment]
Hi @Pymann - this issues list is primarily for documentation feedback, so you should also ask your question on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site. Thanks!
