### ISSUE TITLE
Not working for Azure Function Python v2

### ISSUE THREAD

**Issue by xinlaoda** [MicrosoftDocs/azure-dev-docs#1194]
I set up Azure function by python v2, but it cannot be scan and import to Azure functionapp.
Do we support Azure Function Python v2?

**Comment by KarlErickson** [comment]
Hi @xinlaoda - this issues list is primarily for documentation feedback, so you might have a better chance of getting an answer to your question by asking it on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site as well. Thanks!
