### ISSUE TITLE
Locally proxy api requests

### ISSUE THREAD

**Issue by smolattack** [MicrosoftDocs/azure-dev-docs#1201]
This article promises to teach how to
`Locally proxy front-end requests to local back-end API using the [SWA CLI](https://github.com/Azure/static-web-apps-cli).`

Where is that information described please?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf4853ab-4f0f-78e4-a892-9e4c2d7bdf65
* Version Independent ID: cf4853ab-4f0f-78e4-a892-9e4c2d7bdf65
* Content: [Create static web app with serverless app - Azure](https://learn.microsoft.com/en-us/azure/developer/javascript/how-to/with-web-app/static-web-app-with-swa-cli)
* Content Source: [articles/javascript/how-to/with-web-app/static-web-app-with-swa-cli.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/how-to/with-web-app/static-web-app-with-swa-cli.md)
* Service: **azure-javascript**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@smolattack This content is within [step 4](https://learn.microsoft.com/en-us/azure/developer/javascript/how-to/with-web-app/static-web-app-with-swa-cli#4-optional-build-and-run-local-app), in substep 2, using the SWA CLI. You can learn about [SWA CLI](https://azure.github.io/static-web-apps-cli/docs/use/install/). 

Is there any thing specific about the proxy you didn't understand in relation to the steps in the tutorial? 

#in-progress

**Comment by smolattack** [comment]
Well it doesn't work for me. I've made logged an issue over swa cli as well. The api calls aren't intercepted. Would be useful if you stated the precise version of the tools used to create the article.

**Comment by diberry** [comment]
@manekinekko Do you have any idea why the SWA CLI Proxy might not work? Any troubleshooting steps?

**Comment by manekinekko** [comment]
Hi @diberry @smolattack I left an response on the other repo: https://github.com/Azure/static-web-apps-cli/issues/723#issuecomment-1640328938. Please let me know if that helps.

**Comment by diberry** [comment]
@smolattack The website, when using the SWA CLI to proxy to the API, has to be access with port 4280. Can you try that port and verify the website, including requests to the API work for you?
