### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by AHI-Technologies** [MicrosoftDocs/azure-dev-docs#1202]
[Enter feedback here]

this line in your documentation seems to fail as it requires "new" before DefaultAzureCredential();

// Acquire credential
const tokenCredential = DefaultAzureCredential();

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfeae622-1391-1fac-ca16-e8566d406413
* Version Independent ID: dfeae622-1391-1fac-ca16-e8566d406413
* Content: [Local dev: Auth JS apps to Azure services with service principal - Azure](https://learn.microsoft.com/en-us/azure/developer/javascript/sdk/authentication/local-development-environment-service-principal?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json&tabs=azure-portal#1---register-the-application-in-azure)
* Content Source: [articles/javascript/sdk/authentication/local-development-environment-service-principal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/sdk/authentication/local-development-environment-service-principal.md)
* Service: **azure-javascript**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@AHI-Technologies Thank you for reporting this.

**Comment by diberry** [comment]
This is fixed now.
