### ISSUE TITLE
Just hours ago the ConfigureRemotingForAnsible.ps1 scripts was moved in github. 

### ISSUE THREAD

**Issue by sagneta** [MicrosoftDocs/azure-dev-docs#1203]
[Enter feedback here]
Here is the new URL: https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb5f4824-c6e0-5b17-d79b-93395ff4452d
* Version Independent ID: 7da82adc-2656-daef-c2b5-e871a932e2da
* Content: [Create a Windows virtual machine in Azure using Ansible](https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-windows?tabs=ansible)
* Content Source: [articles/ansible/vm-configure-windows.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure-windows.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
