### ISSUE TITLE
Wrong title in navigation bar

### ISSUE THREAD

**Issue by jorisaeles** [MicrosoftDocs/azure-dev-docs#1204]
Title in the navigation bar at the left is different from the title of the article making it difficult for customers to find this article: [Tutorial: WebLogic Server with Elastic on Azure] vs [Migrate WebLogic Server applications to JBoss EAP on Azure App Service]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f98546da-1e53-aeec-e89f-d1f8c1e65099
* Version Independent ID: f98546da-1e53-aeec-e89f-d1f8c1e65099
* Content: [Migrate WebLogic Server applications to JBoss EAP on Azure App Service](https://learn.microsoft.com/en-us/azure/developer/java/migration/migrate-weblogic-to-jboss-eap-on-azure-app-service)
* Content Source: [articles/java/migration/migrate-weblogic-to-jboss-eap-on-azure-app-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migrate-weblogic-to-jboss-eap-on-azure-app-service.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
Thanks, @jorisaeles!
