### ISSUE TITLE
New Template needed

### ISSUE THREAD

**Issue by sammyfilly** [MicrosoftDocs/azure-dev-docs#1209]
azd init --template todo-python-mongo

**Comment by KarlErickson** [comment]
Hi @sammyfilly - thanks for the feedback, but it looks like the issue boilerplate has been removed. Can you tell us which article you're referring to and provide some more details about the problem? Thanks!

**Comment by KarlErickson** [comment]
@alexwolfmsft it looks like this is for *azure-developer-cli/get-started.md*.
