### ISSUE TITLE
allow_blob_public_access terraform attribute obsolete in azurerm provider 3.0+

### ISSUE THREAD

**Issue by WeetA34** [MicrosoftDocs/azure-dev-docs#1212]
Hello

the terraform example to create the tfstate resources doesn't work.
allow_blob_public_access must be replaced by allow_nested_items_to_be_public in azurerm_storage_account terraform resource.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Store Terraform state in Azure Storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
