### ISSUE TITLE
Wrong host.json and local.settings.json paths

### ISSUE THREAD

**Issue by stavshamir** [MicrosoftDocs/azure-dev-docs#1216]
Thanks for writing this document!
Some of the steps in this documents are:
- Copy this [pom.xml](https://github.com/Azure/azure-functions-java-worker/blob/dev/samples/spring-cloud-example/pom.xml)
- Create the files `host.json` and `local.settings.json` in `src/main/azure`.

However, when running `mvn package` as instructed, the following error is encountered: 
```
Cannot invoke "com.fasterxml.jackson.databind.JsonNode.at(String)" because "hostJson" is null
```

This is because the copied `pom.xml` contains the following lines:
```xml
<hostJson>${project.basedir}/src/main/resources/host.json</hostJson>
<localSettingsJson>${project.basedir}/src/main/resources/local.settings.json</localSettingsJson>
```

The paths specified in the tags point to `src/main/resources` instead of `src/main/azure` as instructed in the beginning of the documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Spring Cloud Function in Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure?toc=%2Fazure%2Fazure-functions%2Ftoc.json#create-a-new-maven-project)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
Fixed in #1217
