### ISSUE TITLE
Terraform in wsl

### ISSUE THREAD

**Issue by tempuku** [MicrosoftDocs/azure-dev-docs#1218]
Hi team!
Please add in docs information about wsl. I've found solution on [stackoverflow](https://stackoverflow.com/questions/71080337/unable-to-create-azura-resources-using-terraform-despite-being-a-subscription-ow#:~:text=sudo%20vim%20%2Fetc%2Fresolv.conf%20and%20change%20nameserver%20value%20to,action%20or%20write%20a%20script%20to%20automate%20it%21), but It's not obvious why does it happen and how this nameserver's ip changing resolve the problem.
Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: defde479-942c-4405-8e0e-aa441f143059
* Version Independent ID: aebf621c-1770-6ddf-695c-3d70be2a56b6
* Content: [Troubleshoot common problems when using Terraform on Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/troubleshoot)
* Content Source: [articles/terraform/troubleshoot.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/troubleshoot.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
