### ISSUE TITLE
Build failure in Jenkins for sample odd-even Azure Function App

### ISSUE THREAD

**Issue by albal** [MicrosoftDocs/azure-dev-docs#1219]
Getting this issue when running the pipeline trying to build a function app:

```[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ odd-or-even-function ---
[INFO] Building jar: /home/jenkins/workspace/AzureFunc/target/odd-or-even-function-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- azure-functions-maven-plugin:1.0.0-beta-7:package (package-functions) @ odd-or-even-function ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.226 s
[INFO] Finished at: 2023-08-03T15:15:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-7:package (package-functions) on project odd-or-even-function: Execution package-functions of goal com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-7:package failed: A required class was missing while executing com.microsoft.azure:azure-functions-maven-plugin:1.0.0-beta-7:package: javax/xml/bind/JAXBException
```

Tried adding these dependencies:
```
<dependencies>
    <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.1</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>2.3.1</version>
    </dependency>
</dependencies>
```

Use Java Open JDK 11 on the build worker. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8984381e-8bfd-776c-c2f7-cc0f608c756d
* Version Independent ID: 73f51811-5f38-a96a-58c6-0683c0242ee4
* Content: [Tutorial - Deploy to Azure Functions using Jenkins](https://learn.microsoft.com/en-us/azure/developer/jenkins/deploy-to-azure-functions)
* Content Source: [articles/jenkins/deploy-to-azure-functions.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/deploy-to-azure-functions.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
CC: @grayzu 

@ehcmke Thank you for your feedback. However, at this time, our current Jenkins support is limited to security fixes.
