### ISSUE TITLE
com.azure.spring.autoconfigure.jms.*

### ISSUE THREAD

**Issue by rcope313** [MicrosoftDocs/azure-dev-docs#1220]
My previous project has used apis com.azure.spring.autoconfigure.jms.ConnectionStringResolver and com.azure.spring.autoconfigure.jms.ServiceBusKey. However, those apis are deprecated & I cannot find where they resolve to now. Please advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba296613-10da-d4c8-16a1-d92127887789
* Version Independent ID: ba296613-10da-d4c8-16a1-d92127887789
* Content: [Migration guide for Spring Cloud Azure 4.0 - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/migration-guide-for-4.0#authentication-changes)
* Content Source: [articles/java/spring-framework/migration-guide-for-4.0.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/migration-guide-for-4.0.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **rujche**

**Comment by KarlErickson** [comment]
@chenrujun can you comment here? Thanks!

**Comment by Netyyyy** [comment]
Hi @rcope313 , thanks for reaching out.
May I know what situation you are using the deprecated apis?
If you want to do authentication,  please refer to [this doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus?tabs=use-a-service-bus-queue%2Cpasswordless#code-the-application), we now provide two authentication methods: [Azure Active Directory (Azure AD) authentication](https://learn.microsoft.com/en-us/azure/service-bus-messaging/authenticate-application) and [Shared Access Signatures (SAS) authentication](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-sas). Hope this can help you.
