### ISSUE TITLE
Clearer instructions.

### ISSUE THREAD

**Issue by IndusFusion1** [MicrosoftDocs/azure-dev-docs#1221]
Hey, New developer to backend and push notifications, trying to follow this step by step but it is poorly written and open to interpretation, it is also out of date in some code parts with updates to flutter and using older .net framework.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94b0eeab-4627-9795-8d11-16187ea82d6c
* Version Independent ID: 963a4858-9631-c1a7-b4ef-e74f74bf95e6
* Content: [Send push notifications to Flutter apps using Azure Notification Hubs via a backend service](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-flutter)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-flutter.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-flutter.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
