### ISSUE TITLE
Error code next_hop_type  = "vnetlocal"

### ISSUE THREAD

**Issue by zorglob** [MicrosoftDocs/azure-dev-docs#1222]
next_hop_type  for spoke1-rt and spoke2-rt should be set to next_hop_type = "VnetLocal" 

It is case sensitive and it will trigger an error if not used correctly as here next_hope_type = "vnetlocal"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b701b1c8-1b00-f16d-36eb-781c3ce062e8
* Version Independent ID: 9c43b7f0-2d05-c946-7ffe-c3599b99958e
* Content: [Create a hub virtual network appliance in Azure using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/hub-spoke-hub-nva)
* Content Source: [articles/terraform/hub-spoke-hub-nva.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/hub-spoke-hub-nva.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
