### ISSUE TITLE
Wront target port in containerapp up example

### ISSUE THREAD

**Issue by Badidzetai** [MicrosoftDocs/azure-dev-docs#1225]
In the page linked, in section "Deploy to web app to Azure", in the version for FastAPI, the command is 

`az containerapp up \
  --resource-group web-fastapi-aca-rg --name web-aca-app \ 
  --ingress external --target-port 80 --source . `

and should instead be

`az containerapp up \
  --resource-group web-fastapi-aca-rg --name web-aca-app \ 
  --ingress external --target-port 3100 --source . `

To fit with the rest of the configuration in the tutorial. I changed the value on my side in the command and it fixed the issues I was getting of the application page not connecting.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 991b7193-7756-1662-ca0d-c89b53c61658
* Version Independent ID: 991b7193-7756-1662-ca0d-c89b53c61658
* Content: [Deploy a Flask or FastAPI web app as a container in Azure Container Apps - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-containerize-simple-web-app?tabs=web-app-fastapi)
* Content Source: [articles/python/tutorial-containerize-simple-web-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-containerize-simple-web-app.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by bobtabor-msft** [comment]
This was fixed some time ago. Closing now.
