### ISSUE TITLE
<xref:IO> cannot be redirected to any link

### ISSUE THREAD

**Issue by ChenxiJiang333** [MicrosoftDocs/azure-dev-docs#1227]
* Reference Article: [azure.mgmt.resource.resources.v2020_10_01.operations.ResourceGroupsOperations class](https://learn.microsoft.com/en-us/python/api/azure-mgmt-resource/azure.mgmt.resource.resources.v2020_10_01.operations.resourcegroupsoperations?view=azure-python#azure-mgmt-resource-resources-v2020-10-01-operations-resourcegroupsoperations-create-or-update)
* Content Source: [docs-ref-autogen/azure-mgmt-resource/azure.mgmt.resource.resources.v2020_10_01.operations.ResourceGroupsOperations.yml](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/main/docs-ref-autogen/azure-mgmt-resource/azure.mgmt.resource.resources.v2020_10_01.operations.ResourceGroupsOperations.yml#L171)

`<xref:IO>` defined cannot be redirected to its reference page like other types, but still shows in the format like it's in the yml file.
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/119990644/fd5aace2-3440-490d-af04-2b9f6be3ec46)

Expected behavior:
IO type should be able to be redirected to its reference link.

Original issue:
https://github.com/Azure/azure-sdk-for-python/issues/31647

**Comment by KarlErickson** [comment]
@ChenxiJiang333 this issues list is intended for customer feedback about the docs in this repo, which doesn't include reference content. Please use Azure DevOps or other, internal channels to provide feedback. Thanks!

CC @bobtabor-msft
