### ISSUE TITLE
Mixed Keys not supported like prefix.keygroup-key

### ISSUE THREAD

**Issue by Thomas-Bergmann** [MicrosoftDocs/azure-dev-docs#123]
Hi,
I got multiple problems with combining Azure Keyvault Spring and Keycloak. It points out that the not supported dot "." in secret keys of Azure Keyvault produces a lot of trouble.

I used the "starter" to provide an simple example.

I used following versions:
com.microsoft.azure:azure-keyvault-secrets-spring-boot-starter:2.2.0
org.springframework.boot:spring-boot-starter-parent:2.2.6.RELEASE
org.keycloak:keycloak-core:9.0.3

# Mixed Keys
This is used by keycloak for example ```keycloak.auth-server-url```, see https://www.keycloak.org/docs/latest/securing_apps/
```
    @Value("${test.minus-key}")
    private String mySecretProperty;
```
throws
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'test.minus-key' in value "${test.minus-key}"
```
# Unbound keys

The unbound keys exception should help operations and developer to avoid configuration mistakes. This will identify typing errors or configuration of older versions.
Important is here the configuration
```
ignoreUnknownFields = false
```
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration based on declaration in
 * org.keycloak.adapters.springboot.KeycloakSpringBootProperties
 *
 */
@ConfigurationProperties(prefix = "test", ignoreUnknownFields = false)
public class DemoConfiguration
{
    @Value("${test.minus-key}")
    private String minusValue = "testValue";
}

throws

```
Caused by: org.springframework.boot.context.properties.bind.UnboundConfigurationPropertiesException: The elements [test.minus.key, test.dot.key] were left unbound.
	at org.s.boot.context.properties.bind.handler.NoUnboundElementsBindHandler.checkNoUnboundElements(NoUnboundElementsBindHandler.java:91)
```

**Comment by KarlErickson** [comment]
@Thomas-Bergmann thanks for the info! We'll look into integrating this guidance into the docs.
@seanli1988 can you comment here? Thanks.

**Comment by saragluna** [comment]
@chenrujun please take a look at this.

**Comment by saragluna** [comment]
@KarlErickson could you please assign this to @chenrujun?

**Comment by KarlErickson** [comment]
@chenrujun please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by han-gao** [comment]
I'll create PR soon.

**Comment by han-gao** [comment]
Hi, @Thomas-Bergmann 

Although in secret keys of Azure Keyvault doesn't support setting `"."`,  it doesn't affect our use `"."` in our project. 
`azure-keyvault-secrets-spring-boot-starter` will load all secrets from Azure Keyvault, and format the secret. 
The format secret code is [`toKeyVaultSecretName()`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot/src/main/java/com/azure/spring/keyvault/KeyVaultOperation.java#L182).
The comment of method explains the formatting rules in detail:
```java
    /**
     * For convention we need to support all relaxed binding format from spring, these may include:
     * <table>
     * <tr><td>Spring relaxed binding names</td></tr>
     * <tr><td>acme.my-project.person.first-name</td></tr>
     * <tr><td>acme.myProject.person.firstName</td></tr>
     * <tr><td>acme.my_project.person.first_name</td></tr>
     * <tr><td>ACME_MYPROJECT_PERSON_FIRSTNAME</td></tr>
     * </table>
     * But azure keyvault only allows ^[0-9a-zA-Z-]+$ and case insensitive, so
     * there must be some conversion between spring names and azure keyvault
     * names. For example, the 4 properties stated above should be convert to
     * acme-myproject-person-firstname in keyvault.
     *
     */
```

At last `azure-keyvault-secrets-spring-boot-starter`  to save these secrets in a map. Our properties(`@Value` or `@ConfigurationProperties`) will get the value from the map, and format the property name as a key for get value. So we just need to keep the property name and secret name after formatting the same. The [README.md](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-keyvault-secrets-readme?view=azure-java-stable#save-secrets-in-azure-key-vault) also describes it.

**Comment by KarlErickson** [comment]
@han-gao is this guidance something we should put in the docs? If so, will you be creating a PR? If not, we can close this issue. Thanks!

**Comment by han-gao** [comment]
@KarlErickson 
This is already pointed out in this [document](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-keyvault-secrets-readme?view=azure-java-stable#save-secrets-in-azure-key-vault).
