### ISSUE TITLE
The important note about alpha and beta is the same.

### ISSUE THREAD

**Issue by torumakabe** [MicrosoftDocs/azure-dev-docs#1233]
Some confusion. Please confirm that the expression is intended. Thanks.

Alpha
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/993850/f2eb0f8a-7596-458c-a6a4-3af37a754ee3)

Beta
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/993850/e41a1bfe-7394-4852-ae33-54cb32bc58cf)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23796963-527c-fb46-9b38-0fab0b60792a
* Version Independent ID: 23796963-527c-fb46-9b38-0fab0b60792a
* Content: [Azure Developer CLI versioning and feature release strategy](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/feature-versioning)
* Content Source: [articles/azure-developer-cli/feature-versioning.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/feature-versioning.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by gkulin** [comment]
This is correct. Neither Alpha nor Beta are recommended for business-critical scenarios. Anything business critical should rely on stable features. We detail that in our versioning strategy here: https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/feature-versioning

**Comment by alexwolfmsft** [comment]
#please-close
