### ISSUE TITLE
Broken Link to DevContainer Spec

### ISSUE THREAD

**Issue by racouster** [MicrosoftDocs/azure-dev-docs#1234]
Dev Container Spec link should be
https://github.com/Azure-Samples/todo-nodejs-mongo/blob/main/.devcontainer/devcontainer.json

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Version Independent ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Content: [Get started using Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=localinstall)
* Content Source: [articles/azure-developer-cli/get-started.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/get-started.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
#please-close
