### ISSUE TITLE
host key verification failed on first SSH

### ISSUE THREAD

**Issue by djsmusa** [MicrosoftDocs/azure-dev-docs#1235]
Hi, I just attempted to follow these instructions, and could not connect to the new VM with SSH - receiving the error "host key verification failed".

I had to use "ssh -o StrictHostKeyChecking=no"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Get Started - Install Jenkins on an Azure Linux VM](https://learn.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
