### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by zuboje** [MicrosoftDocs/azure-dev-docs#1238]
This page and code need to be updated. Is anyone from the Microsoft team considering updating this documentation or not? Are you going to support Flutter long-term? If yes, I suggest updating this article every six months to reflect the current state of Flutter. This code if replicated, is actually not working correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94b0eeab-4627-9795-8d11-16187ea82d6c
* Version Independent ID: 963a4858-9631-c1a7-b4ef-e74f74bf95e6
* Content: [Send push notifications to Flutter apps using Azure Notification Hubs via a backend service](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-flutter)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-flutter.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-flutter.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
