### ISSUE TITLE
Non functioning revision + solution

### ISSUE THREAD

**Issue by lukasareskog** [MicrosoftDocs/azure-dev-docs#1239]
I had to do "import os" in settings.py to get the revision to work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9da0e881-4b7a-f0da-c25f-ac50de8cae27
* Version Independent ID: 9da0e881-4b7a-f0da-c25f-ac50de8cae27
* Content: [Build and deploy a Python web app with Azure Container Apps - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-python-web-app-azure-container-apps-02?tabs=vscode-aztools%2Ccreate-database-psql)
* Content Source: [articles/python/tutorial-deploy-python-web-app-azure-container-apps-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-deploy-python-web-app-azure-container-apps-02.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by bobtabor-msft** [comment]
Internal 182762

**Comment by JimacoMS4** [comment]
Hi @lukasareskog -- thanks very much for your feedback! I also encountered the same issue when I ran through the topic. Based partly on your feedback, we're considering updating how settings are presented in this sample. I'll update the sample and post here once we reach a final decision.

Thanks again for taking the time to provide feedback, and, also, my apologies for the lengthy interlude in responding. We had an internal mix up and lost track of this issue. 

-Jimaco

**Comment by JimacoMS4** [comment]
#assign @JimacoMS4

**Comment by JimacoMS4** [comment]
Hi @lukasareskog -- sorry for the long delay here. It looks like this was addressed in the following PR: https://github.com/Azure-Samples/msdocs-python-django-azure-container-apps/pull/13. I'm going to close this issue. Thanks again for your contribution to our documentation. Please feel free to @-comment me here or open another issue and reference this one if you feel the prob;lem hasn't been adequately addressed.
