### ISSUE TITLE
Deploy Python web app to Azure App Service - problem

### ISSUE THREAD

**Issue by haenf** [MicrosoftDocs/azure-dev-docs#124]
[Enter feedback here]

I studied the VSCode tutorial "Deploy Python web app to Azure App Service on Linux". For some small Python/Flask applications it worked without any problems. But when I tried it out on a couple of bigger Python/Flask application that I have running for more than a year as Azure web apps for Windows, I got stuck. It looks like there is a problem with what happens to virtual environment logic during deployment. Do you have any idea what is going wrong?

requirements.txt
------------------

aniso8601>=8.0.0
asn1crypto>=1.3.0
astroid>=2.3.3
attrs>=19.3.0
cffi>=1.14.0
click>=7.1.1
colorama>=0.4.3
cryptography>=2.9.1
et-xmlfile>=1.0.1
Flask>=1.1.2
Flask-Cors>=3.0.8
Flask-HTTPAuth>=3.3.0
Flask-SQLAlchemy>=2.4.1
gevent>=1.5.0
greenlet>=0.4.15
idna>=2.9
importlib-metadata>=1.6.0
isort>=4.3.21
itsdangerous>=1.1.0
jdcal>=1.4.1
Jinja2>=2.11.2
jsonschema>=3.2.0
lazy-object-proxy>=1.4.3
lml>=0.0.9
MarkupSafe>=1.1.1
mccabe>=0.6.1
passlib>=1.7.2
pycparser>=2.20
pyexcel>=0.5.15
pyexcel-io>=0.5.20
pylint>=2.4.4
pymongo>=3.10.1
PyMySQL>=0.9.3
pyrsistent>=0.16.0
python-dateutil>=2.8.1
pytz>=2019.3
six>=1.14.0
SQLAlchemy>=1.3.16
texttable>=1.6.2
typed-ast>=1.4.1
Werkzeug>=1.0.1
wrapt>=1.11.2
zipp>=3.1.0

import statements in main module
--------------------------------------

This are opening statements in the main module importing things from libraries in the virtual environment

from flask import Flask, make_response, jsonify, g, abort, request, url_for, session
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy
from flask_httpauth import HTTPBasicAuth
from passlib.apps import custom_app_context as pwd_context
from itsdangerous import (TimedJSONWebSignatureSerializer as Serializer, BadSignature, SignatureExpired)
...

output from employment in VSCode
----------------------------------------

3:39:53 PM Trexyz-modApi: Creating zip package...
3:40:02 PM Trexyz-modApi: Starting deployment...
3:42:03 PM Trexyz-modApi: Fetching changes.
3:42:03 PM Trexyz-modApi: Cleaning up temp folders from previous zip deployments and extracting pushed zip file 
        /tmp/zipdeploy/69cc36cd-cea5-49ac-8b15-498c9fe6ffa7.zip (18.56 MB) to /tmp/zipdeploy/extracted
3:42:20 PM Trexyz-modApi: Updating submodules.
3:42:20 PM Trexyz-modApi: Preparing deployment for commit id '659ff9aef7'.
3:42:20 PM Trexyz-modApi: Generating deployment script.
3:42:21 PM Trexyz-modApi: Using cached version of deployment script (command: 'azure -y --no-dot-deployment -r 
        "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"').
3:42:21 PM Trexyz-modApi: Running deployment command...
3:42:21 PM Trexyz-modApi: Command: "/home/site/deployments/tools/deploy.sh"
3:42:21 PM Trexyz-modApi: Handling Basic Web Site deployment.
3:42:24 PM Trexyz-modApi: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
3:42:29 PM Trexyz-modApi: Running post deployment command(s)...
3:42:29 PM Trexyz-modApi: Triggering recycle (preview mode disabled).
3:42:29 PM Trexyz-modApi: Deployment successful.
3:42:33 PM: Deployment to "TmodApi" completed.

detail of default_docker log
------------------------------

2020-04-24T14:44:37.488177991Z Contents of startupScript: gunicorn --bind=0.0.0.0 --
	timeout 600 TmodApi:app
2020-04-24T14:44:37.488449610Z Launching oryx with: -appPath /home/site/wwwroot -
	output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'gunicorn --bind=0.0.0.0 --timeout 600 TmodApi:app'
…
2020-04-24T14:44:37.495429000Z Cound not find build manifest file at '/home/site/wwwroot/oryx-
	manifest.toml'
…
2020-04-24T14:44:39.412483553Z WARNING: Could not find virtual environment directory /home/site/wwwroot/
	antenv.
2020-04-24T14:44:39.412768873Z WARNING: Could not find package directory /home/site/wwwroot/
	__oryx_packages__.
…
2020-04-24T14:44:40.169478384Z [2020-04-24 14:44:40 +0000] [40] [ERROR] Exception in worker process
…
2020-04-24T14:44:40.176182655Z   File "/home/site/wwwroot/TmodApi.py", line 5, in <module>
2020-04-24T14:44:40.176186555Z     from flask_cors import CORS
2020-04-24T14:44:40.176190055Z ModuleNotFoundError: No module named 'flask_cors'
2020-04-24T14:44:40.183947500Z [2020-04-24 14:44:40 +0000] [40] [INFO] Worker exiting (pid: 40)
2020-04-24T14:44:40.265837547Z [2020-04-24 14:44:40 +0000] [38] [INFO] Shutting down: Master
2020-04-24T14:44:40.266117967Z [2020-04-24 14:44:40 +0000] [38] [INFO] Reason: Worker failed to boot.

If I comment out the statement "from flask_cors import CORS" and I do a deployment again, then I get ModuleNotFoundError: No module named 'flask_sqlalchemy'. And so on…

After deployment the original directory structure is present in the Azure web app, also the 'env' directory. But it looks like the env is not visible anymore to the application in Azure…

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 319f2b79-1166-a9cd-9b29-2c9ef64b8a0b
* Version Independent ID: 2a050547-6bb3-2f91-b5b3-000f249abf8c
* Content: [Step 5: Deploy a Python web app to Azure App Service on Linux using VS Code](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-05)
* Content Source: [articles/python/tutorial-deploy-app-service-on-linux-05.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-deploy-app-service-on-linux-05.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@haenf Thanks for writing out this issue in detail. The container log clearly shows that it's not finding the virtual environment folder, antenv, which is where the flask_cors library (and everything else) is supposed to be installed. 

The error before that, however, says "Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'" (interesting typo with "Cound"!). That manifest file, in fact, is what points to "antenv" as the virtual environment, and should be generated during deployment as part of the build process.

In VS Code, can you look at the folder on App Service, as shown in at the end of Step 5 (https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-05), and check whether oryx-manifest.toml is present? If not, that would explain the failure.

Something you can try, then, is to create an application setting for the App Service (right click the "Application Settings" node in the VS Code Azure App Service explorer) called SCM_DO_BUILD_DURING_DEPLOYMENT with the value of true. This setting is supposed to force an oryx build during deployment. By default, a .zip deployment, which is what the VS Code extension seems to use, would have this setting as false, but you can try setting it to true.

Beyond these tests, though, the error suggests a problem with the VS Code deployment process. In that case, the right next step would be to file the issue with the VS Code extension engineering team via https://github.com/microsoft/vscode-azureappservice/issues.

Let me know what you find out.

**Comment by haenf** [comment]
Kraig,

 

Thank you for your quick reply. The SCM_DO_BUILD_DURING_DEPLOYMENT = true statement helped indeed, as you can see from these log details:

 

2020-04-25T09:05:57.133228101Z Extracting to directory /antenv...

2020-04-25T09:06:03.387041527Z Using packages from virtual environment antenv located at /antenv.

2020-04-25T09:06:03.387452057Z Updated PYTHONPATH to ':/antenv/lib/python3.8/site-packages'

2020-04-25T09:06:07.451031876Z [2020-04-25 09:06:07 +0000] [44] [INFO] Starting gunicorn 20.0.4

2020-04-25T09:06:07.452151256Z [2020-04-25 09:06:07 +0000] [44] [INFO] Listening at: http://0.0.0.0:8000 (44)

2020-04-25T09:06:07.452581587Z [2020-04-25 09:06:07 +0000] [44] [INFO] Using worker: sync

2020-04-25T09:06:07.462997630Z [2020-04-25 09:06:07 +0000] [46] [INFO] Booting worker with pid: 46

2020-04-25T09:06:09.401517534Z  * Serving Flask app "TmodApi" (lazy loading)

2020-04-25T09:06:09.402102376Z  * Environment: production

2020-04-25T09:06:09.408856458Z    WARNING: This is a development server. Do not use it in a production deployment.

2020-04-25T09:06:09.408881860Z    Use a production WSGI server instead.

2020-04-25T09:06:09.408950165Z  * Debug mode: on

2020-04-25T09:06:09.419781238Z  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)

2020-04-25T09:06:09.420881816Z  * Restarting with stat

2020-04-25T09:06:09.915294816Z [2020-04-25 09:06:09 +0000] [49] [INFO] Starting gunicorn 20.0.4

2020-04-25T09:06:09.916199080Z [2020-04-25 09:06:09 +0000] [49] [ERROR] Connection in use: ('0.0.0.0', 8000)

 

But then, as you can see from the last line, I ran into the next error. I have no idea yet where that comes from…

 

Kind regards,

Hans Nederbragt

 

enference  infologica  |  +31 6 55 378 352  |  www.enference.nl

**Comment by kraigb** [comment]
It looks like gunicorn is trying to use port 8000 but the app is running on 5000. In that case, I believe you need to change the -b 0.0.0.0 line in your startup command to -b 0.0.0.0:5000 (see https://docs.gunicorn.org/en/stable/settings.html#bind). Or to be more precise, try this with your startup command:

gunicorn --bind=0.0.0.0:5000 --timeout 600 TmodApi:app

**Comment by haenf** [comment]
Kraig,

 

In my code I have set the wsgi server to its defaults ('0.0.0.0', 8080) and then gunicorn had no problems with it. According to the log files the building process now functions ok. But there is still some kind of error in the container, because I can't approach it with Postman. I don't know what is going on inside, and I find it hard to debug (the source without being containerized works fine…). I think it is a beautiful workflow, from VSCode to Azure, but on the other hand it is not very transparent (at least not for me)… 

 

So for now I returned to 'simple old' Windows Server and IIS, less elegant - but it works :- )

 

Thank you for your help though!

 

Kiind regards,

Hans Nederbragt

 

enference  infologica  |  06 - 55 378 352  |  www.enference.nl

**Comment by kraigb** [comment]
I'm glad you're at least unblocked. Nevertheless, the engineering team will likely want to know about the issue you're having. Can you file one at https://github.com/microsoft/vscode-azureappservice/issues so they can investigate?

In the meantime, I'm closing this docs issue as it appears resolved. But feel free to open again if needed.
