### ISSUE TITLE
why is it not all in python?

### ISSUE THREAD

**Issue by diegobentley** [MicrosoftDocs/azure-dev-docs#1241]
your documentation in general is terrible. All over the place. This one in particular, for example, is called: **Access Azure Storage using the Azure libraries for Python**. So you think, "wow that's cool, finally an example with just ONE sdk".... but no. It's just another bad taste joke from the Microsoft geniuses. 

Step 4.a.5 forces you to use Azure CLI. 

Then you might think, "ok, not so bad. Let's just look online for the python equivalent of that CLI command"... there is no such thing.

How this is such a profitable company is beyond me. 

the CLI command:
```
az role assignment create --assignee <AZURE_CLIENT_ID> \
    --role "Storage Blob Data Contributor" \
    --scope "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/PythonAzureExample-Storage-rg/providers/Microsoft.Storage/storageAccounts/pythonazurestorage12345/blobServices/default/containers/blob-container-01"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2df172b-4e8a-109d-f07b-dcf904a96a3e
* Version Independent ID: b2df172b-4e8a-109d-f07b-dcf904a96a3e
* Content: [Use Azure Storage with the Azure SDK for Python - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-storage-use?tabs=bash)
* Content Source: [articles/python/sdk/examples/azure-sdk-example-storage-use.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/examples/azure-sdk-example-storage-use.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by rohit-ganguly** [comment]
Hi, thanks for the feedback. The `azure-mgmt-authorization` library in the Python SDK allows you to do this, but it's currently not well-documented or accepted widely as official guidance. We're working on a good way to get this guidance into our documentation and make it more accessible to developers.

[This link](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2022_04_01.operations.roleassignmentsoperations?view=azure-python) should have the create operation with the same parameters needed. You'll need to instantiate an [AuthorizationManagementClient](https://learn.microsoft.com/en-us/python/api/azure-mgmt-authorization/azure.mgmt.authorization.v2022_04_01.authorizationmanagementclient?view=azure-python) and then access this role assignments client through the role_assignments attribute.

I've created [this issue](https://github.com/Azure/azure-sdk-for-python/issues/33126) to track in our Azure SDK repo for any future updates we bring. 
 
Thanks again for the feedback.
