### ISSUE TITLE
Wrong port in docs

### ISSUE THREAD

**Issue by plasne** [MicrosoftDocs/azure-dev-docs#1244]
The example shows creating an app on port 3100 but then the `az containerapp up` it shows it using port 80.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 991b7193-7756-1662-ca0d-c89b53c61658
* Version Independent ID: 991b7193-7756-1662-ca0d-c89b53c61658
* Content: [Deploy a Flask or FastAPI web app as a container in Azure Container Apps - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-containerize-simple-web-app?tabs=web-app-flask)
* Content Source: [articles/python/tutorial-containerize-simple-web-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-containerize-simple-web-app.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by JimacoMS4** [comment]
Hi @planse -- thanks for your feedback! We've fixed this issue and the `az containerapp up` command now uses port 3100. Since this item has been fixed, at this time, I'm going to go ahead and close this issue.

Thanks for helping us improve our documentation!

-Jimaco

**Comment by JimacoMS4** [comment]
**Note**: Issue also reported and resolved here: https://github.com/MicrosoftDocs/azure-dev-docs/issues/1207.
