### ISSUE TITLE
Wrong filename in the azure devops pipeline task for azd?

### ISSUE THREAD

**Issue by Banchio** [MicrosoftDocs/azure-dev-docs#1245]
When using AzDO as a provider, the final step is **azd as an Azure DevOps task** but then it refers to a **.github\workflows\azure-dev.yml**
I guess this should be **azdo/pipeline/azure-dev.yml** maybe a typo, HTH

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f953ea6-ae2f-b258-3eac-e86a12398d5a
* Version Independent ID: 4f953ea6-ae2f-b258-3eac-e86a12398d5a
* Content: [Configure a pipeline and push updates using GitHub Actions or Azure DevOps](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub)
* Content Source: [articles/azure-developer-cli/configure-devops-pipeline.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/configure-devops-pipeline.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thank you, this will be resolved in an upcomign PR.

#please-close
