### ISSUE TITLE
Swashbuckle step 2 remove

### ISSUE THREAD

**Issue by fileman** [MicrosoftDocs/azure-dev-docs#1247]
I think the step 2 should be removed or wrong namespace in file, since the following don't exist

`using Microsoft.AspNetCore.Datasync.Swashbuckle;` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b58f99f9-9e79-1af2-8c23-0fce5927b9ad
* Version Independent ID: b58f99f9-9e79-1af2-8c23-0fce5927b9ad
* Content: [How to use the ASP.NET Core SDK for Azure Mobile Apps](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/server/dotnet-core)
* Content Source: [articles/mobile-apps/azure-mobile-apps/howto/server/dotnet-core.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/howto/server/dotnet-core.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Fixed in source - will be included in next publish.

#please-close
