### ISSUE TITLE
Deploy code from a GitHub repository 

### ISSUE THREAD

**Issue by Hasanofal** [MicrosoftDocs/azure-dev-docs#1248]
I'm trying to make a python script that deploys an app from GitHub.

I followed the tutorial, and everything is working until the last step that sets the source control for the app from a GitHub repo.

Here is the error I get:
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: {"Code":"BadRequest","Message":"Repository 'UpdateSiteSourceControl' operation failed with Microsoft.Web.Hosting.SourceControls.OAuthException: GitHub GetRepository: Bad credentials\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<ProcessResponse>d__34`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.SourceControls.GitHubProxy.<GetRepository>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.GitHubSiteRepositoryProvider.<UpdateSiteSourceControl>d__3.MoveNext() in C:\\__w\\1\\s\\src\\Hosting\\AdministrationService\\Microsoft.Web.Hosting.Administration\\Providers\\GitHubSiteRepositoryProvider.cs:line 43\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Administration.WebCloudController.<>c__DisplayClass369_1.<<UpdateSiteSourceControl>b__1>d.MoveNext() in C:\\__w\\1\\s\\src\\Hosting\\AdministrationService\\Microsoft.Web.Hosting.Administration\\Controllers\\WebCloudController.cs:line 11602\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.AsyncHelper.RunSync[TResult](Func`1

From the error message, it looks like azure doesn't have access to the repo. But my repo is public which I forked from the tutorial repo. 

If I must give access to azure from GitHub is there a way to do it from the python SDK instead of doing it from the azure portal?

Thank you for you support!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ded5425-f840-6dc7-ee03-8d9745bba378
* Version Independent ID: 1ded5425-f840-6dc7-ee03-8d9745bba378
* Content: [Create and deploy a Python web app to Azure App Service using the Azure SDK libraries - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-web-app?tabs=cmd)
* Content Source: [articles/python/sdk/examples/azure-sdk-example-web-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/examples/azure-sdk-example-web-app.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by Hasanofal** [comment]
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/135200340/a29081ee-6d8d-4b7a-b3b5-2914b5f86c8c)

Just tried deploying from the portal and getting same error even after authorizing access

**Comment by JimacoMS4** [comment]
Hi @Hasanofal -- Apologies for the tardy response on this issue, as I mentioned in the other issue you filed, we had an internal mix-up and lost track of a few issues. 

Can you provide a little more information about the particular situation here? In the other issue you filed. https://github.com/MicrosoftDocs/azure-dev-docs/issues/1249, you mentioned that you were trying to run the tutorial using `AzureDefaultCredential` and a service principal. Did you encounter this situation while running the tutorial as-is, meaning with `AzureCliCredentail` and having logged into your Azure user account via `az login` or you using some other account/login? 

Thanks - Jimacol

**Comment by JimacoMS4** [comment]
Related to https://github.com/MicrosoftDocs/azure-dev-docs/issues/1249

**Comment by Hasanofal** [comment]
Hi,

After I filed the other issue and before finding the [ZIP file workaround](https://github.com/MicrosoftDocs/azure-dev-docs/issues/1249#issuecomment-1820379823), I went back to using `AzureCliCredentail`.

My question was about authorizing azure to access the Github account that owns the repository I want to deploy from.

If I try to run the tutorial as is, without giving access I get the error I wrote in the question. I think the tutorial should mention that you need to authorize azure to access your github account before running the code.

Right now the only way I know to authorize Azure is to create a web app on the portal and go to deployment center and clicking authorize:
![Screenshot from 2023-11-21 11-45-15](https://github.com/MicrosoftDocs/azure-dev-docs/assets/135200340/1f3a85b7-db3d-4862-8953-dbdae557f40c)

It will open a window that allows you to give access:
![Screenshot from 2023-11-21 11-46-28](https://github.com/MicrosoftDocs/azure-dev-docs/assets/135200340/6ef5c701-ea32-41f9-a211-be09442fee45)

After doing this, you can run the tutorial with no issues and deploy new apps from the SDK since Azure already has access.

My question is can I authorize access to my Github account from the SDK without using the portal?

If not, its fine for me I can close the issue since I will use the same repo in all my web apps so I can give access once using the portal.

If you want to replicate the error you can try removing the authorization by going to your github account -> settings -> applications -> authorized OAuth apps -> and removing Azure App Service:
![Screenshot from 2023-11-21 11-44-35](https://github.com/MicrosoftDocs/azure-dev-docs/assets/135200340/3788aad8-21b9-4223-b89b-65389e5721f9)

And try to run the tutorial again.

**Comment by JimacoMS4** [comment]
@JimacoMS4 self reference for tracking

**Comment by JimacoMS4** [comment]
Hi @Hasanofal -- thanks for your explanation. I'll reach out to our team and see if I can find out if you can authorize your Azure account w/GitHub via the SDK. Barring that, I'll see if you can at least authorize your account without first creating a web app. Whatever the solution is, I totally agree that we need to explain this better in the article. I'll keep you posted.

**Comment by JimacoMS4** [comment]
Hi @Hasanofal -- I checked with the Azure App Service documentation team. Their take is that, currently, you need to go through the portal flow to authorize App Service Build Service with GitHub. This necessary to configure the CI/CD flow. 

That said, I looked at the topic in a little more detail. Based on the listed equivalent Azure CLI commands, it's clear to me that what the Python script should be implementing is External Git deployment (manual integration). For public repos, this form of deployment requires no pre-authorization with GitHub since it doesn't deposit any artifacts in the repo. To this end, I added the `is_manual_integration` parameter to the call that configures source control:

```python
poller = app_service_client.web_apps.begin_create_or_update_source_control(RESOURCE_GROUP_NAME,
    WEB_APP_NAME, 
    { 
        "location": "GitHub",
        "repo_url": REPO_URL,
        "branch": "master",
        "is_manual_integration": True
    }
)
```

This sets up External Git with manual integration in your web app. You do have to manually sync the web app to pull your code from the configured repo/branch. I added a section that uses the `az webapp deployment source sync` command to do just that. There may be a Python API to do this, and I might, at a later date, add that to the script.

In addition to using the CLI credential, I've tested this script using `DefaultAzureCredential` and running it with both my Azure creds and a service principal. I gave the service principal the Owner role on the subscription, but I suspect you might be able to grant it the Contributor role (less privileged) instead.

Please have a look at the topic again. I'll leave this issue open for a few days in case you have additional comments and then close it.

Thanks again for taking the time to help us improve our documentation,

Jimaco

**Comment by JimacoMS4** [comment]
Hi @Hasanofal so, you can, if you want to, sync the web app with the repo in python with this API: https://learn.microsoft.com/en-us/python/api/azure-mgmt-web/azure.mgmt.web.v2019_08_01.operations.webappsoperations?view=azure-python#azure-mgmt-web-v2019-08-01-operations-webappsoperations-sync-repository.

You can add the following call at the end of the script if you want to do this programmatically:

```python
app_service_client.web_apps.sync_repository(RESOURCE_GROUP_NAME, WEB_APP_NAME)
```
**Note** -- the method returns `None`. I might add this to the topic next week. Then again, you'll be required to sync anytime you push a new change to the repo/branch, so maybe I'll leave it as-is with the CLI command. At any rate, will close this in the next few days.

**Comment by JimacoMS4** [comment]
Hi @Hasanofal I made the change I mentioned in the previous comment. The script now includes a call to sync with the repository (deploy the code). At this time, I'm going to close this issue. If you think there is still something that needs to be addressed, please open a new issue and reference this issue from it. Thanks again for your help improving our documentation.

Best,

Jimaco
