### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by hire-him** [MicrosoftDocs/azure-dev-docs#125]
Why use ansible when helm deployment is possible. I am trying to understand use case ? or ansible and helm are complimentary solutions to each other ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2283dc1-c38e-81ee-c9d9-fd986933b1d5
* Version Independent ID: 39d3c09c-6179-ea2e-7e4b-38bbe5026026
* Content: [Tutorial - Configure Azure Kubernetes Service (AKS) clusters in Azure using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/aks-configure-clusters?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Faks%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [articles/ansible/aks-configure-clusters.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/aks-configure-clusters.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@hire-him Thank you for the question. Unfortunately, we don't offer subjective opinions regarding comparing products - especially when one of those products is not something we document. However, a quick web search does return several links where others have compared Ansible and Helm.

#please-close
