### ISSUE TITLE
Found a bug in passwordless call

### ISSUE THREAD

**Issue by dasha91** [MicrosoftDocs/azure-dev-docs#1251]
When calling the call mentioned in the documentation: az connection create postgres --resource-group $resourceGroup \
       --connection postgres_conn \
       --target-resource-group $resourceGroup \
       --server $server \
       --database $databaseName \
       --user-account \
       --query authInfo.userName \
       --output tsv 

I get the following error: 

The behavior of this command has been altered by the following extension: serviceconnector-passwordless
Client type is not specified, use default one: --client-type none
Command execution failed, command is: az postgres server db show --ids /subscriptions/ad70ac39-7cb2-4ed2-8678-f192bc4272b6/resourceGroups/aks-postgres-compete/providers/Microsoft.DBforPostgreSQL/servers/aks-cli-postgres1234/databases/demo, error message is: 
 ERROR: 'db' is misspelled or not recognized by the system.

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

If I run the following code: az postgres db show -g $resourceGroup -s $server -n $databaseName; 

I can see the database and server are there and valid: 

{
  "charset": "UTF8",
  "collation": "English_United States.1252",
  "id": "/subscriptions/ad70ac39-7cb2-4ed2-8678-f192bc4272b6/resourceGroups/aks-postgres-compete/providers/Microsoft.DBforPostgreSQL/servers/aks-cli-postgres1234/databases/demo",
  "name": "demo",
  "resourceGroup": "aks-postgres-compete",
  "type": "Microsoft.DBforPostgreSQL/servers/databases"
}

I've also already upgraded my CLI using az upgrade.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b87dfa07-47f3-2854-fc2e-13c4e925403e
* Version Independent ID: c54574d0-8fb1-b5a1-56ff-862e031a4124
* Content: [Use Spring Data JDBC with Azure Database for PostgreSQL - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql?tabs=passwordless%2Cservice-connector&pivots=postgresql-passwordless-single-server)
* Content Source: [articles/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql.md)
* Service: **postgresql**
* GitHub Login: @KarlErickson
* Microsoft Alias: **v-yeyonghui**

**Comment by KarlErickson** [comment]
@hui1110 can you please take a look? Thanks!

**Comment by hui1110** [comment]
@dasha91 This looks like an issue with the extension `serviceconnector-passwordless`, I created this [issue](https://github.com/Azure/azure-cli/issues/27469).

**Comment by KarlErickson** [comment]
Thanks, @hui1110!
