### ISSUE TITLE
It doesn't describe the steps to create a terraform configuration file.

### ISSUE THREAD

**Issue by rlmishra** [MicrosoftDocs/azure-dev-docs#1255]
It doesn't describe the steps to create a terraform configuration file.

**Comment by TomArcherMsft** [comment]
@rlmishra As @KarlErickson mentions, we need some additional context. If you could supply the following, that would help mee to address your concerns:
- Article URL
- Expectations that were not met

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
