### ISSUE TITLE
Terraform provider azuread is not used anywhere on "how-to"

### ISSUE THREAD

**Issue by mloskot** [MicrosoftDocs/azure-dev-docs#1259]
Why this page instructs to add this to `providers.tf` 

```hcl
    azuread = {
      source = "hashicorp/azuread"
    }
```

while the `azuread` is not used anywhere in this how-to?

IMHO, the hole sequence of How-To's starting from https://learn.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop would appreciate review and clean-up.

See also
- https://github.com/MicrosoftDocs/azure-dev-docs/issues/1258

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 954f37c7-64b8-759a-6f67-20d7847a9a85
* Version Independent ID: 954f37c7-64b8-759a-6f67-20d7847a9a85
* Content: [Configure Azure Virtual Desktop Session Hosts using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host)
* Content Source: [articles/terraform/create-avd-session-host.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-avd-session-host.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
