### ISSUE TITLE
Creating a service principal step fails as a required parameter isn't specified

### ISSUE THREAD

**Issue by RickGarnerBHR** [MicrosoftDocs/azure-dev-docs#1261]
In **Create a service principal** (Azure Powershell tab) the call to _$sp = New-AzADServicePrincipal..._  fails as it requires a -Scope argument

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5cbb8da-d7df-723f-c7a5-5872381bb4aa
* Version Independent ID: fbd4f2e5-d160-236e-8cc0-ea58ac18a1d0
* Content: [Install Terraform on Windows with Azure PowerShell](https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-windows-powershell?tabs=azure-powershell#authenticate-to-azure-via-a-microsoft-account)
* Content Source: [articles/terraform/get-started-windows-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/get-started-windows-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@RickGarnerBHR Thank you for the feedback. I just copied and pasted the code and it works. Also, the reference document for that cmdlet doesn't appear to show -Scope as a required parameter. Please share your cmdlet call and the error message you're getting.

![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/4117258/9fe0d52e-e756-4ae8-b6d8-ac82b2411bf0)

**Comment by RickGarnerBHR** [comment]
I retried it with a different login / azcontext and it worked ok. Sorry to waste your time.
Rick

**Comment by TomArcherMsft** [comment]
@RickGarnerBHR I'm happy you were able to get it to work! Thanks for updating us.
