### ISSUE TITLE
AuthenticationToken class does not exists

### ISSUE THREAD

**Issue by tfierens** [MicrosoftDocs/azure-dev-docs#1262]
I'm following the article from https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication?pivots=vs2022-windows

and there are a couple of issues:

1. It states to install Microsoft Identity Library (MSAL), but the latter does not exists, so I installed Microsoft Identity Client. I assume this is correct but it is confusing to have another name in the article.

2. When pasting the function  "public async Task<AuthenticationToken> GetAuthenticationToken()" into my page, I managed to address all the errors bar the "AuthenticationToken". When I press Ctrl+. , it only gives me the option to install "Microsoft.AspNetCore.Authentication.Abstractions" which I assume is invalid.

Why isn't it finding the AuthenticationToken in the Microsoft Identity Library?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Version Independent ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Content: [Add authentication to your .NET MAUI app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication?pivots=vs2022-windows)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Todo:
1. Ensure MSAL is identified correctly.
2. Add the appropriate usings statement to the top of the app - it's Microsoft.Datasync.Client.Authentication (for the OP)

For @tfierens:  We provide support over on the GitHub repo - https://github.com/azure/azure-mobile-apps.  It's a great place to ask questions of the community as well!

**Comment by tfierens** [comment]
@adrianhall thanks for that. I missed the Datasync using statement but at the top of the article where it mentions that that the Microsoft Identity Library Nuget should be installed, it would be no harm to add that the Datasync Nuget should also be installed.

Thanks,

Thierry

**Comment by adrianhall** [comment]
Re-reviewing this (with the code in front of me)

1) When talking about installing the NuGet, we step-by-step walk through and explicitly mention adding Microsoft Identity Client - see https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication?pivots=vs2022-windows#configure-a-native-client-application (at the bottom of the section)

2) AuthenticationToken is available in Microsoft.Datasync.Client namespace - we explicitly add the Microsoft.Datasync.Client namespace in the same section with this code snippet:

```csharp
using Microsoft.Datasync.Client;
using Microsoft.Identity.Client;
using System.Diagnostics;
```

(this is cut and paste from the document). 

Also, in the quickstart, the Datasync.Client NuGet is pre-added.  In the client HOW-TO (which is what you would refer to with your own application away from the tutorial), we explicitly note the addition of the correct NuGet.

I do have a heading to add to separate the creation of the app registration from the code.  But that's the only change I see happening here.

#please-close
