### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by Kavikrishnanp** [MicrosoftDocs/azure-dev-docs#1263]
I see a small typo here "Use [az container create](https://learn.microsoft.com/en-us/cli/azure/container#az-container-create) to create **and** Azure Container Instance."  i guess its supposed to be "create **an** Azure Container Instance". Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc269e1e-9a34-d676-bdd0-979e565bbdc4
* Version Independent ID: 88a4c2d4-1dff-3afd-9dde-652c1f93ac4a
* Content: [Tutorial - Use Azure Container Instances as a Jenkins build agent](https://learn.microsoft.com/en-us/azure/developer/jenkins/azure-container-instances-as-jenkins-build-agent)
* Content Source: [articles/jenkins/azure-container-instances-as-jenkins-build-agent.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/azure-container-instances-as-jenkins-build-agent.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Kavikrishnanp Thanks for the correction. #sign-off
