### ISSUE TITLE
Terraform not a complete open source tool anymore

### ISSUE THREAD

**Issue by PriyanshNegi** [MicrosoftDocs/azure-dev-docs#1265]
We can add about terraform changing its license to BSL to aware people.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0717ae9-8312-3218-5c54-8dc9f56170fc
* Version Independent ID: ba9cefc2-294a-0f38-16f6-f37f7fe98f76
* Content: [Overview of Terraform on Azure - What is Terraform?](https://learn.microsoft.com/en-us/azure/developer/terraform/overview)
* Content Source: [articles/terraform/overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/overview.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@PriyanshNegi 

Thanks for the feedback.

The article, [Overview of Terraform on Azure - What is Terraform?](https://learn.microsoft.com/en-us/azure/developer/terraform/overview), introduces the Terraform Azure providers and explains some of the benefits of using Terraform on Azure. 

The HashiCorp Terraform licensing terms don't impact any of that content.
