### ISSUE TITLE
Invalid document link 

### ISSUE THREAD

**Issue by hund030** [MicrosoftDocs/azure-dev-docs#1267]
In Prerequisites section, there is invalid document link:
The resources and their configuration created in the [previous article][./tutorial-deploy-python-web-app-azure-container-apps-02.md] of this tutorial series.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad995982-9156-c13c-5295-a52b2bd3cdd2
* Version Independent ID: ad995982-9156-c13c-5295-a52b2bd3cdd2
* Content: [Configure CI/CD for a Python web app in Azure Container Apps - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-python-web-app-azure-container-apps-03?tabs=azure-portal%2Cgit-github)
* Content Source: [articles/python/tutorial-deploy-python-web-app-azure-container-apps-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-deploy-python-web-app-azure-container-apps-03.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by JimacoMS4** [comment]
Hi @hund030,

Thanks so much for your feedback, and your help improving our documentation! The link has been fixed and the updated topic is now live. I'm going to go ahead and close this issue.
Thanks again, 

Jimaco

**Comment by JimacoMS4** [comment]
#please-cl;ose

**Comment by JimacoMS4** [comment]
@bobtabor-msft @KarlErickson Can one of you please close this. The topic has been updated.
