### ISSUE TITLE
Description of "azd down" can cause unexpected deletion for user resources.

### ISSUE THREAD

**Issue by noiri-hub** [MicrosoftDocs/azure-dev-docs#1268]
"azd down" command can delete all resources in resource group easily.
Some users deleted their resource by mistake since they thought this "azd down" delete only the resources created by "azd up".
It is just as dangerous as complete mode deployment in ARM template, so I think there should be as much warning.

Azure Resource Manager deployment modes - Complete mode
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-modes#complete-mode

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ca20ae88-3294-f0cf-9cdf-25f1afda9e3d
* Version Independent ID: ca20ae88-3294-f0cf-9cdf-25f1afda9e3d
* Content: [Azure Developer CLI reference](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-down)
* Content Source: [articles/azure-developer-cli/reference.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/reference.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by Coruscate5** [comment]
Same thing just happened to me - 1.5 at least said "16 resources would be deleted" even though bicep just creates one, at least I can say "no" before deletion

**Comment by alexwolfmsft** [comment]
Recent versions of AZD now prompt for a confirmation and list the number of resources that will be deleted. You can also use the --force or --purge flags to set whether this prompt appears and whether items that are soft-deleted by default should be purged.

[azd down reference](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#azd-down)

#please-close
