### ISSUE TITLE
Mention using AZD devcontainer feature

### ISSUE THREAD

**Issue by mattmazzola** [MicrosoftDocs/azure-dev-docs#1269]
I think the page is not very clear about how to use or apply AZD to a dev container and may be hard for users to understand what to do.

The page has a link to [Advanced Installation Methods](https://github.com/Azure/azure-dev/blob/main/cli/installer/README.md#advanced-installation-scenarios) which suggest adding something like `RUN curl -fsSL https://aka.ms/install-azd.sh | bash -s -- --install-folder "~/mybin"` to your Docker file, but this may be intimidating for new users.

I saw there is an AZD dev container feature here:
https://github.com/azure/azure-dev/pkgs/container/azure-dev%2Fazd

I think the dev container documentation should say something like this:

1. Add the `azd` feature to your `devcontainer.json`:
```
	"features": {
                ...
		"ghcr.io/azure/azure-dev/azd:0": {},
                ....
	}
```

2. Rebuild your .devcontainer

This makes it very clear and explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Version Independent ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Content: [Install the Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux)
* Content Source: [articles/azure-developer-cli/install-azd.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/install-azd.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thank you, this will be resolved in an upcoming docs release.

#please-close
