### ISSUE TITLE
Syntax error in Custom Docker Example

### ISSUE THREAD

**Issue by mattmazzola** [MicrosoftDocs/azure-dev-docs#1270]
The `web` and `project` lines are under the `docker` section or object, but `web:` is supposed to indicate another `service`

It should be removing the indentation of `web` and move `project` under it.
Something like

```diff
name: yourApp-aca
metadata:
    template: yourApp-aca@0.0.1-beta
services:
  api:
    project: src/api
    language: js
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ../
-     web:
-     project: src/web
+ web:
+   project: src/web
    language: js
    host: containerapp
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a201d9c1-ae07-63bf-d364-95fc91641876
* Version Independent ID: a201d9c1-ae07-63bf-d364-95fc91641876
* Content: [Azure Developer CLI's azure.yaml schema](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-schema)
* Content Source: [articles/azure-developer-cli/azd-schema.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/azd-schema.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thank you, this will be resolved in an upcoming PR.

#please-close
