### ISSUE TITLE
More Detailed Descriptions

### ISSUE THREAD

**Issue by lydiacrimedev** [MicrosoftDocs/azure-dev-docs#1271]
I feel some of the descriptions could expand just a tad further. I know you're trying to keep descriptions short but some of them do not explain what the service is or does.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acf3b7e8-ad14-606e-ebd3-71c3db32dd3a
* Version Independent ID: acf3b7e8-ad14-606e-ebd3-71c3db32dd3a
* Content: [Key Azure services for developers](https://learn.microsoft.com/en-us/azure/developer/intro/azure-developer-key-services?ns-enrollment-type=Collection&ns-enrollment-id=22emcr3216gr5r)
* Content Source: [articles/intro/azure-developer-key-services.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/intro/azure-developer-key-services.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thank you for your feedback. We are planning to extensively revamp this article in the next ~3 months, and we will comprehensively review the descriptions and how we're presenting the scenarios for the services in this article at that time. Your feedback has been added to the internal work item that is tracking that work.
