### ISSUE TITLE
How do I configure AZD to execute a Dry Run or What If deployment to evaluate process?

### ISSUE THREAD

**Issue by mattmazzola** [MicrosoftDocs/azure-dev-docs#1273]
I often write deployment scripts which by default perform [WhatIf](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deploy-what-if?tabs=azure-powershell%2CCLI) deployments. This allows verifying all the resources and names are as intended before executing the full deployment which may be costly.

It also can add extra mitigation against mistakes because the user has to opt-in to full deployments

I wanted to know if there is first class support for this type of model in AZD or if there is planned support on the roadmap?

Perhaps there could be a configuration option like `azd config set whatIfDeploymentDefault true` to enable the behavior I describe above.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2c0acc4-c861-1e33-9169-fb04aeabb7d1
* Version Independent ID: e2c0acc4-c861-1e33-9169-fb04aeabb7d1
* Content: [Azure Developer CLI FAQ](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/faq)
* Content Source: [articles/azure-developer-cli/faq.yml](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/faq.yml)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by KarlErickson** [comment]
Hi @mattmazzola - thanks for the input! I've assigned this issue to the content publisher who owns the article. However, since, this is more of a product question than a documentation issue, I suggest that you also ask your question at the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site.

**Comment by mattmazzola** [comment]
Ok, thanks, I didn't know about the `--preview` option. I will test it out and see if it fits the neeed.

I originally opened the issue because I thought this could be another Frequently Asked Question that would be useful to add to the documentation.  There is a some fragmentation of how this preview operation is done across various Azure products

Product | Term
--- | ---
azcopy | --dry-run
az cli | --what-if
azd | --preview

This means when customer transitions from each produce looking for the term they had learned, they may think it doesn't exist; however, it does but it is called something else.

### Example:
Question: How do I execute Dry Run or What If deployments using azd?
Answer: Use the [`--preview` option](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/reference#options-25) when executing commands

**Comment by alexwolfmsft** [comment]
Thank you, this is great feedback - I will pass this along to other members of our product team and look at surfacing this information more obviously, such as the FAQ you mentioned.

**Comment by alexwolfmsft** [comment]
#please-close
