### ISSUE TITLE
Need to specify 'Scope' when granting a role to a service principal

### ISSUE THREAD

**Issue by huwgeric** [MicrosoftDocs/azure-dev-docs#1274]
[Enter feedback here]

In the section of "Create a service principal", at step 6:
$sp = New-AzADServicePrincipal -DisplayName <service_principal_name> -Role "Contributor"

'-Scope' should be used here to specify the scope of role 'contributor'.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0a29143-0d6f-8a49-8c19-e6a48c5f9ba5
* Version Independent ID: e3c8bcff-6ae2-79d0-92c9-18fb5cd58f5b
* Content: [Configure Terraform in Azure Cloud Shell with Azure PowerShell](https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-powershell?tabs=azure-powershell#authenticate-to-azure-via-a-microsoft-account)
* Content Source: [articles/terraform/get-started-cloud-shell-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/get-started-cloud-shell-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
