### ISSUE TITLE
After all of the steps my organization will not allow the app to authenticate

### ISSUE THREAD

**Issue by blanthor** [MicrosoftDocs/azure-dev-docs#1277]
Documentation did not state how to create a new directory from my Visual Studio Enterprise account. I proceeded as best I could. When I finally ran the Android app, I was redirected to the Microsoft Account and not allowed to authenticate. Error message: "Needs admin approval \n unverified \n needs permissions to access resources in your organization". There is also incomplete information on how to publish from VS 2022.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Version Independent ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Content: [Add authentication to your .NET MAUI app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Unfortunately, this is an organizational restriction that we can neither predict, nor advise on as it pertains to how your organization has set up the Microsoft Entra ID.

#please-close
