### ISSUE TITLE
wrong link for how-to guides

### ISSUE THREAD

**Issue by adalfa** [MicrosoftDocs/azure-dev-docs#1279]
The link for the left menu entry
how-to guides-> terraform how-to guides for Azure Service->Networking->Azure Application Gateway->Application Gateway ingress controller in AKS
points to https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview where I cannot see any how-to for terraform

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0717ae9-8312-3218-5c54-8dc9f56170fc
* Version Independent ID: ba9cefc2-294a-0f38-16f6-f37f7fe98f76
* Content: [Overview of Terraform on Azure - What is Terraform?](https://learn.microsoft.com/en-us/azure/developer/terraform/overview)
* Content Source: [articles/terraform/overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/overview.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
