### ISSUE TITLE
fileUris  (404) Not Found

### ISSUE THREAD

**Issue by spawnmarvel** [MicrosoftDocs/azure-dev-docs#1281]
[Enter feedback here]
Hi, I am doing the tutorial and there is an error on the file uri for the custom script extension, 404.

"Error creating the VM extension: (VMExtensionProvisioningError) VM has reported a failure when processing extension 'winrm-extension' (publisher 'Microsoft.Compute' and type 'CustomScriptExtension'). Error message: \"Failed to download all specified files. Exiting. Error Message: CustomScript failed to download the blob https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1 because it does not exist. Please create the blob and try again, the response code and message returned were: \"The remote server returned an error: (404) Not Found.

Could you update with correct uri?
Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb5f4824-c6e0-5b17-d79b-93395ff4452d
* Version Independent ID: 7da82adc-2656-daef-c2b5-e871a932e2da
* Content: [Create a Windows virtual machine in Azure using Ansible](https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-windows?tabs=ansible)
* Content Source: [articles/ansible/vm-configure-windows.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure-windows.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
