### ISSUE TITLE
i like it

### ISSUE THREAD

**Issue by prasetiacahyahadi** [MicrosoftDocs/azure-dev-docs#1282]
Thank you for making a basic tutorial about Git in Visual Studio Code

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9458247-a093-fb93-6108-a6bb4a1a4616
* Version Independent ID: 5109264f-c976-d71c-a3c4-dd6492dd3f1c
* Content: [Clone GitHub repository with VSCode - JavaScript on Azure](https://learn.microsoft.com/en-us/azure/developer/javascript/how-to/with-visual-studio-code/clone-github-repository?tabs=create-repo-command-palette%2Cinitialize-repo-activity-bar%2Ccreate-branch-command-palette%2Ccommit-changes-command-palette%2Cpush-command-palette)
* Content Source: [articles/javascript/how-to/with-visual-studio-code/clone-github-repository.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/how-to/with-visual-studio-code/clone-github-repository.md)
* Service: **azure-javascript**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by KarlErickson** [comment]
@diberry for awareness. 
Thanks, @prasetiacahyahadi!
