### ISSUE TITLE
Adding the VMs to the LB

### ISSUE THREAD

**Issue by mapeterson42** [MicrosoftDocs/azure-dev-docs#129]
Am I missing something or does this just create 2 VMs and a Load Balancer that aren't in any way connected without additional work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef91226-6c89-f8f1-3400-28d633cd1791
* Version Independent ID: 19ea3aee-2e71-0764-110c-fadf241c377f
* Content: [Tutorial - Create an Azure VM cluster with Terraform and HCL](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-with-infrastructure#feedback)
* Content Source: [articles/terraform/create-vm-cluster-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-vm-cluster-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@mapeterson42 According to the checklist at the beginning of the article, that is correct. If you would like, I can add to our documentation backlog the idea of extending this tutorial. #please-close

**Comment by mattgillard** [comment]
Why is this closed?
A basic tutorial on the Microsoft Docs site should *work*.  This does not and could be an endless source of frustration for newcomers to terraform and azure.

All it needs is a missing azurerm_network_interface_backend_address_pool_association resource.

resource "azurerm_network_interface_backend_address_pool_association" "example" {
  count = 2
  network_interface_id    = element(azurerm_network_interface.test.*.id,count.index)
  ip_configuration_name   = "testConfiguration"
  backend_address_pool_id = azurerm_lb_backend_address_pool.test.id
}

**Comment by TomArcherMsft** [comment]
@mattgillard You're correct. I replied 2 years ago, so I'm not sure what I was thinking but it appears I misunderstood the OP's point. I'm finishing up a complete rewrite of the AGIC/AKS article and will fix this next.

**Comment by TomArcherMsft** [comment]
@mattgillard Quick FYI that I haven't forgotten this, but some things are in flight I can't talk about. I'll try to get this done by Monday.
