### ISSUE TITLE
Indenting Docker sample is wrong in azd azure.yml schema reference docs

### ISSUE THREAD

**Issue by obiwanjacobi** [MicrosoftDocs/azure-dev-docs#1292]
The indenting of the docker sample is wrong.
https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-schema#docker-options-sample

The `web` entries are skewed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a201d9c1-ae07-63bf-d364-95fc91641876
* Version Independent ID: a201d9c1-ae07-63bf-d364-95fc91641876
* Content: [Azure Developer CLI's azure.yaml schema](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-schema)
* Content Source: [articles/azure-developer-cli/azd-schema.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/azd-schema.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thank you, resolved in an upcomign PR.

#please-close
