### ISSUE TITLE
msrestazure package is deprecated - need to update code samples

### ISSUE THREAD

**Issue by karpikpl** [MicrosoftDocs/azure-dev-docs#1296]
Sample code on the page references deprecated `msrestazure` azure package:

```python
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD as CLOUD
```
Is there a different way to get azure cloud endpoints, without referencing `msrestazure`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3651a7d-904a-7eaa-2949-43e57fe1a0ce
* Version Independent ID: c3651a7d-904a-7eaa-2949-43e57fe1a0ce
* Content: [Connect to all regions using Azure libraries for Python multicloud - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-sovereign-domain)
* Content Source: [articles/python/sdk/azure-sdk-sovereign-domain.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/azure-sdk-sovereign-domain.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by JimacoMS4** [comment]
Hi @karpikpl -- good point. I'll reach out to our product team. It looks like this still might be an open issue in the code repo: https://github.com/Azure/azure-sdk-for-python/issues/29023. You might want to follow progress in that issue.

**Comment by JimacoMS4** [comment]
Hi @karpikpl -- just an update. I've been working offline with one of our developers to update this topic. We're just finalizing edits. It should go live sometime this weekend or by Monday AM at the latest. 

-Jimaco

**Comment by JimacoMS4** [comment]
Hi @karpikpl -- The updated code snippets and some accompanying text changes are now live. Please have a look. I'll leave this issue open for a day or so in case you have additional feedback.

Thanks,

Jimaco

**Comment by karpikpl** [comment]
awesome, thank you!
we'll use `azure.identity.AzureAuthorityHosts`. Hopefully this also helps others doing work in different clouds

**Comment by karpikpl** [comment]
Hey @JimacoMS4 
one question about the solution 

```python
import os
from azure.mgmt.resource import ResourceManagementClient, SubscriptionClient
from azure.identity import DefaultAzureCredential, AzureAuthorityHosts

authority = AzureAuthorityHosts.AZURE_CHINA
resource_manager = "https://management.chinacloudapi.cn" # <----- This value is hardcoded?
```

Only authority is available from the identity package, but what about other cloud specific endpoints? 
* sql management
* resource management
* gallery
* AD
* graph
* etc. ?
