### ISSUE TITLE
I tried to run on Ansible playbooks by copying but it shows multiple errors

### ISSUE THREAD

**Issue by sloharadmin** [MicrosoftDocs/azure-dev-docs#1297]
[Enter feedback here]
As per guidelines , I have copied the playbook to create the image in gallery but it show errors like:

ansible-playbook [core 2.15.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/playbooks/06-update-image-in-galery.yml': line 4, column 15, but may
be elsewhere in the file depending on the exact syntax problem. even the block connection : local does not exists in my playbook: 

The offending line appears to be:

  hosts: all
    connection: local
              ^ here
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b82b6a1b-abea-4172-2de2-7accec990d4f
* Version Independent ID: 13a09ebc-9fa3-07bd-b96c-1e2a755fc1f7
* Content: [Tutorial - Create a VM or virtual machine scale set from the Azure Shared Image Gallery using Ansible](https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-from-azure-shared-image-gallery?tabs=ansible)
* Content Source: [articles/ansible/vm-configure-from-azure-shared-image-gallery.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure-from-azure-shared-image-gallery.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
