### ISSUE TITLE
Is a step missing? 

### ISSUE THREAD

**Issue by dfberry** [MicrosoftDocs/azure-dev-docs#1298]
Perhaps a step is missing? I'm running a dev container that doesn't have azd and I want to add azd. The page goes from prereqs to updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Version Independent ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Content: [Install the Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux)
* Content Source: [articles/azure-developer-cli/install-azd.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/install-azd.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thanks, this will be resolved in the next docs publish.

#please-close
