### ISSUE TITLE
Missing pre-requisites

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-dev-docs#130]
The line in the script configuration "public_key     = file("/home/azureuser/.ssh/authorized_keys")" assumes that this is a local folder that exists with the appropriate keys in it - typically only present on a Linux host.  Anyone executing this on a Windows host would see a failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Quickstart - Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@aricbernard Thank you for the feedback. I've added a note to the documentation explaining the requirements of the Azure VM Agent and warning Windows users.#please-close
