### ISSUE TITLE
missing dot "." at the end of the command

### ISSUE THREAD

**Issue by vitorleo** [MicrosoftDocs/azure-dev-docs#1300]
Following the tutorial, the step 2
"Build and push the docker image to ACR."
Only worked for me when I added a dot at the end of the command
**docker build -t <loginServer>/<imageName>:latest .**

Source:
https://stackoverflow.com/questions/76652039/docker-build-go-project-failed

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8981cd21-b358-5fb3-0b93-f39372e5045e
* Version Independent ID: 8981cd21-b358-5fb3-0b93-f39372e5045e
* Content: [Deploy a Go web app to Azure Container Apps - Go on Azure](https://learn.microsoft.com/en-us/azure/developer/go/deploy-container-apps)
* Content Source: [articles/go/deploy-container-apps.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/deploy-container-apps.md)
* Service: **azure**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by bobtabor-msft** [comment]
Internal: 186416
