### ISSUE TITLE
is JWE supported?

### ISSUE THREAD

**Issue by ChrisMeeusen** [MicrosoftDocs/azure-dev-docs#1301]
I'm currently using         
<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>spring-cloud-azure-starter-active-directory</artifactId>
    <version>5.2.0</version>
</dependency>

to protect an API with AAD / Entra Id JWT tokens and have been asked to enable JWE to encrypt the JWT payload.  I saw some rather complete documentation on how to do that in .Net here:

https://github.com/AzureAD/microsoft-identity-web/wiki/Token-Decryption

Does the spring-cloud-azure-starter-active-directory package support validating and decrypting JWE tokens from Entra id?  If so are their docs / samples I'm not seeing here?

Thanks!

**Comment by KarlErickson** [comment]
Hi @ChrisMeeusen - I'm not aware of any such documentation/samples. You might want to post your question at the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site. Thanks!
