### ISSUE TITLE
The registry DNS name webappacr123.azurecr.io is already in use.

### ISSUE THREAD

**Issue by silvermineai** [MicrosoftDocs/azure-dev-docs#1303]
You should inform people to replace webappacr123 with something else. or, even better, make these commands dynamic like the google cloud documentation, where the user can input the name and have these commands dynamically update.

```
❯ az acr create --resource-group web-app-simple-rg \
> --name webappacr123 --sku Basic --admin-enabled true
(AlreadyInUse) The registry DNS name webappacr123.azurecr.io is already in use. You can check if the name is already claimed using following API: https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/checknameavailability
Code: AlreadyInUse
Message: The registry DNS name webappacr123.azurecr.io is already in use. You can check if the name is already claimed using following API: https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/checknameavailability
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34782954-131e-7e8f-5a8d-1b2f59de078d
* Version Independent ID: 34782954-131e-7e8f-5a8d-1b2f59de078d
* Content: [Deploy a Flask or FastAPI web app as a container in Azure App Service - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-containerize-simple-web-app-for-app-service?tabs=web-app-flask)
* Content Source: [articles/python/tutorial-containerize-simple-web-app-for-app-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-containerize-simple-web-app-for-app-service.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by bobtabor-msft** [comment]
Internal 186405

**Comment by JimacoMS4** [comment]
Hi @silvermineai -- thanks for your feedback! I totally agree that we should at least mention that you need to replace the app name with your own name as it winds up being part of the DNS name and must be globally unique. Full disclosure, I think the same might be true of the ACR name as well. I'll talk with the team and see whether we want to set these as environment variables with some guidance or just warn folks that they may need to replace them. 

As to your point about the GCM documentation. It looks interesting. We do have some training content which is somewhat analogous -- especially where CLI commands are concerned. For example, https://learn.microsoft.com/en-us/training/modules/host-a-web-app-with-azure-app-service/1-introduction. 

Anyway, I'll keep you posted on progress with this topic. 

Thanks again for your feedback,

- Jimaco

**Comment by JimacoMS4** [comment]
Hi @silvermineai thanks, again, for your feedback. The topic has been updated with a note in this section: https://learn.microsoft.com/en-us/azure/developer/python/tutorial-containerize-simple-web-app-for-app-service?tabs=web-app-flask. A bullet was also added to the notes in this section: https://learn.microsoft.com/en-us/azure/developer/python/tutorial-containerize-simple-web-app-for-app-service?tabs=web-app-flask#deploy-web-app-to-azure. 

I'll leave this issue open for a couple of days, in case you want to provide additional feedback. I'll close it by EOD Monday. 

Thanks again,

-Jimaco

**Comment by JimacoMS4** [comment]
Hi @silvermineai -- The topic is now live. Please check out the indicated sections in my last comment. I'll leave this issue open for another day or so in case you have additional feedback. 

-Jimaco

**Comment by JimacoMS4** [comment]
Hi @silvermineai -- I'm going to go ahead and close this issue. If you have additional feedback, it would be best to open a new issue and reference this one. 

Thanks for helping us improve our documentation,

Jimaco
