### ISSUE TITLE
WebSecurityConfigurerAdapter is deprecated

### ISSUE THREAD

**Issue by gandra** [MicrosoftDocs/azure-dev-docs#1305]
[Enter feedback here]

WebSecurityConfigurerAdapter is deprecated
Can you provide example witout using deprectaed features?

https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Add sign-in with Azure Active Directory B2C to a Spring Web App - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@edburns can you please take a look? Thanks!

**Comment by KarlErickson** [comment]
@edburns ping

**Comment by AndersGM** [comment]
@KarlErickson Just wanted to mention that also 
```java
http.apply(AadResourceServerHttpSecurityConfigurer.aadResourceServer())
```
from [here](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide?tabs=SpringCloudAzure5x) is marked for removal.

I am not sure what to use instead. A quick look at the code might suggest the code below?
```java
AadResourceServerHttpSecurityConfigurer.aadResourceServer().init(http);
```

**Comment by KarlErickson** [comment]
@saragluna we think you are the correct SME for this? Can you please take a look.

**Comment by KarlErickson** [comment]
Work item filed at https://dev.azure.com/msazure/AzureDMSS/_workitems/edit/27312154
