### ISSUE TITLE
Incorrect syntax in Create virtual network interface card code

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-dev-docs#131]
The following two lines of code in the Create virtual network interface card are incorrect using out-dated syntax and will result in a failure:

subnet_id                     = "${azurerm_subnet.myterraformsubnet.id}"
public_ip_address_id          = "${azurerm_public_ip.myterraformpublicip.id}"

The corresponding code in the Complete Terraform script section is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Quickstart - Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@aricbernard Thanks for the feedback. I updated the code in question.

#please-close
