### ISSUE TITLE
Broken links, stale references to Azure AD instead of Entra, and wrong Auth guidance

### ISSUE THREAD

**Issue by joshfree** [MicrosoftDocs/azure-dev-docs#1314]
Reporting three (3) issues

1) The Java libraries, drivers, and Spring modules page instructs users to install MSAL for Authentication.  This should change to point users to Azure Identity SDK.
2) the link to `Microsoft Entra Spring Boot Starter` is broken
3) References to `Azure AD` and `Azure Active Directory` need to be changed to `Microsoft Entra ID` (/cc @scottaddie)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8d7ffb1-3e05-a916-8133-0ba300ec46b9
* Version Independent ID: b8d7ffb1-3e05-a916-8133-0ba300ec46b9
* Content: [Java libraries, drivers, and Spring modules for Azure - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/sdk/libraries-drivers-modules)
* Content Source: [articles/java/sdk/libraries-drivers-modules.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/sdk/libraries-drivers-modules.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by JonathanGiles** [comment]
I'll work with @g2vinay to get the messaging updated.

**Comment by scottaddie** [comment]
@joshfree On the page you linked to, I only see references to Azure Active Directory B2C. Per https://learn.microsoft.com/entra/fundamentals/new-name#what-names-arent-changing, that product name isn't changing.

**Comment by KarlErickson** [comment]
@JonathanGiles do you have the required work represented in your Azure Devops somewhere? I.e. can we close this issue?

**Comment by KarlErickson** [comment]
@joshfree if these issues are still valid, please work directly with @JonathanGiles, file an Azure DevOps work item for him, or submit a PR to fix them. Thanks!

**Comment by joshfree** [comment]
Yes this is still a problem. Please reactivate and assign to Jonathan instead of closing/losing the details. Thank you.

**Comment by KarlErickson** [comment]
@srnagar can you please represent this issue in the SDK repo issues list as well? Thanks!

@joshfree we're closing all the issues in this repo as we transition to the new feedback system. Going forward, all feedback on the SDK docs will be represented as an issue in the SDK repo.

**Comment by srnagar** [comment]
Created an issue in azure-sdk-for-java repo - https://github.com/Azure/azure-sdk-for-java/issues/39237
