### ISSUE TITLE
enable-ip-forwarding.sh script does not exist in specified path

### ISSUE THREAD

**Issue by norg-msexton** [MicrosoftDocs/azure-dev-docs#1328]
This script no longer exists, cause the terraform apply to fail
https://raw.githubusercontent.com/mspnp/reference-architectures/master/scripts/linux/enable-ip-forwarding.sh

Correct path or contents of the script would be really helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b701b1c8-1b00-f16d-36eb-781c3ce062e8
* Version Independent ID: 9c43b7f0-2d05-c946-7ffe-c3599b99958e
* Content: [Create a hub virtual network appliance in Azure using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/hub-spoke-hub-nva)
* Content Source: [articles/terraform/hub-spoke-hub-nva.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/hub-spoke-hub-nva.md)
* Service: **virtual-network**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
We appreciate your contributions to our community.

Unfortunately, we have not been able to review this issue in a timely manner and sincerely apologize for the delayed response.

We're moving to a new feedback system, so we're closing out older issues.

If you feel that the problem has not been addressed, respond to this issue with any additional information.

#please-close

**Comment by kbcz1989** [comment]
@TomArcherMsft Hello. This problem has not been addressed.

The script is still being referenced in official docs here:
https://learn.microsoft.com/en-us/azure/developer/terraform/hub-spoke-hub-nva

Repository does not seem to exist anymore.
