### ISSUE TITLE
Error 404 for `http://repos.azul.com/azure-only/zulu/apt`

### ISSUE THREAD

**Issue by kenorb** [MicrosoftDocs/azure-dev-docs#1329]
Mentioned `http://repos.azul.com/azure-only/zulu/apt` repository doesn't exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 365605bc-4e02-f671-3cb2-53c6ed29fc71
* Version Independent ID: 2f2ffb0a-bd46-6a70-0ff6-82215a6f5c8c
* Content: [Tutorial - Deploy to Azure App Service with Jenkins and the Azure CLI](https://learn.microsoft.com/en-us/azure/developer/jenkins/deploy-to-azure-app-service-using-azure-cli)
* Content Source: [articles/jenkins/deploy-to-azure-app-service-using-azure-cli.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/deploy-to-azure-app-service-using-azure-cli.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@kenorb It's been decided that Jenkins on Azure documentation support is limited to security issues only. Thanks for your feedback, but I need to close this issue.
