### ISSUE TITLE
How to allow azure devops to connect to jenkins accepting connection from VPN only?

### ISSUE THREAD

**Issue by taragurung** [MicrosoftDocs/azure-dev-docs#133]
The documentation is great but suppose If Jenkins accept request from certain IP only or Let's say the request to Jenkins comes via VPN only. For such scenario may be you can add some link to the resource guiding how to put the ip ranges or any ip's that azure provides.
---
#### Documents

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5c28a5-b211-e95d-f145-06898f60ef2c
* Version Independent ID: 49ee2033-65c8-e36c-3c67-057fc253efe0
* Content: [Deploy to Linux virtual machine using Jenkins and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-to-linux-vm-using-azure-devops-services)
* Content Source: [articles/jenkins/deploy-to-linux-vm-using-azure-devops-services.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-to-linux-vm-using-azure-devops-services.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hello @taragurung,

That's a great suggestion, however it's outside the scope of the article to include that level of detail on the networking aspect.

Please let me know if you disagree and if I'm misunderstanding your request.

Thank you,
