### ISSUE TITLE
Invalid Image

### ISSUE THREAD

**Issue by intellispear** [MicrosoftDocs/azure-dev-docs#1330]
The Image here appears to be invalid for the LTS however I found swapping it for Ubuntu2204 fixed the problem
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Get Started - Install Jenkins on an Azure Linux VM](https://learn.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@intellispear Thanks for your feedback, but it's been decided that Jenkins on Azure documentation support is limited to security issues only. Therefore, I'm closing this issue.
