### ISSUE TITLE
mySampleApp failed 

### ISSUE THREAD

**Issue by intellispear** [MicrosoftDocs/azure-dev-docs#1331]
The Image here appears to be invalid for the LTS however I found swapping it for Ubuntu2204 fixed the problem

Also: when running the sample app in Jenkins I received this 

Started by user [Stuart Pexxxx]({URL ommitted }0/user/stuart)
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/mySampleApp
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/mySampleApp/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/spring-guides/gs-spring-boot.git # timeout=10
Fetching upstream changes from https://github.com/spring-guides/gs-spring-boot.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
 > git fetch --tags --force --progress -- https://github.com/spring-guides/gs-spring-boot.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision c15a4897789810abc37cc08b69f0a4a49a2c0b86 (refs/remotes/origin/main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c15a4897789810abc37cc08b69f0a4a49a2c0b86 # timeout=10
Commit message: "Update to Spring Boot 3.2.0."
First time build. Skipping changelog.
[Gradle] - Launching build.
[complete] $ /var/lib/jenkins/workspace/mySampleApp/complete/gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'spring-boot'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:3.2.0.
     Required by:
         project : > org.springframework.boot:org.springframework.boot.gradle.plugin:3.2.0
      > No matching variant of org.springframework.boot:spring-boot-gradle-plugin:3.2.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.3' but:
          - Variant 'apiElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
          - Variant 'javadocElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
          - Variant 'mavenOptionalApiElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
          - Variant 'mavenOptionalRuntimeElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
          - Variant 'runtimeElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
          - Variant 'sourcesElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.0 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org/.

BUILD FAILED in 10s
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure
Finished: FAILURE
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Get Started - Install Jenkins on an Azure Linux VM](https://learn.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@intellispear We appreciate very much you taking the time to provide feedback. However, Jenkins on Azure support is now limited to security issues. Therefore, I'm closing this issue.
