### ISSUE TITLE
Stackoverflow Link

### ISSUE THREAD

**Issue by clavrus** [MicrosoftDocs/azure-dev-docs#1335]
I don't think a link to a stackoverflow page is appropriate for a MS Learn article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5cbb8da-d7df-723f-c7a5-5872381bb4aa
* Version Independent ID: fbd4f2e5-d160-236e-8cc0-ea58ac18a1d0
* Content: [Install Terraform on Windows with Azure PowerShell](https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-windows-powershell?tabs=bash)
* Content Source: [articles/terraform/get-started-windows-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/get-started-windows-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by clavrus** [comment]
[Update your system's global path](https://stackoverflow.com/questions/1618280/where-can-i-set-path-to-make-exe-on-windows) to the executable.

**Comment by TomArcherMsft** [comment]
@clavrus Thanks for your feedback. S/O link removed.
