### ISSUE TITLE
.azdo

### ISSUE THREAD

**Issue by pascostefan** [MicrosoftDocs/azure-dev-docs#1341]
Hi, shouldn't it be `.azdo/pipelines` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f953ea6-ae2f-b258-3eac-e86a12398d5a
* Version Independent ID: 4f953ea6-ae2f-b258-3eac-e86a12398d5a
* Content: [Configure a pipeline and push updates using GitHub Actions or Azure DevOps](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/configure-devops-pipeline?tabs=GitHub)
* Content Source: [articles/azure-developer-cli/configure-devops-pipeline.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/configure-devops-pipeline.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Thank you for raising this issue - this will be fixed soon in an upcoming PR.

**Comment by alexwolfmsft** [comment]
#please-close
