### ISSUE TITLE
Reference to recommended way is needed for each plug-in

### ISSUE THREAD

**Issue by thiruma0203** [MicrosoftDocs/azure-dev-docs#1342]
The document has "Important" section that says "Many Azure services have Jenkins plug-ins. Some of these plug-ins will be out of support as of February 29, 2024. Azure CLI is the currently recommended way to integrate Jenkins with Azure services. For more information, refer to the article [Jenkins plug-ins for Azure](https://learn.microsoft.com/en-us/azure/developer/jenkins/plug-ins-for-azure)." 

However, URL link ”Jenkins plug-ins for Azure” navigates to nowhere, that is quite confusing.

If Azure CLI is recommended way after deprecation of Jenkins plug-ins, pointers to information that contain alternative Azure CLI way for each plugin are desirable, so that readers can better understand what actions must be taken.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77979df7-63f8-160a-ed04-f1e01ff417b3
* Version Independent ID: 3c2bc077-2f84-1e6d-e85e-5800c4de2527
* Content: [Jenkins plug-ins for Azure](https://learn.microsoft.com/en-us/azure/developer/jenkins/plug-ins-for-azure)
* Content Source: [articles/jenkins/plug-ins-for-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/plug-ins-for-azure.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@thiruma0203 Is the plugins page not displaying for you? The page seems to be working now. Or are you asking for documentation for how to use Azure CLI with various plugins? The plugins page contains links for each Jenkins Azure plugs to its support page on plugins.jenkins.io. If the page for the desired plugin doesn't have any documentation, I might suggest contacting the specific team via their email or a GitHub Issue.

**Comment by thiruma0203** [comment]
@TomArcherMsft, the page is displaying for me, but it appears confusing that [Jenkins plug-ins for Azure](https://learn.microsoft.com/en-us/azure/developer/jenkins/plug-ins-for-azure) links to the same page. The page has a link to itself.

Also, as there are several tutorials as Azure documents (such as https://learn.microsoft.com/en-us/azure/developer/jenkins/azure-storage-blobs-as-build-artifact-repository) , navigations to these might be helpful to readers, if these work as replacement of deprecating plugins.
