### ISSUE TITLE
please review the terraform code snipped 

### ISSUE THREAD

**Issue by syntetic81** [MicrosoftDocs/azure-dev-docs#1343]
At your Site you wrote:
## https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
**data "azurerm_role_definition" "storage_role" {
  name = "Storage File Data SMB Share Contributor"
}**

resource "azurerm_role_assignment" "af_role" {
  scope              = azurerm_storage_account.storage.id
  **role_definition_id = data.azurerm_role_definition.storage_role.id**
  principal_id       = azuread_group.aad_group.id
}

if you do it like that, it will end up in a change on your resource azurerm_role_assignment.af_role - because of the role_definition_id in the data block ist not complete. (it does not contain /subscription/[ID]/resourceGroup/[RG-Name].........

If you use the build in roles it makes more sense to use the definition name. Than you can delete the Data Block
resource "azurerm_role_assignment" "af_role" {
  scope              = azurerm_storage_account.storage.id
  role_definition_name = "Storage File Data SMB Share Contributor"
  principal_id       = azuread_group.aad_group.id
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01ec1841-b3c7-8195-02c9-26300bac2882
* Version Independent ID: 01ec1841-b3c7-8195-02c9-26300bac2882
* Content: [Configure Azure Files for FSLogix profiles for Azure Virtual Desktop using Terraform - Azure](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-azure-files-storage)
* Content Source: [articles/terraform/create-avd-azure-files-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-avd-azure-files-storage.md)
* Service: **azure**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@syntetic81 Thanks for the feedback. The AVD set of Terraform articles is being rewritten over the next couple of months.
