### ISSUE TITLE
docs typo: to install the dotnet package do npm install dotenv

### ISSUE THREAD

**Issue by ncook-hxgn** [MicrosoftDocs/azure-dev-docs#1347]
Minor typo: "To use the `dotnet` package" should likely be "To use the `dotenv` package"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dfeae622-1391-1fac-ca16-e8566d406413
* Version Independent ID: dfeae622-1391-1fac-ca16-e8566d406413
* Content: [Local dev: Auth JS apps to Azure services with service principal - JavaScript on Azure](https://learn.microsoft.com/en-us/azure/developer/javascript/sdk/authentication/local-development-environment-service-principal?tabs=azure-portal#4---set-local-development-environment-variables)
* Content Source: [articles/javascript/sdk/authentication/local-development-environment-service-principal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/sdk/authentication/local-development-environment-service-principal.md)
* Service: **azure-javascript**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
Hi @ncook-hxgn Thank you for reporting this. Fix will be live tomorrow. #in-progress
