### ISSUE TITLE
Net6.0 not supported

### ISSUE THREAD

**Issue by ardb-uk** [MicrosoftDocs/azure-dev-docs#1349]
[Enter feedback here]

The dependencies for the TodoApp.MAUI project need updating to net7.0. If you open the TodoApp,MAUI xml file, and change the references from net6.0 to net7.0 you clear the 4 errors and can build and run the app!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6e86e0a-c6ee-b84f-8ff9-ffbc24d4c5a7
* Version Independent ID: a6e86e0a-c6ee-b84f-8ff9-ffbc24d4c5a7
* Content: [Build a .NET MAUI app with Azure Mobile Apps](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/index.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/index.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
The build "errors" are actually warnings about an unsupported environment, not errors in the code.

I welcome you to open an issue at https://github.com/azure/azure-mobile-apps to update the sample.  It's NOT an issue with documentation and there will be no changes to the docs as a part of this change.

#pleaseclose
