### ISSUE TITLE
Disconnect in information

### ISSUE THREAD

**Issue by AllenVisser** [MicrosoftDocs/azure-dev-docs#135]
There is a disconnect in the procedure. 
No mention is made around how to first login to Azure via az login and then running the sample script.
Following your article, step for step, this is my outcome. i know how to find a workaround for the az login before running the samp script again.
Error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce73b1a7-dbe9-3273-670f-e8eb235b0771
* Version Independent ID: b6b527b8-d6e3-fb58-7169-4322f896e991
* Content: [Quickstart - Install and configure Terraform to provision Azure resources](https://docs.microsoft.com/en-us/azure/developer/terraform/install-configure)
* Content Source: [articles/terraform/install-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/install-configure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@AllenVisser Could you give me a little more info on your environment. Are you using CloudShell, a Linux VM, or Windows?

**Comment by TomArcherMsft** [comment]
@AllenVisser 

The article assumes a basic test environment of Cloud Shell where logging in is not necessary. 

However, I understand your point about the disconnect for people using other environments. Even when using Cloud Shell, it would be nice to cover how to switch accounts from the one automatically associated with the Microsoft account used to sign into the portal. 

To that end, I´ve completely rewritten the article and named it appropriately as a "Cloud Shell" version of the quickstart. I'm now writing a Windows/PowerShell version. After that, I'll write versions of the quickstart for other environments (Linux VM/AzCli, Windows/AzCli). 

Thanks for your feedback!
