### ISSUE TITLE
The tutorial is 8 years old.

### ISSUE THREAD

**Issue by ricfo-tricentis** [MicrosoftDocs/azure-dev-docs#1354]
It's using Ubuntu 16.04 and old terraform resources.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 560d5902-d21c-a085-86a2-3189dde5d76c
* Version Independent ID: 7c19fad6-c65a-847d-a98c-0f9c9e4c6217
* Content: [Create an Azure virtual machine scale set using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-hcl)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-scaleset-network-disks-hcl.md)
* Service: **virtual-machine-scale-sets**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Hi, @ricfo-tricentis. Thank you for your feedback. We are looking at rewriting some of these VM/VMSS articles over the next couple of months. Thanks again for calling this issue out.
