### ISSUE TITLE
Missing Gradle?

### ISSUE THREAD

**Issue by brucedkyle** [MicrosoftDocs/azure-dev-docs#136]
I seem to be missing a step. I might have misunderstood the steps, but when I get to Build, I do not see Gradle. In what I think is the Build tab/section has:
- Copy artifacts from another project
- Deploy to Azure Container Service (AKS)
- Deploy to Kubernetes
- Download from Azure Strorage
- Execute Windows batch command
- Execute shell
- Invoke top-level Maven targets
- Queue an ACR Quick Task
- Set build pending status in TFS/Team Services
- Update Azure Virtual Machine Scale Set
- Update Azure Virtual Machine Scale Set Instances

Is this because I picked a Jenkins release type that does not include Gradle and blocks me from completing this tutorial?

What am I missing?  Many thanks in advance for your answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Quickstart - Create a Jenkins server on Azure](https://docs.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@brucedkyle I've rewritten this article and tested the steps, so the issue you saw should be resolved. Let me know if you still the issue and I'll investigate.
