### ISSUE TITLE
Wrong spring data reactive redis properties.

### ISSUE THREAD

**Issue by gsbindhani** [MicrosoftDocs/azure-dev-docs#1364]
### Wrong spring data reactive redis properties

Properties provided for spring data redis are not working with the dependencies mentioned in the page.
Please update with below relevant properties under **Section 1**

```
# Specify the DNS URI of your Redis cache.
spring.data.redis.host=<your-redis-name>.redis.cache.windows.net
# Specify the access key for your Redis cache.
spring.data.redis.password=<your-redis-access-key>
# Specify that you want to use SSL.
spring.data.redis.ssl.enabled=true
# Specify the port for your Redis cache.
spring.data.redis.port=6380
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2985bd1-1292-408a-ed6c-2b5ca73d113e
* Version Independent ID: b9dc82b9-a34a-9fc8-8dc7-ae405e05e5b8
* Content: [use Azure Redis Cache in Spring - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache)
* Content Source: [articles/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-initializer-java-app-with-redis-cache.md)
* Service: **cache**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by Netyyyy** [comment]
Hi @gsbindhani ,Thank you for reporting this issue. We have received your submission and will take a look. We appreciate your input and will review this matter as soon as possible.
Please feel free to provide any additional information or context that you think may be helpful. We'll keep you updated on the progress of our review.
