### ISSUE TITLE
Ansible 2.10 with azure.azcollection instructions not working

### ISSUE THREAD

**Issue by clumsyhands** [MicrosoftDocs/azure-dev-docs#1366]
Are the instructions for 2.10 up to date?

1. Running the CLI command to create a centOS VM does not complete - it creates all prerequisite resources (Nics/VNETS/Disk etc), then times out when attempting to complete the actual CentOS VM after 20 minutes.

I had a look at trying to create the VM manually and there is no Cent OS 8.5 image available for East US. Latest one I can find is Cent OS 8.2

2) Using CentOS 8.2, running this command fails: 
"ansible-galaxy collection install azure.azcollection"

I get an error to say Ansible command does not exist. After looking at previous issues, I found this resolved issue from the year 2021 :https://github.com/MicrosoftDocs/azure-dev-docs/issues/402 which says to run "pip3 install ansible[azure]" before "ansible-galaxy collection install azure.azcollection". 

This fixed my issue, but the official documentation has not been updated to include this?

3) On running "sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt" I get an error:
```
ERROR: Could not find a version that satisfies the requirement msgraph-sdk==1.0.0 (from versions: 1.0.0a0, 1.0.0a1, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a7, 1.0.0a8, 1.0.0a9, 1.0.0a10, 1.0.0a11, 1.0.0a12, 1.0.0a13)
ERROR: No matching distribution found for msgraph-sdk==1.0.0
``` 
Is the MS Graph version "1.0.0" not available any more?

Can someone please help me with each of my points above?

**Comment by TomArcherMsft** [comment]
@clumsyhands Thanks for your feedback. We are moving to a new feedback system and I need to close this issue. However, I have enough information to see if this is something we can fix or need to remove. Thanks again.
