### ISSUE TITLE
After install plugin received the error "Require plugin 'com.intellij.modules.java' to be installed"

### ISSUE THREAD

**Issue by rathanak** [MicrosoftDocs/azure-dev-docs#1368]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac47849-d1c7-3c23-d764-8e7824b85f51
* Version Independent ID: 8ac47849-d1c7-3c23-d764-8e7824b85f51
* Content: [Install the Azure Toolkit for IntelliJ - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/install-toolkit)
* Content Source: [articles/java/toolkit-for-intellij/install-toolkit.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/toolkit-for-intellij/install-toolkit.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **jialuogan**

**Comment by KarlErickson** [comment]
@silenceJialuo can you please take a look? Thanks!

**Comment by KarlErickson** [comment]
@silenceJialuo ping. Could you please represent this issue in Azure DevOps so that we can close it? Thanks!

**Comment by silenceJialuo** [comment]
Hi @rathanak, thanks for contacting us. 

It seems you have installed our toolkit in non-IntelliJ IDEA products. Please note that the Azure Toolkit is only compatible with IntelliJ IDEA or Eclipse.
