### ISSUE TITLE
Please Update Tutorial

### ISSUE THREAD

**Issue by caromeva** [MicrosoftDocs/azure-dev-docs#137]
Hi Microsoft Girls and Guys,

Please you could update the tutorial, i made this tutorial following all example, including this sample https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-b2c-oidc-spring-boot-sample 
But I have errors, the pictures of process of creation of user flow in point 4 into this section : Add an application registration for your Spring Boot app are obsolete, the interface in azure change and the tutorial is old.
I need an updated example to Azure Active Directory B2C.
Thanks so much!!! and if is possible for your, stay at home.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc#feedback)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @panli
* Microsoft Alias: **panli**

**Comment by KarlErickson** [comment]
@caromeva thanks for the feedback! We'll investigate and update the topic.

**Comment by wujack778** [comment]
@caromeva hey man，I am dealing with this issue . Maybe i will update the picture about  'Add an application registration for your Spring Boot app' ,If you have any other questions about this issue, you can leave commet to me.
