### ISSUE TITLE
Missing instruction about how to add azd feature

### ISSUE THREAD

**Issue by pamelafox** [MicrosoftDocs/azure-dev-docs#1371]
It feels like this page is missing a section? It doesn't seem to actually say how to install azd in a dev container. I expected it to include the syntax for "features" in devcontainer.json

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Version Independent ID: 2f283f7f-dc6c-e976-8994-7b685852b701
* Content: [Install the Azure Developer CLI](https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/install-azd?tabs=winget-windows%2Cbrew-mac%2Cscript-linux&pivots=env-dev-container)
* Content Source: [articles/azure-developer-cli/install-azd.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/install-azd.md)
* Service: **azure-dev-cli**
* GitHub Login: @alexwolfmsft
* Microsoft Alias: **alexwolf**

**Comment by alexwolfmsft** [comment]
Hey @pamelafox thanks for pointing this out, I agree, it should have a sample devcontainer.json - I'll update this.

**Comment by alexwolfmsft** [comment]
This update will go out with the next docs publish.

#please-close
