### ISSUE TITLE
Wrong Ansible URL for ConfigureRemotingFoAnsible.ps1

### ISSUE THREAD

**Issue by JKindonNtx** [MicrosoftDocs/azure-dev-docs#1372]
Wrong Ansible URL for ConfigureRemotingFoAnsible.ps1

Should be: https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1

Tracked via https://github.com/ansible/ansible/issues/81240

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb5f4824-c6e0-5b17-d79b-93395ff4452d
* Version Independent ID: 7da82adc-2656-daef-c2b5-e871a932e2da
* Content: [Create a Windows virtual machine in Azure using Ansible](https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-windows?tabs=ansible)
* Content Source: [articles/ansible/vm-configure-windows.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure-windows.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Duplication of #1318. Closing issue.
