### ISSUE TITLE
ansible authentication

### ISSUE THREAD

**Issue by onkarthg** [MicrosoftDocs/azure-dev-docs#138]
as per this documentation, there is no need to ssh key for dynamic ansible but its showing errors, please could you provide me solution on this

**Comment by TomArcherMsft** [comment]
@onkarthg What article are you referring to?

**Comment by TomArcherMsft** [comment]
@onkarthg I haven't heard back from you, so I'm going to close this issue. Please feel free to respond if you're still encountering problems, and I'll help to resolve. Thanks.
