### ISSUE TITLE
Sample script is amazingly complex 

### ISSUE THREAD

**Issue by deathgaze** [MicrosoftDocs/azure-dev-docs#144]
and no explaination of it is given. This is not a very useful "tutorial", more like "here is a repo that does almost everything for you. it's basically undocumented, glhf." Perhaps a more simple tutorial is needed that gets users familiar with the basics of deploying code to kubernetes before jumping straight into the complexities of blue/green deployments. As it is now, it looks as if I'll have to spend several days understanding this code before I'll glean anything useful from it for my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 894ba3cc-d09b-192f-3ea8-1ae79b722903
* Version Independent ID: 2972d37a-a658-9c8b-7d81-0fb0d8f2bded
* Content: [Tutorial - Deploy to Azure Kubernetes Service using the blue/green deployment pattern](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-to-aks-using-blue-green-deployment-pattern)
* Content Source: [articles/jenkins/deploy-to-aks-using-blue-green-deployment-pattern.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-to-aks-using-blue-green-deployment-pattern.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@deathgaze You're correct. This is really more of a sample for people already advanced in this area. I've put this on my backlog to simplify this article - either by adding another simpler article that is read before this one and/or adding more explanation to this one. Thanks for alerting me to this.
