### ISSUE TITLE
Failed to deploy VM

### ISSUE THREAD

**Issue by basanaguk** [MicrosoftDocs/azure-dev-docs#146]
Ansible solution template in the Azure Marketplace doesn't deploy successfully, fails for ansiblehost/Init.
Can provide complete error for investigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbac8547-e10d-0438-e698-a60333d9eaea
* Version Independent ID: 387803db-c79d-137e-a70c-5b68d0e7d772
* Content: [Quickstart - Deploy the Ansible solution template for Azure to CentOS](https://docs.microsoft.com/en-us/azure/developer/ansible/solution-template-deploy#feedback)
* Content Source: [articles/ansible/solution-template-deploy.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/solution-template-deploy.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by basanaguk** [comment]
Complete error response from deployment below:

`{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "VMExtensionProvisioningError",
                "message": "VM has reported a failure when processing extension 'Init'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\nu-manylinux1_x86_64.whl (387kB)\nRequirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography->ansible[azure])\nRequirement already satisfied (use --upgrade to upgrade): ipaddress; python_version < \"3\" in /usr/lib/python2.7/site-packages (from cryptography->ansible[azure])\nCollecting pyparsing>=2.0.2 (from packaging->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)\nCollecting chardet<4,>=3.0.2 (from requests[security]->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)\nCollecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests[security]->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl (126kB)\nCollecting idna<3,>=2.5 (from requests[security]->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)\nCollecting certifi>=2017.4.17 (from requests[security]->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl (157kB)\nCollecting pyOpenSSL>=0.14; extra == \"security\" (from requests[security]->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl (53kB)\nCollecting paramiko (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl (206kB)\nCollecting colorama>=0.3.9 (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl\nCollecting wheel==0.30.0 (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/0c/80/16a85b47702a1f47a63c104c91abdd0a6704ee8ae3b4ce4afc49bc39f9d9/wheel-0.30.0-py2.py3-none-any.whl (49kB)\nCollecting humanfriendly>=4.7 (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/8e/2d/2f1b0a780b8c948c06c74c8c80e68ac354da52397ba432a1c5ac1923c3af/humanfriendly-8.2-py2.py3-none-any.whl (86kB)\nCollecting applicationinsights>=0.11.1 (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/a1/53/234c53004f71f0717d8acd37876e0b65c121181167057b9ce1b1795f96a0/applicationinsights-0.11.9-py2.py3-none-any.whl (58kB)\nCollecting tabulate<=0.8.2,>=0.7.7 (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz (45kB)\nCollecting PyJWT (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl\nCollecting pygments (from azure-cli-core==2.0.35->ansible[azure])\n  Downloading https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz (3.3MB)\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-build-nyqW5b/pygments/setup.py\", line 38, in <module>\n        packages = find_packages(include=['pygments', 'pygments.*']),\n    TypeError: find_packages() got an unexpected keyword argument 'include'\n    \n    ----------------------------------------\nFailed to run sudo pip install ansible[azure]\n\n[stderr]\nwarning: /var/cache/yum/x86_64/7/epel/packages/python2-pip-8.1.2-12.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY\nImporting GPG key 0x352C64E5:\n Userid     : \"Fedora EPEL (7) <epel@fedoraproject.org>\"\n Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5\n Package    : epel-release-7-11.noarch (@extras)\n From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7\nCommand \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-nyqW5b/pygments/\nYou are using pip version 8.1.2, however version 20.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
            }
        ]
    }
}`

**Comment by TomArcherMsft** [comment]
@basanaguk I just published a new article for installing Ansible that should resolve any issues. Please let me know if you encounter any further problems. https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm
