### ISSUE TITLE
"Java Flight Recorder" in title should be modified

### ISSUE THREAD

**Issue by anishi1222** [MicrosoftDocs/azure-dev-docs#147]
Indeed the name of "Java Flight Recorder" was correct when Flight Recorder was a part of Oracle proprietary products. However, when this product was open sourced, this was rebranded "JDK Flight Recorder" due to Java trademark issues. So, I would like to propose that the title of this content should be modified and not "Java Flight Recorder" but "JDK Flight Recorder" should be used. If contents are specific to Zulu product, "Zulu Flight Recorder" would be good.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2728adf-facf-65b3-a545-3196d1000235
* Version Independent ID: 9f9d3426-1c6b-0c81-71af-1843ff2eb866
* Content: [Review data with Java Flight Recorder and Mission Control](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-jdk-flight-recorder-and-mission-control#feedback)
* Content Source: [articles/java/fundamentals/java-jdk-flight-recorder-and-mission-control.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/fundamentals/java-jdk-flight-recorder-and-mission-control.md)
* Service: **azure-java**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@anishi1222 thanks for the feedback! I'll confirm and update the topic.
