### ISSUE TITLE
No longer supported

### ISSUE THREAD

**Issue by nabeelp** [MicrosoftDocs/azure-dev-docs#149]
According to the issue logged at https://github.com/chef-partners/azure-chef-extension/issues/292, this method of installing the extension is no longer supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c6aa7c-6cee-f980-5446-8ca3be824078
* Version Independent ID: 4e42cb98-b847-f42c-ce31-4d9c686457a9
* Content: [Install the Chef client from the Azure portal](https://docs.microsoft.com/en-us/azure/developer/chef/client-install-from-azure-portal#feedback)
* Content Source: [articles/chef/client-install-from-azure-portal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/chef/client-install-from-azure-portal.md)
* Service: **chef**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@nabeelp Thanks. I'm following up with Chef Software to make a decision on this.

**Comment by TomArcherMsft** [comment]
@nabeelp We are no longer updating the Chef documentation on docs.microsoft.com. We'll be removing the outdated information we have in order to avoid confusion. For the most accurate, update-to-date information, please see the [Chef documentation for Azure](https://docs.chef.io/azure_portal/)
