### ISSUE TITLE
Wrong parameter name

### ISSUE THREAD

**Issue by carniwar** [MicrosoftDocs/azure-dev-docs#156]
In section "Create PostgreSQL database using the psql command-line utility", step 1 provides the description "Specifies the PostgreSQL server port, which is 5432 by default." for "host" parameter for the second time. Should be "port" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42aebd73-b9e2-c565-cb51-4212c6675087
* Version Independent ID: feb7b212-4f0d-6c55-37fd-d5b383863bc9
* Content: [How to use Spring Data JPA with Azure PostgreSQL](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql#feedback)
* Content Source: [articles/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql.md)
* Service: **postgresql**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@carniwar thanks for catching this! I've updated the topic and will close this issue when the change goes live.
