### ISSUE TITLE
Error while attempting to get secret from Vault

### ISSUE THREAD

**Issue by georgepapad** [MicrosoftDocs/azure-dev-docs#157]
Has anyone seen this error while attempting to get the secret from the vault 

020-05-13T17:06:34.2940600Z TASK [debug] *******************************************************************
2020-05-13T17:06:34.3470632Z ok: [localhost] => {
2020-05-13T17:06:34.3472376Z     "output['secrets'][0]['secret']": "VARIABLE IS NOT DEFINED!: list object has no element 0"
2020-05-13T17:06:34.3472751Z }

I can get the secret via JSON and az cli with no issue. Getting this to work via ansible it has troublesome. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db9852a7-a21b-494a-c17e-448876f6cdf2
* Version Independent ID: 1ffa0bb6-5d10-cee8-d4d9-7b3cbf829c0c
* Content: [Tutorial - Use Azure Key Vault with a Linux virtual machine in Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/key-vault-configure-vm-security)
* Content Source: [articles/ansible/key-vault-configure-vm-security.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/key-vault-configure-vm-security.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hi @georgepapad,

Within the tutorial there is an additional task that must be added to the playbook to register the `output` variable.

```
    - name: Get latest version of a secret
      azure_rm_keyvaultsecret_info:
        vault_uri: "{{ kv_uri }}"
        name: "{{ kv_secret_name }}"
      register: output
```

The task uses the `azure_rm_keyvaultsecret_info` module to retrieve the secret from Azure Key Vault and stores the JSON output in an Ansible variable called `output`.

That variable is then parsed and displayed on the screen with the **debug** module in the following task.

```
    - debug:
        var: output['secrets'][0]['secret'] 
```

Can you confirm you have the above tasks within your playbook?

Thank you,

**Comment by Duffney** [comment]
Another option would be to use '{{lookup(azure_keyvault_secret)}}`

```
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Look up secret when ansible host is general VM
      vars:
        url: 'https://ansiblekeyvaultdev.vault.azure.net/'
        secretname: 'adminPassword'
      debug: msg="the value of this secret is {{lookup('azure_keyvault_secret',secretname,vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant)}}"
```

Please let me know if either of these options resolves your issue. :)

**Comment by Duffney** [comment]
Please let me know if these suggestions do not resolve your issue.
