### ISSUE TITLE
Undefined  oauth2Login

### ISSUE THREAD

**Issue by franciscoslour** [MicrosoftDocs/azure-dev-docs#158]
Hello,
I tried the example mentioned, but I'm having the following error: oauth2Login () Undefined in HttpSecurity dependency

---
#### Detalhes do Documento

⚠ *Não edite esta secção. É necessário para a ligação de problemas docs.microsoft.com ➟ GitHub.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/pt-pt/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory#feedback)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@fransico-s-lourenco thanks for the feedback! We'll investigate and update the topic.

**Comment by fransico-s-lourenco** [comment]
Thank you in advance

**Comment by wujack778** [comment]
Hello @franciscoslour ，I am following this issue. When I send the request according to the above [document](https://docs.microsoft.com/pt-pt/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory#feedback) configuration, I can succeed. But I don’t know the reason for your problem . Do you have more error information and configuration information? Can you  post it？

**Comment by wujack778** [comment]
@KarlErickson The customer has not responded , i can't get more error information , maybe you can close it.

**Comment by KarlErickson** [comment]
@franciscoslour I'm closing this issue but if the problem is still occurring for you, please reopen and provide details. Thanks!
