### ISSUE TITLE
oauth2AllowIdTokenImplicitFlow needed

### ISSUE THREAD

**Issue by enak** [MicrosoftDocs/azure-dev-docs#162]
In the Manifest, I also had to set `oauth2AllowIdTokenImplicitFlow` to true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@KarlErickson - Thanks @enak. Karl would you please investigate?

**Comment by moarychan** [comment]
Hi @enak , this doc has been updated, the value `oauth2AllowIdTokenImplicitFlow` should be set to `true`, please review.
