### ISSUE TITLE
Pay close attention to version dependencies

### ISSUE THREAD

**Issue by erosen03** [MicrosoftDocs/azure-dev-docs#164]
In order to get Ansible to work properly with Azure, you must have the exact component versions in the 'sudo pip install ansible[azure]'. However, you will most likely have newer versions already, and this will cause issues. Tell pip install to overwrite existing component versions by using the '--ignore-installed' paramter:

sudo pip install ansible[azure] --ignore-installed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ac6b7d-76dc-189b-4ce7-d5f2b4043162
* Version Independent ID: 5982bd9f-1339-3a62-75a4-35161e88368e
* Content: [Quickstart - Install Ansible on Linux virtual machines in Azure](https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm)
* Content Source: [articles/ansible/install-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/install-on-linux-vm.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@erosen03 I just published a new article for installing Ansible that should resolve any issues. Please let me know if you encounter any further problems. https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm

**Comment by erosen03** [comment]
Thanks, @TomArcherMsft. That's a good post, and very nice  that there is now a simple .sh file to get things installed properly. I'll use that for the next Ansible controller.
