### ISSUE TITLE
Don't forget to install the Azure CLI

### ISSUE THREAD

**Issue by erosen03** [MicrosoftDocs/azure-dev-docs#165]
Ansible needs the Azure CLI installed in order to properly pull inventory from Azure. Use these instructions to properly install the Azure CLI: 

https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm

It is not as simple as getting it from the OS' package manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ac6b7d-76dc-189b-4ce7-d5f2b4043162
* Version Independent ID: 5982bd9f-1339-3a62-75a4-35161e88368e
* Content: [Quickstart - Install Ansible on Linux virtual machines in Azure](https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm)
* Content Source: [articles/ansible/install-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/install-on-linux-vm.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@erosen03 Thanks for the feedback. The environment in which we normally test is Cloud Shell, which doesn't require Azure CLI installation. 

However, there are many other environments that we should document. Therefore, I rewrote the "Getting Started" article and made it clear that it's about Cloud Shell. 

I'm currently writing a "Getting Started" for Windows/PowerShell, and soon will be doing Linux/AzCli (which I'm assuming is your environment). 

As this feedback has been captured and on my backlog, I'm closing the issue. 

Please feel free to ping me anytime with further feedback.
