### ISSUE TITLE
Install the resource management library

### ISSUE THREAD

**Issue by rajeshpolinati** [MicrosoftDocs/azure-dev-docs#167]
Please change the command from "azire-cli-core" to "azure-cli-core"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf9ee4a-da91-9fcf-5f87-63672ecfc30c
* Version Independent ID: a4e01885-e638-59b3-698c-6123b25b6260
* Content: [Provision a resource group using the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-resource-group#feedback)
* Content Source: [articles/python/azure-sdk-example-resource-group.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-resource-group.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for reporting this...I just published a bunch of new material and it's not surprising that there's a typo here and there.

**Comment by kraigb** [comment]
By the way, @rajeshpolinati, I'd love to hear any thoughts you have on this and the other articles on the Python Dev Center. I just overhauled a bunch of it and would appreciate any feedback.
