### ISSUE TITLE
Step 4: Run the script; filename typo

### ISSUE THREAD

**Issue by codycodes** [MicrosoftDocs/azure-dev-docs#169]
Please change the command from:

`python provision_blob.py` 

to:

`python provision_rg.py`

To run the file provision_rg.py, created in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf9ee4a-da91-9fcf-5f87-63672ecfc30c
* Version Independent ID: a4e01885-e638-59b3-698c-6123b25b6260
* Content: [Provision a resource group using the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-resource-group)
* Content Source: [articles/python/azure-sdk-example-resource-group.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-resource-group.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for pointing that out! Just a copy-paste error from one of the other articles I put together at the same time.

**Comment by kraigb** [comment]
By the way, @codycodes, I'd love to hear any thoughts you have on this and the other articles on the Python Dev Center. I just overhauled a bunch of it and would appreciate any feedback.
