### ISSUE TITLE
Extra word

### ISSUE THREAD

**Issue by ajafry** [MicrosoftDocs/azure-dev-docs#170]
Small correction to the second sentence:
Cloud Shell ~~provides~~ enables you to use either a Bash or PowerShell command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39fcf122-bbe5-875a-a5e7-8d12f4926c95
* Version Independent ID: b606b1bf-3a39-b39d-9bae-6c367dcbc6ab
* Content: [Quickstart - Run Ansible playbooks via Bash in Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/ansible/cloudshell-run-playbook)
* Content Source: [articles/ansible/cloudshell-run-playbook.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/cloudshell-run-playbook.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ajafry Thanks for the feedback. I'll fix this typo this week.

**Comment by TomArcherMsft** [comment]
@ajafry I was finally able to get to this today. It should be live by tomorrow afternoon (PST). Thanks again for letting us know.
