### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by andrewCluey** [MicrosoftDocs/azure-dev-docs#171]
Everything appears to work, all looks good, but the final step (sample app) doesn't result in a publicly available page (just the app GW 502 error).

I was expecting that the Ingress controller would configure the app gateway, with all backend targets etc, but the back end target is missing.

is this intended? Shouldn't the sample yml file result in the app gateway having a target backend FQDN/IP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Tutorial - Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#feedback)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@andrewCluey I apologize for this Issue being dropped. I've completely rewritten and tested this article. The article should go live Monday.
