### ISSUE TITLE
Extra word

### ISSUE THREAD

**Issue by gbroiles** [MicrosoftDocs/azure-dev-docs#172]
In the sentence beginning with “All the resources in the same group are be co-located in that data center...”, “group are be located” should be “group are located”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23cb0e26-3ae1-1499-d71f-92fc8e473fce
* Version Independent ID: f345fb2f-bd3d-e186-5768-75ab27cd113f
* Content: [Provisioning, accessing, and managing resources on Azure](https://docs.microsoft.com/en-us/azure/developer/python/cloud-development-provisioning#feedback)
* Content Source: [articles/python/cloud-development-provisioning.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/cloud-development-provisioning.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@gbroiles Thanks for catching the typo and reporting the issue! I'll get it fixed right away.

**Comment by kraigb** [comment]
Fixed; update will go out with next publish cycle. 

@gbroiles Just to note, because this is a new article I just added to the Dev Center last week, I'd be happy to hear any feedback on the content.

**Comment by gbroiles** [comment]
@kraigb, I found it generally helpful and clear, just though it might be nice to fix the extra word. I was in Nevada City last weekend, it's a beautiful place! I'll take a look at the docs again and see if anything else jumps out at me.
