### ISSUE TITLE
I keep getting errors while running 'terraform plan'

### ISSUE THREAD

**Issue by tonyabedini** [MicrosoftDocs/azure-dev-docs#173]
With 1.38 I got errors about "location" being an invalid resource.  After a 'terraform init', now I'm getting this error:

Error: Invalid resource type

  on .terraform/modules/mycompute/terraform-azurerm-compute-3.2.0/main.tf line 205, in resource "azurerm_network_interface_security_group_association" "test":
 205: resource "azurerm_network_interface_security_group_association" "test" {

The provider provider.azurerm does not support resource type
"azurerm_network_interface_security_group_association"

This is the page where I'm copying from EXACTLY: https://docs.microsoft.com/en-us/azure/developer/terraform/install-configure

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df42c6c6-f4e0-072f-3fca-e3d97ccfe261
* Version Independent ID: da6a6e53-0803-3692-85cb-9a77fc231946
* Content: [Tutorial - Create an Azure VM cluster with Terraform using the Module Registry](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-module)
* Content Source: [articles/terraform/create-vm-cluster-module.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-vm-cluster-module.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@tonyabedini The article's code has been updated to work with the latest version of the Azure provider.
