### ISSUE TITLE
EnvVar needs more details

### ISSUE THREAD

**Issue by churstz** [MicrosoftDocs/azure-dev-docs#175]
The docs reference pulling the SUBSCRIPTION_ID from an Environment Variable but what context is the CLI being used to expand out the value from this variable?  This looks like powershell variable expansion not envvar, not even for bash or cmd expansion.  This doesn't track

az account set --subscription="${SUBSCRIPTION_ID}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce73b1a7-dbe9-3273-670f-e8eb235b0771
* Version Independent ID: b6b527b8-d6e3-fb58-7169-4322f896e991
* Content: [Quickstart - Install and configure Terraform to provision Azure resources](https://docs.microsoft.com/en-us/azure/developer/terraform/install-configure#feedback)
* Content Source: [articles/terraform/install-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/install-configure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@churstz Thanks for the feedback. I'm currently rewriting that article and saw the same thing. That part of the instructions has been removed.
