### ISSUE TITLE
azure-cli-core, not azure-core-cli

### ISSUE THREAD

**Issue by fitzgeraldsteele** [MicrosoftDocs/azure-dev-docs#176]
[Enter feedback here]
In the requirements.txt section, it says azure-core-cli. It should be azure-cli-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72557de-b5e1-5cd2-bff1-f23d9221337b
* Version Independent ID: bfab25db-3a95-a704-dca9-7c67b2387c97
* Content: [Provision a virtual machine using the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-virtual-machines?tabs=bash)
* Content Source: [articles/python/azure-sdk-example-virtual-machines.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-virtual-machines.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@fitzgeraldsteele Right you are. Thanks for reporting the glitch, which I'll fix straight away.
