### ISSUE TITLE
Jenkins diagram is outdated

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#177]
The Jenkins diagram  shows Contrainer Service ( former ACS) which should be AKS

See also https://github.com/MicrosoftDocs/architecture-center/issues/2149
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Quickstart - Create a Jenkins server on Azure](https://docs.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ezYakaEagle442 This article has been rewritten, so the error you mention should be corrected. Thanks for the feedback. Let me know if you still see this error and I'll reopen the issue.
