### ISSUE TITLE
VueJS and 404 responses

### ISSUE THREAD

**Issue by estaylorco** [MicrosoftDocs/azure-dev-docs#178]
The support documentation is fantastic, and following the advice contained in it actually produces a working web app.

There is only one problem though: what to do about the infamous 404 responses when Vue’s router is set to history mode.

It would seem to me that your configuration is getting into the middle of the issue somehow. I say that because no matter what I do, either on the front end or the back end, I cannot solve the problem.  It would be helpful if you could provide advice as to what to do on both the front end and the back end to solve the problem.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d6851cb-0c9f-23ef-f231-ff97f44eb721
* Version Independent ID: 1fcdbb4a-ee88-9dcd-3ec9-e2064d832ceb
* Content: [Deploy a Spring Boot JAR file Web App to Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@estaylorco thanks for reporting this! We'll look into it.

**Comment by yucwan** [comment]
@estaylorco There seems to be no Vue related in the docs: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin, are you pointing to a wrong docs?

**Comment by estaylorco** [comment]
@yucwan It's been 3 months since I posted this, so I'd appreciate it if you could help me rehydrate this issue.  I'm not pointing to any docs.  How do you come to offer up the link in your post?  What's interesting is that the metadata associated with my original post references Linux.  I would never be on the Linux side, unless Linux is synonymous with macOS's Darwin for this context.

I apologize, but I've simply lost context on my original post.

**Comment by yucwan** [comment]
@estaylorco Thanks for reply. Will close this issue then.
