### ISSUE TITLE
Tutorial Create a kubernetes cluster has errors

### ISSUE THREAD

**Issue by heikkito** [MicrosoftDocs/azure-dev-docs#179]
**Section just before the Kubernetes cluster is brought up:** 

toni@Azure:~/clouddrive/terraform-aks-k8s$ terraform plan -out out.plan
var.client_secret
  Enter a value:

**The 'Enter a value' part is not mentioned at all in the tutorial. It does seem to want the secret ID created by in the SP creation part so adding that and it goes forward to this error.** 

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

Error: Error in function call

  on k8s.tf line 41, in resource "azurerm_kubernetes_cluster" "k8s":
  41:             key_data = file(var.ssh_public_key)
    |----------------
    | var.ssh_public_key is "~/.ssh/id_rsa.pub"

Call to function "file" failed: no file exists at /home/toni/.ssh/id_rsa.pub.

**I cannot find any mentions of this in the docs or pre-requisite links from earlier.** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Tutorial - Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by heikkito** [comment]
Note: Issue is easily fixable by doing a ssh-keygen in .\ssh folder as the keys are needed for the nodes but still the base issue remains: no mentions of what this could be so at the moment users who get this will be interrupted badly in the tutorial.

**Comment by kbetts-wwt** [comment]
Same issue as heikkito. Tutorial stopped at:

Error: Error in function call

  on k8s.tf line 41, in resource "azurerm_kubernetes_cluster" "k8s":
  41:             key_data = file(var.ssh_public_key)
    |----------------
    | var.ssh_public_key is "~/.ssh/id_rsa.pub"

Call to function "file" failed: no file exists at
C:\Users\xxxx\.ssh\id_rsa.pub.

**Comment by TomArcherMsft** [comment]
@heikkito I've rewritten and tested this article. I apologize the long wait.
