### ISSUE TITLE
Typo in __init__.py

### ISSUE THREAD

**Issue by thilakarajk** [MicrosoftDocs/azure-dev-docs#18]
I guess there is a typo in [`__init.py__`](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-03#__initpy__) heading. It should be `__init__.py`

**Comment by kraigb** [comment]
@thilakarajk Please close this issue as I've make the fix.

**Comment by thilakarajk** [comment]
Sure @kraigb .
