### ISSUE TITLE
Syntax changes and deprecated warnings

### ISSUE THREAD

**Issue by Roblarson** [MicrosoftDocs/azure-dev-docs#184]
The sample code needs to be updated across this scenario due to updates of the Terraform Azure provider. Tags now require a = in the definition, there are a series of deprecated warnings when you attempt to plan this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e973d5-b117-99c6-f0a0-c7d779ea3ea0
* Version Independent ID: d4d46d49-d837-6d99-2f50-5578f67b1e89
* Content: [Tutorial - Validate a hub and spoke network in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-validation)
* Content Source: [articles/terraform/hub-spoke-validation.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/hub-spoke-validation.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Roblarson Thanks for the feedback. The tags syntax has been updated in all Terraform docs. You should see the change published by afternoon.
