### ISSUE TITLE
VNET configuration missing?

### ISSUE THREAD

**Issue by martinyy108** [MicrosoftDocs/azure-dev-docs#185]
Just wonder why this template doesn't have vnet configuration? We want to use Ansible for automation inside the Azure subscription and also has a policy that VM can not have public IP directly assigned.

Regards,

Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbac8547-e10d-0438-e698-a60333d9eaea
* Version Independent ID: 387803db-c79d-137e-a70c-5b68d0e7d772
* Content: [Quickstart - Deploy the Ansible solution template for Azure to CentOS](https://docs.microsoft.com/en-us/azure/developer/ansible/solution-template-deploy)
* Content Source: [articles/ansible/solution-template-deploy.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/solution-template-deploy.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@martinyy108 I've reached out to the engineering team that owns the solution template. I'll update this Issue as soon as they reply.

**Comment by TomArcherMsft** [comment]
@martinyy108 I talked to the engineering team responsible for the Ansible template, and they suggested submitting a [GitHub Issue](https://github.com/Azure/ansible/issues). I'm closing this Issue as this is not a doc issues, but please feel free to follow up with any additional feedback.
