### ISSUE TITLE
Stage 2 & 3 are duplicates

### ISSUE THREAD

**Issue by stuarthallows** [MicrosoftDocs/azure-dev-docs#19]
Stage 2 & 3 are duplicates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 545a3d32-4b23-8a9e-afc4-e48b1783ce2e
* Version Independent ID: 183441d2-7809-36c3-eafb-0745fab9fa75
* Content: [Deploy the static Node.js app files to Azure Storage from Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-04?tabs=angular#feedback)
* Content Source: [javascript/tutorial-vscode-static-website-node-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-static-website-node-04.md)
* Service: **app-service**
* GitHub Login: @kraigb
* Microsoft Alias: **buhollan**

**Comment by kraigb** [comment]
@stuaruhallows Egads, that's almost embarrassing. :) I'll get it fixed. Thanks for pointing it out! I appreciate it.

**Comment by kraigb** [comment]
Fix is in place. Should be published live tomorrow.
