### ISSUE TITLE
I am getting the error message  ModuleNotFoundError: No module named 'azure

### ISSUE THREAD

**Issue by pkvk14** [MicrosoftDocs/azure-dev-docs#191]
Hi Support,
I am using VSCODE and run same command but getting the error message but it is working fine in python Compiler
**Error Code:**
from azure.common.client_factory import get_client_from_cli_profile
ModuleNotFoundError: No module named 'azure'

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72557de-b5e1-5cd2-bff1-f23d9221337b
* Version Independent ID: bfab25db-3a95-a704-dca9-7c67b2387c97
* Content: [Provision a virtual machine using the Azure SDK libraries for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-virtual-machines?tabs=cmd)
* Content Source: [articles/python/azure-sdk-example-virtual-machines.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-virtual-machines.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Hi @pkvk14, assuming that you created a virtual environment for the project, then you need to make sure that VS Code is selecting that environment as the Python interpreter.

To be more specific, from what you indicate, I assume that you're able to run the code directly from a command prompt in which you've activated the virtual environment you created, yes? (And with which you ran pip install -r requirements.txt.)

When you run VS Code and open that same project folder (or run code . from the command line), typically VS Code finds and activates the virtual environment automatically. However, run the Python: Select Interpreter command from the command palette and make sure the virtual environment is selected. Then you should be able to run the code within VS Code.

If the virtual environment isn't activated in VS Code, then you'd be running on your default global python environment that probably doesn't have the Azure libraries installed.

Let me know if this resolves your issue.

**Comment by kraigb** [comment]
Closing as I assume this is resolved given that there's been no reply.
