### ISSUE TITLE
update tutorial with Az commands instead of AzureRm

### ISSUE THREAD

**Issue by daseth** [MicrosoftDocs/azure-dev-docs#192]
Is it possible to have the tutorial updated to use the new Az powershell module?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 595d5a93-e1ca-fdab-0cd1-91f5fb00d002
* Version Independent ID: 05e2a696-518a-0f22-f7d4-4b2d5b18c825
* Content: [Quickstart - Configure a Windows virtual machine in Azure using Chef](https://docs.microsoft.com/en-us/azure/developer/chef/windows-vm-configure)
* Content Source: [articles/chef/windows-vm-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/chef/windows-vm-configure.md)
* Service: **chef**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@daseth I'm following up with the Chef Software team on this and will update this Issue when I have news.

**Comment by TomArcherMsft** [comment]
@daseth We are no longer updating the Chef documentation on docs.microsoft.com. We'll be removing the outdated information we have in order to avoid confusion. For the most accurate, update-to-date information, please see the [Chef documentation for Azure](https://docs.chef.io/azure_portal/)
