### ISSUE TITLE
imports missed in DemoApplication.java

### ISSUE THREAD

**Issue by itahirov** [MicrosoftDocs/azure-dev-docs#194]
[in my case following imports needed to be add to DemoApplication.java
import io.r2dbc.spi.ConnectionFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.ClassPathResource;
import org.springframework.data.r2dbc.connectionfactory.init.ConnectionFactoryInitializer;
import org.springframework.data.r2dbc.connectionfactory.init.ResourceDatabasePopulator;
Overwise compilation failed with ConnectionFactory creation and initialization errors. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05b955d-5688-f2c3-5c7e-30d269fc6f48
* Version Independent ID: 83b6c7bf-8693-71c0-c933-b36610f7b4c2
* Content: [Use Spring Data R2DBC with Azure SQL Database](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server)
* Content Source: [articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-sql-server.md)
* Service: **sql-database**
* GitHub Login: @bmitchell287
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
@jdubois can you take a look? Thanks!

**Comment by jdubois** [comment]
Thanks for the feedback! Indeed, it would be easier with the import, let me fix that.

**Comment by jdubois** [comment]
The PR is ready to be merged :-)
