### ISSUE TITLE
missing proper documentation

### ISSUE THREAD

**Issue by samitkumarpatel** [MicrosoftDocs/azure-dev-docs#196]
[Enter feedback here]
The keyvault usage of springboot doccuments are missing a lot of details, like :
The maven dependency details. It was missing how to pass the client-secret for keyvault along with client-id. Also, it's missing an example i.e. How to use keyvault key and vaule in spring properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [How to use the Spring Boot Starter for Azure Key Vault](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
The topic has been updated. Closing this issue.
