### ISSUE TITLE
show ip address of VM in command line

### ISSUE THREAD

**Issue by magixus** [MicrosoftDocs/azure-dev-docs#198]
After creating all resources needed to lunch a VM, a command line is used to show the public ip @ :
```shell
vm show --resource-group myResourceGroup --name myVM -d --query [publicIps] --o tsv
```
The `--o` option shows error:  
``` 
az: error: ambiguous option: --o could match --only-show-errors, --output
```
it should be correct with `-o` (delete one dash)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Tutorial  - Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@magixus You're correct. It should be either `--output` or `-o`. I updated the article.
