### ISSUE TITLE
managed AKS cluster - creating from MS Documentation

### ISSUE THREAD

**Issue by edervaldonetoMS** [MicrosoftDocs/azure-dev-docs#199]
Hello,
I´ve been testing some repro and found some issues below. 
https://docs.microsoft.com/en-us/azure/developer/ansible/aks-configure-clusters

The yml on the line "tasks" is the wrong position, should be below " - name" to work fine.
Another interesting point is that only works in the location "**eastus**". I have tried to create in another region like "**westeurope**", "**southeastasia**" without success (screeshot below).

![image](https://user-images.githubusercontent.com/56553626/84805544-54f23400-affc-11ea-9f54-7ab19b1bd1d3.png)

**Error "southeastasia"**
![image](https://user-images.githubusercontent.com/56553626/84805254-e1e8bd80-affb-11ea-8b27-a129226d2c85.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2283dc1-c38e-81ee-c9d9-fd986933b1d5
* Version Independent ID: 39d3c09c-6179-ea2e-7e4b-38bbe5026026
* Content: [Tutorial - Configure Azure Kubernetes Service (AKS) clusters in Azure using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/aks-configure-clusters)
* Content Source: [articles/ansible/aks-configure-clusters.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/aks-configure-clusters.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@edervaldonetoMS 

Thanks for the feedback on the code formatting issue.

As for supported regions, please refer to the [Azure products by region](https://azure.microsoft.com/global-infrastructure/services/?products=kubernetes-service) to determine where a given product or service is supported. From that page, it appears that AKS is not supported in the regions you attempted.

**Comment by TomArcherMsft** [comment]
@edervaldonetoMS Per our discussion, I'm assigning this to the AKS writer for their input.

@zr-msft, @edervaldonetoMS is helping a customer for whom the updated code was working up until a couple of days ago.

**Comment by edervaldonetoMS** [comment]
Hi @TomArcherMsft 
As we talked, follow the Screenshot to the supported regions.
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=kubernetes-service

**WestEurope**
![image](https://user-images.githubusercontent.com/56553626/84993371-229e1f00-b141-11ea-9283-8328ca93321e.png)

**Southeastasia**
![image](https://user-images.githubusercontent.com/56553626/84993501-43ff0b00-b141-11ea-9ae9-a73cd3fb19fd.png)

**Comment by edervaldonetoMS** [comment]
@zr-msft 
Can we have any update? The customer is waiting for some feedback which is affecting PROD environment.
Thanks

**Comment by zr-msft** [comment]
@edervaldonetoMS this doesn't appear to be a docs issue, so i'm removing myself as the assignee

**Comment by TomArcherMsft** [comment]
@zr-msft Could you add the AKS engineering team to this thread? Not being the AKS writer, I don't have those contacts to help the customer.
