### ISSUE TITLE
Incorrect curl syntax for Mac

### ISSUE THREAD

**Issue by VedAustin** [MicrosoftDocs/azure-dev-docs#20]
Original:
curl --header "Content-Type: application/json" --request POST \
    --data {"name":"Visual Studio Code"} http://localhost:7071/api/HttpExample

What worked for me:
curl --header "Content-Type: application/json" --request POST \
    --data **'{"name":"Visual Studio Code"}'** http://localhost:7071/api/HttpExample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32211a5a-ad60-b982-b27e-1f2c7caef1c9
* Version Independent ID: 32a098cf-c39d-342b-5b7e-d9a62f6a9454
* Content: [Tutorial: Debug the Azure Functions Python code locally with Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-04#feedback)
* Content Source: [python/tutorial-vs-code-serverless-python-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-vs-code-serverless-python-04.md)
* Service: **azure-functions**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks, I'll make a fix.
