### ISSUE TITLE
az: error: unrecognized arguments: --password

### ISSUE THREAD

**Issue by saifbadran9** [MicrosoftDocs/azure-dev-docs#200]
Hi Team,

Creating service principal command is failing on the argument --password
az ad sp create-for-rbac --name "yourAzureServicePrincipalName" --password yourSecurePassword

However, it works without adding password, it's automatically generated (as also mentioned in the document).

Also, it works the same without quotation marks on the name, despite what is mentioned in the document.

See the screenshot for the 3 scenarios:

![image](https://user-images.githubusercontent.com/31154438/84866006-cf18cc00-b081-11ea-9456-e61c78900c31.png)

Not sure if this is a documentation bug or the argument has changed or no longer used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fd46b73-61b1-0abc-1e8d-7e14f1893712
* Version Independent ID: 94b1c084-a988-f125-1127-feb890fb8bb7
* Content: [Tutorial - Deploy from GitHub to Azure App Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-azure-app-service)
* Content Source: [articles/jenkins/deploy-from-github-to-azure-app-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-azure-app-service.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@saifbadran9 Thanks for the feedback. It looks like this is an older doc that we need to update.

**Comment by TomArcherMsft** [comment]
@saifbadran9 This article has been updated to reflect the change to the `az ad sp create-for-rbac` command. It should be live tomorrow. Thanks again for the heads-up.
