### ISSUE TITLE
Great Doc

### ISSUE THREAD

**Issue by bharatsavanur11** [MicrosoftDocs/azure-dev-docs#201]
Followed all the steps for JDK 11 and it worked like a charm. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d6851cb-0c9f-23ef-f231-ff97f44eb721
* Version Independent ID: 1fcdbb4a-ee88-9dcd-3ec9-e2064d832ceb
* Content: [Deploy a Spring Boot JAR file Web App to Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@bharatsavanur11 thanks!
