### ISSUE TITLE
Can't find dependence：spring-cloud-azure-servicebus-queue-stream-binder

### ISSUE THREAD

**Issue by CherrieYu** [MicrosoftDocs/azure-dev-docs#202]
When I want to use  Spring Cloud Azure Stream Binder for Azure Service Bus by reference doc  to add the dependence element：
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-cloud-azure-servicebus-queue-stream-binder</artifactId>
    <version>1.1.0.RC5</version>
</dependency>
But I could't found it in maven repository

**Comment by KarlErickson** [comment]
@CherrieYu thanks for the comment. It looks like you're referring to the *pom.xml* snippet [here](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus#use-the-spring-cloud-stream-binder-starter) in the topic "How to use Spring Cloud Azure Stream Binder for Azure Service Bus". 

I was able to find the [1.1.0.RC5 version](https://search.maven.org/artifact/com.microsoft.azure/spring-cloud-azure-servicebus-queue-stream-binder/1.1.0.RC5/jar) but it looks like there are later versions you could try. I'll create a work item to update the topic.

**Comment by han-gao** [comment]
Hi, @CherrieYu 
1.1.0.RC5 version will have the above problems. This is the document update is not timely,Now the documentation has been updated. You can also find the latest version in the [maven repository](https://mvnrepository.com/artifact/com.microsoft.azure/spring-cloud-azure-servicebus-topic-stream-binder).

**Comment by KarlErickson** [comment]
topic has been updated
