### ISSUE TITLE
Typo in Ansible Code Example

### ISSUE THREAD

**Issue by BenMitchell1979** [MicrosoftDocs/azure-dev-docs#203]
There is a minor typo in the Ansible Example where the "Name" parameters has duplicate entries and thus can be confusing (these should be unique). The first entry should be "Get info of backend server 1". 
```ansible
    - name: Get info of backend server 2
      azure_rm_resource_facts:
        api_version: '2018-04-01'
        resource_group: "{{ resource_group }}"
        provider: containerinstance
        resource_type: containergroups
        resource_name: "{{ aci_1_name }}"
      register: aci_1_output
    - name: Get info of backend server 2
      azure_rm_resource_facts:
        api_version: '2018-04-01'
        resource_group: "{{ resource_group }}"
        provider: containerinstance
        resource_type: containergroups
        resource_name: "{{ aci_2_name }}"
      register: aci_2_output
```

It should read

```ansible
    - name: Get info of backend server 1
      azure_rm_resource_facts:
        api_version: '2018-04-01'
        resource_group: "{{ resource_group }}"
        provider: containerinstance
        resource_type: containergroups
        resource_name: "{{ aci_1_name }}"
      register: aci_1_output
    - name: Get info of backend server 2
      azure_rm_resource_facts:
        api_version: '2018-04-01'
        resource_group: "{{ resource_group }}"
        provider: containerinstance
        resource_type: containergroups
        resource_name: "{{ aci_2_name }}"
      register: aci_2_output
```
---

Regards,
BenTheBuilder

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add408b4-ddd7-7c3c-0f52-eb0f255620f9
* Version Independent ID: 128452df-e3d5-3e32-1afa-25dcc979c21c
* Content: [Tutorial - Manage web traffic with Azure Application Gateway using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/application-gateway-configure)
* Content Source: [articles/ansible/application-gateway-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/application-gateway-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@BenMitchell1979 Thanks for the correction. I've updated the article and it should be live in a couple of hours.
