### ISSUE TITLE
No such yml properties

### ISSUE THREAD

**Issue by Chaitanyahegde** [MicrosoftDocs/azure-dev-docs#204]
Hi,

The compiler does not recognize these properties. 
Has the property names changed ?

azure.keyvault.enabled=true
azure.keyvault.uri=Your-Keyvault-uri
azure.keyvault.client-id=Your-Client-ID
azure.keyvault.tenant-id=Your-Tenant-ID

I have added the dependency - azure-keyvault-secrets-spring-boot-starter.

Am I missing something.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [How to use the Spring Boot Starter for Azure Key Vault](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@Chaitanyahegde thanks for alerting us to this issue. We'll investigate and update the topic as needed.

**Comment by edburns** [comment]
I am unable to reproduce this.  #pleaseclose
