### ISSUE TITLE
Syntax error in variables.tf file

### ISSUE THREAD

**Issue by orhuidobro** [MicrosoftDocs/azure-dev-docs#209]
In file `variables.tf` the line:
`variable "tags" = {`
should be:
`variable "tags" {`
The `=` sign results in an Terraform error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560d5902-d21c-a085-86a2-3189dde5d76c
* Version Independent ID: 7c19fad6-c65a-847d-a98c-0f9c9e4c6217
* Content: [Tutorial - Create an Azure virtual machine scale set using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-hcl)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-vm-scaleset-network-disks-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@orhuidobro What version of Terraform are you using? In what environment (Cloud Shell, Linux VM, etc)? 

The most recent versions are:
- Terraform v0.12.26
- provider.azurerm v2.15.0

**Comment by orhuidobro** [comment]
$ terraform --version
Terraform v0.12.25
+ provider.azurerm v2.5.0
+ provider.random v2.2.1

$ cat provider.tf
provider "azurerm" {
    version = "=2.5.0"
    features {}

**Comment by TomArcherMsft** [comment]
@orhuidobro I see the issue. I thought it was an assignment, but you're referring to where it's being (incorrectly) used in a variable block. You're correct. The = sign is not valid in that context. I'll fix. Thanks for the feedback.

**Comment by orhuidobro** [comment]
You are welcome.

**Comment by TomArcherMsft** [comment]
@orhuidobro I made the fix and it will be published tomorrow morning (PST).
