### ISSUE TITLE
Correct command is "keytool -keystore cacerts -importcert -alias bc2025ca -file bc2025.crt because we are downloading crt" certificate

### ISSUE THREAD

**Issue by shubhammicrosoft1** [MicrosoftDocs/azure-dev-docs#21]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a02dd0f-6929-1b9b-da8d-55848b733460
* Version Independent ID: a440a8b3-a190-645d-8210-5b29ad633c25
* Content: [Add a root certificate for Azure to the Java CA store](https://docs.microsoft.com/en-us/azure/java/java-sdk-add-certificate-ca-store?view=azure-java-stable#feedback)
* Content Source: [java/java-sdk-add-certificate-ca-store.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/java-sdk-add-certificate-ca-store.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@selvasingh - Asir would you please validate this issue/update to the command? Thanks

**Comment by selvasingh** [comment]
This needs to be verified and fixed
