### ISSUE TITLE
Exception: redirectUriTemplate cannot be empty

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/azure-dev-docs#210]
I get the following exception when updating my single-sign-on project from spring boot 2.1.4.RELEASE to
spring boot 2.2.4.RELEASE.

What should I change, that I can  secure my Java web app using the Spring Boot Starter for Azure Active Directory like I did before?

MY Pom File looks like:

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<!-- <version>2.1.4.RELEASE</version> -->
		<version>2.2.4.RELEASE</version>
		
	</parent>

<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>14.2.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>2.1.6</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

<dependencies>
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-active-directory-spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-jose</artifactId>
		</dependency>

```

I hope you can help me. Should I user somewhere another version? With Spring Boot 2.1.4.RELEASE everything works fine.

`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfig': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.OAuth2ClientConfiguration$OAuth2ClientWebMvcSecurityConfiguration': Unsatisfied dependency expressed through method 'setAuthorizedClientRepository' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizedClientRepository' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2WebSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'authorizedClientRepository' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizedClientService' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2WebSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'authorizedClientService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clientRegistrationRepository' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/client/servlet/OAuth2ClientRegistrationRepositoryConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository]: Factory method 'clientRegistrationRepository' threw exception; nested exception is java.lang.IllegalArgumentException: redirectUriTemplate cannot be empty`

**Comment by einue** [comment]
I could solve my problem for spring boot 2.2.4 by using
<dependency>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>2.2.4</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>


Furthermore I have to register my app as multi-tenant app described here:
https://docs.microsoft.com/en-US/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant#update-registration-to-be-multi-tenant

**Comment by KarlErickson** [comment]
@einue thanks for the comment and the solution info! We'll look into this and update the docs as appropriate.

**Comment by einue** [comment]
@KarlErickson  where do I get the docs for it?

**Comment by KarlErickson** [comment]
@einue the topic is [Tutorial: Secure a Java web app using the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory).

**Comment by einue** [comment]
@KarlErickson   i know the tutorial but actually there is nothing about compatible versions  included... I hope this will added be soon. thanks.

**Comment by moarychan** [comment]
Hi @einue , thank you for your reply, it's difficult to add a version compatibility description in tutorial, because there are too many versions, you can find the [azure spring bom](https://mvnrepository.com/artifact/com.microsoft.azure/azure-spring-boot-bom) according to your spring boot version used. You can also pay attention to [azure spring module](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/README.md) for more detailed information.
