### ISSUE TITLE
Misleading information about CosmosDB

### ISSUE THREAD

**Issue by SogoGolf** [MicrosoftDocs/azure-dev-docs#211]
We use CosmosDB and you are absolutely right about this as described in the documentation:

_Your application users won't always have internet connectivity. Applications are designed and expected to work with or without an internet connection. Developers must choose the right solution for storing and syncing their data to the cloud to provide a great customer experience for their application._

However - you DONT answer that question in terms of _how_ CosmosDB solves the problem ? From our understanding it is NOT possible using currently available CosmosDB API's, to sync data between mobile app clients and CosmosDB !!! Given that is the case it seems like the paragraph above from this documentation page is very misleading and should be **removed**. Do you agree ?
.
.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0863cd21-1efc-a123-d8c3-c9b21873ca54
* Version Independent ID: 62fc3700-e827-29b7-f253-7bac94f80f47
* Content: [Store, manage, and persist application data in the cloud with Visual Studio App Center and Azure services](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/data-storage)
* Content Source: [articles/mobile-apps/data-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/data-storage.md)
* Service: **mobile-services**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by codemillmatt** [comment]
Thanks for the feedback @SogoGolf. 

You're correct, there isn't an off-the-shelf component that enables Cosmos to work offline. You would need to roll your own, most likely with SQLite as the on device data store.

Same could be said for Azure SQL.

However, I don't think the paragraph should be removed. I'll word it a bit better to reduce confusion that either Cosmos or Azure SQL comes w/ offline sync out of the box.

**Comment by codemillmatt** [comment]
changes made/merged - will be visible on next publish

@KarlErickson - #please-close

**Comment by KarlErickson** [comment]
thanks @codemillmatt !
