### ISSUE TITLE
Error in sample code for Route Table association

### ISSUE THREAD

**Issue by Niceboy06600** [MicrosoftDocs/azure-dev-docs#212]
Hello,

in the sample code for the association of the route, there are curly brackets missing on the last line:

   route_table: "{ route_table_name }"

iso
   route_table: "{{ route_table_name }}"

It leads to an error :-( when running the ansible script.

Thanks for updating the sample code.
Vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01ad8c9-f6e4-32bf-3ca9-03954e526d01
* Version Independent ID: 4de81aca-0f02-42a5-e4aa-633416fbebaf
* Content: [Tutorial - Configure Azure route tables using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/route-table-configure)
* Content Source: [articles/ansible/route-table-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/route-table-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hello @Niceboy06600,

I appreciate you filing this issue and I'm looking into it. :) 

I'll let you know once it has been resolved.

Thank you,

**Comment by Duffney** [comment]
Hi @Niceboy06600,

The issue has been merged, thank you for your contribution!

Have a wonderful day,
