### ISSUE TITLE
Not clear where client-id comes from

### ISSUE THREAD

**Issue by jonckvanderkogel** [MicrosoftDocs/azure-dev-docs#215]
Under "Configure and compile your app" it states:

azure.keyvault.enabled=true
azure.keyvault.uri=Your-Keyvault-uri
azure.keyvault.client-id=Your-Client-ID
azure.keyvault.tenant-id=Your-Tenant-ID

However, nowhere on the page is it described where you should get this "client-id". Tenant-id is also not very clear but if you run `az keyvault list` you are actually able to retrieve this. I have no idea where the client-id should come from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [How to use the Spring Boot Starter for Azure Key Vault](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#feedback)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@jonckvanderkogel thanks for pointing out the missing info! We'll investigate and update the topic.

**Comment by jonckvanderkogel** [comment]
@KarlErickson that's great, thank you. In the meantime, could you please confirm that what I need to do here is create a service principal which will give me the client-id I need to link my application to the key vault? I have been trying to piece together other parts of the documentation and it would appear that the service principle is the way to go but if you could confirm it that would be great and potentially save me some time on a path that will not pan out. Thanks!

**Comment by KarlErickson** [comment]
@jonckvanderkogel unfortunately I'm not a subject-matter expert here, but I've brought it to the attention of the product team.

**Comment by edburns** [comment]
Fixed in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/921 .  #pleaseclose

**Comment by KarlErickson** [comment]
Thanks, @edburns !
