### ISSUE TITLE
github repo

### ISSUE THREAD

**Issue by wilferac** [MicrosoftDocs/azure-dev-docs#217]
Can you please share a github repo with the code for this example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71c199c-c217-1edf-b6a3-987303c43a71
* Version Independent ID: 7085914e-878e-5f25-0e03-4b7685fd1db6
* Content: [Use Spring Data R2DBC with Azure Database for MySQL](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-r2dbc-with-azure-mysql)
* Content Source: [articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-mysql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-data-r2dbc-with-azure-mysql.md)
* Service: **mysql**
* GitHub Login: @bmitchell287
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
Hi @wilferac - thanks for the comment! We've added sample links to several topics, including this one. I hope it helps!
