### ISSUE TITLE
Helm init tiller

### ISSUE THREAD

**Issue by ahmedig** [MicrosoftDocs/azure-dev-docs#218]
This is outdated, as helm init is not supported anymore and tiller has gone away.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Tutorial - Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by SychevIgor** [comment]
it's common problem of microsoft aks documentation. they everywhere using helm 2 and don't agree to update to helm3.

**Comment by oofnikj** [comment]
Isn't one of the core maintainers of Helm employed by Microsoft? 😕

**Comment by Duffney** [comment]
helm init has been removed from the article and helm 2 steps have been replaced with helm 3. Please let me know if you run into any more issues. :)
