### ISSUE TITLE
Missing argument in command

### ISSUE THREAD

**Issue by ahmedig** [MicrosoftDocs/azure-dev-docs#219]
I get this error when running the helm install helm-config.yaml
The command is missing a name.

Error: must either provide a name or specify --generate-name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Tutorial - Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#install-azure-ad-pod-identity)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
I've updated the article per your suggestion @ahmedig, thank you!

Please let me know if you run into any other issues. :)
