### ISSUE TITLE
Typo in section

### ISSUE THREAD

**Issue by sean-ludeman** [MicrosoftDocs/azure-dev-docs#22]
"...If you're like to work primarily with serverless code..."

"you're" should be "you" or "you'd"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79696ede-0ff7-43d8-7c9c-4fc9d6b0bf78
* Version Independent ID: 630cfc5c-6609-672d-d051-27ce27ecd941
* Content: [Deploy Node.js web apps to Azure](https://docs.microsoft.com/en-us/azure/javascript/node-howto-deploy-web-app#feedback)
* Content Source: [javascript/node-howto-deploy-web-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/node-howto-deploy-web-app.md)
* Service: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks, I'll fix that.
