### ISSUE TITLE
Document needs update.

### ISSUE THREAD

**Issue by souravmishra-msft** [MicrosoftDocs/azure-dev-docs#221]
The github link present in this document lands up on a blank page and looks like the sample has been removed from there. Can the document be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0fb1c0-486c-bbf3-cbc1-2c1dda60e6ba
* Version Independent ID: 599225e9-1ecc-22c1-5d81-f200df9f74da
* Content: [Spring Boot Starters for Azure](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure#azure-active-directory)
* Content Source: [articles/java/spring-framework/spring-boot-starters-for-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/spring-boot-starters-for-azure.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@souravmishra-msft thanks for the feedback! I'll fix that right away.

**Comment by shashishailaj** [comment]
@KarlErickson Thank you . They seem to have moved to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring .

**Comment by KarlErickson** [comment]
@souravmishra-msft I've fixed this - the update should appear tomorrow. Thanks again!
