### ISSUE TITLE
404 error in Net page on azure doc in Chinese

### ISSUE THREAD

**Issue by lrxtom2** [MicrosoftDocs/azure-dev-docs#225]
**Describe the bug**
404 error when refer to [文档](https://docs.microsoft.com/zh-cn/dotnet/azure/sdk/index.yml) link at .Net on Azure document page in zh-cn.

**To Reproduce**
1. Go to ['用于 .NET 的 Azure SDK'](https://docs.microsoft.com/zh-cn/dotnet/azure/#----net---azure-sdk)
2. Click on '文档'
3. See error

**Comment by lrxtom2** [comment]
refer to https://github.com/MicrosoftDocs/feedback/issues/2938

**Comment by KarlErickson** [comment]
@lrxtom2 thank you for the feedback!

@CamSoper can you address this?

**Comment by CamSoper** [comment]
Here's the PR for the fix:  https://github.com/dotnet/docs/pull/19462

@KarlErickson since we can't link this issue to that PR, I'm fine with closing this one now, or you can wait to verify. I leave it up to you. 🙂

**Comment by KarlErickson** [comment]
@CamSoper it did link, so it should close when your PR merges. Thanks for the fix!

**Comment by CamSoper** [comment]
@KarlErickson Merged. Looks like you'll need to close this manually 🙁

**Comment by KarlErickson** [comment]
@CamSoper not sure but you might need the magic words "fixed <ref to issue>" (or synonym) to get the automatic close.
