### ISSUE TITLE
servlet error

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [MicrosoftDocs/azure-dev-docs#226]
Hi,

While following the tutorial on https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage

I followed all the steps but while doing the curl command (curl -d 'new message' -H 'Content-Type: text/plain' localhost:8080/blob), I got the below error:

Getting error : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.ClassCastException: class org.springframework.web.context.support.ServletContextResource cannot be cast to class org.springframework.core.io.WritableResource (org.springframework.web.context.support.ServletContextResource and org.springframework.core.io.WritableResource are in unnamed module of loader 'app')] with root cause

event log error: 12:50 PM	StorageApplication: Failed to retrieve application JMX service URL

I've replicated all the steps in the tutorial expect for 1 change: 

<dependency>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>spring-azure-starter-storage</artifactId>
   <version>1.2.5</version>
</dependency>

The above dependency is out of service so I used the below one:

<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-storage</artifactId>
    <version>8.6.5</version>
</dependency>

Please let me know what can be the cause for this issue? Thanks

**Comment by KarlErickson** [comment]
@AshutoshAhmadAlexandar thanks for the feedback! @yiliuTo can you provide input here? Thanks!

**Comment by yiliuTo** [comment]
Hi @AshutoshAhmadAlexandar , the starter `com.microsoft.azure spring-azure-starter-storage` has been deprecated and thus this doc is not applied either. For the use of azure storage blob, we provide a [sample](https://github.com/microsoft/azure-spring-boot/tree/2.3.x/azure-spring-boot-samples/azure-spring-boot-sample-storage-blob) which you can refer to.

**Comment by AshutoshAhmadAlexandar** [comment]
does this new sample has a documentation page except for github repo? Can't seem it find it.

**Comment by yiliuTo** [comment]
Sorry we don't have a document.

**Comment by yiliuTo** [comment]
Hi @AshutoshAhmadAlexandar , we provide another starter of storage blob: [spring-cloud-starter-azure-storage](https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-starters/spring-starter-azure-storage) in the repo [Spring Cloud Azure](https://github.com/microsoft/spring-cloud-azure), and here is the associated [sample project](https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/storage-resource-sample). Hope it could help.

**Comment by wujack778** [comment]
**hey friend ，maybe you can try this dependency com.microsoft.azure spring-starter-azure-storage 1.2.5**

**Comment by wujack778** [comment]
@AshutoshAhmadAlexandar
