### ISSUE TITLE
Unable to download the python script

### ISSUE THREAD

**Issue by samanthpulluru** [MicrosoftDocs/azure-dev-docs#227]
https://raw.githubusercontent.com/ansible-collections/community.general/master/scripts/inventory/azure_rm.py seems to be invalid and wget is failing.

Tried accessing the azure_rm.py link placed above the wget section and that returns a 404.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059a1972-09ee-02a7-8159-07ba04a2c763
* Version Independent ID: 4323aa16-062c-1b11-fb73-11777c34f88e
* Content: [Tutorial - Configure dynamic inventories of your Azure resources using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure)
* Content Source: [articles/ansible/dynamic-inventory-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/dynamic-inventory-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@samanthpulluru The new URL is https://github.com/ansible-collections/community.general/blob/main/scripts/inventory/azure_rm.py

The article has been updated and will publish today.

**Comment by samanthpulluru** [comment]
Hi Tom,

Thanks for the update. Appreciate it.

Have a good day!

Regards
Samanth
