### ISSUE TITLE
Question: Why I Have to registered App to be multi-tenant?

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/azure-dev-docs#228]
In the tutorial you select for "Who can use the Application or access the Api?" the option "Accounts in this organizational directory only".

This throws the following error:

 Application **** is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

If I choose "Accounts in any organizational directory" It works for me.

Is there anyoption to restrict the application as single-tenant?

**Comment by KarlErickson** [comment]
Hi @einue - thanks for the comment! Which tutorial are you referring to?

**Comment by einue** [comment]
@KarlErickson : https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory

**Comment by KarlErickson** [comment]
Thanks @einue. @yiliuTo is this something you can address?

**Comment by lu-cheng** [comment]
If you need to request a cross tenant API, you need to set it to multi-tenant. If you want to use a single-tenant, you need to create and use your own tenant API, for example: https://login.microsoftonline.com/{tenantid} /oauth2/v2.0/authorize

**Comment by einue** [comment]
> If you need to request a cross tenant API, you need to set it to multi-tenant. If you want to use a single-tenant, you need to create and use your own tenant API, for example: [https://login.microsoftonline.com/{tenantid}](https://login.microsoftonline.com/%7Btenantid%7D) /oauth2/v2.0/authorize

@lu-cheng I will try, but how can I get the following artifact?.... 

Could not find artifact com.microsoft.azure:azure-active-directory-spring-boot-starter:pom:2.3.3-beta.1 in central (https://repo.maven.apache.org/maven2)

**Comment by lu-cheng** [comment]
@einue You can refer to this document: https://dev.azure.com/azure-sdk/public/_packaging?_a=connect&feed=azure-sdk-for-java

**Comment by einue** [comment]
@lu-cheng Thanks. This sample works for me with the single tenant registration!
