### ISSUE TITLE
Issues during tutorial

### ISSUE THREAD

**Issue by satrijotomo** [MicrosoftDocs/azure-dev-docs#229]
When trying this tutorial, I came across two issues:
1. Terraform init failed with authentication error when I used a storage with more than 11 chars. It seems that the file ".terraform/terraform.tfstate" only stores up to 11 char.
2. Terraform apply failed with ""System node pool must use VM sku with more than 2 cores and 4GB memory". This because k8s.tf uses  "Standard_DS1_v2". Changing it to "Standard_DS2_v2" (at the minimum) fixed the issue.

Can you please confirm if the issues above are valid and if they are, can you please update the doc?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Tutorial - Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@satrijotomo I've rewritten and tested this article. Apologies for not coming back and updating the Issue.
