### ISSUE TITLE
Question about secure pages by groups

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/azure-dev-docs#231]
I have another question:

I used the configuration:

azure.activedirectory.active-directory-groups=Test-1,Test-2 .

I expected, people who aren't in the group Test-1 or Test-2 couldn't authenticate to my application but they can, if my Controllers hasn't the annotations @PreAuthorize("hasRole('Group1')") or @Secured(...). 

How does it works? I expected, that the "azure.activedirectory.active-directory-groups" is somehow used automatically in the OAUTH2-Flow by WebSecurityConfig. Otherwise I  have to secure each of my vaadin-views by @secured. But then the spring-property azure.activedirectory.active-directory-groups is never used?

I use

spring: 2.2.4.RELEASE
and
```
<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-spring-boot-bom</artifactId>
	<version>2.2.3</version>
	<type>pom</type>
	<scope>import</scope>
</dependency>

<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>azure-active-directory-spring-boot-starter</artifactId>
</dependency>
```

When I use 
![image](https://user-images.githubusercontent.com/33625116/88032014-aa5ebb00-cb3d-11ea-87c7-fbea603a4bd9.png)
this setting, I can assign users to application.

Have I done or understand anything right? But I don't know for which step the config parameter "azure.activedirectory.active-directory-groups" is used. I hope you can explain this part for me.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@yiliuto can you comment?

**Comment by moarychan** [comment]
hi @einue , first, please note this item  `azure.activedirectory.active-directory-groups` has been changed to `azure.activedirectory.user-group.allowed-groups` in latest snapshot version.


After AAD authenticated, there's token returned; when front-end requests restricted backend api, this method `com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter#doFilterInternal` will intercept, User's UserPrincipal instance will be created with groups that are returned via method `com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient#getGroups`, you can debug the method to confirm the result for current user. UserPrincipal 's user groups will reserve the groups matched with configuration `azure.activedirectory.active-directory-groups` in your properties. Using the method of  `@PreAuthorize("hasRole('ROLE_group1')")` will be recognized by Security and further intercepted. This [ repo sample ](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory) works well in my local testing.

**Comment by einue** [comment]
@moarychan  I will try it with your repo sample. Here I get the error "Could not find artifact com.microsoft.azure:azure-active-directory-spring-boot-starter:pom:2.3.3-beta.1 in central (https://repo.maven.apache.org/maven2)" .

Is there a maven repo, I can add to get the dependency

 <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-active-directory-spring-boot-starter</artifactId>
      <version>2.3.3-beta.1</version> 
    </dependency>

?

**Comment by einue** [comment]
@moarychan  I debugged my application and I think, now I do understand.

The property azure.activedirectory.user-group.allowed-groups is to list all Groups which I want use in my App? Afterwards the AzureADGraphclient matchs this groups in the  getGrantedAuthorities-Method and returns the relevant groups.


So but If no group is  matching, it will return "ROLE_USER" which is the DEFAULT_AUTHORITY. 


And I really have to secure each controller by @hasRole or @Secured? Otherwise the user with ROLE_USER which could be any AD-User can access my views, apis whatever...?

**Comment by moarychan** [comment]
hi @einue , this group ROLE_USER is default authority,  if it matches more than one group, there will be no ROLE_USER.

And I really have to secure each controller by @hasRole or @secured? Otherwise the user with ROLE_USER which could be any AD-User can access my views, apis whatever...?
   -- You can compare with the sample configuration, please confirm you enable this annotation `@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true)` in security config class.

**Comment by einue** [comment]
My Scenario is the following:
A user with no matching role from the properties try to login my application.

This is my SecurityConfig

`@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true, proxyTargetClass = true)
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Autowired
    private OAuth2UserService<OidcUserRequest, OidcUser> oidcUserService;

	//@Autowired
	//private AADAuthenticationFilter aadAuthFilter;


	@Override
    protected void configure(HttpSecurity http) throws Exception {
           	
    	http
        .csrf().disable()

        .requestCache().requestCache(new CustomRequestCache())

		// Restrict access to our application.
		.and().authorizeRequests()
		.antMatchers("/app/*").permitAll() //TODO muss raus
        .antMatchers("/test").permitAll() //TODO muss raus
        .antMatchers("/adlogin").permitAll()
        .antMatchers("/adlogin/*").permitAll()
		.requestMatchers(SecurityUtils::isFrameworkInternalRequest).permitAll()
		.anyRequest()
        .authenticated()
        .and()
        .oauth2Login()
        	.loginPage("/oauth2/authorization/azure").permitAll() //include own LoginPage
        	//.loginPage("/adlogin")
        	.successHandler(new SavedRequestAwareAuthenticationSuccessHandler())	
        	.defaultSuccessUrl(LOGIN_SUCCESS_URL,true)	
        	.failureUrl(LOGIN_FAILURE_URL)
        	.userInfoEndpoint()
        	.oidcUserService(oidcUserService);
    }
    
    /**
	 * Allows access to static resources, bypassing Spring security.
	 */
	@Override
	public void configure(WebSecurity web) throws Exception {
		web.ignoring().antMatchers(
				// client-side JS code
				"/VAADIN/**",

				// the standard favicon URI
				"/favicon.ico",

				// the robots exclusion standard
				"/robots.txt",

				// web application manifest
				"/manifest.webmanifest",
				"/sw.js",
				"/offline-page.html",

				// icons and images
				"/icons/**",
				"/images/**",

				// (development mode) H2 debugging console
				"/h2-console/**" );
	}`

These are the relevant properties:

`## Specifies your Active Directory ID:
azure.activedirectory.tenant-id=7cb49299-d45d-48ff-99b4-4eb24bb46683

## Specifies your App Registration's Application ID:
spring.security.oauth2.client.registration.azure.client-id=*************
## Specifies your App Registration's secret key:
spring.security.oauth2.client.registration.azure.client-secret=********************


# Specifies the list of Active Directory groups to use for authorization:
azure.activedirectory.user-group.allowed-groups=testing`


My DemoView is a VaadinView is not tagged by @PreAuthorize("hasRole('ROLE_group1')") .

My test-user can login and can access my DemoView even tough the test-user hasn't the role testing.  Is this the right behavior? Or should my test-user don't have access to the DemoView? 

This is the point where I am struggleing.


I use the tutorial https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory , too.

@moarychan  Thanks for your explanations... and sorry

**Comment by moarychan** [comment]
hi @einue , please try [this sample](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-backend-v2), it's very similar to your needs, change  client id, client secret, tenant-id, allowed-groups configuration.

**Comment by einue** [comment]
@moarychan  I try the example. This is exactly the same behavior as in my application.

My User Ursula.Test which doesn't match any of the required groups can access the route "localhost:8080" but could not access the routes /group1 or /group2, see screenshot . 

So I conclude, that the if the user returns the "ROLE_USER", the user can access all routes which aren't secured by groups. Right?


![image](https://user-images.githubusercontent.com/33625116/88788390-8df1fc80-d195-11ea-9333-d0d3316899d1.png)

**Comment by moarychan** [comment]
hi @einue , yes, access all routes which aren't secured by groups, means no `@PreAuthorize` marked endpoint, you can test further.

**Comment by moarychan** [comment]
hi @einue , does your program run normally? if works, please help close this issue, thanks.

**Comment by einue** [comment]
@moarychan, Now I have understand the functionality! Thank's a lot.
