### ISSUE TITLE
Basic ALB is created with this code

### ISSUE THREAD

**Issue by kbetts-wwt** [MicrosoftDocs/azure-dev-docs#233]
The coding in this article works great for walking through the creation of a basic AKS cluster via Terraform. However, because a `load_balancer_sku` is not specified in code, a Basic ALB is provisioned, not a Standard ALB. I worked with PSS to figure out why this happens, since a Standard ALB should be the default. Alas, I dont have anymore time to troubleshoot. But it is confirmed that the code, as written in this article, only generates a Basic ALB. 

Why is this a problem? If you decide to follow other Microsoft documents for adding things to this cluster (say for instance an ingress controller), you'll find you are unable to because of the ALB type. For example, the article below shows how to add an Nginx ingress controller to your cluster. It states you should have an AKS cluster before you begin. If you follow this article to create the cluster with terraform, the Ingress Controller article wont work because only a Basic ALB is provisioned.
https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip

The real issue is understanding why only a Basic ALB is provisioned by default when it should be a Standard. Until that is figured out, my suggestion would be to add this code snippet to the k8s.tf file so that other MSFT articles can be completed successfully.

    network_profile {
        load_balancer_sku = "Standard"
        network_plugin = "kubenet"
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Tutorial - Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks#feedback)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@kbetts-wwt Thanks for your feedback. As you noted, this article doesn't do good job of implementing a useful LB. Therefore, it's been removed from the article and I have it on my backlog to write an article specifically working with LBs.
