### ISSUE TITLE
failures in Jenkins deployment script 

### ISSUE THREAD

**Issue by ms-zhouma** [MicrosoftDocs/azure-dev-docs#235]
I ran `azure-jenkins.sh`. It was able to output a url, but I can't connect to it.
Scanning through the full output, it seems things started to go wrong in the CustomScript step.
Full log can be found [here](https://gist.github.com/ms-zhouma/e181f2c2bd058b1c8127812042e81680).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c8677e-3fcd-56c0-fa71-64d758a02ca8
* Version Independent ID: ffb63abe-0c37-4c6c-0560-3e2df33e7e5b
* Content: [Tutorial - Deploy from GitHub to Azure Kubernetes Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-aks#deploy-jenkins-to-an-azure-vm)
* Content Source: [articles/jenkins/deploy-from-github-to-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-aks.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by ms-zhouma** [comment]
In case this helps, I SSHed into the VM and manually run steps in `config-jenkins.sh` and saw the `oracle-java8-installer` is no longer available. (When you try to add repository, you get a special warning.) Switching to openjdk (and the key stuff accordingly) helped get me unblocked.

**Comment by Duffney** [comment]
Hi @ms-zhouma,

I've submitted a PR to update the documentation. The `azure-jenkins.sh` that was referenced had several issues and is no longer maintained. I replaced it with a prerequisite and updated the article accordingly.

The Changes should be reflected in a day or two.

I appreciate you taking the time to file the issue, thank you!
