### ISSUE TITLE
the kubectl version installed in jenkins VM is out-of-date 

### ISSUE THREAD

**Issue by ms-zhouma** [MicrosoftDocs/azure-dev-docs#238]
As of today I get a v1.16.10 cluster when I follow [this doc](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough). But in `config-jenkins.sh`, a v1.8.0 version of kubectl is copied to Jenkins VM.

This is causing Jenkins build to fail.
I tried to bump the kubectl version to v1.18.0 and got unblocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c8677e-3fcd-56c0-fa71-64d758a02ca8
* Version Independent ID: ffb63abe-0c37-4c6c-0560-3e2df33e7e5b
* Content: [Tutorial - Deploy from GitHub to Azure Kubernetes Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-aks#deploy-jenkins-to-an-azure-vm)
* Content Source: [articles/jenkins/deploy-from-github-to-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-aks.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hi @ms-zhouma,

I have submitted a PR to replace the version locked kubectl script with the `az aks install-cli` AzCLI command to resolve the issue.

You should see the changes reflected in the article within a few days.

Thank you!
