### ISSUE TITLE
please update procedure to specify LB SKU as standard. 

### ISSUE THREAD

**Issue by porrascarlos802018** [MicrosoftDocs/azure-dev-docs#239]
if the load balancer type is not specified, by default terraform seems to create basic LB.
STANDARD should be the default and to have terraform deploying STANDARD we need to add the network profile

    network_profile {
        load_balancer_sku = "Standard"   had to add this to force a Standard ALB; otherwise Basic
        network_plugin = "kubenet"
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Tutorial - Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@porrascarlos802018 The LB has been removed from this article as it will be explained better and be a focal point of a future article.
