### ISSUE TITLE
Issue with Batch Example?

### ISSUE THREAD

**Issue by konstantin-magg** [MicrosoftDocs/azure-dev-docs#240]
Is there an issue with the Batch example?

```
$ source .venv/share/activate
bash: .venv/share/activate: No such file or directory
```

[packaging.python.org](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment) suggests this command (which - at least on my machine - works):

```
source env/bin/activate
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c507d59-970e-feae-b034-8dc27f04d6b4
* Version Independent ID: 0c608a8f-a794-1f3e-6047-24dd2108633b
* Content: [Configure your local Python environment for Azure development](https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=cmd)
* Content Source: [articles/python/configure-local-development-environment.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/configure-local-development-environment.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@konstantin-magg Thanks for filing the issue. The exact command that works to activate a virtual environment depends on the name of the virtual environment folder. In the article you mention, the previous instruction is `python -m venv .venv` which creates a virtual environment in a folder named *.venv*. Therefore the activate command would be `source .venv/share/activate` as indicated.

If, however, you have used the command `python -m venv env` instead (perhaps out of muscle memory!), then yes, the activate command would be `source env/share/activate`. 

In any case, the article, as written, is accurate.
