### ISSUE TITLE
Dependency for eventhub starter in not in public repo

### ISSUE THREAD

**Issue by Myslyvchuk** [MicrosoftDocs/azure-dev-docs#241]
[Enter feedback here]
<dependency>
   <groupId>com.microsoft.azure</groupId>
   <artifactId>spring-cloud-azure-starter-eventhub</artifactId>
   <version>1.0.0.M2</version>
</dependency>
 You cannot reach this dependency from maven public repo. You need to have either some dependencyManagement section (which is not specified) or something else
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52000652-22d7-ec02-3e24-4a4c97672050
* Version Independent ID: 09d45663-2663-50cc-1388-cb6852860515
* Content: [How to use the Spring Boot Starter for Apache Kafka with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@Myslyvchuk thanks for the feedback! We'll look into this.

**Comment by KarlErickson** [comment]
topic has been updated
