### ISSUE TITLE
The playbook sample in the document is outdated

### ISSUE THREAD

**Issue by chunliu** [MicrosoftDocs/azure-dev-docs#243]
The code of the playbook `vmss-create.yml` is outdated. The latest version of azure_rm_loadbalancer has been changed and the code in the playbook is not compatible with it anymore. Running the playbook without change will fail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aba862e-8fdc-8ef5-60d3-eae435b3ae5b
* Version Independent ID: 18c56460-7500-771a-0edc-92b1401bd6ec
* Content: [Tutorial - Configure virtual machine scale sets in Azure using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/vm-scale-set-configure)
* Content Source: [articles/ansible/vm-scale-set-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/vm-scale-set-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Hi, @chunliu. This issue has been resolved and you should see it updated in the docs today.
