### ISSUE TITLE
Sample code in the document is outdated

### ISSUE THREAD

**Issue by chunliu** [MicrosoftDocs/azure-dev-docs#246]
The ansible modules used in the sample code in the document, `azure_rm_publicipaddress_facts` and `azure_rm_loadbalancer_facts`, are deprecated. It shows the deprecated warning now, and will fail with the future version of Ansible. The modules need to be replaced with `azure_rm_publicipaddress_info` and `azure_rm_loadbalancer_info`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127ac634-16ce-4f19-7060-0752c5538eba
* Version Independent ID: e85ac4f5-726d-5011-0a8e-c7ebb2bb5773
* Content: [Tutorial - Deploy apps to virtual machine scale sets in Azure using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/vm-scale-set-deploy-app)
* Content Source: [articles/ansible/vm-scale-set-deploy-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/vm-scale-set-deploy-app.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Hi, @chunliu. The fix for this was merged this morning and should be live later today. Thanks for your feedback.
