### ISSUE TITLE
Tried the steps!! But Getting Error

### ISSUE THREAD

**Issue by codebrigade2020** [MicrosoftDocs/azure-dev-docs#249]
Getting this error:
Unable to acquire on-behalf-of token for client f93*****-3***-4***-a***

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@codebrigade2020 thanks for the report! We'll investigate.

**Comment by KarlErickson** [comment]
@yiliuTo can you comment here?

**Comment by codebrigade2020** [comment]
Hi @KarlErickson  I have fixed it after I verified the solutions on other websites. I think it's outdated in Azure docs. If the docs are up-to-date, will be much helpful for students like me in projects.

**Comment by yiliuTo** [comment]
@KarlErickson @codebrigade2020 Thanks for the reporting, we will check the doc.
