### ISSUE TITLE
Valid Types For PartitionKey

### ISSUE THREAD

**Issue by MP7373** [MicrosoftDocs/azure-dev-docs#251]
I was running a sample app with an int set as the partition key on my document and got the error:

java.lang.IllegalArgumentException: type of PartitionKey field must be String

I couldn't find anywhere on this page something explaining what types are valid for the partition key.
Is it possible to have an int as a partition key or does it have to be a String using this library?

Also In regards to general cosmos db documentation it is incredibly difficult to find anything about what sort of data types cosmos db supports. I don't know if it supports only JSON types or other types as well.

This page just has all String fields on the example document classes so It's hard to no what is actually supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a03983-f9b2-360a-68d4-3f8a5f7b6923
* Version Independent ID: 3463f85f-dd80-85bb-4dbd-cba82fc5c4ef
* Content: [Spring Data Azure Cosmos DB developer's guide](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb)
* Content Source: [articles/java/spring-framework/how-to-guides-spring-data-cosmosdb.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/how-to-guides-spring-data-cosmosdb.md)
* Service: **azure-java**
* GitHub Login: @kushagraThapar
* Microsoft Alias: **kuthapar**

**Comment by KarlErickson** [comment]
@MP7373 thanks for the feedback! @jdubois and/or @kushagraThapar can you comment here?

**Comment by kushagraThapar** [comment]
@MP7373 - String partition key is a limitation on current spring-data-cosmosdb SDK. However, cosmos db actually supports different partition key types - including int, long, bool, string, etc. 

In the new `azure-spring-data-cosmos` release, this limitation is addressed and users can choose any type of partition key they want to as long as it is supported by cosmos db backend: https://github.com/Azure/azure-sdk-for-java/issues/13654

@anfeldma-ms - can you please provide an update on partition key support from cosmosdb backend ?

**Comment by KarlErickson** [comment]
Topic has been updated.
