### ISSUE TITLE
Page links to azure_rm.py inventory script that says its deprecated

### ISSUE THREAD

**Issue by bbgobie** [MicrosoftDocs/azure-dev-docs#252]
Comment in the script says it was deprecated since 2018
https://github.com/ansible-collections/community.general/blob/main/scripts/inventory/azure_rm.py

The new link in the comment actually currently returns a 404

"Important note (2018/10)
========================
This inventory script is in maintenance mode: only critical bug fixes but no new features.
There's new Azure external inventory script at https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/azure_rm.py,
with better performance and latest new features. Please go to the link to get latest Azure inventory."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059a1972-09ee-02a7-8159-07ba04a2c763
* Version Independent ID: 4323aa16-062c-1b11-fb73-11777c34f88e
* Content: [Tutorial - Configure dynamic inventories of your Azure resources using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure)
* Content Source: [articles/ansible/dynamic-inventory-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/dynamic-inventory-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@bbgobie  Maybe I'm misunderstanding your question, but the section your'e referring to states to use that file is for Ansible < 2.8. Therefore, it's specifically for people who are using an older version of Ansible. I'm going to close this issue, but if I've misunderstood your concern, please let me know and I'll reopen.
