### ISSUE TITLE
Code example for creating a storage blob fails with error

### ISSUE THREAD

**Issue by brooke-hamilton** [MicrosoftDocs/azure-dev-docs#255]
Under section "[3: Write code to provision storage resources](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-storage?tabs=cmd#3-write-code-to-provision-storage-resources)", the command to create a storage container throws an error.

```
container = storage_client.blob_containers.create(RESOURCE_GROUP_NAME, STORAGE_ACCOUNT_NAME, CONTAINER_NAME, {})
```

The error is:
```
Deserializer is not able to find {} as valid enum in <enum 'PublicAccess'>
ValueError: '{}' is not a valid PublicAccess

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/msrest/serialization.py", line 910, in serialize_enum
    enum_obj(result)
  File "/usr/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: '{}' is not a valid PublicAccess
```

The error can be fixed by replacing `{}` with `"None"` for the PublicAccess parameter in the command, like this:
```
container = storage_client.blob_containers.create(RESOURCE_GROUP_NAME, STORAGE_ACCOUNT_NAME, CONTAINER_NAME, "None")
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd8f944-4414-8b64-6564-35f24725385e
* Version Independent ID: f63c52f7-0a66-1bbe-dae2-5a9ade5f1e84
* Content: [Provision Azure Storage with the Azure libraries for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-storage?tabs=cmd)
* Content Source: [articles/python/azure-sdk-example-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-storage.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@brooke-hamilton Thanks for the issue and the suggested fix. Can you tell me what version of the azure-mgmt-storage library you're using (from pip freeze)?

**Comment by kraigb** [comment]
Correction, only BlobContainersOperations.list was changed; create wasn't affected. I also just ran the example code using the 11.1 azure-mgmt-storage library and everything worked fine. And I'm running Python 3.8.3.

I tried "None" as in your example, but the code failed. {} still works on my end (on a Windows machine).

Can you give the output of pip freeze so I can compare library versions?

**Comment by brooke-hamilton** [comment]
Thank you for looking into this.

I have `azure-mgmt-storage==7.1.0`

In case this helps, running `pip3 freeze | grep azure-mgmt` returns this:
```BASH
azure-mgmt==5.0.0a1
azure-mgmt-advisor==3.0.0
azure-mgmt-alertsmanagement==0.2.0rc2
azure-mgmt-apimanagement==0.1.0
azure-mgmt-appconfiguration==0.3.0
azure-mgmt-applicationinsights==0.2.0
azure-mgmt-appplatform==0.1.0
azure-mgmt-attestation==0.1.0
azure-mgmt-authorization==0.60.0
azure-mgmt-automation==0.1.1
azure-mgmt-azurestack==0.1.0
azure-mgmt-batch==7.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-botservice==0.2.0
azure-mgmt-cdn==4.1.0rc1
azure-mgmt-cognitiveservices==5.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==10.0.0
azure-mgmt-consumption==3.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==3.0.0rc8
azure-mgmt-containerservice==8.2.0
azure-mgmt-cosmosdb==0.11.0
azure-mgmt-costmanagement==0.1.0
azure-mgmt-databoxedge==0.1.0
azure-mgmt-databricks==0.1.0
azure-mgmt-datafactory==0.8.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==4.0.0
azure-mgmt-datashare==0.1.0rc1
azure-mgmt-deploymentmanager==0.2.0
azure-mgmt-devspaces==0.2.0
azure-mgmt-devtestlabs==4.0.0
azure-mgmt-dns==3.0.0
azure-mgmt-documentdb==0.1.3
azure-mgmt-edgegateway==0.1.0
azure-mgmt-eventgrid==3.0.0rc4
azure-mgmt-eventhub==3.0.0
azure-mgmt-frontdoor==0.3.0
azure-mgmt-hanaonazure==0.12.0
azure-mgmt-hdinsight==1.4.0
azure-mgmt-healthcareapis==0.1.0
azure-mgmt-hybridcompute==0.1.1
azure-mgmt-imagebuilder==0.3.0
azure-mgmt-iotcentral==2.0.0
azure-mgmt-iothub==0.10.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==2.0.0
azure-mgmt-kusto==0.5.0
azure-mgmt-labservices==0.1.1
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==4.0.0rc2
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-machinelearningservices==0.1.0
azure-mgmt-maintenance==0.1.0
azure-mgmt-managedservices==1.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.2.1
azure-mgmt-media==2.1.0
azure-mgmt-mixedreality==0.1.0
azure-mgmt-monitor==0.7.0
azure-mgmt-msi==1.0.0
azure-mgmt-netapp==0.8.0
azure-mgmt-network==9.0.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-operationsmanagement==0.1.0
azure-mgmt-peering==0.1.0rc2
azure-mgmt-policyinsights==0.4.0
azure-mgmt-powerbidedicated==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-privatedns==0.1.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.4.0
azure-mgmt-recoveryservicesbackup==0.6.0
azure-mgmt-redis==7.0.0rc1
azure-mgmt-relay==0.2.0
azure-mgmt-reservations==0.7.0
azure-mgmt-resource==8.0.0
azure-mgmt-resourcegraph==2.0.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-security==0.3.0
azure-mgmt-serialconsole==0.1.0
azure-mgmt-servermanager==2.0.0
azure-mgmt-servicebus==0.6.0
azure-mgmt-servicefabric==0.4.0
azure-mgmt-signalr==0.3.0
azure-mgmt-sql==0.16.0
azure-mgmt-sqlvirtualmachine==0.5.0
azure-mgmt-storage==7.1.0
azure-mgmt-storagecache==0.2.0
azure-mgmt-storagesync==0.2.0
azure-mgmt-subscription==0.5.0
azure-mgmt-timeseriesinsights==0.1.0
azure-mgmt-trafficmanager==0.51.0
azure-mgmt-vmwarecloudsimple==0.2.0
azure-mgmt-web==0.44.0
```

**Comment by kraigb** [comment]
Ah, you're running a really old version then. Run pip install --upgrade azure-mgmt-storage and the code should work fine.

From the looks of things, you must have installed all the Azure libraries together at one point? There used to be a single meta-package that did this, but it's since been retired as we recommend installing the specific libraries you need into a virtual environment.

https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-library-package-index has all the current library versions.

**Comment by kraigb** [comment]
Given that the docs are accurate for current library versions, I'm closing this issue. If there is need for further discussion, please reopen. Thanks.

**Comment by brooke-hamilton** [comment]
Thank you for looking into this--I really appreciate the detailed answer.

Separately (not related to this issue) I'm looking into how these older packages were installed. I'm using a three-week old installation of Ubuntu, and these packages show that they were installed on 8/7 - just a week ago. There are a limited number of packages and tools that I configured, so I want to know which one put these here.

**Comment by kraigb** [comment]
Yes, it's curious that you have all older libraries on a new installation, especially that you have the whole collection of them all together. Like I said, the current recommendation is to install only the libraries you need as there is no longer a single "SDK" download or install. Let me know if you discover anything interesting.
