### ISSUE TITLE
Code Issue

### ISSUE THREAD

**Issue by dmoksh** [MicrosoftDocs/azure-dev-docs#258]
Code under the section Authenticate with DefaultAzureCredential has an error.

Last line should be `retrieved_secret = secret_client.get_secret("secret-name-01")` 

Instead it is presented as `retrieved_secret = client.get_secret("secret-name-01")`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036cc96e-fbb8-bced-0a5b-ef6e332264b8
* Version Independent ID: 7b70016c-feb0-7da1-5995-2d1fa8bce9a9
* Content: [How to authenticate Python applications with Azure services](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd)
* Content Source: [articles/python/azure-sdk-authenticate.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-authenticate.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Right you are! I'll get that bit corrected.
