### ISSUE TITLE
Add how to run the convenience file

### ISSUE THREAD

**Issue by alex--thomas** [MicrosoftDocs/azure-dev-docs#259]
[Enter feedback here]
Hi,

The doc says:
For convenience, create a .sh or .cmd file with these commands that you can run whenever you open a terminal or command prompt for local testing.

I'm a newbie to the CLI and although I have created the file (in VSCode) I don't know how to run it...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c507d59-970e-feae-b034-8dc27f04d6b4
* Version Independent ID: 0c608a8f-a794-1f3e-6047-24dd2108633b
* Content: [Configure your local Python environment for Azure development](https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=cmd&ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-Powdp5X0TtJf09W_eFBPUQ&epi=je6NUbpObpQ-Powdp5X0TtJf09W_eFBPUQ&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__jszmhpvqmkkfr1dkkk0sohzw0m2xiixnz9c9zwdk00)(7593)(1243925)(je6NUbpObpQ-Powdp5X0TtJf09W_eFBPUQ)()&irclickid=_jszmhpvqmkkfr1dkkk0sohzw0m2xiixnz9c9zwdk00)
* Content Source: [articles/python/configure-local-development-environment.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/configure-local-development-environment.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@alex--thomas Thanks for the feedback. I'll clarify that paragraph. It just means creating a script file that contains the same lines. The script usually has an extension of .sh (mac/Linux) or .cmd (Windows) so you can just run the script directly from the command line. For example, I have these commands in a file named setenv.cmd, so when I open a new command prompt I can just run "setenv" to define the variables.
