### ISSUE TITLE
azure-cosmosdb-spring-boot-starter version 3.0.0 not in maven

### ISSUE THREAD

**Issue by vermacodes** [MicrosoftDocs/azure-dev-docs#261]
As mentioned in https://github.com/MicrosoftDocs/azure-dev-docs/commit/22d75cfe8b6841ce17b8aecdf6f5410b59bf01ae

<version>3.0.0-beta.1</version> is not in maven.

Latest version in maven is (2.3.3); which downloads azure-cosmos version 3.7.3 and that creates issues alongside azure cosmos v4

If this new verison (3.0.0) have the fix, then please add this to maven central.

**Comment by KarlErickson** [comment]
@vermacodes thanks for the feedback! We'll look into this.

**Comment by KarlErickson** [comment]
This has been fixed.
