### ISSUE TITLE
wrong command to expose the pod

### ISSUE THREAD

**Issue by imod** [MicrosoftDocs/azure-dev-docs#264]
The command to expose a pod is described as:

`kubectl expose deployment gs-spring-boot-docker --type=LoadBalancer --port=80 --target-port=8080` but this raises the following error: `Error from server (NotFound): deployments.apps "gs-spring-boot-docker" not found`

it seem it correct command should be:

`kubectl expose pod gs-spring-boot-docker --type=LoadBalancer --port=80 --target-port=8080`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200ae7a0-87fe-9d4d-db79-12495746fbd8
* Version Independent ID: 0aaa8a60-4aec-ac05-a9bc-7d9a4883c637
* Content: [Deploy Spring Boot Application to the Azure Kubernetes Service - Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@imod thanks for the report! We'll look into this and update the topic.
