### ISSUE TITLE
Powershell command - variable naming error

### ISSUE THREAD

**Issue by nvinod-net** [MicrosoftDocs/azure-dev-docs#266]
The powershell command should be changed from "$psCredential = Get-Credential" to "$spCredential = Get-Credential"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c31173-3e96-c871-5a2d-743a26522b4d
* Version Independent ID: 5b281d75-b37e-0301-e1fd-431e0344d0c7
* Content: [Quickstart - Configure Terraform using Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell)
* Content Source: [articles/terraform/get-started-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@nvinod-net Thanks for the feedback. I've corrected the code. It should be live later this morning (PST).
