### ISSUE TITLE
VAR "aks_enable_rbac" isn't used

### ISSUE THREAD

**Issue by pezzos** [MicrosoftDocs/azure-dev-docs#269]
You define "aks_enable_rbac" in variables.tf but it's not used in 
resource "azurerm_kubernetes_cluster" "k8s"

You have to add:
  role_based_access_control {
    enabled = var.aks_enable_rbac
  }

**Comment by KarlErickson** [comment]
for [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)

**Comment by Duffney** [comment]
Hello @pezzos,

I've added ` role_based_acces_control` to the `azurerm_kubernetes_cluster` code snippet. The changes will be made available after the next build.

Thank you so much for your contribution!
