### ISSUE TITLE
text nitpick

### ISSUE THREAD

**Issue by JeroenStravers1** [MicrosoftDocs/azure-dev-docs#27]
The sentence "You must import func from azure.functions; importing the logging module is optional but recommended." is incorrect. You're importing the azure.functions package and using func as its alias, not importing a specific module named func from azure.functions.

I suggest changing it to "You must import azure.functions; importing the logging module is optional but recommended.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7556d3d-8a73-692e-1754-90e2fe7ff806
* Version Independent ID: 637221f8-9585-0771-619b-8866ead7584d
* Content: [Tutorial: Examine the Python code files for Azure Functions in Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-03#feedback)
* Content Source: [python/tutorial-vs-code-serverless-python-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-vs-code-serverless-python-03.md)
* Service: **azure-functions**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@JeroenStravers1 Good catch, and thanks for the report! You're welcome to make the fix directly, if you like. There's an "Edit" button on the top right of the page that takes you to GitHub to submit a PR with edits. I can edit otherwise, but I wanted to give you the opportunity to make a contribution.

**Comment by kraigb** [comment]
Edit made; closing.
