### ISSUE TITLE
Missing information to test

### ISSUE THREAD

**Issue by pezzos** [MicrosoftDocs/azure-dev-docs#270]
There is a part named "Install a sample app" explaining how to install a sample app. 
But there is no mention to try if this app works.

**Comment by KarlErickson** [comment]
for [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)

**Comment by TomArcherMsft** [comment]
@pezzos I've rewritten and tested this article. It will publish tomorrow morning (PST).
