### ISSUE TITLE
Helm init doesn't exist anymore in Helm v3

### ISSUE THREAD

**Issue by pezzos** [MicrosoftDocs/azure-dev-docs#271]
Helm init has been removed from Helm v3 so all the part in the "Installing Helm" part is to be reviewed.
There is no more Tiller and the client directories are initialised automatically when you start using helm.

**Comment by KarlErickson** [comment]
for [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)

**Comment by Duffney** [comment]
An updated version of the article is now live which includes changes for Helm 3, removing the init command from the require steps. Also reviewed the installing Helm section as advised.

Thank you for your contribution. :)
