### ISSUE TITLE
helm install -f helm-config.yaml application-gateway-kubernetes-ingress/ingress-azure doesn't work

### ISSUE THREAD

**Issue by pezzos** [MicrosoftDocs/azure-dev-docs#272]
helm install -f helm-config.yaml application-gateway-kubernetes-ingress/ingress-azure doesn't work, Helm is waiting for a name.

I suggest:

helm install -f helm-config.yaml appgw-ingress application-gateway-kubernetes-ingress/ingress-azure

**Comment by KarlErickson** [comment]
for [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)

**Comment by Duffney** [comment]
Hey @pezzos,

I've gone through and updated the article to reflect the changes. Please let me know if you run into any more issues.

Thank you for taking the time to file the issue, have a wonderful day!
