### ISSUE TITLE
Good article

### ISSUE THREAD

**Issue by suda007** [MicrosoftDocs/azure-dev-docs#275]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@suda007 Thanks! Please feel free to let us know any ideas you have for us to make improvements.
