### ISSUE TITLE
token auth flow doesn't work

### ISSUE THREAD

**Issue by skwongg** [MicrosoftDocs/azure-dev-docs#28]
following the instructions yields a microsoft-standard error as follows:

Error: failed to get oauth token from device flow: failed to finish device auth flow: autorest/adal/devicetoken: Error while retrieving OAuth token: Unknown Error

In 2019, you would expect a more descriptive error than "Unknown Error"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8f297cb-245c-d353-b709-e3f7c34e12ca
* Version Independent ID: 186aaf08-938a-c05b-68db-0f0efe5dd60f
* Content: [Authentication with the Azure SDK for Go](https://docs.microsoft.com/en-us/azure/go/azure-sdk-go-authorization#feedback)
* Content Source: [go/azure-sdk-go-authorization.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/go/azure-sdk-go-authorization.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by Duffney** [comment]
Hi @skwongg,

I've updated the article and added a call out the new [azidentity](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity) that is now recommended for authentication. Please let me know if you have any concerns or questions. 

Thank you! :)
