### ISSUE TITLE
Add notes about section heading for adding ansible config

### ISSUE THREAD

**Issue by 211217613** [MicrosoftDocs/azure-dev-docs#282]
Add information or the entire code block for the section that states to add hostkeychecking = False to a local ~/.ansible.cfg.

For example the code block should read

```
[defaults]
host_key_checking = False
```

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059a1972-09ee-02a7-8159-07ba04a2c763
* Version Independent ID: 4323aa16-062c-1b11-fb73-11777c34f88e
* Content: [Tutorial - Configure dynamic inventories of your Azure resources using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure)
* Content Source: [articles/ansible/dynamic-inventory-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/dynamic-inventory-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@211217613 I'm not sure what you're asking for here. Could you elaborate please?

**Comment by 211217613** [comment]
There is a section that states to add `host_key_checking = False` to your local/user ansible config. But if you add `host_key_checking = False` to an empty `~/.ansible.cfg` ansible throws an error. 

The tutorial should add that if the file `~/.ansible.cfg` is empty, a heading of `[defaults]` should be added.

**Comment by Duffney** [comment]
Hi @211217613,

I've submitted a PR to resolve this issue.

Thank you for taking the time to file the issue!

**Comment by TomArcherMsft** [comment]
Hi, @211217613. Thanks for the feedback. I apologize for missing your reply to me. It appears that @Duffney has resolved the issue and that fix will publish today. Please let us know if the fix doesn't address the issue.
