### ISSUE TITLE
Spring cloud binder example with functional approach. 

### ISSUE THREAD

**Issue by bilak** [MicrosoftDocs/azure-dev-docs#284]
Hello,
following [documentation](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus) uses approach with [@StreamListener](https://github.com/spring-cloud/spring-cloud-stream/blob/master/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/annotation/StreamListener.java). But as noted in source of `StrealmListener` it will be deprecated in future releases. 
```
NOTE: It is no longer recommended to use StreamListener in favor of functional programming model.
It will be deprecated and subsequently removed in the future
```

So can we have example with functional model? 
How can we handle messages that must contain some header.

Also it would be nice if you can provide also some examples how to do integration tests without using real service bus (in case when we don't have internet connection for example)

Thanks

**Comment by KarlErickson** [comment]
@seanli1988 can you comment? Thanks.

**Comment by seanli1988** [comment]
I've added this request to our service bus backlog. We'll address it in the month of December.

**Comment by han-gao** [comment]
Hi, @bilak The document has now been updated. About uses approach with `@StreamListener`, [Spring Cloud Azure Stream Binder for Service Bus queue Code Sample](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-cloud-sample-servicebus-queue-binder) and [Spring Cloud Azure Stream Binder for Service Bus topic Code Sample](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-cloud-stream-binder-servicebus-topic) there is `@StreamListener` tutorial in the above samples.

**Comment by bilak** [comment]
@han-gao I was asking about examples **without** `@StreamListener` 
@seanli1988 any updates on this topic?

**Comment by saragluna** [comment]
@bilak I've replied in the other thread. Sorry for the delay and we'll work on this.

**Comment by saragluna** [comment]
@wujack778 we should also create a PR to change this doc https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus

**Comment by wujack778** [comment]
> @wujack778 we should also create a PR to change this doc https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus

get

**Comment by KarlErickson** [comment]
Content updated.
