### ISSUE TITLE
Doesn't support Servicebus with session enabled

### ISSUE THREAD

**Issue by saurabhgangwar** [MicrosoftDocs/azure-dev-docs#285]
It doesn't support Servicebus with session enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbecafd0-c6db-9cb0-c5a4-328946446ec6
* Version Independent ID: 40cea238-c2de-fd1d-fef7-c1a850b54158
* Content: [How to use the Spring Boot Starter for Azure Service Bus JMS](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md)
* Service: **azure-java**
* GitHub Login: @seanli1988
* Microsoft Alias: **seal**

**Comment by KarlErickson** [comment]
@seanli1988 can you comment? Thanks.

**Comment by seanli1988** [comment]
@saurabhgangwar can you elaborate on how you are planning to use session in servicebus with Spring? code snippet will do.

**Comment by saurabhgangwar** [comment]
Sorry for responding late. Actually, since this JMS starter kit wasn't useful for writing/reading to the Session Enabled Service Bus Queues so we had to update our implementation by using the service bus API in place of this starter kit. So there is not much information left with me but I am trying to put a summary of the issues we were facing.

1. @JmsTemplate wasn't able to write messages to the session enabled queue by default as there is no easy way to set up "SessionId" for the message. With some research we figured out that we had to set up a string property "JMSXGroupId" with the message that results in the session id, but strangely this is not documented.

2. @JmsTemplate doesn't support scheduling for delayed processing of the message. Please refer: https://stackoverflow.com/questions/45631740/how-to-send-scheduled-message-to-azure-service-bus-with-jms
Even the solution proposed in the answer doesn't work with the latest JMSTextMessage class. 

3. Message Reciever doesn't work with the session enabled queue. Someone already reported it to you here: https://github.com/Azure/azure-service-bus/issues/326
but I see the ticket is closed but the last comment says that it did not work with JAVA. Please fix it for the future pickers of this started kit, if someone cares.

Thanks.


CC: @KarlErickson

**Comment by seanli1988** [comment]
Thank you for your feedback @saurabhgangwar . I've backlogged these feature requests in our enhancements for the service bus starter.

**Comment by KarlErickson** [comment]
Thanks @saurabhgangwar and @seanli1988 - closing this issue.
