### ISSUE TITLE
Deprecated Syntax

### ISSUE THREAD

**Issue by afflom** [MicrosoftDocs/azure-dev-docs#286]
Love the tutorial, but there are a few deprecated items in the Terraform configs:
```
Plan: 50 to add, 0 to change, 0 to destroy.

Warning: "location": [DEPRECATED] location is no longer used

  on hub-nva.tf line 70, in resource "azurerm_virtual_machine_extension" "enable-routes":
  70: resource "azurerm_virtual_machine_extension" "enable-routes" {



Warning: "resource_group_name": [DEPRECATED] This field has been deprecated and is no longer used - will be removed in 2.0 of the Azure Provider

  on hub-nva.tf line 70, in resource "azurerm_virtual_machine_extension" "enable-routes":
  70: resource "azurerm_virtual_machine_extension" "enable-routes" {



Warning: "virtual_machine_name": [DEPRECATED] This field has been deprecated in favor of `virtual_machine_id` - will be removed in 2.0 of the Azure Provider

  on hub-nva.tf line 70, in resource "azurerm_virtual_machine_extension" "enable-routes":
  70: resource "azurerm_virtual_machine_extension" "enable-routes" {
```
Good job guys. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e973d5-b117-99c6-f0a0-c7d779ea3ea0
* Version Independent ID: d4d46d49-d837-6d99-2f50-5578f67b1e89
* Content: [Tutorial - Validate a hub and spoke network in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-validation)
* Content Source: [articles/terraform/hub-spoke-validation.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/hub-spoke-validation.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@afflom Thank you for the feedback. I went through the code and I believe I've fixed all the warnings and errors to bring the example current. Please let me know if you see any further issues.
