### ISSUE TITLE
Kubernetes dashboard now deprecated in AKS

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#287]
Kubernetes dashboard is now deprecated in AKS

It is replaced by [https://azure.microsoft.com/en-us/updates/kubernetes-resource-view-is-in-public-preview](https://azure.microsoft.com/en-us/updates/kubernetes-resource-view-is-in-public-preview) 

Could you please update the doc accordingly ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200ae7a0-87fe-9d4d-db79-12495746fbd8
* Version Independent ID: 0aaa8a60-4aec-ac05-a9bc-7d9a4883c637
* Content: [Deploy Spring Boot Application to the Azure Kubernetes Service - Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@ezYakaEagle442 thanks for the feedback! We'll look into this and update the topic.

**Comment by saragluna** [comment]
I will take a look at this.

**Comment by saragluna** [comment]
@KarlErickson could you please also add me as assginee?

**Comment by saragluna** [comment]
https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1857, @KarlErickson and @ezYakaEagle442 please help review this PR.
