### ISSUE TITLE
Why is LIST permission required?

### ISSUE THREAD

**Issue by jschrap** [MicrosoftDocs/azure-dev-docs#29]
The best practise is to set the access permissions to least privilege.
This means that GET should be sufficient. 
Yet the (springboot) app fails if it doesn't have LIST.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70f3e5d-76c3-41c5-8b38-1497c9b7a96d
* Version Independent ID: 03a0848b-acc4-6638-e2cf-8cba08111ce7
* Content: [How to use the Spring Boot Starter for Azure Key Vault](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#feedback)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@yucwan can you provide some input here?
@bmitchell287 for awareness.

**Comment by jschrap** [comment]
I believe the latest Springboot version fixes this.

**Comment by edburns** [comment]
Fixed in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1005 .
