### ISSUE TITLE
Deprecated FlexVolume suggestion

### ISSUE THREAD

**Issue by jhyot** [MicrosoftDocs/azure-dev-docs#290]
The page suggests to use FlexVolume for Key Vault access, but the given link https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/README.md says that FlexVolume is deprecated in favor of another solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3830ec12-c308-1d59-07c8-be295d8db7a3
* Version Independent ID: b4439660-4af0-12eb-408b-ec9a181ec505
* Content: [Migrate Spring Boot applications to run on Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-kubernetes-service)
* Content Source: [articles/java/migration/migrate-spring-boot-to-azure-kubernetes-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/migration/migrate-spring-boot-to-azure-kubernetes-service.md)
* Service: **azure-java**
* GitHub Login: @mriem
* Microsoft Alias: **manriem**

**Comment by KarlErickson** [comment]
@jhyot thanks for the feedback!
@mnriem can you comment?

**Comment by mnriem** [comment]
@KarlErickson That is correct. It should be changed to refer to the solution mentioned at https://github.com/Azure/secrets-store-csi-driver-provider-azure
