### ISSUE TITLE
Not useful

### ISSUE THREAD

**Issue by saurabhgangwar** [MicrosoftDocs/azure-dev-docs#291]
This starter kit serves no purpose in practical situations. You can not do basic things like reading from session enabled queue, setting up ScheduledEnqueueTimeUtc. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbecafd0-c6db-9cb0-c5a4-328946446ec6
* Version Independent ID: 40cea238-c2de-fd1d-fef7-c1a850b54158
* Content: [How to use the Spring Boot Starter for Azure Service Bus JMS](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md)
* Service: **azure-java**
* GitHub Login: @seanli1988
* Microsoft Alias: **seal**

**Comment by KarlErickson** [comment]
@saurabhgangwar Thank you for the feedback! I'm sorry the content isn't useful for you.
@seanli1988 can you comment? Thanks.

**Comment by seanli1988** [comment]
this is a duplicate issue as https://github.com/MicrosoftDocs/azure-dev-docs/issues/285#issuecomment-692989732
please close it out
