### ISSUE TITLE
The example shall use real city name instead of same as the variable name.

### ISSUE THREAD

**Issue by jayarajjg** [MicrosoftDocs/azure-dev-docs#293]
[Enter feedback here]

In the below example code, it would be easy to understand and intuitive if an actual city like "Seattle" is used instead of "city". When the new PartitionKey("city") is passed to findById method, it gives an impression that PartitionKey object should be constructed for the domain object field "city" that is annotated with "@PartitionKey".

    final Address newAddress = new Address("12345", "city");

    // There's no need to specify a partition key in the save operation.
    repository.save(updatedAddress);

    // Provide a partition key when performing a find-by-id operation.
    final Optional<Address> addressById = repository.findById("12345", new PartitionKey("city"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a03983-f9b2-360a-68d4-3f8a5f7b6923
* Version Independent ID: 3463f85f-dd80-85bb-4dbd-cba82fc5c4ef
* Content: [Spring Data Azure Cosmos DB developer's guide](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb?source=docs)
* Content Source: [articles/java/spring-framework/how-to-guides-spring-data-cosmosdb.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/how-to-guides-spring-data-cosmosdb.md)
* Service: **azure-java**
* GitHub Login: @kushagraThapar
* Microsoft Alias: **kuthapar**

**Comment by KarlErickson** [comment]
@jayarajjg thanks for the feedback! That's a good point - I'll update the topic.
