### ISSUE TITLE
ruby sdk documentation

### ISSUE THREAD

**Issue by tbugfinder** [MicrosoftDocs/azure-dev-docs#294]
Hi,

compared to the Azure Python Documentation the Ruby Documentation is non-existent.
Could more ruby-sdk documentation be added on top of the limited info in ruby-sdk repo?

Thanks

**Comment by KarlErickson** [comment]
@tbugfinder thanks for the feedback! @DavidCBerry13 can you comment?

**Comment by DavidCBerry13** [comment]
As of February 2021, the Azure Ruby SDK has entered retirement, so we are no longer updating this documentation.  You can see the official announcement in the Azure SDK for Ruby GitHub repo --> https://github.com/Azure/azure-sdk-for-ruby/blob/master/SUPPORT.md

**Comment by DavidCBerry13** [comment]
#please-close
