### ISSUE TITLE
Missing docs on how to deploy Java Spring Boot app on Windows using jar files

### ISSUE THREAD

**Issue by allantargino** [MicrosoftDocs/azure-dev-docs#30]
Hi there,

So far we only have examples on how to deploy a Spring Boot JAR files on Linux.

This scenario works perfectly fine on Windows with our current Maven plugin, as long after the deploy someone uses the following container configuration:

![image](https://user-images.githubusercontent.com/13934447/69971913-6744ce80-14ff-11ea-8d69-4d8a810e3184.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 69c11e55-5a5e-584d-5c4b-71cea89d34da
* Content: [Deploy a Spring Boot JAR file Web App to Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin)
* Content Source: [java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
Topic has been updated.

**Comment by allantargino** [comment]
Thank you very much, @KarlErickson !
