### ISSUE TITLE
typo in the last code snippet, should be Authorizer and not Authoize

### ISSUE THREAD

**Issue by elraikhm** [MicrosoftDocs/azure-dev-docs#301]
[Enter feedback here]
typo in the last code snippet, should be Authorizer and not Authoize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496addbb-39f0-09cd-4fc9-c5786bb90495
* Version Independent ID: 53cd2418-bd7b-b469-8d34-f9f2f7fd1b8f
* Content: [Authentication with the Azure SDK for Go](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization)
* Content Source: [articles/go/azure-sdk-authorization.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/go/azure-sdk-authorization.md)
* Service: **azure**
* GitHub Login: @barbkess
* Microsoft Alias: **barbkess**

**Comment by KarlErickson** [comment]
@elraikhm thanks for the feedback! We'll get that fixed.
