### ISSUE TITLE
AADSTS50011 Error - redirect uri mismatch when deployed to App Service

### ISSUE THREAD

**Issue by arshadazeem** [MicrosoftDocs/azure-dev-docs#303]
When [Spring Boot Starter for Azure AD](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory) is deployed to Azure App Service the redirect uri scheme is getting changed from https to http resulting in `AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application`

Here are steps to reproduce it
1. Deploy Spring Boot Starter for Azure AD to Azure App Service (tried with mvn webapp plugin, `<runtime><os>linux</os><javaVersion>jre8</javaVersion><webContainer>jre8</webContainer></runtime>`)
2. Register an app in Azure AD with Redirect URI: [](https://<appservice>.azurewebsites.net/login/oauth2/code/azure)
3. When the app service is accessed, we get the “AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application” error

Similar issue for .Net has been documented here: https://github.com/AzureAD/microsoft-identity-web/issues/115

**Comment by KarlErickson** [comment]
Hi @arshadazeem - thanks for the input! This Issues list is for documentation. Could you reopen the issue at https://github.com/Azure/azure-sdk-for-java/issues ? Thanks!
