### ISSUE TITLE
disks.create_or_update() in newest Azure python SDK got renamed to disks.begin_create_or_update()

### ISSUE THREAD

**Issue by NillsF** [MicrosoftDocs/azure-dev-docs#308]
Code examples for creating or updating disks in Python not up to date anymore.

disks.create_or_update() in newest Azure python SDK got renamed to disks.begin_create_or_update(). The page should be reviewed in depth to make sure everything still works.

Needs to be updated in multiple documents (I'll open another issue for another document where I found the issue)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e955711-fac5-bfc2-c9d2-f62244c0c257
* Version Independent ID: cb1535f7-4517-7afc-1f2b-954c8003f47d
* Content: [Managed Disks](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-samples-managed-disks)
* Content Source: [articles/python/azure-sdk-samples-managed-disks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-samples-managed-disks.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for the quick report! I just received word yesterday that the libraries had been updated, so it's on my list to make the appropriate changes in the examples. Do please file issues for any bit that needs updating--it really helps.

And if you feel to create a PR to this repo with the necessary edits, we're happy to receive the contributions and will get them merged in short order.

**Comment by NillsF** [comment]
I'll open a PR for this one, but wanted to make sure to open this issue since there might be a bigger changes in the SDK that I didn't pick up on.

**Comment by kraigb** [comment]
Besides various method name changes, the updated libraries are now based on azure.core and therefore use the newer authentication methods, such as DefaultAzureCredential. But that change affects only the client object creation step, which is something we cover in the authentication article (that I'll be updating).

I've merged the PR--thanks so much!

**Comment by nickzhums** [comment]
> Besides various method name changes, the updated libraries are now based on azure.core and therefore use the newer authentication methods, such as DefaultAzureCredential. But that change affects only the client object creation step, which is something we cover in the authentication article (that I'll be updating).
> 
> I've merged the PR--thanks so much!

thanks for explaining the situation Kraig :)
