### ISSUE TITLE
Sample/Instructions for Spring REST APIs with AAD Spring Boot Starter

### ISSUE THREAD

**Issue by allantargino** [MicrosoftDocs/azure-dev-docs#31]
Hi there,

Currently we don't have enough docs on how to use AAD Spring Boot Starter with REST APIs - only web applications.

@cljung did an awesome job creating the following blog post:
* http://www.redbaronofazure.com/?p=7607
And also documenting his finds at:
* https://github.com/cljung/java-rest-api

I believe we could incorporate his findings in the official Microsoft docs (if @cljung agrees, of couse)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf5423d-6c4c-26a8-89bb-7686794716d0
* Version Independent ID: 998d0369-045c-d32c-d07e-ff7d4352e878
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@allantargino thanks for the input! We'll take this suggestion into consideration in our planning.

**Comment by seanli1988** [comment]
thank you for your feedback and I've noted it down in our backlog. we are lacking reference guides for most of our Spring modules and we will improve it over time.

**Comment by allantargino** [comment]
Thank you folks!

**Comment by KarlErickson** [comment]
Closing this issue since we're tracking this in our internal backlog.
