### ISSUE TITLE
Expects virtual network and subnets (appgwsubnet, kubesubnet) to exist. If created previously, then expects the resources to be imported on Terraform.

### ISSUE THREAD

**Issue by san-biqmind** [MicrosoftDocs/azure-dev-docs#310]
**If virtual network and subnets do not exist, the following error is thrown:**

Error: Error: Subnet "kubesubnet" (Virtual Network "aksVirtualNetwork" / Resource Group "aks-test2-cluster-test-terraform") was not found

  on main.tf line 52, in data "azurerm_subnet" "kubesubnet":
  52: data "azurerm_subnet" "kubesubnet" {

Error: Error: Subnet "appgwsubnet" (Virtual Network "aksVirtualNetwork" / Resource Group "aks-test2-cluster-test-terraform") was not found

  on main.tf line 58, in data "azurerm_subnet" "appgwsubnet":
  58: data "azurerm_subnet" "appgwsubnet" {

**If the resource is created**

Error: A resource with the ID "/subscriptions/a9813cfb-3a3c-472e-b5c8-8407842c6f14/resourceGroups/ContourBiqmindTesting/providers/Microsoft.Network/virtualNetworks/aksVirtualNetwork" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_network" for more information.

  on resources.tf line 30, in resource "azurerm_virtual_network" "test":
  30: resource "azurerm_virtual_network" "test" {

Error: A resource with the ID "/subscriptions/a9813cfb-3a3c-472e-b5c8-8407842c6f14/resourceGroups/ContourBiqmindTesting/providers/Microsoft.Network/publicIPAddresses/publicIp1" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_public_ip" for more information.

  on resources.tf line 62, in resource "azurerm_public_ip" "test":
  62: resource "azurerm_public_ip" "test" {

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@san-biqmind Thanks for your feedback. I sincerely apologize it took so long to get to this, but the article had to be completely rewritten. I've done that and tested the demo successfully. The article should go live Monday.
