### ISSUE TITLE
Deployed app unable to install module psycopg2 and whitenoise

### ISSUE THREAD

**Issue by v-shsid** [MicrosoftDocs/azure-dev-docs#311]
While following the tutorial, we got stuck at the part "Run Django database migrations" because the web app container was failing to start up. When checking the deployment log, in oryx build, I found

![image](https://user-images.githubusercontent.com/55831238/94533698-16624b80-0272-11eb-9411-87f789471038.png)

Next, I added module 'psycopg2-binary' in requirements.text and got another build error
![image](https://user-images.githubusercontent.com/55831238/94533856-4d386180-0272-11eb-84ea-574257d03a50.png)

After adding this two in requirements.text, the web app finally was able to start up. Then I was able to connect to SSH and complete the tutorial without any issue.

Also, when I just added psycopg2, it was downloading the module source code and trying to build with gcc, which led to another error as gcc is not included by default. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d873da-7721-07bf-9584-78d1b5788167
* Version Independent ID: 81490eea-63aa-d729-c9fb-6753961e39cc
* Content: [Tutorial: Deploy a Django app with PostgreSQL using the Azure portal](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-python-postgresql-app-portal)
* Content Source: [articles/python/tutorial-python-postgresql-app-portal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-python-postgresql-app-portal.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@v-shsid Thanks. There have been multiple issues with requirements.txt for Django apps in the container that are being investigated. Stay tuned.

**Comment by kraigb** [comment]
Closing as the current sample's requirements.txt that contains psycopg2-binary and whitenoise works as expected. In the meantime, https://github.com/Azure-Samples/djangoapp/issues/3 is tracking the issue of having psycopg2-binary in requirements.txt at all, as it shouldn't be necessary (but currently is because the container for App Service lacks gcc to build the wheel).

**Comment by hurricaneMitch** [comment]
> 
> 
> Closing as the current sample's requirements.txt that contains psycopg2-binary and whitenoise works as expected. In the meantime, [Azure-Samples/djangoapp#3](https://github.com/Azure-Samples/djangoapp/issues/3) is tracking the issue of having psycopg2-binary in requirements.txt at all, as it shouldn't be necessary (but currently is because the container for App Service lacks gcc to build the wheel).

Any update on removing the requirement of having a binary requirement?

**Comment by kraigb** [comment]
No, there hasn't been any progress on having gcc installed in the App Service container where the app is deployed, which is what's necessary to build the non-binary psycopg2. Hopefully we can get some traction on it once the App Service engineering team is done with other build/environment issues that currently have higher priority.
