### ISSUE TITLE
Add that Authorization header is redacted by default when using DEBUG level logging

### ISSUE THREAD

**Issue by kristapratico** [MicrosoftDocs/azure-dev-docs#312]
Can we add this detail about the Authorization header being redacted in the table that shows the logging levels under this [section](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-logging#set-logging-levels)?

I'm thinking something like this:

> logging.DEBUG | Detailed information that is commonly used for troubleshooting. Debug is the only logging level that includes sensitive information such as account keys in headers; **however, the Authorization header will be redacted by default.** Debug output typically includes a stack trace for exceptions. The debug level automatically enables the info, warning, and error levels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc90337e-c8fd-23fb-b5e6-e20db3538497
* Version Independent ID: 288a4523-e630-9683-5ce4-34dbc6cd7812
* Content: [Configure logging in the Azure libraries for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-logging)
* Content Source: [articles/python/azure-sdk-logging.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-logging.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kristapratico** [comment]
Closing as we are questioning if this is the right behavior. Will re-open if necessary.

**Comment by kraigb** [comment]
OK. Note that if you're MSFT internal, you should use the azure-dev-docs-pr repo instead of the public repo here. You can also make a PR directly for the edit if/when you need it.

**Comment by kristapratico** [comment]
I didn't know that, thanks! :)
