### ISSUE TITLE
Need More Code Sample for Simple Backend Web to Send Push Notifications for Xamarin Apps

### ISSUE THREAD

**Issue by techmanDAV** [MicrosoftDocs/azure-dev-docs#317]
Iread through the article and was able to follow some parts of it.  I am new developing Mobile aoos with xamarin.  However, I wasable to setup the Firebase, Apple developer, APN certs, etc.  I am also able to send test messages.  The probleis tha tI had a difficult time following the instructions on how to build a simple web backend to send notifications.  Can you direct me to ducumentation that is more straightforward.  I would greatly appreciate it.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by mikeparker104** [comment]
Hi @techmanDAV. Were there specific aspects that you found difficult to follow? Would some additional information or hints have helped? The [ASP.NET docs](https://dotnet.microsoft.com/apps/aspnet) has a getting started [tutorial](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio) covering the basics of building a web API with ASP.NET Core.

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
