### ISSUE TITLE
Add node_modules to .gitignore

### ISSUE THREAD

**Issue by jpcarrascal** [MicrosoftDocs/azure-dev-docs#318]
The node_modules directory should not be commited to the repo. It caused this error to me when trying to add files before commiting:

_open("node_modules/.bin/acorn"): Invalid argument_

(Using windows VSCode and WSL)

I fixed by first creating .gitignore and then adding node_modules to it, as suggested here: https://stackoverflow.com/questions/47815353/unable-to-push-to-git-repo-node-package-open-error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c647713-734d-b449-8fc0-fdd5c39d1649
* Version Independent ID: 72826a8a-934a-e7a0-8e6a-c8a82fd4f8e3
* Content: [Deploy apps to Azure App Service from Visual Studio Code](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial-vscode-azure-app-service-node-03)
* Content Source: [articles/javascript/tutorial-vscode-azure-app-service-node-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial-vscode-azure-app-service-node-03.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@jpcarrascal Thanks for reporting this. Looks like the express generator command is incorrect. #in-progress

**Comment by diberry** [comment]
The correct command to create the express app, which also creates the .gitignore file correctly and deploys correctly is:

```console
npx express-generator expressApp1 -–git --view pug
```

where the git switch is before the view switch. This should be published today. I'm closing this issue, if you find you still have a problem, please reopen this. #please-close
