### ISSUE TITLE
link to azure_rm.py should be updated in the documentation

### ISSUE THREAD

**Issue by ceesios** [MicrosoftDocs/azure-dev-docs#319]
The inventory plugin has been moved to the azure collection:
https://raw.githubusercontent.com/ansible-collections/azure/dev/plugins/inventory/azure_rm.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059a1972-09ee-02a7-8159-07ba04a2c763
* Version Independent ID: 4323aa16-062c-1b11-fb73-11777c34f88e
* Content: [Tutorial - Configure dynamic inventories of your Azure resources using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure?tabs=ansible)
* Content Source: [articles/ansible/dynamic-inventory-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/dynamic-inventory-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ceesios Thanks for the link. The article has been updated and should publish shortly.
