### ISSUE TITLE
  path pointing incorrectly

### ISSUE THREAD

**Issue by paromitaroy** [MicrosoftDocs/azure-dev-docs#320]
The path included in the yaml file (https://github.com/Azure/terraform/blob/master/samples/integration-testing/src/azure-pipeline.yaml) is not right. It points to 'examples/basic-testing/src/checkov.sh' which does not exist in the repo, it should be 'samples/integration-testing/src/*

![image](https://user-images.githubusercontent.com/55242088/95217329-f808cc80-07ea-11eb-9290-e4f5c3f047a5.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1572ea-d197-2543-b3ea-07b5bf7e8483
* Version Independent ID: 6651e0a0-be7d-6a50-43ff-83760f9fa380
* Content: [Tutorial - Integration testing with Terraform and Azure](https://docs.microsoft.com/en-us/azure/developer/terraform/best-practices-integration-testing)
* Content Source: [articles/terraform/best-practices-integration-testing.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/best-practices-integration-testing.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@paromitaroy Thanks for the feedback. I've alerted the dev to update this file. It should be fixed and live tomorrow (PST).

**Comment by jcorioland** [comment]
@paromitaroy thanks for reporting this issue. I've just merged a PR that fixes the issue in the [sample repository YAML pipeline file](https://github.com/Azure/terraform/blob/master/samples/integration-testing/src/azure-pipeline.yaml). You should be able to sync your fork and move forward.
cc @TomArcherMsft
