### ISSUE TITLE
Variable descriptions wrong

### ISSUE THREAD

**Issue by svendhoest** [MicrosoftDocs/azure-dev-docs#321]
I see you use the description "Containers DNS server IP address." for variables 4 times.

It's only right in one of the places.

It would be helpful if you describe the use of different networks, e.g. subnet for kubernetes,  subnet for application gateway backend etc.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@svendhoest Thanks for the note. This looks like a copy/paste error. I'll correct today and update this issue when it's done.

**Comment by TomArcherMsft** [comment]
@svendhoest This article has been updated and will publish either this weekend or Monday.
