### ISSUE TITLE
Link to create a compute client doesn't actually show compute client creation

### ISSUE THREAD

**Issue by josegonzalez** [MicrosoftDocs/azure-dev-docs#322]
The doc page it links to (currently [this](https://docs.microsoft.com/en-us/python/api/overview/azure/virtualmachines?view=azure-python)) shows direct usage of `compute_client`, and doesn't show anything about how that was constructed or what needs to be imported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e955711-fac5-bfc2-c9d2-f62244c0c257
* Version Independent ID: cb1535f7-4517-7afc-1f2b-954c8003f47d
* Content: [Managed Disks](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-samples-managed-disks)
* Content Source: [articles/python/azure-sdk-samples-managed-disks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-samples-managed-disks.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for pointing that out (within this older article that's kept around for legacy purposes). I'll update the link to https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-virtual-machines?tabs=cmd, which is the current example on provisioning a virtual machine with the azure-mgmt-compute library.
