### ISSUE TITLE
AttributeError: 'SnapshotsOperations' object has no attribute 'create_or_update'

### ISSUE THREAD

**Issue by josegonzalez** [MicrosoftDocs/azure-dev-docs#323]
When I try the example at "Create a snapshot of a Managed Disk that is currently attached to a virtual machine", I get the following stacktrace:

```
Traceback (most recent call last):
  File "app.py", line 78, in <module>
    main()
  File "app.py", line 73, in main
    snapshot_disk(resource_group, credential, subscription_id)
  File "app.py", line 44, in snapshot_disk
    async_snapshot_creation = compute_client.snapshots.create_or_update(
AttributeError: 'SnapshotsOperations' object has no attribute 'create_or_update'
```

The code is more or less what is shown on the page, except with variables in place of hardcoded strings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e955711-fac5-bfc2-c9d2-f62244c0c257
* Version Independent ID: cb1535f7-4517-7afc-1f2b-954c8003f47d
* Content: [Managed Disks](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-samples-managed-disks)
* Content Source: [articles/python/azure-sdk-samples-managed-disks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-samples-managed-disks.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
The azure-mgmt-compute library was updated not long ago, and we haven't updated this particular example page yet (which isn't even linked from the TOC, hence it being a bit low on the priority stack). Use begin_create_or_update as you'd see in the current ref docs for that library: https://docs.microsoft.com/en-us/python/api/azure-mgmt-compute/azure.mgmt.compute.v2020_06_30.operations.snapshotsoperations?view=azure-python#methods.

**Comment by kraigb** [comment]
Closed via https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1139
