### ISSUE TITLE
azurerm_virtual_machine_extension syntax changed

### ISSUE THREAD

**Issue by stephaneclavel** [MicrosoftDocs/azure-dev-docs#324]
The arguments used for azurerm_virtual_machine_extension seem to have changed. 

Please refer to https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html

Thanks for the tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b701b1c8-1b00-f16d-36eb-781c3ce062e8
* Version Independent ID: 9c43b7f0-2d05-c946-7ffe-c3599b99958e
* Content: [Tutorial - Create a hub virtual network appliance in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-hub-nva)
* Content Source: [articles/terraform/hub-spoke-hub-nva.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/hub-spoke-hub-nva.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
This appears to have been addressed. Please let me know if this is still a problem, and I'll have the author take a look.
