### ISSUE TITLE
no ip forwarding required

### ISSUE THREAD

**Issue by stephaneclavel** [MicrosoftDocs/azure-dev-docs#325]
Hello

In resource azurerm_network_interface "onprem-nic"
parameter enable_ip_forwarding = true is not required.

No traffic transits via this vm. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d38e7ab9-9595-9f39-d29e-7e9e267d7ef5
* Version Independent ID: ef16a6a7-e224-fc25-e6f8-af6777f588d5
* Content: [Tutorial - Create on-premises virtual network in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-on-prem)
* Content Source: [articles/terraform/hub-spoke-on-prem.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/hub-spoke-on-prem.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@stephaneclavel Thanks for the feedback. I'm looking into this now.

**Comment by TomArcherMsft** [comment]
@stephaneclavel I've asked the dev who wrote that series to look into it. When he gets back to me, I'll update the article accordingly.
