### ISSUE TITLE
Secure pages for a Group which has children in which the user is

### ISSUE THREAD

**Issue by einue** [MicrosoftDocs/azure-dev-docs#329]
I have following issue:

I secure my View by @Secured("ROLE_parent") .
Now, the user is not directly in group parent but in it's child-group named "child".
The Application does not resolve nested groups. Hence, I have no access to the view ....

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@einue thanks for the feedback - we'll look into this.
@lu-cheng @moarychan @yiliuTo can you provide any input on this? Thanks.

**Comment by backwind1233** [comment]
@einue  our starter doesn't support the feature now, and we will do a feature release to support this.

**Comment by KarlErickson** [comment]
@backwind1233 thanks for the info. Closing the issue.

**Comment by einue** [comment]
@backwind1233  do you have a timeline for this new feature for me?

**Comment by backwind1233** [comment]
@einue  we will do a feature release to support this as soon as possible.

**Comment by moarychan** [comment]
Hi @einue ,  is it necessary to consider a scenario where only users in the current group need to be authorized to access?  the current approach is like this; the other is to allow the current user's belonging group and its transitive groups, which contains the parent group to be authorized, this is the scenario you want.

Therefore, we plan to add an optional configuration item to enable these situations respectively.

**Comment by einue** [comment]
@moarychan : 
Are you're changes in the master branch right now?

Which version do I need for using the new feature?

I tried:

        ```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-active-directory-spring-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>
```

If I do so, the property 
      azure.activedirectory.user-group.group-relationship: transitive
      
is unknown.
