### ISSUE TITLE
Azure function returns response in text format

### ISSUE THREAD

**Issue by swagulkarni** [MicrosoftDocs/azure-dev-docs#33]
While trying this code, the response returned is in the form of type application/text. 
How do we default it to application/json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 898b3dea-b80d-e3b2-7c37-ec68ce7db31a
* Version Independent ID: d960aed3-1ab4-3c8b-7abd-ccb58fbc5fd1
* Content: [Getting started with Spring Cloud Function in Azure](https://docs.microsoft.com/en-us/azure/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @JuDubois
* Microsoft Alias: **judubois**

**Comment by swagulkarni** [comment]
@KarlErickson - Kindly  update on this ticket.

**Comment by oliverlayug** [comment]
return request.createResponseBuilder(HttpStatus.OK).body(handleRequest(request.getBody().get(), context)).header("Content-Type", "application/json").build();

I wonder if there is an easier way.

**Comment by KarlErickson** [comment]
@yucwan can you provide some input here?
@bmitchell287 for awareness.

**Comment by KarlErickson** [comment]
@jdubois can you comment here? Please also update the topic if necessary. Thanks!

**Comment by jdubois** [comment]
This complicates the code quite a bit, but is indeed more correct.
I've fixed this in the default sample, see PR https://github.com/Azure-Samples/hello-spring-function-azure/pull/13 and PR https://github.com/Azure-Samples/hello-spring-function-azure/pull/12

I'm going to add a PR to fix it in this docs too

**Comment by jdubois** [comment]
PR done in the docs at https://github.com/MicrosoftDocs/azure-dev-docs/pull/151
