### ISSUE TITLE
Where do you save the file create_rg.yml

### ISSUE THREAD

**Issue by srazasyed** [MicrosoftDocs/azure-dev-docs#330]
Where do you save the file `create_rg.yml` before running the following command in Azure Cloud Shell?

`ansible-playbook create_rg.yml --extra-vars "name=<resource_group_name> location=<resource_group_location>"`

**NOTE**: When I save create_rg.yml file in my local folder as `C:\MyFolder\create_rg.yml` the above command gives the following error:

>**ERROR**! the playbook: C:\MyFolder\create_rg.yml could not be found

**Comment by TomArcherMsft** [comment]
@srazasyed You mention using Azure Cloud Shell, but then refer to what looks like a Windows location. If you're using the Azure Cloud Shell to run the commands, then you need to save the playbook within Cloud Shell. Could you explain your environment more in terms of where you're storing the file and where you're running the command?

**Comment by TomArcherMsft** [comment]
@srazasyed I'm going to close this issue, but if you reply, I'm happy to help you further.

**Comment by srazasyed** [comment]
@TomArcherMsft I'm new to `ansible`. Could you please point out where in `cloud shell` should I save the `.yaml` file to run the ansible playbook?

**Comment by TomArcherMsft** [comment]
@srazasyed 

I intentionally don't include the exact file location as that depends on each person's individual environment. 

However, if your new to Ansible/Azure and simply testing, I would do the following:

(I specify a directory name of `ansible-test`. That name can be whatever valid unique name you want.)

1. Open Cloud Shell (Azure CLI)
1. cd clouddrive
1. mkdir ansible-test 
1. cd ansible-test
1. code create_rg.yml
1. paste code from article
1. <Ctrl>S
1. <Ctrl>Q

You can then view the file via `cat create_rg.yml`
