### ISSUE TITLE
Create New Function Project Doesn't Give The Option To Select Python

### ISSUE THREAD

**Issue by dgpoulet** [MicrosoftDocs/azure-dev-docs#335]
I have VS Code configured for Azure, and to run Python and Java and others. I have the Azure extension logged in and the current environment is set for Python 3.8. 

I'm following the instructions here but when I select "New Project" from the Azure Functions extension, then select a working folder, the only languages I'm offered are Java 8 and 11. There's no option to select Python.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e66276c-7132-a15b-04c7-97bac2135f1d
* Version Independent ID: 6357c307-34af-166b-9b6d-9c5a4cecdb5d
* Content: [Step 2: Create a Python function for Azure Functions with VS Code](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-02)
* Content Source: [articles/python/tutorial-vs-code-serverless-python-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-vs-code-serverless-python-02.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@dgpoulet Can you run "func --version" from the command line and tell me the version number? Also try "func init temp_project" and tell me what languages are presented. I'm surprised that the Azure extension offers only Java, because it should offer other languages besides Python, like JavaScript and TypeScript.

Can you also check versions of the Azure extension (which should be 1.0.0)?

Generally speaking, the Azure extension doesn't depend on language extensions being installed, so I'm thinking it has something to do with either the Azure Functions Core Tools (func) or the Azure extension.

**Comment by dgpoulet** [comment]
func --version is 3.0.2630
Azure Functions extension is 1.0.0

If I run `func init <myFunction>` from the command line it works fine, and I can choose Python and create / deploy to Azure from the command line. 

But VS Code is still a problem. I uninstalled and reinstalled VS Code, installed the Azure extension bundle and the Python extension (and not the Java) but still when I click on "Create New Project" from the Az Functions extension, after I select a folder it goes straight to asking me to select the Java runtime.
![image](https://user-images.githubusercontent.com/32765839/97470152-1de34600-193f-11eb-8df7-53e105558d04.png)

**Comment by kraigb** [comment]
Hmmm...this would appear to be an issue with the extension, not with VS Code or Python, in which case, please file an issue at https://github.com/microsoft/vscode-azurefunctions/issues and close this present one. There's really not anything to change in the documentation, which is the concern of this present issue and repo. Thanks.

**Comment by dgpoulet** [comment]
Okay no problem. Thanks for the quick response.

**Comment by kraigb** [comment]
Sure thing...thanks also for filing the issue, as we always appreciate the feedback, especially where something isn't behaving as expected.
