### ISSUE TITLE
Need Java SDK code to call Azure Storage Blob APIs with support of proxy for CloudBlobClient

### ISSUE THREAD

**Issue by kailasandhale** [MicrosoftDocs/azure-dev-docs#336]
I can see proxy usage examples for Azure storage blob at https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-configure-proxy?tabs=cmd, but it seems they are missing for Java. We specifically need this for CloudBlobClient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7138560-c493-1754-b362-ed297a6275e8
* Version Independent ID: 5868f46b-8d53-eb58-7305-c40e352dbce7
* Content: [Configuring proxies when using Azure libraries](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-configure-proxy?tabs=cmd)
* Content Source: [articles/python/azure-sdk-configure-proxy.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-configure-proxy.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@kailasandhale The page you refer to is specifically oriented for Python, so I'm assigning to one of our content devs who handles Java.

@KarlErickson Assigning over to you for triage.

**Comment by KarlErickson** [comment]
@kailasandhale thanks for the feedback! We'll look into that.

**Comment by KarlErickson** [comment]
Java proxying is covered at https://learn.microsoft.com/en-us/azure/developer/java/sdk/proxying
