### ISSUE TITLE
I cannot find a Jenkins published by Microsoft

### ISSUE THREAD

**Issue by tacowan** [MicrosoftDocs/azure-dev-docs#346]
Is this out of date?  there is no Jenkins marketplace item with publisher Microsoft. "select the Jenkins offering with a publisher of Microsoft, and then select Create."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc269e1e-9a34-d676-bdd0-979e565bbdc4
* Version Independent ID: 88a4c2d4-1dff-3afd-9dde-652c1f93ac4a
* Content: [Tutorial - Use Azure Container Instances as a Jenkins build agent](https://docs.microsoft.com/en-us/azure/developer/jenkins/azure-container-instances-as-jenkins-build-agent)
* Content Source: [articles/jenkins/azure-container-instances-as-jenkins-build-agent.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/azure-container-instances-as-jenkins-build-agent.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@tacoowan The process of installing and configuring Jenkins has changed. Please see the instructions in the article, [Quickstart: Configure Jenkins using Azure CLI](https://docs.microsoft.com/azure/developer/jenkins/configure-on-linux-vm). We are currently updating all Jenkins articles that refer to the solution template to point to the Azure CLI article.
