### ISSUE TITLE
--is-linux Required

### ISSUE THREAD

**Issue by dev-playbook** [MicrosoftDocs/azure-dev-docs#349]
This tutorial does not work when the location is set to <code>uksouth</code>.

When the location is set to <code>westus</code> as instructed, it works as expected.

Also doesn't work in <code>ukwest</code>.

A corrective it to set <code>--is-linux</code> when creating the App Service

    az appservice plan create --name $planname --sku F1 --is-linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c16465-63f3-f230-21b6-cdb276950c70
* Version Independent ID: 8ed2938f-4484-3117-4eb8-291cb6933df9
* Content: [Deploy the app code to Azure App Service using the Azure CLI](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial-vscode-azure-cli-node-04)
* Content Source: [articles/javascript/tutorial-vscode-azure-cli-node-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial-vscode-azure-cli-node-04.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by dev-playbook** [comment]
This tutorial does not work when the location is set to <code>uksouth</code>.

When the location is set to <code>westus</code> as instructed, it works as expected.

Also doesn't work in <code>ukwest</code>.

**Comment by diberry** [comment]
@dev-playbook Thank you for letting us know. I'll add information in a note to distinguish win/linux and region. #in-progress

**Comment by cephalin** [comment]
@dev-playbook I don't reproduce your issue. Both uksouth and ukwest work for me.

**Comment by diberry** [comment]
@dev-playbook I'm closing this issue. If you can reproduce the issue, please reopen with more details.

**Comment by dev-playbook** [comment]
[10-deploy-with-local-git.zip](https://github.com/MicrosoftDocs/azure-dev-docs/files/5535911/10-deploy-with-local-git.zip)

Hi @diberry 

Thanks for looking into this.

I am still able to recreate the issue as described. Without the <code>--is-linux</code> option, the deployment is using the 0.10.40 version of NodeJS.

I've attached a compressed file which includes a ps1 script and outputs of local git deployment from 2 scenarios. The script follows the same process as the tutorial.

If you execute <code>10-deploy-with-local-git.ps1</code> as is on PowerShell with <code>--is-linux</code> commented out in line 25, you should expect the same failure in <code>uksouth-win.txt</code>. As you can see, the code is deployed with NodeJS 0.10.40 runtime.

Once you rolledback, if you include <code>--is-linux</code> in line 25 and execute, you should expect the same success in <code>uksouth-linux.txt</code>. This time the code is deployed with Node v12.18.3 runtime.

As said earlier, this failure also occurred in <code>ukwest</code> but not in <code>westus</code>.

I was using Windows 10.

I hope that clarifies.
