### ISSUE TITLE
spring-cloud-starter-stream-kafka maven dependency version problem 

### ISSUE THREAD

**Issue by asteroy** [MicrosoftDocs/azure-dev-docs#35]
Current version of spring boot 2.2.1 doesn't work with spring-cloud-starter-stream-kafka version 2.0.1.RELEASE. To solve this problem, version 2.2.1.RELEASE should be used

             <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
			<version>2.2.1.RELEASE</version>
		</dependency>

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb8bc1e-65b0-f895-942c-cb3aec127f85
* Version Independent ID: 9c16e082-ac66-6681-6b4c-aa52f63efbb9
* Content: [How to use the Spring Boot Starter for Apache Kafka with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub)
* Content Source: [java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by asteroy** [comment]
I see that version 2.2.1 is still has some problems, but with 3.0.0 looks stable.

<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-stream-kafka</artifactId>
			<version>3.0.0.RELEASE</version>
		</dependency>

**Comment by KarlErickson** [comment]
@asteroy thanks for the feedback! We'll investigate.

**Comment by KarlErickson** [comment]
Topic has been updated.
