### ISSUE TITLE
Command azure_rm_rediscache_facts is depricated

### ISSUE THREAD

**Issue by jhoelzl** [MicrosoftDocs/azure-dev-docs#350]
[Enter feedback here]
Use `azure_rm_rediscache_info` instead.

Source: https://docs.ansible.com/ansible/2.9/modules/azure_rm_rediscache_facts_module.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 860ff5bb-2fb4-e223-fd6b-eacb474dc29b
* Version Independent ID: a535e21a-4413-7834-5ed6-2b29f65583f0
* Content: [Tutorial - Configure caches in Azure Cache for Redis using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/cache-for-redis-configure?tabs=ansible)
* Content Source: [articles/ansible/cache-for-redis-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/cache-for-redis-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @jhoelzl

I appreciate you taking the time to file this issue.

A PR has been submitted to fix the article, changes should be refleced with 24-48 hours.

Thanks!
