### ISSUE TITLE
Out-of-date activate command

### ISSUE THREAD

**Issue by johnduckmanton** [MicrosoftDocs/azure-dev-docs#351]
I believe that the command: 

```source .venv/scripts/activate```

no longer works and should now be (on Python 3.4 and above):

```source .venv/bin/activate```

See https://python3.guide/virtual-environments/virtualenv for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c507d59-970e-feae-b034-8dc27f04d6b4
* Version Independent ID: 0c608a8f-a794-1f3e-6047-24dd2108633b
* Content: [Configure your local Python environment for Azure development](https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=cmd#use-python-virtual-environments)
* Content Source: [articles/python/configure-local-development-environment.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/configure-local-development-environment.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for pointing this out...a little mixup between the Cmd/Windows and Bash/Linux versions that occasionally slip through. I'll get it fixed.
