### ISSUE TITLE
Needs finish - run on Azure

### ISSUE THREAD

**Issue by EdTheC** [MicrosoftDocs/azure-dev-docs#352]
Great tutorial,  but it only runs locally.  I think a great next step would be to show how to get it to azure and run there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81bc2cc-4783-f993-bf50-91b4f09199b9
* Version Independent ID: 137dbf97-0f08-13d2-a47b-5c2a261950a8
* Content: [Upload image to Blob Storage](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/browser-file-upload?tabs=bash&tutorial-step=1)
* Content Source: [articles/javascript/tutorial/browser-file-upload.yml](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/browser-file-upload.yml)
* GitHub Login: @barbkess
* Microsoft Alias: **barbkess**

**Comment by diberry** [comment]
@EdTheC Thank you for your feedback. How would you see that continuation, directly in this specific tutorial or a link to a different tutorial about moving a local code base to Azure for hosting? #in-progress

**Comment by diberry** [comment]
I've updated the [Cleanup](https://docs.microsoft.com/azure/developer/javascript/tutorial/browser-file-upload?preview=tutorialFeedback&tabs=bash&tutorial-step=5) section to include information to deploy to a hosted service on Azure. If this doesn't meet your needs, feel free to reopen this issue.
