### ISSUE TITLE
Appinsgiht Version to be updated

### ISSUE THREAD

**Issue by vimorra** [MicrosoftDocs/azure-dev-docs#354]
[Enter feedback here]
Into the doc is shared the version 1.1.1, wpudl be better to update with the last one, or at least mention that into maven repo is possible download further versions.
https://mvnrepository.com/artifact/com.microsoft.azure/applicationinsights-spring-boot-starter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfc159f-ed51-705e-26f5-0ee7696076be
* Version Independent ID: 647a83b1-b733-c83c-35a3-9aee375645bc
* Content: [Configure Initializer app for Spring Boot Starter - Azure Monitor](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-java-applicationinsights)
* Content Source: [articles/java/spring-framework/configure-spring-boot-java-applicationinsights.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-java-applicationinsights.md)
* Service: **azure-monitor**
* GitHub Login: @dhaval24
* Microsoft Alias: **dhdoshi**

**Comment by KarlErickson** [comment]
@vimorra thanks for the feedback! This topic has been deprecated and removed. For the current recommended approach, see <https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent>.
