### ISSUE TITLE
Extra space error on passing PORT system property in spring

### ISSUE THREAD

**Issue by diop-malick** [MicrosoftDocs/azure-dev-docs#36]
There is a minors error on the xml code of the pom file,
item 4 of the paragraph "Configure Maven Plugin for Azure App Service"

where your say to add the &lt;appSettings&gt; section to the &lt;configuration&gt; section of &lt;azure-webapp-maven-plugin&gt; to listen on the 80 port.

```
<property>
   <name>JAVA_OPTS</name>
   <value>-D server.port=80</value>
</property>
```

there is a space between the chart "D" and the propriety system server.port = 80,
this cause app access fail after deployment on azure App service.

to pass properties directly on command line in Spring, the correct way is -Dproperty.name="value", without space between -D and property name.

So the correct code would be : 

```
<property>
   <name>JAVA_OPTS</name>
   <value>-Dserver.port=80</value>
</property>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 69c11e55-5a5e-584d-5c4b-71cea89d34da
* Content: [Deploy a Spring Boot JAR file Web App to Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin#deploy-the-app-to-azure)
* Content Source: [java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by rdonasco** [comment]
I've spent hours figuring out this problem. If I have read this comment, I could have moved on forward earlier. LOL. Anyways, thanks.

**Comment by yucwan** [comment]
Fixed. Thanks a lot for the feedback.

**Comment by KarlErickson** [comment]
Thanks @diop-malick and @yucwan! I've verified the fix, so I'm closing this.
