### ISSUE TITLE
Specify AzureCNI as mandatory networking plugin and kubectl can't be use

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-dev-docs#362]
Azure CNI plugin is quite serious limitation. Could you highlight in documentation that Azure CLI is mandatory networking plugin and kubectl can't be use

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@SychevIgor Thanks for your feedback. I've completely rewritten and tested this article. The article should go live Monday.
