### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sergong** [MicrosoftDocs/azure-dev-docs#363]
Unfortunately the example fails at the first `terraform apply` with the following error:
**Error**: "features": required field is not set

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4371abd-f9cc-1ee9-1ed3-a5f0488740ce
* Version Independent ID: 14c6cf0f-ec32-15ed-cb38-8eb5860d858e
* Content: [Create an Azure virtual machine scale set from a Packer custom image by using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-using-packer-hcl)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Sergong Thank you for your feedback. I've rewritten this article and everything should be working now. Please let me know if you continue to encounter problems.
