### ISSUE TITLE
Issues with Terraform files in How to Create AGIC in AKS

### ISSUE THREAD

**Issue by felixtsem5** [MicrosoftDocs/azure-dev-docs#365]
I have some difficulties with the example. I am reaching out and see if you can help me with it. If you require a GitHub Issue, I’d be happy to create one.

I am trying to follow the steps in the document, and I have the necessary resources created (a resource group, a storage account with a container, and a service principal). When I try to create the Terraform plan, I got the following error:
```
Error: Error: Subnet "kubesubnet" (Virtual Network "aksVirtualNetwork" / Resource Group "rgTF") was not found

  on resources.tf line 49, in data "azurerm_subnet" "kubesubnet":
  49: data "azurerm_subnet" "kubesubnet" {



Error: Error: Subnet "appgwsubnet" (Virtual Network "aksVirtualNetwork" / Resource Group "rgTF") was not found

  on resources.tf line 55, in data "azurerm_subnet" "appgwsubnet":
  55: data "azurerm_subnet" "appgwsubnet" {
```
I am not a Terraform expert, but reading through the sample code, it looks like Terraform is trying to query for the subnets.
```
data "azurerm_subnet" "kubesubnet" {
  name                 = var.aks_subnet_name
  virtual_network_name = azurerm_virtual_network.test.name
  resource_group_name  = data.azurerm_resource_group.rg.name
}

data "azurerm_subnet" "appgwsubnet" {
  name                 = "appgwsubnet"
  virtual_network_name = azurerm_virtual_network.test.name
  resource_group_name  = data.azurerm_resource_group.rg.name
}
```
Do we need to create these subnets beforehand?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@felixtsem5 Thanks for your feedback. I've completely rewritten and tested this article. The article should go live Monday.
