### ISSUE TITLE
Broken SDK Library List Link

### ISSUE THREAD

**Issue by luisquintanilla** [MicrosoftDocs/azure-dev-docs#37]
The following link returns a 404 https://github.com/Azure/azure-sdk-for-python/blob/master/packages.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b440c3f1-e186-48e8-e98d-508f0d704f72
* Version Independent ID: c4dfd464-e21e-ac43-c355-d2e3f35d6f45
* Content: [Install the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-install?view=azure-python)
* Content Source: [python/python-sdk-azure-install.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/python-sdk-azure-install.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@luisquintanilla Thanks for pointing that out. The package.md file was removed, so I'll update the link to https://azure.github.io/azure-sdk/releases/latest/python.html, which has the links to the pypi instructions and docs for each library.
