### ISSUE TITLE
Android permissions in Xamarin.Forms article about using notification hub with backend

### ISSUE THREAD

**Issue by timvandenhof** [MicrosoftDocs/azure-dev-docs#370]
"Ensure the INTERNET and READ_PHONE_STATE permissions are enabled under Required permissions."
Please describe WHY the READ_PHONE_STATE permission is required. INTERNET is obvious, but READ_PHONE_STATE is not. It seems to me that is not needed to have this Android permission requirement, as also mentioned in this blog post:
https://coronalabs.com/blog/2016/02/23/breaking-change-android-6-and-device-ids/

Maybe this permission can be removed from the article and the sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
