### ISSUE TITLE
unclear directions for ssh in Terraform on Azure docs

### ISSUE THREAD

**Issue by francisrsandoval** [MicrosoftDocs/azure-dev-docs#371]
]https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure
section 'Create Virtual Machine'
"'SSH key data is provided in the ssh_keys section. Provide a public SSH key in the key_data field."

Please direct reader on how to acquire ssh key - I suspect one has to set this up via Azure portal
and, be specific on exactly where in the document to put the key. There is no 'ssh_keys section', nor is their a field called "key_data"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@francisrsandoval Thanks for your feedback. I update the article and it should be published tomorrow.
