### ISSUE TITLE
Add lifecycle ignore_changes example to avoid conflicts/resource changes for AGIC controlled resources

### ISSUE THREAD

**Issue by dave-read** [MicrosoftDocs/azure-dev-docs#372]
[Enter feedback here]
As soon as Ingress resource(s) have been deployed, AGIC will overwrite the initial backend/listener configurations, and Terraform will think it needs to make changes to resources that are actually now "owned" by AGIC.  Details are in this [stackoverflow post](https://stackoverflow.com/questions/63691139/terraform-removes-configurations-resources-created-by-the-application-gateway-in) along with this example for resources to ignore:
```
lifecycle {
  ignore_changes = [
    backend_address_pool,
    backend_http_settings,
    frontend_port,
    http_listener,
    probe,
    redirect_configuration,
    request_routing_rule,
    ssl_certificate,
    tags,
    url_path_map,
  ]
}
```
It would help if the product team(s) review the approach the from stackoverflow post and update this doc as appropriate  to avoid having to figure out why the App Gateway resource has changed and avoid conflicts between Terraform and AGIC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@dave-read Thanks for your feedback. I've completely rewritten and tested this article. It should go live Monday.
