### ISSUE TITLE
[azure-dev-docs] Review the external links to GitHub Actions documentation

### ISSUE THREAD

**Issue by martin389** [MicrosoftDocs/azure-dev-docs#373]
The following docs contain external links to GitHub Actions content on [docs.github.com](https://docs.github.com/):

- "Use variable substitution with GitHub Actions": [[Published article]](https://docs.microsoft.com/en-us/azure/developer/github/github-variable-substitution) - [[Markdown source]](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/github/github-variable-substitution.md).
- "Use GitHub Actions to connect to Azure": [[Published article]](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure) - [[Markdown source]](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/github/connect-from-azure.md).
- "What is GitHub Actions for Azure": [[Published article]](https://docs.microsoft.com/en-us/azure/developer/github/github-actions) - [[Markdown source]](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/github/github-actions.md).

For each doc listed above:
1. Review each link to [docs.github.com](https://docs.github.com/) and [help.github.com](https://help.github.com) to determine if its directing users to the best section for that topic.
2. If there's a more preferable link, or if the link gets redirected: create a PR to update the docs with the new link.

**Comment by martin389** [comment]
👋 We'll be working on this with @juliakm.

**Comment by skedwards88** [comment]
The links in "Use variable substitution with GitHub Actions" and "Use GitHub Actions to connect to Azure" look good! I made some updates to "What is GitHub Actions for Azure" in https://github.com/MicrosoftDocs/azure-dev-docs/pull/378.

**Comment by juliakm** [comment]
Hi @martin389 and @skedwards88! Have we updated all of the links now? I'm wondering if I should close this issue.

**Comment by skedwards88** [comment]
Yes, this is safe to close!

**Comment by juliakm** [comment]
#please-close
