### ISSUE TITLE
Command To Create webapp Is Incorrect

### ISSUE THREAD

**Issue by opticyclic** [MicrosoftDocs/azure-dev-docs#376]
Section 4
> Run the following command to create the App Service, replacing <your_app_name> with a unique name that becomes the URL, http://<your_app_name>.azurewebsites.net. 
> Note that the PowerShell command is slightly different. 
> The --runtime "node|6.9" argument tells Azure to use node version 6.9.x on the server.
>  Azure CLI

    az webapp create --name <your_app_name> --plan myPlan --runtime "node|6.9"

When running this you get the error:

    az webapp create: error: the following arguments are required: --resource-group/-g

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f1b838-0a5e-9248-c4ae-3ab7f45674ff
* Version Independent ID: 8cdc70c3-b2e0-2c20-84d4-20ddb74ba793
* Content: [Create the Azure App Service from the Azure CLI to host the app](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial-vscode-azure-cli-node-03)
* Content Source: [articles/javascript/tutorial-vscode-azure-cli-node-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial-vscode-azure-cli-node-03.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@opticyclic Thank you for letting us know. #in-progress

**Comment by diberry** [comment]
After following the tutorial, I noticed the resource group is set as a default for the Az CLI a few steps above this step. When I completed the steps in order, it worked for me. Can you verify if you completed the steps in order or selected a subset of the steps?   I'll add links to the exact Az CLI commands and a troubleshooting note about the initial default at the top of the article.

**Comment by diberry** [comment]
Closing this now. If you happens again, when using the entire doc, please reopen.
