### ISSUE TITLE
OCM is retired

### ISSUE THREAD

**Issue by dgordonb** [MicrosoftDocs/azure-dev-docs#377]
Outlook Customer Manager was retired July 1, 2020.  Please remove the reference in this article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 003f9d64-7106-95d8-21ab-ea4f9c6208b6
* Version Independent ID: 84b70b16-9f60-d175-3d76-b845c15b2d7b
* Content: [Azure SDK libraries for JavaScript](https://docs.microsoft.com/en-us/azure/developer/javascript/azure-sdk-library-package-index)
* Content Source: [articles/javascript/azure-sdk-library-package-index.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/azure-sdk-library-package-index.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@ramya-rao-a @weshaggard Can you please verify this? #in-progress

**Comment by diberry** [comment]
This issue should have been handled internally. I'm closing to allow that process to finish. Please reopen if you aren't clear with the outcome.
