### ISSUE TITLE
Typo: definitionw should be definitions

### ISSUE THREAD

**Issue by charris-msft** [MicrosoftDocs/azure-dev-docs#379]
In the Tip section:
The container definition**w** are on github.com/Azure-App-Service/python.

should be

The container definition**s** are on github.com/Azure-App-Service/python.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac023b-e576-7e00-ca13-9bfb4597e91e
* Version Independent ID: e7fe954e-c81a-f9e2-6bb5-5aba2ba03be7
* Content: [Tutorial: Deploy Python apps to Azure App Service on Linux from Visual Studio Code](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-01)
* Content Source: [articles/python/tutorial-deploy-app-service-on-linux-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-deploy-app-service-on-linux-01.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks, I'll fix this.
