### ISSUE TITLE
Invalid github URL

### ISSUE THREAD

**Issue by htejwani** [MicrosoftDocs/azure-dev-docs#380]
The Github URL for source code reference on this page:
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory
is invalid, it gives a 404.

Refer Link:
Azure Active Directory Spring Boot Sample
URL: https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-samples/azure-spring-boot-sample-active-directory-backend

**Comment by KarlErickson** [comment]
@htejwani thanks for the feedback! I'll get that fixed.
