### ISSUE TITLE
Clarity for new developers

### ISSUE THREAD

**Issue by manknewl** [MicrosoftDocs/azure-dev-docs#381]
I think the instructions could be more "fool proof" for beginners. 

Include python version for cmd (only bash included) 
Specify that steps 4 - 8 should be executed in the folder created where the app "hello.py" is. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2528d320-70aa-c8b0-effc-dc1d54c135b9
* Version Independent ID: b5b7427c-1e7e-ae3d-93c8-97ea87c0fea7
* Content: [Step 2: Prepare an app for deployment to Azure App Service on Linux from Visual Studio Code](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-02?tabs=windows%2Ccmd)
* Content Source: [articles/python/tutorial-deploy-app-service-on-linux-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-deploy-app-service-on-linux-02.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Fixed in the referenced PR; changes should be visible in the live docs within 24 hours.
