### ISSUE TITLE
add more description on the service principal

### ISSUE THREAD

**Issue by lissff** [MicrosoftDocs/azure-dev-docs#382]
[Enter feedback here]
can we add more documentation or description on the service principal part?
because if we are using az ad create-for-rbac and --skip-assignment
then it is highly possible we will face permission issues when we are trying to create any resource, but we don't know how to grant the permissions, or what is the general permission/role we could refer to.
e.g. contributor role in the resourceGroup/subscription

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c507d59-970e-feae-b034-8dc27f04d6b4
* Version Independent ID: 0c608a8f-a794-1f3e-6047-24dd2108633b
* Content: [Configure your local Python environment for Azure development](https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=cmd)
* Content Source: [articles/python/configure-local-development-environment.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/configure-local-development-environment.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks @lissff - I've added a little more to the article plus some a link to the Python authentication article and to the RBAC docs that describe how to add specific role assignments (which were added to the docs recently). We very much recommend using --skip-assignment exactly to avoid having a service principal with general-purpose permissions; the preferred model is to create a service principal with no permissions and then explicitly assign those permissions that you require. That said, you can certainly drop --skip-assignment and rely on default permissions if that works for you.
