### ISSUE TITLE
Update some steps according to the new Python build changes

### ISSUE THREAD

**Issue by saifbadran9** [MicrosoftDocs/azure-dev-docs#384]
Hi Team,

According to the latest Python build and runtime workflow changes that is announced here:
https://github.com/Azure-App-Service/KuduLite/wiki/Python-Build-Changes

Step 2 in this tutorial:
![image](https://user-images.githubusercontent.com/31154438/102793375-7d475a80-43b2-11eb-82cb-196abeafbc52.png)

Should be update to use $APP_PATH instead of site/wwwroot "cd $APP_PATH"
Since the upgraded apps will no longer have the app running in site/wwwroot, instead it would have a dynamic runtime directory, that can be retrieved using the APP_PATH environment variable.

Step 3:
![image](https://user-images.githubusercontent.com/31154438/102793401-87695900-43b2-11eb-94d6-ad2b162ba24d.png)

Is probably no longer needed, not sure how to confirm when this is needed and when it is not, but in our case we could not find the directory /antenv/, skipping this step worked fine and we were able to successfully deploy the app. So I guess it is worth verifying/mentioning this in the document.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d873da-7721-07bf-9584-78d1b5788167
* Version Independent ID: 81490eea-63aa-d729-c9fb-6753961e39cc
* Content: [Tutorial: Deploy a Django app with PostgreSQL using the Azure portal](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-python-postgresql-app-portal)
* Content Source: [articles/python/tutorial-python-postgresql-app-portal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-python-postgresql-app-portal.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Done.

Please note that the SSH session is reporting an error for antenv/bin/activate, and it's still necessary to manually install dependencies:

 _____
  /  _  \ __________ _________   ____
 /  /_\  \___   /  |  \_  __ \_/ __ \
/    |    \/    /|  |  /|  | \/\  ___/
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/

A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux
Python 3.8.6
Note: Any data outside '/home' is not persisted
-bash: antenv/bin/activate: No such file or directory

**Comment by kraigb** [comment]
One clarification: the source /antenv/bin/activate is still needed, and doing so removes the need to pip install requirements. It appears that App Service is trying to activate antenv by default, but doesn't have the leading /. The antenv folder is there in the root. So I'm leaving the activate command but removing pip install.
