### ISSUE TITLE
Missing segment in url

### ISSUE THREAD

**Issue by mrochon** [MicrosoftDocs/azure-dev-docs#387]
Instruction for adding controllers is missing url segment(s). Currently, it says (in item 8 of the [Configure and compile your app](Create a folder named controller in src/main/java//, replacing <yourGroupId> with the value you entered for Group.)'):

`Create a folder named controller in src/main/java//, replacing <yourGroupId> with the value you entered for Group.`

Note that the url ends with extra '/' and does not have mention your GroupId which is supposed to be replaced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @panli
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@mrochon thanks for the feedback! We'll get this fixed.

**Comment by KarlErickson** [comment]
Fixed
