### ISSUE TITLE
Application is not exchanging the authorization code for token(s)

### ISSUE THREAD

**Issue by mrochon** [MicrosoftDocs/azure-dev-docs#388]
I created a sample Java app as per [these instructions](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc). When running it, I can see that the application is requesting an OAuth2 authorization code from B2C and B2C responds with the authorization code and state parameters to the http://localhost:8080/home endpoint. However, when my app gets this response it redirects itself again to http://localhost:8080, which then displays the standard error page:

`<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Dec 30 12:17:09 PST 2020</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div></div></body></html>`

I was expecting the app to call b2C token endpoint to exchange the code for an id_token, validate it and display user claims in the UI.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @panli
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@mrochon thanks for the feedback! We'll look into this.

**Comment by saragluna** [comment]
@chenrujun please take a look at this.

**Comment by saragluna** [comment]
@KarlErickson could you please add @chenrujun as assignee?

**Comment by KarlErickson** [comment]
@chenrujun please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by michaelqi793** [comment]
I'll create PR soon.

**Comment by michaelqi793** [comment]
@lastnameholiu  Hi Can you reproduce this issue?  If yes, can you share the steps? I can't go any further than reach the login page that has no sign up link.

**Comment by michaelqi793** [comment]
I used the latest AAD B2C jar. 
 ```
    <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>azure-spring-boot-starter-active-directory-b2c</artifactId>
        <version>3.4.0</version>
    </dependency>
```
And the issue cannot be reproduced.  Please refer to the updated instructions:
#517
