### ISSUE TITLE
Azure SDK for Java content issues

### ISSUE THREAD

**Issue by noelbundick** [MicrosoftDocs/azure-dev-docs#39]
I'm looking for information on the new Azure SDK since a few libraries were announced as GA in November 2019, and I've found it's been difficult to find information from docs.microsoft.com. Below are a few issues that I encountered along the way:

* [https://docs.microsoft.com/en-us/azure/java/?view=azure-java-stable](https://docs.microsoft.com/en-us/azure/java/?view=azure-java-stable) doesn't seem to have any links to the new SDK
  * "Upload and download blobs from Storage" takes me to https://github.com/azure/azure-storage-java, which points me to the v12 repo
    * From here I get links to v12, v11 (not recommended), v8 (sync only)
    * What do I click on to learn how to upload/download blobs?
      * Maybe v12 -> azure-storage-blob
      * And/or v12 -> azure-storage-blob -> Samples -> Basic Examples
* There are no new SDK docs on https://docs.microsoft.com/en-us/java/api/, everything references the old `com.microsoft.azure` packages
* Google landed me on https://azure.github.io/azure-sdk-for-java/, which seems to have all the good info, but I wasn't able to find it from docs
  * Why is this a separate experience from docs.microsoft.com?
  * If there’s a good reason – can we get it linked to / discoverable on /searchable from docs.microsoft.com?
  * Most links on the page here are 404. I can see from the paths that those are relative links inside the source repo, but from this site they just error out

**Comment by KarlErickson** [comment]
@bmitchell287 can you follow up on this? Thanks.

**Comment by KarlErickson** [comment]
@noelbundick thanks for the feedback! Just wanted to let you know that these are all known issues that we are thinking about currently. We will definitely update the documentation when we have worked through some related issues. I'm closing this issue for now, but if you have additional feedback, please do not hesitate to reopen it, or create a new issue. Thanks again!
