### ISSUE TITLE
Missing text (typo?) on js authentication instructions

### ISSUE THREAD

**Issue by bendavis78** [MicrosoftDocs/azure-dev-docs#390]
Under the section "Older Azure SDK client authentication", the second bullet is incomplete:

> For best results with older client libraries:
> * Each npm package will show authentication for that exact client library.
> * If your current code uses the `@azure/ms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b321721e-c13d-cd09-9b21-da919281e687
* Version Independent ID: 0858b54a-1f2d-9faf-1561-2d599c559d5d
* Content: [Authenticate with the Azure management modules for Node.js](https://docs.microsoft.com/en-us/azure/developer/javascript/core/node-sdk-azure-authenticate)
* Content Source: [articles/javascript/core/node-sdk-azure-authenticate.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/core/node-sdk-azure-authenticate.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@bendavis78 Thank you for reporting this. #in-progress

**Comment by diberry** [comment]
The fix will be published by tomorrow. Closing this issue now but feel free to reopen if you have further questions about the doc.
