### ISSUE TITLE
Xamarin.Forms - Push Notification Tutorial Typo

### ISSUE THREAD

**Issue by BPurgert** [MicrosoftDocs/azure-dev-docs#392]
Hello! I just followed the guide on setting up push notifications - it was extremely helpful! There is a typo in two of the code snippets (same typo in two spots)

Step 3 under "Handle push notifications for Android"

`if (string.isNullOrWhitespace(Token))
                throw new Exception("Unable to resolve token for FCM");`

and step 3 under "Handle push notifications for iOS"

`if (string.isNullOrWhitespace(Token))
                throw new Exception("Unable to resolve token for APNS")`

Both need a capital "I" in `IsNullOrWhitespace`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#option-2-creating-a-p8-certificate-that-can-be-used-for-token-based-authentication)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by BPurgert** [comment]
Pull request #393 and #394 are open to address this issue.

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
