### ISSUE TITLE
Missing info on how to recover the subscriptionId for the App Gateway.

### ISSUE THREAD

**Issue by DylanGuedes** [MicrosoftDocs/azure-dev-docs#395]
Hello,
on the 2nd item of [this section](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#install-ingress-controller-helm-chart) there is a subsection "key notes" explaining how to retrieve most of the necessary parameters (for instance, `identityResourceID`). However, it is not very clear how can one retrieve the subscription id for the AppGw. I already have set an Azure account and I already have a subscriptionId (for my account), but I wonder if the subscription id for the AppGw is something different.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#feedback)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@DylanGuedes The subscription ID is the one you used to authenticate when running the demo. I've completely rewritten and tested this article. The demo uses a service principal, so the subscription id is the subscription associated with the service principal values you specify in the `terraform.tfvars` file. The article should go live Monday.
