### ISSUE TITLE
Example doesn't actually use service principle to authenticate to Azure

### ISSUE THREAD

**Issue by PaulTzl** [MicrosoftDocs/azure-dev-docs#397]
Hi

I've followed your example through, but when it came to creating the deployment plan I was given an error to say that I needed to run Az Login. Given that your example starts with creating a service principle, it should be using the service principle to authenticate, not prompting you to logon with Az Login.

The following Terraform page talks about how you can use the service principle:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform

Essentially you are missing this part...
ARM_CLIENT_SECRET="00000000-0000-0000-0000-000000000000"

from here...
https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell#set-environment-variables

Or for the purposes of this example, it might simpler to dispense with the service principle and just get people to run Az Login.

Best regards

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c31173-3e96-c871-5a2d-743a26522b4d
* Version Independent ID: 5b281d75-b37e-0301-e1fd-431e0344d0c7
* Content: [Quickstart - Configure Terraform using Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell)
* Content Source: [articles/terraform/get-started-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Hi, Paul,

Thanks for your feedback.

I've updated the env vars to include ARM_CLIENT_SECRET.

However, note that Terraform requires using an SP from PowerShell and even then, you are still going to need to "az login" 

This [GitHub Issue](https://github.com/Azure/azure-cli/issues/16460) explains the technical details. If you wish, you can add your voice (via voting on the original post) to have this issue addressed in future versions.

Thanks,
Tom
