### ISSUE TITLE
Helm 3.4.0 doesn't have Init command available?

### ISSUE THREAD

**Issue by dlew56** [MicrosoftDocs/azure-dev-docs#398]
Reference Page: https://docs.microsoft.com/en-gb/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress#install-helm

When I attempt to run the below, I get the following error in the Azure Cloud Shell:

`helm init --tiller-namespace kube-system --service-account tiller-sa`

Error: unknown command "init" for "helm"

Please confirm if this documentation is accurate for Helm v3.4.0. Should I have another version installed?

I just found this: https://stackoverflow.com/questions/59261340/helm-init-has-been-removed-in-version-3

Thanks!
David

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-gb/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @dlew56,

I've updated the article to use helm 3 instead of helm 2 and removed the deprecated init command from the article.

Thank you for taking the time to file the issue, have a wonderful day!
