### ISSUE TITLE
Need to add @Override to cosmosConfig method

### ISSUE THREAD

**Issue by issacsamuel** [MicrosoftDocs/azure-dev-docs#400]
[Enter feedback here]
The code expects the user to override the cosmosConfig() method that supplies the bean. Because, the parent class AbstractCosmosConfig too defines cosmosConfig() method and if the user uses some other name, say getConfig() for customizing cosmosConfig() it is not picked up by the azure spring data cosmos library. So, to avoid that, the documentation should mark cosmosConfig() method with @Override option along with @Bean so that the client can annotate the method name to properly customize cosmosConfig bean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a03983-f9b2-360a-68d4-3f8a5f7b6923
* Version Independent ID: 3463f85f-dd80-85bb-4dbd-cba82fc5c4ef
* Content: [Spring Data Azure Cosmos DB developer's guide](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb#configure-the-application-based-on-properties)
* Content Source: [articles/java/spring-framework/how-to-guides-spring-data-cosmosdb.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/how-to-guides-spring-data-cosmosdb.md)
* Service: **azure-java**
* GitHub Login: @anfeldma-ms
* Microsoft Alias: **anfeldma**

**Comment by saragluna** [comment]
@backwind1233 please take a look at this.

**Comment by saragluna** [comment]
@KarlErickson could you please add @backwind1233 as an assignee?

**Comment by KarlErickson** [comment]
@backwind1233 please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by backwind1233** [comment]
Thank you @KarlErickson , @lastnameholiu I am looking at this issue and I am willing to create an PR to fix the issue in a few days, do you have any idea or concern about it?
