### ISSUE TITLE
Describe a difference between topicJmsListenerContainerFactory jmsListenerContainerFactory

### ISSUE THREAD

**Issue by Saljack** [MicrosoftDocs/azure-dev-docs#405]
Hi,
there is totaly missing a note that you have to use different ContainerFactories for Queue and Topic and a description what are differences between them. There should be a note that for topics your ConnectionFactory has to set `factory.setSubscriptionDurable(true)`. 
It isn't clear to me if I need to set `factory.setPubSubDomain(true);`. It is not used in your code but I don't know why. I suppose that it is because subscriptions behaves as queus.
Next thing on this page what doesn't make sense is that you have to define `spring.jms.servicebus.topic-client-id` for topics which isn't true. It works without defining this property. Moreover it wasn't clear for me what is Service Bus Subscription ID. I found answer on it in another issue https://github.com/Azure/azure-sdk-for-java/issues/16033 where is a picture what it is. But it looks like a name of topic subscription. So I think it needs more detailed description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbecafd0-c6db-9cb0-c5a4-328946446ec6
* Version Independent ID: 40cea238-c2de-fd1d-fef7-c1a850b54158
* Content: [How to use the Spring Boot Starter for Azure Service Bus JMS](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md)
* Service: **azure-java**
* GitHub Login: @seanli1988
* Microsoft Alias: **seal**

**Comment by saragluna** [comment]
@yiliuTo please take a look at this.

**Comment by saragluna** [comment]
@KarlErickson could you please assign this to @yiliuTo too?

**Comment by KarlErickson** [comment]
@yiliuTo please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by yiliuTo** [comment]
Hi @Saljack sorry for the late response. Currently we have released the latest version of 4.0.0 for this jms starter, so I would like to answer your questions towards the latest versions. And if you still have questions towards the previous versions, we can continue discussion towards the specific version you are using.
1. Now the doc has documented about the different container factories for queues and subscriptions: https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus#receive-messages-from-a-service-bus-subscription. And for subscription container factories, we have set the the durable property as true by default. Also we support to modify it by application properties via `spring.jms.servicebus.listener.subscription-durable`.
2. For pub-sub-domain property, it is now hard-coded in our [configuration](https://github.com/Azure/azure-sdk-for-java/blob/ffb7f704d390f4d162f8bff51d362e7fc0feadc6/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/jms/ServiceBusJmsContainerConfiguration.java#L68) to enable it for both queues and subscriptions, thus you don't need to worry about it.
3. As for the topic client id, it is the client identifier of JMS specification, which is used to uniquely identify the application connection for durable subscriptions. And for more information about Service Bus support for client scoping, you can refer [here](https://docs.microsoft.com/azure/service-bus-messaging/java-message-service-20-entities#client-scoping). So it's only necessary for consuming messages from unshared durable subscriptions, and can be empty for other cases.

**Comment by chenrujun** [comment]
Hi, @KarlErickson 

Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
Hi @KarlErickson , I suppose this issue can be closed since there is no response from the customer for long.
