### ISSUE TITLE
Your doc for MicroProfile on Azure only prescribes Payara Micro as the implementation

### ISSUE THREAD

**Issue by cealsair** [MicrosoftDocs/azure-dev-docs#41]
Please ensure that you are inclusive of all MicroProfile (MP) implementations in the market and not just one, namely Payara Micro. My recommendation would be to direct your readers to the MicroProfile Starter (start.microprofile.io) to generate their MicroProfile sample projects. The MP Starter allows developers to select what implementation they'd like to use for their generated project. Also the MP Starter has a plugin for Visual Studio Code.

Thank you,
Cesar

**Comment by KarlErickson** [comment]
@cealsair thanks for the recommendation, and apologies for the delayed response. We'll take this into consideration when we update these topics.

**Comment by selvasingh** [comment]
@m-reza-rahman - request you to help here.

**Comment by m-reza-rahman** [comment]
@selvasingh can you kindly file an internal issue? We can prioritize it as bandwidth becomes available, likely next semester.

**Comment by KarlErickson** [comment]
@m-reza-rahman I have filed an internal issue and assigned to you. Closing this issue because it is not immediately actionable.
