### ISSUE TITLE
Review Documentation

### ISSUE THREAD

**Issue by budaesandrei** [MicrosoftDocs/azure-dev-docs#411]
Hi Team,

I think this documentation needs to be reviewed. I've followed the steps in 3a exactly but got error:
**'AzureCliCredential' object has no attribute 'signed_session'**

From what I've read on github this module has been updated but the documentation does not reflect that.

Kind Regards,
Andrei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0f84424-a9f2-8dc1-33c5-b693a1fcf97e
* Version Independent ID: da8428e6-1716-9328-58f0-becedb46b8f4
* Content: [List resource groups and resources using the Azure libraries for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-list-resource-groups)
* Content Source: [articles/python/azure-sdk-example-list-resource-groups.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-list-resource-groups.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@budaesandrei Thanks for filing the issue. I just rechecked the code in the article and it is current and accurate, provided that you're using azure-identity 1.5.0+ and azure-mgmt-resource 1.15.0+.

The error you're seeing about signed_session indicates that you're still using an older version of azure-mgmt-resource. It's the same issue described on https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd#defaultazurecredential-object-has-no-attribute-signed-session for DefaultAzureCredential.

So please check the version of the library that you have installed and let me know. I can see that I should update the article to reflect those minimum versions in the requirements.txt file.

**Comment by budaesandrei** [comment]
Hi. Thank you for the quick response. I have checked the version of azure-identity and seems I have 1.5.0.

**Comment by kraigb** [comment]
@budaesandrei The version of **azure-mgmt-resource** is the important version number. It needs to be 1.15.0+. This is also the case for all other azure-mgmt-* libraries--the ones that have been upgraded to work with the latest azure-identity credential objects are all 1.15.x, I believe.

**Comment by budaesandrei** [comment]
Hi @kraigb. I've managed to solve this issue. Seems I had multiple versions of azure-identity and I was running my code on a kernel with an older version. Thanks for the support. I've updated azure-identity for all kernels

**Comment by kraigb** [comment]
Good to hear. I appreciate you filing the issue because it leaves a record of the issue and resolution together. All the best with your projects!
