### ISSUE TITLE
Docs shouldn't use 15.0.0.0/8 for subnets as these are reserved

### ISSUE THREAD

**Issue by stradigi-andres-de-castro** [MicrosoftDocs/azure-dev-docs#412]
https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress

Uses 15.0.0.0/8 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by stradigi-andres-de-castro** [comment]
From wikipedia:

15.0.0.0/8 | ARIN | 1991-09 |   | Various registries (maintained by ARIN). Formerly Hewlett-Packard Company.
-- | -- | -- | -- | --

**Comment by TomArcherMsft** [comment]
@stradigi-andres-de-castro Thanks for your feedback. I've completely rewritten and tested this article. Among the many changes is switching the IP address prefixes to non-reserved values. The article should go live Monday.
