### ISSUE TITLE
terraform init error: Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by rougi4** [MicrosoftDocs/azure-dev-docs#416]
Hi,

I am new in terraform and I am trying to Configure Terraform using Azure Cloud Shell according to the Azure site:

https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell

I have given the following entries in my main.tf and I get the following error when running the 

~/terraform2learn$ more main.tf
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.45.1"
    }
  }
}

provider "azurerm" {
  # Configuration options
}

terraform init
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.45.1"...
- Finding latest version of hashicorp/αzurerm...
- Installing hashicorp/azurerm v2.45.1...
- Installed hashicorp/azurerm v2.45.1 (signed by HashiCorp)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/αzurerm: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/αzurerm

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

It is a fresh new installation of terraform on my Azure portal in the Azure CLI.

Your feedback is more than welcome.

rgds,

Loukas

**Comment by TomArcherMsft** [comment]
Hi, @rougi4. Thanks for the feedback. I'll test this today and get back to you.

**Comment by TomArcherMsft** [comment]
@rougi4 From what I can tell, it's possible that a version change broke the documentation. I'm going to keep researching this and let you know tomorrow what I can determine.

**Comment by rougi4** [comment]
thanks a lot @TomArcherMsft  for your support. Keep me posted. I also believe that some how there is a terraform conflict in terms of versions which might have caused the break of the documentation.

**Comment by TomArcherMsft** [comment]
CC: @grayzu @mozehgir

Hi @rougi4. I've escalated this to the engineering team for their help.

**Comment by grayzu** [comment]
@rougi4 This is a known issue with the Cloud Shell environment that is being worked on by our teams and should be resolved soon.
https://github.com/Azure/go-autorest/issues/612

**Comment by rougi4** [comment]
Thank you very much @grayzu for your update.
I will keep na eye for the development of it.

**Comment by TomArcherMsft** [comment]
@rougi4 Thank your patience as we've worked together with our partner, HashiCorp, to resolve. This issue should be resolved within shortly. Here's the [PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/10740](https://github.com/terraform-providers/terraform-provider-azurerm/pull/10740)

**Comment by rougi4** [comment]
Hi @TomArcherMsft , this is brilliant! It is worth the patience :-) I will keep testing it and I will update you accordingly.

**Comment by TomArcherMsft** [comment]
@rougi4 Thanks much for your patience. Everything appears to be working now. 

Make sure that you see a message like this indicating that the latest version of azurerm is installed. Otherwise, you might be reusing the lock from a previous version.

"- Installing hashicorp/azurerm v2.49.0..."

Here's the code I just tested with:

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.12"
    }
  }
}
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "rg" {
  name = "deleteme"
  location = "eastus"
}
```

**Comment by TomArcherMsft** [comment]
Note that when I attempted to use a previously initialized directory, I received the following message:

**- Reusing previous version of hashicorp/azurerm from the dependency lock file**

Therefore, I received the errors that you were also getting.

I then created a new directory and copied my files into it before running "terraform init" on the new directory. 

That's when I got the message about a new azurerm version installing:

**Installing hashicorp/azurerm v2.49.0...**

I'm going to close this issue, but please let us know if we can assist further.

Cheers,
Tom

**Comment by TomArcherMsft** [comment]
@rougi4 I'm told you can also run `terraform init -upgrade` to force the upgrade :)

**Comment by rougi4** [comment]
Hi @TomArcherMsft I tried it installing the hashicorp/azurerm v2.49.0 and it has worked for me.
Many thanks for all your support.
I guess from my side you can close the issue.

Cheers,

Loukas
