### ISSUE TITLE
Update Azure Active Directory Login example error for HTTPS + App Service Certificate

### ISSUE THREAD

**Issue by kfolkes** [MicrosoftDocs/azure-dev-docs#418]
[Enter feedback here]
On the behalf of Microsoft Customer: 

The example Tutorial: Secure a Java web app using the Spring Boot Starter for Azure Active Directory does not provide details for work via HTTPS/TLS backed with an App Service certificate:
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory

When I tested the tutorial via HTTPS, I was not even getting to the Azure Active Directory login page. When I manually added to my Spring Boot security config instructions for requiring authentication via oauth2Login, I was able to start the Ouath2 flow, though the following error showed up in the web browser:
-------------------------------------------------------
Login with OAuth 2.0
[invalid_token_response] An error occurred while attempting to retrieve the OAuth 2.0 Access Token Response: I/O error on POST request for 'https://login.microsoftonline.com/XXXXXXXXXX/oauth2/v2.0/token': java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext); nested exception is java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
----------------------------------------------------------

 I will appreciate an update of the Active Directory login example and tutorial referenced above with details for HTTPS/TLS backed by an App Service certificate, stored in Key Vault as a certificate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by saragluna** [comment]
@KarlErickson could you please add @chenrujun as an assignee?

**Comment by KarlErickson** [comment]
@chenrujun please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by KarlErickson** [comment]
@kfolkes thanks for the feedback! Please see the comment on issue #439.
