### ISSUE TITLE
Is it impossible to create NAT rule for a VM Scale Set using Terraform?

### ISSUE THREAD

**Issue by hienlt21293** [MicrosoftDocs/azure-dev-docs#419]
When I manually create a VM Scale Set (VMSS) using Azure portal and choose to create a new LoadBalancer while creating the VMSS, a **default inbound NAT rule** is also created which allows me to ssh into each VM in the VMSS via the IP of the LoadBalancer (different port for each VM, obviously). 

But it seems impossible to do it with Terraform. Is this why we have to create a SSH jumpbox in order to access the VM in the VMSS ? 

Also, it seems that the _default inbound NAT rule_ can only appear if I choose to create a new LoadBalancer. If I use an existing LoadBalancer and attach it to the VMSS, there's no way to create NAT rules that are applied to VMs in the VMSS. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560d5902-d21c-a085-86a2-3189dde5d76c
* Version Independent ID: 7c19fad6-c65a-847d-a98c-0f9c9e4c6217
* Content: [Create an Azure virtual machine scale set using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-hcl)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-vm-scaleset-network-disks-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by ArcturusZhang** [comment]
Hi @hienlt21293 it should be possible but in terraform you need to handle everything by yourself.
To do this, aside from the fundamental resources which a VMSS requires (resource group, vnet, subnet), you also need to create the following
- load balancer: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb
- load balancer nat rule: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_nat_rule
And when creating the VMSS, you also need to assign the ID of load balancer nat rule to the `load_balancer_inbound_nat_rules_ids` attribute of the `azurerm_linux|windows_virtual_machine_scale_set` resource.

**Comment by TomArcherMsft** [comment]
@hienlt21293 The reply from our engineer @ArcturusZhang should answer your question. If not, please let us know and we'll continue to help. I'm going to close this issue, but will be updating the documentation per the feedback from @ArcturusZhang.

**Comment by shaonets82** [comment]
As per Terraform documentation lb_natrule cannot be used with virtual machine scale sets.
[lb_natrule](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_nat_rule)
they are suggesting to use lb_nat_pool resource
[lb_natpool](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_nat_pool)

i tried using lb_natpool but backend VMSS IP configuration still not getting added during deployment. I had to manually click the dropdown , select the VMSS and add the IP configuration.
