### ISSUE TITLE
Helm instructions are for Helm v2

### ISSUE THREAD

**Issue by mozts2005** [MicrosoftDocs/azure-dev-docs#420]
[Enter feedback here]
this document list only helm v2 instructions and should have helm v3 not helm v2.
https://helm.sh/blog/helm-v2-deprecation-timeline/

There are 5 other open issues about this topic. 
#218 
#398
#271
#272
#219 

I am happy to submit a pull request updating the page. I just want to make sure that is what the team needs/wants.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@mozts2005 Absolutely! All help is greatly appreciated.

**Comment by Duffney** [comment]
@mozts2005,

The article has been updated to use helm v3 instead of 3 and the changes have been published.

Thank you for filing the issue. :)

**Comment by mozts2005** [comment]
@Duffney as the helm section still references the install of helm tiller this has not been updated to install and use Helm V3 https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md#install-helm

**Comment by Duffney** [comment]
Forgive my inexperience with helm, but to confirm your referring to step 1 of the Install helm section that creates a service account and roleblinding for tiller that's no longer accurate \ needed correct?

I'll update the article and remove that step. Thank you for your reply.

**Comment by mozts2005** [comment]
Yes, the Install Helm Section should be change like this (AS there is no longer a cluster side change that needs to be done when using helm v3+: 


## Add Helm repository 

The code in this section uses [Helm](/azure/aks/kubernetes-helm) - Kubernetes package manager - to install the `application-gateway-kubernetes-ingress` package:

1. Add the AGIC Helm repository:

    ```bash
    helm repo add application-gateway-kubernetes-ingress https://appgwingress.blob.core.windows.net/ingress-azure-helm-package/
    helm repo update
    ```

**Comment by Duffney** [comment]
Got it, thanks for the quick reply! I'll get the article updated and PR submitted by EOD.

Appreciate you.
