### ISSUE TITLE
Error in the doc

### ISSUE THREAD

**Issue by alex-makang** [MicrosoftDocs/azure-dev-docs#426]
[Enter feedback here]

In the doc "Create Virtual Network" part, there is an extra "s" in "address_prefixes" which should be "address_prefixe". Please kindly correct it.

resource "azurerm_subnet" "myterraformsubnet" {
    name                 = "mySubnet"
    resource_group_name  = azurerm_resource_group.myterraformgroup.name
    virtual_network_name = azurerm_virtual_network.myterraformnetwork.name
    address_prefixes       = ["10.0.2.0/24"]
}
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#feedback)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by alex-makang** [comment]
I am seeing error when following this doc.

Error: Unsupported argument

  on main.tf line 29, in resource "azurerm_subnet" "myterraformsubnet":
  29:     address_prefixes       = ["10.0.2.0/24"]

An argument named "address_prefixes" is not expected here. Did you mean
"address_prefix"

**Comment by TomArcherMsft** [comment]
@alex-makang 

The syntax used in the article is the [azurerm_subnet syntax documented on terraform.io](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet). 

In addition, I copied and pasted from the [Complete Terraform script section in the article](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#complete-terraform-script), and the script created all of the resources. 

You might be running an older version of Terraform that predates the syntax being used, or you're running into another issue.

I suggest opening a ticket with HashiCorp to investigate further as the instructions are creating everything as expected.

To help you, there is a [Troubleshooting section](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#troubleshooting) in the article with links to get help directly from HashiCorp and the user community.
