### ISSUE TITLE
Bad instructions 

### ISSUE THREAD

**Issue by AllenVisser** [MicrosoftDocs/azure-dev-docs#428]
Step 5 doesnt work
$UnsecureSecret = ConvertFrom-SecureString -SecureString $sp.Secret -AsPlainText
![badadvice](https://user-images.githubusercontent.com/42998925/107400004-0dc82e80-6b0a-11eb-98a0-217b736b5d60.JPG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c31173-3e96-c871-5a2d-743a26522b4d
* Version Independent ID: 5b281d75-b37e-0301-e1fd-431e0344d0c7
* Content: [Quickstart - Configure Terraform using Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell)
* Content Source: [articles/terraform/get-started-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@AllenVisser The -AsPlainText parameter is only supported in later versions of PowerShell. What version of PowerShell are you using?

**Comment by AllenVisser** [comment]
PS 7.2

**Comment by TomArcherMsft** [comment]
@AllenVisser The blue background in your error message indicates an older version of PowerShell. PowerShell went to a black background in 6.x. For the command to work, you need to verify that you're running in a 7.x shell.

**Comment by TomArcherMsft** [comment]
@AllenVisser

I just spoke with our Azure PowerShell writer - @mikefrobbins - about this.

While the instructions in the Terraform article are correct, there is an updated sequence of instructions that works across all supported versions of PowerShell.

You can see more details about that in the following article: https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azps-5.5.0#password-based-authentication

Here is the relevant code for your scenario:

```
$sp = New-AzADServicePrincipal -DisplayName ServicePrincipalName
​$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret)
$UnsecureSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
```

I'm going to close this issue, but will be updating the article with the new guidance.

Thanks for the feedback!
