### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by zpdeering** [MicrosoftDocs/azure-dev-docs#43]
Is it possible to update this to track the changes that have been made in the 2.5.x versions of the Spring Boot plugin? Especially the AI-Agent.xml stuff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0847a17d-8f32-d22e-e8f9-e2604c8d34bb
* Version Independent ID: d0056593-615e-0147-fa0e-9633ad590b66
* Content: [Configure a Spring Boot Initializer app to use Azure Application Insights SpringBoot Starter](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-java-applicationinsights#feedback)
* Content Source: [java/spring-framework/configure-spring-boot-java-applicationinsights.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-java-applicationinsights.md)
* Service: **azure-monitor**
* GitHub Login: @dhaval24
* Microsoft Alias: **dhdoshi**

**Comment by KarlErickson** [comment]
@zpdeering thanks for the feedback! We'll investigate and make the appropriate updates.

**Comment by KarlErickson** [comment]
Topic has been removed and redirected to current recommended approach.
