### ISSUE TITLE
Using certificates instead of client-secret

### ISSUE THREAD

**Issue by milindvb** [MicrosoftDocs/azure-dev-docs#439]
The sample provided on this page uses client-id and client-secret as auth mechanism for azure ad
Azure ad also supports certificates instead of client-secret
can you provide an example of using certs instead of client-secret?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by saragluna** [comment]
@KarlErickson could you please add @chenrujun as an assignee?

**Comment by KarlErickson** [comment]
@chenrujun please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by han-gao** [comment]
I'll create PR soon.

**Comment by han-gao** [comment]
Hi @milindvb ,

At present, aad stater does not support the use of certificate. but it's a reasonable feature for the AAD starter, I have created an [issue](https://github.com/Azure/azure-sdk-for-java/issues/21650) to support it as a new feature.

**Comment by KarlErickson** [comment]
Thanks, @han-gao. I'll close this issue. We can update the article when the AAD starter supports certificates.
