### ISSUE TITLE
Securing spring api with b2c

### ISSUE THREAD

**Issue by rdonasco** [MicrosoftDocs/azure-dev-docs#44]
Hi Thanks for this detailed instruction on how to secure web application. Do you also have something that can be used to secure a REST API? Thanks a lot for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c3e00f-bdf2-cdb9-53a3-d672e0a1196d
* Version Independent ID: 3bd15057-0071-7aee-cf46-4c50a3061fbb
* Content: [How to use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc#feedback)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @panli
* Microsoft Alias: **panli**

**Comment by bmitchell287** [comment]
@seanli1988 - Hello Sean would you please provide feedback or route to the appropriate contact?

**Comment by saragluna** [comment]
@chenrujun please take a look at this.

**Comment by saragluna** [comment]
@KarlErickson could you please assign this to @chenrujun?

**Comment by chenrujun** [comment]
Hi, @rdonasco .

If it's AAD B2C web-api, please refer to this sample:
https://github.com/Azure-Samples/azure-spring-boot-samples/tree/46286cc4deed8aa842f40448dfd5d64cabb4b44e/azure-active-directory-b2c#4-resource-server

If it's AAD web-api, please refer to this sample: 
https://github.com/Azure-Samples/azure-spring-boot-samples/blob/spring-cloud-azure_4.0/aad/spring-security/docs/servlet/oauth2/client-access-resource-server.md

**Comment by chenrujun** [comment]
Closing this issue because there is no response from customer for a long time.
