### ISSUE TITLE
Deprecation notice for Azure-related Jenkins plugins misleadingly claims CLI is a replacement

### ISSUE THREAD

**Issue by jglick** [MicrosoftDocs/azure-dev-docs#440]
> Azure CLI is the currently recommended way to integrate Jenkins with Azure services.

certainly makes sense for plugin functionality which boils down to offering Pipeline steps (and/or “freestyle” builders/publishers) that do nothing other than communicate with Azure in some way, perhaps involving files in the workspace. It does not make any sense for https://plugins.jenkins.io/azure-artifact-manager/ which provides an implementation of https://jenkins.io/jep/202 or for https://plugins.jenkins.io/azure-credentials/ which integrates with other Jenkins plugins using https://plugins.jenkins.io/credentials/ or https://plugins.jenkins.io/azure-container-agents/ which lets you provision Jenkins agents to begin with, etc.

If there is no intention to maintain any of these plugins past 2024-02-29 then it would be clearer to say that they will be deprecated without replacement—you will simply not be able to use Jenkins well _on_ Azure. You will still be able to use Jenkins for apps _deployed to_ Azure, most easily via the CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77979df7-63f8-160a-ed04-f1e01ff417b3
* Version Independent ID: 3c2bc077-2f84-1e6d-e85e-5800c4de2527
* Content: [Jenkins plug-ins for Azure](https://docs.microsoft.com/en-us/azure/developer/jenkins/plug-ins-for-azure)
* Content Source: [articles/jenkins/plug-ins-for-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/plug-ins-for-azure.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@jglick Thank you for the feedback. I've talked to the engineering team and they've recommended that you email (Azure Jenkins Support](mailto:azurejenkins@microsoft.com)
