### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by darqs1** [MicrosoftDocs/azure-dev-docs#443]
There is an error in script, when I wanna to run it:

```
Failed to compile
src/azure/azure-authentication-context.ts
TypeScript error in src/azure/azure-authentication-context.ts(67,9):
Type 'AccountInfo | null' is not assignable to type 'AccountInfo | undefined'.
  Type 'null' is not assignable to type 'AccountInfo | undefined'.  TS2322

    65 |     handleResponse(response: AuthenticationResult, incomingFunction: any) {
    66 |       if (response !== null) {
  > 67 |         this.account = response.account;
       |         ^
    68 |       } else {
    69 |         this.account = this.getAccount();
    70 |       }
```

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: c627aaef-62e5-1aeb-f034-72790dff714a
* Version Independent ID: ad9d621b-bb91-9d21-2a2e-45183a48c709
* Content: [Tutorial: Add Microsoft login button to React SPA](https://docs.microsoft.com/pl-pl/azure/developer/javascript/tutorial/single-page-application-azure-login-button-sdk-msal#5-add-login-and-logoff-buttons)
* Content Source: [articles/javascript/tutorial/single-page-application-azure-login-button-sdk-msal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/single-page-application-azure-login-button-sdk-msal.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
In progress

**Comment by diberry** [comment]
@darqs1 Thank you for reporting this issue.

Link 67 - the if statement - needs to change to:

```javascript
if(response !==null && response.account !==null) {
```

I'll get the doc fixed next week.

**Comment by darqs1** [comment]
Hello Dina,
Thank You, it is working now!

regards
Darek

pt., 12 lut 2021 o 20:16 Dina Berry <notifications@github.com> napisał(a):

**Comment by diberry** [comment]
The doc and sample have been updated. I'm closing now.
