### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by ndriyo** [MicrosoftDocs/azure-dev-docs#446]
I believe this is an incomplete page of documentation for sample of howto create hub & spoke network topology. The terraform code stops in variables and no declaration of howto create the hub & spoke network. Even further, the variables contain VM variables instead of network variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4746271-7749-e9a0-bcd5-aab9d9cb05a4
* Version Independent ID: 8b70161b-d6a8-4ec4-870b-26660ac89fcd
* Content: [Tutorial - Create a hub and spoke hybrid network topology in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-introduction)
* Content Source: [articles/terraform/hub-spoke-introduction.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/hub-spoke-introduction.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by vinayhegde105** [comment]
Terraform still creating resources since 2 hour and something's wrong with "spoke1.tf" & "spoke2.tf".

Kindly verify and revert.

Thanks in advance.

**Comment by TomArcherMsft** [comment]
@vinayhegde105 When you say "revert", do you mean it was working before on your system and is not working now?

**Comment by vinayhegde105** [comment]
Hi @TomArcherMsft Thanks for the reply.
I was jus following the tutorial and when i run terraform apply, it has created 44 resources and after that it was continuously showing still creating resources. Will this work in "Free plan" or should i opt for "pay-as-you-Go". Please help.

**Comment by TomArcherMsft** [comment]
@vinayhegde105 This should definitely work on the "free plan". I'm on vacation right now, but I'll try to look at why this isn't working. If I can't look at it this week, I'll test this early next week.

**Comment by vinayhegde105** [comment]
@TomArcherMsft Thank you.
Wishing you a great vacation!
