### ISSUE TITLE
It's better to add azure key vault secret springboot starter dependencies in the document

### ISSUE THREAD

**Issue by rachelxj-ms** [MicrosoftDocs/azure-dev-docs#448]
If user starts from an existing spring boot project, it's not clear which dependency should be added in the project. 

https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#add-key-vault-integration-to-the-app, step 3, The Key Vault integration provides a Spring PropertySource that is populated from the values of the Key Vault. Some more implementation details are available in the reference documentation.
it goes to this link: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets/README.md, 
the dependency (this one is correct, same as when I use spring initializer https://start.spring.io/ to add the dependencies) shows it's
`<dependency>`
    `<groupId>com.azure.spring</groupId>`
    `<artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>`
    `<version>3.2.0-beta.1</version>`
`</dependency>`
but if I click Package(Maven) on the same page, it shows another dependency:

`<dependency>`
    `<groupId>com.microsoft.azure</groupId>`
    `<artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>`
    `<version>2.3.5</version>`
    `<scope>runtime</scope>`
`</dependency>`

this causes a misunderstanding if I start from an existing project, which would be a lot of people's choice.

So please add pom settings as well in the document

   `<properties>`
		`<azure.version>3.1.0</azure.version>`
  ` </properties>`
  `<dependencies>`
          ` <dependency>`
			`<groupId>com.azure.spring</groupId>`
			`<artifactId>azure-spring-boot-starter-keyvault-secrets</artifactId>`
           `</dependency>`
`</dependencies>`
`<dependencyManagement>`
		`<dependencies>`
			`<dependency>`
				`<groupId>com.azure.spring</groupId>`
				`<artifactId>azure-spring-boot-bom</artifactId>`
				`<version>${azure.version}</version>`
				`<type>pom</type>`
				`<scope>import</scope>`
			`</dependency>`
		`</dependencies>`
	`</dependencyManagement>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [Tutorial on reading a secret from Azure Key Vault in a Spring Boot application](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by saragluna** [comment]
@KarlErickson could you please add @chenrujun as an assignee?

**Comment by KarlErickson** [comment]
@chenrujun please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by michaelqi793** [comment]
I'll create PR soon

**Comment by michaelqi793** [comment]
[#512 ](https://github.com/MicrosoftDocs/azure-dev-docs/pull/512)
