### ISSUE TITLE
Running Terraform from Azure Cloud shell

### ISSUE THREAD

**Issue by alxy** [MicrosoftDocs/azure-dev-docs#449]
Hi,

I'm following the [linked content page](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell) to run Terraform from Azure cloud shell. The steps I executed are as followed are as followed:

1. Open Cloud Shell (bash mode)
2. Run `az login`. That outputs the following and I was indeed able to go the mentioned website and enter the code:
```
Cloud Shell is automatically authenticated under the initial account signed-in with. Run 'az login' only if you need to use a different account
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ******** to authenticate.
```
3. Run `az account show`. This shows the correct subscription (where I want to deploy my resources) with `isDefault` set to true.
4. Run `terraform init`. Output:
```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```
5. Create `main.tf` file with the following content:
```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.48.0"
    }
  }
}

provider "azurerm" {
  # Configuration options
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}
```
6. Run `terraform plan`. Output:
```bash
$ terraform plan

Warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider



Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/****************************************/providers?api-version=2016-02-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":{"code":"bad_request_102","message":"Required metadata header not specified"}} Endpoint http://localhost:50342/oauth2/token?api-version=2017-09-01&resource=https%3A%2F%2Fmanagement.azure.com%2F

  on main.tf line 10, in provider "azurerm":
  10: provider "azurerm" {
```

Am I doing something wrong here? Running terraform locally against the same subscription works for me, however, I am not able to do so in Azure Cloud console, even though the documentation suggests that this should be possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by alxy** [comment]
Ok, I made an interesting finding. It seems to be an issue with recent `azurerm` provider versions. From my trials it seems to work up until version `2.43.0`, but not for higher versions.

The related changelog item is [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#2440-january-21-2021).

**Comment by TomArcherMsft** [comment]
@alxy Thanks for the feedback. There is a known issue with Cloud Shell and Terraform at the moment. The engineering team is working with HashiCorp to resolve and it should be fixed very soon.

**Comment by TomArcherMsft** [comment]
@alxy We're close to a solution. You can follow the issue at https://github.com/MicrosoftDocs/azure-dev-docs/issues/416. Closing as duplicate.

**Comment by TomArcherMsft** [comment]
@alxy This is now resolved. I added some notes to #416
