### ISSUE TITLE
Getting started with Spring Cloud Functions in Azure: A couple of updates

### ISSUE THREAD

**Issue by mjg123** [MicrosoftDocs/azure-dev-docs#451]
Hi, I'm following this guide after seeing @jdubois at DevNexus. I had to change a couple of small things before it would work:

## start-class
The `<start-class>` is different in the [linked](https://github.com/Azure-Samples/hello-spring-function-azure/blob/master/pom.xml) `pom.xml` than in the docs. The XML snippet in the docs says `com.example.HelloFunction`, which is correct, but in the linked pom it's `com.example.DemoApplication`.  Maybe this is obvious but it doesn't cause any errors until quite near the end of the doc & it's hard to figure out what needs changing at that point.

## test imports
HelloFunctionTest.java code sample has

```
import org.junit.Test;
```

but I think this needs to be

```
import org.junit.jupiter.api.Test;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Getting started with Spring Cloud Function in Azure](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @jdubois
* Microsoft Alias: **judubois**

**Comment by jdubois** [comment]
Thanks @mjg123 !
Indeed, I updated the sample code, and this documentation should be synced up with it.
I haven’t tested yet but both of your comments look correct.
I will update this, but I’ll need a couple of weeks before I have some time for this.

**Comment by jdubois** [comment]
Both issues should be fixed once my PR https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1586 is merged, thanks a lot @mjg123 !
@KarlErickson can you have a look?

**Comment by KarlErickson** [comment]
@jdubois @mjg123 I merged the PR, so I'll close this issue. Thanks!
