### ISSUE TITLE
authentical issue with Azure China

### ISSUE THREAD

**Issue by sanju918** [MicrosoftDocs/azure-dev-docs#453]
[Enter feedback here]
I'm getting follwoing error

```
Traceback (most recent call last):
  File "temp.py", line 22, in <module>
    subscription = next(subscription_client.subscriptions.list())
  File "/Users/s0p05wq/azure/Azure-China/env/lib/python3.7/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/Users/s0p05wq/azure/Azure-China/env/lib/python3.7/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/s0p05wq/azure/Azure-China/env/lib/python3.7/site-packages/azure/mgmt/resource/subscriptions/v2019_11_01/operations/_subscriptions_operations.py", line 221, in internal_paging
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: AuthenticationFailed
Message: Authentication failed.
```
using the example code for azure china

```
import os, adal
from azure.mgmt.resource import SubscriptionClient
from msrestazure.azure_active_directory import AdalAuthentication
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD

# Retrieve the IDs and secret to use with ServicePrincipalCredentials
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]
tenant_id = os.environ["AZURE_TENANT_ID"]
client_id = os.environ["AZURE_CLIENT_ID"]
client_secret = os.environ["AZURE_CLIENT_SECRET"]

LOGIN_ENDPOINT = AZURE_CHINA_CLOUD.endpoints.active_directory
RESOURCE = AZURE_CHINA_CLOUD.endpoints.active_directory_resource_id

context = adal.AuthenticationContext(LOGIN_ENDPOINT + '/' + tenant_id)

credential = AdalAuthentication(context.acquire_token_with_client_credentials,
                                RESOURCE, client_id, client_secret)

subscription_client = SubscriptionClient(credential)

subscription = next(subscription_client.subscriptions.list())
print(subscription.subscription_id)

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036cc96e-fbb8-bced-0a5b-ef6e332264b8
* Version Independent ID: 7b70016c-feb0-7da1-5995-2d1fa8bce9a9
* Content: [How to authenticate Python applications with Azure services](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd)
* Content Source: [articles/python/azure-sdk-authenticate.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-authenticate.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@sanju918 Thanks for your patience. I'm checking into this issue to make sure the code in the documentation is correct. In the meantime, have you tried the code shown in https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-sovereign-domain that uses DefaultAzureCredential?

**Comment by kraigb** [comment]
@sanju918 To follow up, the code is correct in the docs but only for older versions of azure.mgmt.resource (those not using azure.core). When using the current library, you should be using DefaultAzureCredential or another credential/auth method from the azure-identity library (which is the azure.core version).

Accordingly, I'm moving the section of the docs that show adal to a section for deprecated auth methods.
