### ISSUE TITLE
Azure PythonSDK docs badly out of date

### ISSUE THREAD

**Issue by morganbye-ivadolabs** [MicrosoftDocs/azure-dev-docs#454]
Steps 4a and 4b use the `BlobClient` class which is no longer in v12 of the SDK.

This should be updated to likely use:
* BlockBlobService
* PageBlobService

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef952ca-bc5a-ad1a-f793-80e823a666c8
* Version Independent ID: 4747f26a-05e4-8e00-203f-c61e75e83690
* Content: [Use Azure Storage with the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-storage-use?tabs=cmd)
* Content Source: [articles/python/azure-sdk-example-storage-use.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-storage-use.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@morganbye-ivadolabs Thanks for the issue; I'll be updating the article in the next week or two. I appreciate the alert.

**Comment by kraigb** [comment]
Hello again. I validated that the article works as expected with the current versions of the Azure Storage library, which, according to pip freeze, is azure-storage-blob==12.8.0. The BlobkBlobService and PageBlobService classes you mention are not current; they come from older library versions and do not exist in the current libraries.

I'm closing this issue, accordingly, as the docs are up to date. If you still feel a change is necessary, please explain with more details and working sample code that's been verified with current library versions.
