### ISSUE TITLE
Add "Pulumi on Azure" content?

### ISSUE THREAD

**Issue by infin8x** [MicrosoftDocs/azure-dev-docs#455]
👋🏻 hello! We at Pulumi would love to contribute a section for "Pulumi on Azure", similar to the [Terraform on Azure](https://docs.microsoft.com/en-us/azure/developer/terraform/) content. Is that something you would be open to? If so, what's the best way to get started? Should we share an outline? Start a draft PR and invite feedback?

**Comment by TomArcherMsft** [comment]
Hi @infin8x. We had a similar discussion with Joe D. last year. If you'd like to discuss further, email me offline and I'd be happy to discuss.
