### ISSUE TITLE
error on running Acquire a credential object using CLI-based authentication

### ISSUE THREAD

**Issue by windyir** [MicrosoftDocs/azure-dev-docs#456]
# Import the needed credential and management objects from the libraries.
from azure.identity import AzureCliCredential
from azure.mgmt.resource import ResourceManagementClient
import os

# Acquire a credential object using CLI-based authentication.
credential = AzureCliCredential()

# Retrieve subscription ID from environment variable.
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]

# Obtain the management object for resources.
resource_client = ResourceManagementClient(credential, subscription_id)

# Retrieve the list of resource groups
group_list = resource_client.resource_groups.list()

# Show the groups in formatted output
column_width = 40

print("Resource Group".ljust(column_width) + "Location")
print("-" * (column_width * 2))

for group in list(group_list):
    print(f"{group.name:<{column_width}}{group.location}")
###################################################
Traceback (most recent call last):
  File "", line 24, in <module>
    for group in list(group_list):
  File "", line 143, in __next__
    self.advance_page()
  File "", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "", line 512, in internal_paging
    response = self._client.send(request, stream=False, **operation_config)
  File "", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "", line 150, in send
    response = self.next.send(request, **kwargs)
  File "", line 65, in send
    self._creds.signed_session(session)
AttributeError: 'AzureCliCredential' object has no attribute 'signed_session'

**Comment by KarlErickson** [comment]
@kraigb this issue applies to multiple topics under the Examples TOC node, e.g. <https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-resource-group>.

**Comment by kraigb** [comment]
@windyir Can you check what versions of the Azure libraries you're using. The signed_session error occurs when you're using an older version of azure-mgmt-resource (below 15.0.0); that library was updated recently, so if you're using an older version then you'll see this error.

I just tested the code for the resource group examples, e.g. https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-list-resource-groups and https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-resource-group, which are using the following library versions. The code in all cases works as expected.

azure-common==1.1.26
azure-core==1.10.0
azure-identity==1.5.0
azure-mgmt-core==1.2.2
azure-mgmt-resource==15.0.0

Please check your library versions using pip freeze and report back. If you have azure-mgmt-resource below 15.0.0, please update to the newest version.

**Comment by windyir** [comment]
I didn't specify the version in azure-mgmt-resource and now it works Thanks.

**Comment by windyir** [comment]
I didn't specify the version in azure-mgmt-resource and now it works Thanks.

**Comment by kraigb** [comment]
Perfect--thanks for checking and I'm delighted you have it working now.
