### ISSUE TITLE
Outdated Springboot Version 

### ISSUE THREAD

**Issue by irfanazam1** [MicrosoftDocs/azure-dev-docs#457]
Hi

The document mentions to select Springboot version 2.3.3 from the Springboot initializer project. The mentioned version is no longer available on the Springboot initializer page. 

Regards,
Irfan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [Tutorial on reading a secret from Azure Key Vault in a Spring Boot application](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by saragluna** [comment]
@KarlErickson could you please add @chenrujun as an assignee too?

**Comment by KarlErickson** [comment]
@chenrujun please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by chenrujun** [comment]
PR created: https://github.com/MicrosoftDocs/azure-dev-docs/pull/510
