### ISSUE TITLE
Direct link to download Azul Zulu is broken

### ISSUE THREAD

**Issue by ninarn** [MicrosoftDocs/azure-dev-docs#459]
Under "Download the 64-bit Azul Zulu JDK 8" the first link "zulu-8-azure-jdk_8.44.0.11-8.0.242-..." seems to be broken. Nothing happens when I click it. I had to right click and "open in another tab" and then it downloaded the file. This applies to the same links under the three sections Windows, Mac, and Linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733d4a97-401b-afe5-cf02-325e5e7286ef
* Version Independent ID: f31fe3ee-ddba-5da3-e158-0da3c8af8cc7
* Content: [Install the Azul Zulu JDK for Azure and Azure Stack](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-jdk-install)
* Content Source: [articles/java/fundamentals/java-jdk-install.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/fundamentals/java-jdk-install.md)
* Service: **azure-java**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@KarlErickson - Karl, would you please take a look at this issue? Thanks.

**Comment by KarlErickson** [comment]
@ninarn thanks for letting us know about this issue. It appears to be a browser security issue. The link works directly in Edge, but in Chrome it doesn't. We will investigate and update the doc to make this clear.
