### ISSUE TITLE
Configuring Jenkins access to AKS as an issue

### ISSUE THREAD

**Issue by gabriel-ayusso** [MicrosoftDocs/azure-dev-docs#460]
On step [Configure Access](https://github.com/MicrosoftDocs/azure-dev-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%2015c8677e-3fcd-56c0-fa71-64d758a02ca8%0A*%20Version%20Independent%20ID%3A%20ffb63abe-0c37-4c6c-0560-3e2df33e7e5b%0A*%20Content%3A%20%5BTutorial%20-%20Deploy%20from%20GitHub%20to%20Azure%20Kubernetes%20Service%20using%20Jenkins%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdeveloper%2Fjenkins%2Fdeploy-from-github-to-aks)%0A*%20Content%20Source%3A%20%5Barticles%2Fjenkins%2Fdeploy-from-github-to-aks.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-dev-docs%2Fblob%2Fmaster%2Farticles%2Fjenkins%2Fdeploy-from-github-to-aks.md)%0A*%20Service%3A%20**jenkins**%0A*%20GitHub%20Login%3A%20%40TomArcherMsft%0A*%20Microsoft%20Alias%3A%20**tarcher**) it says to copy `~/.kube/config` to `/var/lib/jenkins/config` but it not worked for me. Instead I need to copy the file to `/var/lib/jenkins/.kube/` folder to give Jenkins access on AKS.

Hope this helps someone. :-)

Bests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c8677e-3fcd-56c0-fa71-64d758a02ca8
* Version Independent ID: ffb63abe-0c37-4c6c-0560-3e2df33e7e5b
* Content: [Tutorial - Deploy from GitHub to Azure Kubernetes Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-aks)
* Content Source: [articles/jenkins/deploy-from-github-to-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-aks.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hi @gabriel-ayusso,

I've made the necessary changes to the article and submited a PR.

Thanks so much for your contribution!
