### ISSUE TITLE
terraform plan -out out.plan returns Invalid function argument 

### ISSUE THREAD

**Issue by Lroca88** [MicrosoftDocs/azure-dev-docs#462]
[Enter feedback here]
After following step by step the tutorial I encounter an error when running `terraform plan -out out.plan`.
![image](https://user-images.githubusercontent.com/5395468/110714994-660a5300-81d2-11eb-8874-49edd627950c.png)

The reason is there is no such ~/.ssh/id_rsa.pub file.  Actually there is no .ssh folder in the Cloud Shell .
![image](https://user-images.githubusercontent.com/5395468/110715240-d913c980-81d2-11eb-9752-216a9bd7545e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Lroca88 The error seems to indicate that there is no SSH public key file found in your home directory's .ssh directory. Have you created an SSH pair and stored it there for Terraform to pick up?

**Comment by Lroca88** [comment]
No I didn't, I was just replicating the steps from the tutorial. I think the section about copying a public key is missing.

**Comment by TomArcherMsft** [comment]
@Lroca88 You're correct. The article should explain that an SSH key is required and point to information on how to create one. I'll get that fixed so that it's more clear what's needed to run the sample.

**Comment by TomArcherMsft** [comment]
@Lroca88 This was fixed some time ago, but I neglected to close the issue.
