### ISSUE TITLE
 Error: "features": required field is not set

### ISSUE THREAD

**Issue by abhijeetuk** [MicrosoftDocs/azure-dev-docs#463]
Need to update the document as we get error as 
Error: "features": required field is not set
For new learners, we have tough time to follow this document as we are not able to create resource in Azure via Visual Studio code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14080c3b-027f-93e1-fd0f-4bea971f51b0
* Version Independent ID: 5894d6ec-4347-153c-fa9a-203d41275153
* Content: [Configure the Azure Terraform Visual Studio Code extension](https://docs.microsoft.com/en-us/azure/developer/terraform/configure-vs-code-extension-for-terraform)
* Content Source: [articles/terraform/configure-vs-code-extension-for-terraform.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/configure-vs-code-extension-for-terraform.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@abhijeetuk Thank you for your feedback. I believe you're referring to steps to install/configure Terraform, right? If so, this content has been rewritten and published yesterday. Please let me know if you continue to encounter problems and I will investigate.
