### ISSUE TITLE
Service Principal "az login" example command contains wrong placeholder

### ISSUE THREAD

**Issue by awkimball** [MicrosoftDocs/azure-dev-docs#464]
Hi all,

Under the section "Authenticate via Azure Service Principal" I see the command to login to the azure cli: 

```
az login --service-principal -u <service_principal_name> -p "<service_principal_password>" --tenant "<service_principal_tenant>"
```

and it suggests to use the service principal name/<azure_principal_name> for the `-u` argument. Unfortunately, in my experience using the service principal's name does not work. When I use the name, I get a 400 unauthorized error. 

Instead, it seems to require the service principal's appId. Maybe a better placeholder for this line would be `<azure_principal_appId>` instead of `<azure_principal_name>`? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@awkimball Thank you for the feedback. These articles (the Get Started content and the Authentication steps) have been rewritten. Please let me know if you see any continued or new issues. Thanks again!
