### ISSUE TITLE
This article did not describe the cosmosdb configuration class setup. 

### ISSUE THREAD

**Issue by gitbingsun** [MicrosoftDocs/azure-dev-docs#469]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e3106a-5816-3c78-7b7d-80de140403b4
* Version Independent ID: 0d963e32-ae56-09dc-8774-87a241fc8590
* Content: [How to use the Spring Boot Starter with the Azure Cosmos DB SQL API](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md)
* Service: **cosmos-db**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by saragluna** [comment]
@KarlErickson could you please assign this issue to @backwind1233 too?

**Comment by KarlErickson** [comment]
@backwind1233 please coordinate with @lastnameholiu who has also been looking at these issues. Thanks!

**Comment by backwind1233** [comment]
@gitbingsun I am looking at this issue , but I am not sure my understanding is correct, can you explain it a little bit?

**Comment by backwind1233** [comment]
Linked PR [#1860](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1860)
