### ISSUE TITLE
applicationinsights-spring-boot-starter 1.1.1 stopped working

### ISSUE THREAD

**Issue by petetian** [MicrosoftDocs/azure-dev-docs#47]
applicationinsights-spring-boot-starter 1.1.1 is way too old. I had a client using this example, and the telemetry data end up nowhere. Better update to 2.5.1, the latest version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0847a17d-8f32-d22e-e8f9-e2604c8d34bb
* Version Independent ID: d0056593-615e-0147-fa0e-9633ad590b66
* Content: [Configure a Spring Boot Initializer app to use Azure Application Insights SpringBoot Starter](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-java-applicationinsights)
* Content Source: [java/spring-framework/configure-spring-boot-java-applicationinsights.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-java-applicationinsights.md)
* Service: **azure-monitor**
* GitHub Login: @dhaval24
* Microsoft Alias: **dhdoshi**

**Comment by bmitchell287** [comment]
@seanli1988 - Hello Sean could you please provide feedback or help route to the appropriate contact?

**Comment by KarlErickson** [comment]
Topic has been removed and redirected to current recommended approach.
