### ISSUE TITLE
Spring boot Azure Function Debug steps

### ISSUE THREAD

**Issue by debinaik** [MicrosoftDocs/azure-dev-docs#472]
I was going through the steps by below link to setup spring boot azure function. But I could not find the command to debug the spring boot azure function locally. I have tried few options to debug locally but IntelliJ starts encountering runtime error.Please provide the correct steps to debug locally.

 https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure

**Comment by saragluna** [comment]
@KarlErickson could you please assign this issue to me @saragluna?

**Comment by saragluna** [comment]
@debinaik 

You could follow below steps to debug locally:
1. Add `-DenableDebug` when run `mvn azure-functions:run` --> `mvn azure-functions:run -DenableDebug`
2. If you're using Intellij IDEA, [create](https://www.jetbrains.com/help/idea/tutorial-remote-debug.html#63ca70c5) a `Remote JVM Debug` run configuration to attach and then you could debug locally.

Please let me know if you have further questions.

**Comment by KarlErickson** [comment]
@saragluna will you be creating a PR to add this content to the article? Thanks.
