### ISSUE TITLE
ErrorPAge

### ISSUE THREAD

**Issue by riyazega** [MicrosoftDocs/azure-dev-docs#474]
[Enter feedback here]
I followed following link to implement Azure AD on Spring Boot Microservices

https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory

But after login I am getting following error message.
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'f1c3aed3-45dc-4867-88c5-215c25137390'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@riyazega thanks for the feedback! I'm sorry that you're encountering an error. To be sure I understand, are you referring to the log in described in the section [Build and test your app](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?source=docs#build-and-test-your-app), using the password described in step 5 of the section [Add a user account to your directory, and add that account to a group](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?source=docs#add-a-user-account-to-your-directory-and-add-that-account-to-a-group)?

**Comment by saragluna** [comment]
@KarlErickson could you please add @chenrujun as an assignee too?

**Comment by riyazega** [comment]
Issue has been solved .
Thanks
