### ISSUE TITLE
Clarity on Redirect URIs in Spring Boot Starter for Azure AD

### ISSUE THREAD

**Issue by BillyBolton** [MicrosoftDocs/azure-dev-docs#476]
Following the [Tutorial: Secure a Java web app using the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory#configure-and-compile-your-app) is not successful. From comparing the 
[Azure AD Spring Boot Starter client library for Java](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-active-directory#accessing-a-web-application) tutorial, it seems the Redirect URIs should not have `azure` at the end, such as in the first referenced tutorial. 

There are many open issues related to absent RedirectURIs. Perhaps this is why. It's also very confusing that there isn't a central spot of tutorials available -- I'm not sure if some are outdated, have bugs, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory#configure-and-compile-your-app)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by BillyBolton** [comment]
Duplicated issue, original is here: https://github.com/MicrosoftDocs/azure-dev-docs/issues/475

I'd like to highlight still that there should be improvement in where to find tutorials. All that I have tried thus far are not stable.

**Comment by KarlErickson** [comment]
@BillyBolton thanks for the suggestion. We have recently added a [learning resources](https://docs.microsoft.com/en-us/azure/developer/java/learning-resources/) section that we are planning to extend over time. This may be a good location to collect the tutorials that are spread throughout the service documentation. I will bring this up to our internal stakeholders.
