### ISSUE TITLE
issue when running ansible-playbook create_rg.yml to test the installation

### ISSUE THREAD

**Issue by neosdutertre** [MicrosoftDocs/azure-dev-docs#478]
[Enter feedback here]
Hi,
when following the procedure, the playbook test ends up with the below message, what's wrong ? thanks,
```
$ ansible-playbook test_create_rg.yml --extra-vars "name=ncms4test location=northeurope"
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Found variable using reserved name: name

PLAY [localhost] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************
ok: [localhost]

TASK [Creating resource group - "ncms4test"] ********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'urllib3.packages.six'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on ncms4jumpbox's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP ******************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ac6b7d-76dc-189b-4ce7-d5f2b4043162
* Version Independent ID: 5982bd9f-1339-3a62-75a4-35161e88368e
* Content: [Quickstart - Configure Ansible using Azure CLI](https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=ansible)
* Content Source: [articles/ansible/install-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/install-on-linux-vm.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by neosdutertre** [comment]
while digging into the issue, I found that six is installed in /usr/local/lib/python3.6/site-packages/ and urllib3 is searching for it in /usr/lib/python3.6/site-packages ...

**Comment by Duffney** [comment]
Hi @neosdutertre,

I appreciate you raising the issue, can you tell me which version of Ansible you're using and if you're using the azurerm modules or the azcollection?

Thanks!

**Comment by neosdutertre** [comment]
Hi @Duffney I did exactly as the documentation indicates. So i believe this is azcollection (installed with ansible-galaxy).

**Comment by Duffney** [comment]
Interesting, I'm in the process of updating the install and configure docs to include 2.9 and 2.10 changes.

I'll go through the tutorial and attempt to replicate the error and get back to you.

Have a wonderful day! :)

**Comment by Duffney** [comment]
Hey @neosdutertre 

Walking through the article I was able to successfully create a resource group with the test playbook at the end. Looking at the error my best guess is that the Azure collection dependencies didn't get installed properly.

Please run the following install commands to re-install the Azure collection:

```
# Install Ansible.
pip3 install ansible[azure]

# Install Ansible modules and plugins for interacting with Azure.
ansible-galaxy collection install azure.azcollection

# Install required modules for Ansible on Azure
wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt

# Install Ansible modules
sudo pip3 install -r requirements-azure.txt

```

I've found using docker containers to be particularly useful in troubleshooting installs. 

If you'd like here are a [few examples](https://github.com/Duffney/ansible-azure-samples/tree/main/ansible-container) I've been working on. 

Please let me know if this helps you resolve the issue.

Best of luck! :)

**Comment by Duffney** [comment]
Hey @neosdutertre 

Walking through the article I was able to successfully create a resource group with the test playbook at the end. Looking at the error my best guess is that the Azure collection dependencies didn't get installed properly.

Please run the following install commands to re-install the Azure collection:

```
# Install Ansible.
pip3 install ansible[azure]

# Install Ansible modules and plugins for interacting with Azure.
ansible-galaxy collection install azure.azcollection

# Install required modules for Ansible on Azure
wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt

# Install Ansible modules
sudo pip3 install -r requirements-azure.txt

```

I've found using docker containers to be particularly useful in troubleshooting installs. 

If you'd like here are a [few examples ](https://github.com/Duffney/ansible-azure-samples/tree/main/ansible-container) I've been working on. 



Please let me know if this helps you resolve the issue.

Best of luck! :)

**Comment by neosdutertre** [comment]
Thanks a lot for digging into the details; I will attempt a new test asap, and will try to provide better clues to what happens (whether it would happen again) ! 
have a great day

**Comment by Duffney** [comment]
Most welcome, I'll close the issue for now as I can't replicate it exactly following the doc. But please do keep me updated, I'm happy to help if I can. :)
