### ISSUE TITLE
Small bug in code snippet

### ISSUE THREAD

**Issue by Iuzuz** [MicrosoftDocs/azure-dev-docs#479]
Hello!

This page has a small bug. The following code line is wrong:

`SpringApplication.run(HelloFunction.class, args);`

Instead, it should be:

`SpringApplication.run(DemoApplication.class, args);`

Regards,
Iuzuz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Getting started with Spring Cloud Function in Azure](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @jdubois
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
@Iuzuz - thanks! Fixed.
