### ISSUE TITLE
Where shall I put this file "terraform_azure.tf"

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/azure-dev-docs#482]
Where shall I put this file "terraform_azure.tf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Create a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#complete-terraform-script)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@kind03 The file name and location are user-specific. You could put in pretty much any directory from which you want to call the Terraform commands.

**Comment by kind03** [comment]
Thanks!
