### ISSUE TITLE
Give Examples On Configuring Storage Accounts In Different Ways 

### ISSUE THREAD

**Issue by opticyclic** [MicrosoftDocs/azure-dev-docs#483]
The page says:
> The storage account can be created with the Azure portal, PowerShell, the Azure CLI, or Terraform itself. 

However, there are only examples of Azure CLI and Terraform.

Add examples on doing it with the portal as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Tutorial - Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @opticyclic,

Great callout. I've removed the verbiage that calls out the portal specific instructions to improve clarity. While the operation can be handled within the Azure portal the article is focused on automating those actions through command-line tools and Terraform.

Changes to the article will be reflected after the PR is merged.

Thank you for your feedback!
