### ISSUE TITLE
Terraform Example Is Incomplete

### ISSUE THREAD

**Issue by opticyclic** [MicrosoftDocs/azure-dev-docs#484]
The page says:

> To configure Terraform to use the back end, the following steps need to be done:
>    *  Include a backend configuration block with a type of azurerm.
>    * Add a storage_account_name value to the configuration block.
>    * Add a container_name value to the configuration block.
>    * Add a key value to the configuration block.

The terraform example only creates a resource group though.

You should also point out that the storage account name needs to be unique across the whole of Azure.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/error-storage-account-name

It is implied in the az cli example:

    STORAGE_ACCOUNT_NAME=tstate$RANDOM

but you don't explicitly say it and this will need to be in the terraform example.   
Maybe with https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/string

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Tutorial - Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hi @opticyclic,

I've updated the article to point out that Azure storage account names must be globally unique. Within the call out I also put a link to the troubleshooting document you mentioned. :)

Currently the article shows how to configure the storage account with Azure CLI and then Terraform uses that storage account as its backend to create a second resource group. To improve coverage, I also added tabs for configuring the storage account with Azure PowerShell and Terraform.

Changes will be reflected once the PR is merged.

Thank you for your awesome feedback!
