### ISSUE TITLE
azure.storage.blob SDK example does not work

### ISSUE THREAD

**Issue by pgombar** [MicrosoftDocs/azure-dev-docs#485]
Hi,

Under the [Set Logging Levels](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-logging#set-logging-levels) section, an example is given to change the log level for `azure.storage.blob` logger. However, this does not work since that specific library logs its HTTP requests in the `azure` namespace, not `azure.storage.blob` and the customer would not see a change in log levels if they try to change `azure.storage.blob`.

The correct way to do this would be to either
1) Specifically disable logging from HTTP request client by using `logging.getLogger('azure.core.pipeline.policies.http_logging_policy')`.
(Reference [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/core/azure-core/azure/core/pipeline/policies/_universal.py#L377-L379).)
2) Constraining logs from `azure` namespace instead.

Opening this issue because we had a customer open a ticket for Azure Functions saying they followed the instructions outlined here for reducing logs from storage SDK, but it didn't work for them. A suggestion would be to either expand the current instructions with details given above or use a different example in the doc. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc90337e-c8fd-23fb-b5e6-e20db3538497
* Version Independent ID: 288a4523-e630-9683-5ce4-34dbc6cd7812
* Content: [Configure logging in the Azure libraries for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-logging)
* Content Source: [articles/python/azure-sdk-logging.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-logging.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@pgombar Thanks for this! I'll put it in my backlog to make appropriate revisions.
