### ISSUE TITLE
Update instructions to reflect change in branch name

### ISSUE THREAD

**Issue by peterdongan** [MicrosoftDocs/azure-dev-docs#489]
Step 3 in the **Create your first job** section instructs you to link to this repo: [https://github.com/spring-guides/gs-spring-boot.git](https://github.com/spring-guides/gs-spring-boot.git)

The screenshot shows the branch specifier as `*/master`. However the repo recently started using a "main" branch instead of a "master" one, so the job now fails if the branch specifier is not updated or removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Quickstart - Configure Jenkins using Azure CLI](https://docs.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
@peterdongan I'll get the screenshot updated to reflect the branch name change, thank you. :)

**Comment by Duffney** [comment]
Pull request has been submitted. The update will be live 24 hours after the PR is accepted.

Thank you again @peterdongan for filing the issue. :)
