### ISSUE TITLE
Issue while deploying Spring Boot app using the Fabric8 Maven Plugin 

### ISSUE THREAD

**Issue by ni3git** [MicrosoftDocs/azure-dev-docs#49]
I am trying to deploy my Spring Boot app using the Fabric8 Maven Plugin by following instructions available at https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin. I am using my existing AKS Cluster. Springboot app is dockerized 
I have added below entry into into my settings.xml in .m2 directory:
   <server>
      <id>copoacrregistry.azurecr.io</id>
      <username>copoAcrRegistry</username>
      <password>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx</password>
   </server>

Here are the required entries added to the pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.2.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>company.copo</groupId>
	<artifactId>copo-orgnization-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>copo-orgnization-service</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<azure.version>2.2.0</azure.version>
		<docker.image.prefix>copoacrregistry.azurecr.io</docker.image.prefix>
	    <jib-maven-plugin.version>1.7.0</jib-maven-plugin.version>
	    <java.version>1.8</java.version>
	    <maven.test.skip>true</maven.test.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
	            <exclusion>
	                <groupId>org.springframework.boot</groupId>
	                <artifactId>spring-boot-starter-logging</artifactId>
	            </exclusion>
	        </exclusions>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-active-directory-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage-spring-boot-starter</artifactId>
		</dependency>
	    <dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-log4j2</artifactId>
	    </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
		   <groupId>org.springframework.security</groupId>
		   <artifactId>spring-security-oauth2-client</artifactId>
		</dependency>
		<dependency>
		   <groupId>org.springframework.security</groupId>
		   <artifactId>spring-security-oauth2-jose</artifactId>
		</dependency>
		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
        </dependency>
        <dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>applicationinsights-spring-boot-starter</artifactId>
		    <version>1.1.1</version>
		</dependency>
		<dependency>
	        <groupId>com.microsoft.azure</groupId>
	        <artifactId>applicationinsights-logging-log4j2</artifactId>
	        <version>2.1.1</version>
	    </dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>${azure.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
			  <artifactId>jib-maven-plugin</artifactId>
			  <groupId>com.google.cloud.tools</groupId>
			  <version>${jib-maven-plugin.version}</version>
			  <configuration>
			     <from>
			         <image>openjdk:8-jre-alpine</image>
			     </from>
			     <to>
			         <image>${docker.image.prefix}/${project.artifactId}</image>
			     </to>
			  </configuration>
			</plugin>
			<plugin>
			  <groupId>com.spotify</groupId>
			  <artifactId>dockerfile-maven-plugin</artifactId>
			  <version>1.3.4</version>
			  <configuration>
			    <repository>${docker.image.prefix}/${project.artifactId}</repository>
			    <serverId>${docker.image.prefix}</serverId>
			    <registryUrl>https://${docker.image.prefix}</registryUrl>
			  </configuration>
			</plugin>
			<plugin>
  			  <groupId>io.fabric8</groupId>
			  <artifactId>fabric8-maven-plugin</artifactId>
			  <version>3.5.30</version>
			  <configuration>
			    <ignoreServices>false</ignoreServices>
			    <registry>${docker.image.prefix}</registry>
			  </configuration>
			</plugin>
		</plugins>
	</build>
	
	<profiles>
        <profile>
            <id>sql</id>
            <properties>
                <database.platform>sqlserver</database.platform>
            </properties>
            <dependencies>
                <dependency>
                    <groupId>com.microsoft.sqlserver</groupId>
                    <artifactId>mssql-jdbc</artifactId>
                    <scope>runtime</scope>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
</project>

When I run “mvn package dockerfile:build -DpushImage” command it creates docker image locally (I see it when i run 'docker image ls' command in cmd) but do not push it to azure container registry. I am expecting it to be pushing image to azure acr. Not sure if I am missing anything. Any help/pointers will be of great help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76b6b729-3a37-ab90-5126-37af758e8ff3
* Version Independent ID: 41665aaf-a99b-1fa8-7e7d-7a7d992133ac
* Content: [Deploy a Spring Boot app using the Fabric8 Maven Plugin](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin#feedback)
* Content Source: [java/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@seanli1988 - Sean could you please provide guidance for this issue or route to the appropriate contact?

**Comment by KarlErickson** [comment]
We are no longer prioritizing Fabric8 content and have removed this topic, so I'm closing the issue.
