### ISSUE TITLE
terraform plan fails

### ISSUE THREAD

**Issue by limingr** [MicrosoftDocs/azure-dev-docs#491]
Followed the  steps exactly, it fails with error.
(1) Link https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret mentions 

$ export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_CLIENT_SECRET="00000000-0000-0000-0000-000000000000"
$ export ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_TENANT_ID="00000000-0000-0000-0000-000000000000"

How do you do the export in powershell?

(2) It does not look like the part "Alternatively " is complete.  I cannot follow the instructions.

Thanks

PS D:\Tests\terraform> terraform plan
╷
│ Error: Error building AzureRM Client: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
│
│ To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
│ auth method - instructions for which can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
│
│ Alternatively you can authenticate using the Azure CLI by using a User Account.
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on 1stTerraform.tf line 9, in provider "azurerm":
│    9: provider "azurerm" {

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by limingr** [comment]
I found a workaround

**Comment by TomArcherMsft** [comment]
@limingr That's actually HashiCorp's documentation. What was your workaround?
