### ISSUE TITLE
Excellent doc page

### ISSUE THREAD

**Issue by RussFerns** [MicrosoftDocs/azure-dev-docs#493]
Excellent doc page and video - that's all.  
[shouldn't always come here to complain :)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6758e597-965a-92c5-2fd3-5bcc5702deac
* Version Independent ID: d0619375-0c8e-c2d4-f059-b1ae17fe7c52
* Content: [Deploy Docker containers to Azure App Service from Visual Studio Code](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/tutorial-vscode-docker-node/tutorial-vscode-docker-node-01?tabs=bash)
* Content Source: [articles/javascript/tutorial/tutorial-vscode-docker-node/tutorial-vscode-docker-node-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/tutorial-vscode-docker-node/tutorial-vscode-docker-node-01.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by KarlErickson** [comment]
@RussFerns thanks! CC @diberry
