### ISSUE TITLE
Suggestion - Please add a section / directive for adding Application Insights to spring boot

### ISSUE THREAD

**Issue by carolga** [MicrosoftDocs/azure-dev-docs#494]
[Enter feedback here]
Hello!  Is there a way to also add a directive for wiring Application Insights?  This is lacking and we are getting cases about it.

Thanks!
-cg :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0fb1c0-486c-bbf3-cbc1-2c1dda60e6ba
* Version Independent ID: 599225e9-1ecc-22c1-5d81-f200df9f74da
* Content: [Spring Boot Starters for Azure](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure)
* Content Source: [articles/java/spring-framework/spring-boot-starters-for-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/spring-boot-starters-for-azure.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by saragluna** [comment]
@KarlErickson could you please add me as an assignee too?

**Comment by KarlErickson** [comment]
@saragluna thanks!

**Comment by carolga** [comment]
Hello!

Just wanted to point out that the link is returning a 404.

Is this the link?
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#configuration-options

Thanks!
-cg 😊

Carol Garcha
Support Escalation Engineer
Azure Rapid Response – Web Apps
+1 469.775.0142
Working Hours: M-F 8:00 am-5:00 pm US CT
Need help outside of my working hours?
Locate an engineer: ***@***.******@***.***>
Manager: Gail Heimann / ***@***.******@***.***>
***@***.***D7570E.4DB44F20]

-------------------------------------------- 😊 --------------------------------------------
The Ultimate Guide to Running Healthy Apps in the Cloud
https://azure.github.io/AppService/2020/05/15/Robust-Apps-for-the-cloud.html
-------------------------------------------- 😊 --------------------------------------------
