### ISSUE TITLE
Missing info about NewAuthorizerFromCLI for AuthN using 'az cli'

### ISSUE THREAD

**Issue by michalswi** [MicrosoftDocs/azure-dev-docs#496]
I think it's worth to be mentioned here that you can authenticate by requesting a token from the Azure CLI. I am pointing to this part:

https://github.com/Azure/go-autorest/blob/master/autorest/azure/auth/auth.go#L276

```
func NewAuthorizerFromCLI() (autorest.Authorizer, error) {
	settings, err := GetSettingsFromEnvironment()
	if err != nil {
		return nil, err
	}
(...)
```

You have to log in in to Azure via "az login", and it will use the CLI's currently logged in identity.

```
import (
	"log"
	"github.com/Azure/go-autorest/autorest/azure/auth"
)

func main() {
authorizer, err := auth.NewAuthorizerFromCLI()
	if err != nil {
		log.Fatalf("AuthN failed: %s", err)
	}
(...)
```

Thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496addbb-39f0-09cd-4fc9-c5786bb90495
* Version Independent ID: 53cd2418-bd7b-b469-8d34-f9f2f7fd1b8f
* Content: [Authentication with the Azure SDK for Go](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization)
* Content Source: [articles/go/azure-sdk-authorization.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/go/azure-sdk-authorization.md)
* Service: **azure**
* GitHub Login: @barbkess
* Microsoft Alias: **barbkess**

**Comment by diberry** [comment]
@scottaddie Is this for you - should we make you the owner of Go content via the [DocFx[(https://github.com/MicrosoftDocs/azure-dev-docs-pr/blob/master/articles/docfx.json#L78) file
