### ISSUE TITLE
Public vs Private Access Storage Account

### ISSUE THREAD

**Issue by garthoid** [MicrosoftDocs/azure-dev-docs#499]
Thanks for this article but I noticed that it does not warn the reader that it requires the storage account to have public access. This may be sub-optimal to some users who do not wish their storage accounts to have a public endpoint due to policy, paranoia, or just best practices regardless of RBAC/TLS. So I suggest the following:

1. Warn readers that the steps in these instructions require a public internet accessible storage.
2. Provide a link to a very useful set of instruction outlining how to use a storage account with Private Link via an Azure DevOps pipeline for state file storage(do you have one? If not can you write it? If so, can you tell me where it is?)

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Tutorial - Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @garthoid,

Excellent point and suggestion. I've added a callout to the article indicating that it creates the storage account with pubic. And have begun researching your suggested topic to see if it's feasible to configure the backend without public access and or to use private link.

Changes to the article will take effect once the PR is merged.

Thank you for your detailed feedback and suggestion!

**Comment by lorenzmeyer77** [comment]
@Duffney  Is there now a way to use a private storage account as backend for terraform? Is it somewhere documented? I could not find it.

**Comment by garthoid** [comment]
@lorenzmeyer77 I faced the same challenge you now face and I had to piece together information from different sources. Although this was recorded in August 2021 and things change quickly in the cloud, you may still find it useful.

https://youtu.be/_LgihYlhzOk
