### ISSUE TITLE
Azure Function NodeJs debugging in visual studio code doesn't seem to work

### ISSUE THREAD

**Issue by JljHook** [MicrosoftDocs/azure-dev-docs#50]
npm WARN saveError ENOENT: no such file or directory, open 'C:\package.json'
npm WARN saveError EPERM: operation not permitted, open 'C:\package-lock.json.107866002'
npm WARN enoent ENOENT: no such file or directory, open 'C:\package.json'
npm WARN !invalid#2 No description
npm WARN !invalid#2 No repository field.
npm WARN !invalid#2 No README data
npm WARN !invalid#2 No license field.

up to date in 0.468s
found 0 vulnerabilities

Terminal will be reused by tasks, press any key to close it.

&gt; Executing task: func host start &lt;

Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca06dae8-9f56-748a-877e-d5e23f79eddc
* Version Independent ID: 05f0d483-4026-2b14-74de-5040ffb55e21
* Content: [Run the Azure Functions application locally in Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-03#feedback)
* Content Source: [javascript/tutorial-vscode-serverless-node-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-serverless-node-03.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Hi @JljHook, thanks for filing this issue. From the looks of the output, it appears that you're trying to start the function in the c:\ root folder instead of the project folder. That suggests that in step 2, https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-02, you didn't start VS Code within a subfolder created for the project, and instead launched it from c:\. Can you verify?

**Comment by JljHook** [comment]
Hi,
I started Vsc in the project folder with code. Command. I tried to change
folder to correct one from terminal as well.

**Comment by kraigb** [comment]
In this case it seems like you may have a configuration issue more to do with VS Code and/or how the functions project is set up. Can you follow up by filing an issue with the engineering team on https://github.com/microsoft/vscode-azurefunctions, which is the repo for the VS Code Functions extension that's driving the process? That is, I don't think there's an immediate documentation issue here, which is what I handle in this present repo, in which case I'll close this issue. However, when you open the issue on vscode-azurefunctions, please reference this one, and when you find out more from the engineering team, do report back. Thanks.
