### ISSUE TITLE
Change Terraform output command 

### ISSUE THREAD

**Issue by sri53** [MicrosoftDocs/azure-dev-docs#500]
[Enter feedback here]
When I use  the below command. It will append the EOT in starting and ending of the file.
`echo "$(terraform output kube_config)" > ./azurek8s `

So when I run the get nodes command its not working.
`kubectl get nodes`
error: error loading config file "./azurek8s": yaml: line 2: mapping values are not allowed in this contex

Solution:
Change the command like below
`echo "$(terraform output -raw kube_config)" > ./azurek8s`

About command will write the raw output to the azurek8s file

```
 terraform version
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.58.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sri53 Thanks for the feedback. This article has been updated and will publish later today (PST).
