### ISSUE TITLE
Code Example error

### ISSUE THREAD

**Issue by tekgnu** [MicrosoftDocs/azure-dev-docs#505]
The line for authenticating using the AzureCliCredential is written:
subscription_id = os.environ["AZURE_SUBSCRIPTION_ID"]  

This should be: 
subscription_id = os.environ["AZ_SUBSCRIPTION_ID"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cf9ee4a-da91-9fcf-5f87-63672ecfc30c
* Version Independent ID: a4e01885-e638-59b3-698c-6123b25b6260
* Content: [Provision a resource group using the Azure libraries for Python](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-example-resource-group)
* Content Source: [articles/python/azure-sdk-example-resource-group.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/azure-sdk-example-resource-group.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@tekgnu Thanks for filing this issue. For this particular article, AZURE_SUBSCRIPTION_ID is coming from the configuration described in the prerequisite article, https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=cmd. 

Where would the AZ_SUBSCRIPTION_ID be coming from? I don't know of any tool that creates this automatically, and I'm not aware that the Azure CLI utilizes it. Did I miss something? Please clarify?

In the end, the code can use whatever environment variable you want to set, as it's under your control.

**Comment by kraigb** [comment]
@tekgnu Because the article is correct so far as I know, I'm closing this issue. If you have any comment or reply to my previous questions, please reopen.
