### ISSUE TITLE
Send push notifications deprecated function call

### ISSUE THREAD

**Issue by nicholasfulton** [MicrosoftDocs/azure-dev-docs#506]
Step 12 of the Android native project section contains a code snippet which uses an obsolete method.
Current code:
if (DeviceInstallationService.NotificationsSupported)
{
    FirebaseInstanceId.GetInstance(Firebase.FirebaseApp.Instance)
        .GetInstanceId()
        .AddOnSuccessListener(this);
}

Looking at references for the Java libraries, it appears this is the C#-adapted best way to complete this section.
if (DeviceInstallationService.NotificationsSupported)
{
    FirebaseInstallations.Instance
        .GetToken(true).AddOnSuccessListener(this);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#configure-the-native-ios-project-for-push-notifications)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by nielscup** [comment]
It would be nice to know which package versions you used in the tutorials because it is not working with the latest packages ` Xamarin.Firebase.Messaging`

**Comment by leonardbarbu** [comment]
On the latest package versions, the following calls are removed and now are producing errors.
```
FirebaseInstanceId.GetInstance(Firebase.FirebaseApp.Instance)
.GetInstanceId()
.AddOnSuccessListener(this);
```

**Comment by hugomr89** [comment]
@leonardbarbu  I know its been almost a month but I just ran into the same issue, like nielscup mentioned replace the code in the sample for:

if (DeviceInstallationService.NotificationsSupported)
{
FirebaseInstallations.Instance
.GetToken(true).AddOnSuccessListener(this);
}

also, add the reference to the nuget package:

**Xamarin.Google.Dagger.**

I'vejust tested it and its working.

**Comment by Raystorm7** [comment]
Hi @hugomr89 ,
I have used the code you provided but this error is trigger now:
![image](https://user-images.githubusercontent.com/7420345/150963389-f61f4706-f0a6-45c9-9dfc-49710110b562.png)

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
