### ISSUE TITLE
No ansible[azure] anymore

### ISSUE THREAD

**Issue by kohtala** [MicrosoftDocs/azure-dev-docs#509]
There has been no `ansible[azure]` for a year now.

```
$ pip install ansible[azure]
Collecting ansible[azure]
  Downloading ansible-3.4.0.tar.gz (31.9 MB)
     |████████████████████████████████| 31.9 MB 24.5 MB/s
  WARNING: ansible 3.4.0 does not provide the extra 'azure'
```

The `requirements-azure.txt` contains a bunch of pinned versions. That may be fine for a CI development environment, but if you need to actually use it and have anything else in your environment, that is asking for version conflict. Is there somewhere some more permitting dependency requirements? Surely it can not be that the version must match down to patch level.

The dependencies are also very old as many packages are behind 10 major versions. I'll create another issue on that, but mention it as it shows the need for another `requirements.txt` file.

```
$ pip install -r https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
...
$ pip list --outdated
Package                           Version Latest Type
--------------------------------- ------- ------ -----
azure-cli-core                    2.11.1  2.23.0 wheel
azure-cli-nspkg                   3.0.2   3.0.4  wheel
azure-common                      1.1.11  1.1.27 wheel
azure-keyvault                    1.0.0a1 4.1.0  wheel
azure-mgmt-authorization          0.51.1  1.0.0  wheel
azure-mgmt-automation             0.1.1   1.0.0  wheel
azure-mgmt-batch                  5.0.1   15.0.0 wheel
azure-mgmt-cdn                    3.0.0   11.0.0 wheel
azure-mgmt-compute                10.0.0  20.0.0 wheel
azure-mgmt-containerinstance      1.4.0   7.0.0  wheel
azure-mgmt-containerregistry      2.0.0   2.8.0  wheel
azure-mgmt-containerservice       9.1.0   15.1.0 wheel
azure-mgmt-core                   1.2.0   1.2.2  wheel
azure-mgmt-cosmosdb               0.5.2   6.3.0  wheel
azure-mgmt-devtestlabs            3.0.0   9.0.0  wheel
azure-mgmt-dns                    2.1.0   8.0.0  wheel
azure-mgmt-hdinsight              0.1.0   7.0.0  wheel
azure-mgmt-iothub                 0.7.0   2.0.0  wheel
azure-mgmt-keyvault               1.1.0   9.0.0  wheel
azure-mgmt-loganalytics           1.0.0   10.0.0 wheel
azure-mgmt-managedservices        1.0.0   6.0.0  wheel
azure-mgmt-marketplaceordering    0.1.0   1.1.0  wheel
azure-mgmt-monitor                0.5.2   2.0.0  wheel
azure-mgmt-network                12.0.0  19.0.0 wheel
azure-mgmt-nspkg                  2.0.0   3.0.2  wheel
azure-mgmt-privatedns             0.1.0   1.0.0  wheel
azure-mgmt-rdbms                  1.9.0   8.0.0  wheel
azure-mgmt-recoveryservices       0.4.0   1.0.0  wheel
azure-mgmt-recoveryservicesbackup 0.6.0   0.11.0 wheel
azure-mgmt-redis                  5.0.0   12.0.0 wheel
azure-mgmt-resource               10.2.0  17.0.0 wheel
azure-mgmt-search                 3.0.0   8.0.0  wheel
azure-mgmt-servicebus             0.5.3   6.0.0  wheel
azure-mgmt-sql                    0.10.0  2.0.0  wheel
azure-mgmt-storage                11.1.0  18.0.0 wheel
azure-mgmt-trafficmanager         0.50.0  0.51.0 wheel
azure-mgmt-web                    0.41.0  2.0.0  wheel
azure-nspkg                       2.0.0   3.0.2  wheel
azure-storage                     0.35.1  0.37.0 sdist
humanfriendly                     8.2     9.1    wheel
idna                              2.10    3.1    wheel
knack                             0.7.2   0.8.2  wheel
msal                              1.0.0   1.11.0 wheel
msal-extensions                   0.1.3   0.3.0  wheel
msrest                            0.6.10  0.6.21 wheel
portalocker                       1.7.1   2.3.0  wheel
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ac6b7d-76dc-189b-4ce7-d5f2b4043162
* Version Independent ID: 5982bd9f-1339-3a62-75a4-35161e88368e
* Content: [Quickstart - Configure Ansible using Azure CLI](https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=ansible)
* Content Source: [articles/ansible/install-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/install-on-linux-vm.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hi @kohtala,

I have submitted a PR to address the warning message while installing Ansible in version 2.10. The `ansible[azure]` module isn't required for 2.10 but is still used by those on 2.9 and below. To account for that I included a section of instructions that lists out the steps for installing the Azure components for each version.

As for the requirements file being out of date and handling of those dependencies, I'll do my best to find you an answer and get back to you. :)

**Comment by kohtala** [comment]
> I have submitted a PR to address the warning message while installing Ansible in version 2.10. The `ansible[azure]` module isn't required for 2.10 but is still used by those on 2.9 and below. To account for that I included a section of instructions that lists out the steps for installing the Azure components for each version.

Thanks. It is not just of being required, but `ansible[azure]` is not there at all in 2.10. I think the error message is cosmetic, but indeed misleading.

> As for the requirements file being out of date and handling of those dependencies, I'll do my best to find you an answer and get back to you. :)

I took a look at this. I wrote some suggestion to relax the dependencies on the ansible-collections/azure#441. Would be great if I found some time to make a PR for it.

**Comment by Duffney** [comment]
Hey @kohtala,

My PR to correct the documentation is in review, the changes should be visible within the next few days. I also contacted the engineering team and passed along the information you provided. I was informed it's on their radar and being tracked under the ansible-collections repo. I wish I had more info, but I was told that's the best place to log issues and to keep track of the progress.

I'll go ahead and close this issue on the documentation, but please let me know if you find any other issues with the docs.

Thank you for taking the time to file this issue. :)

Have a wonderful day!
