### ISSUE TITLE
The title and the content in the article don't match

### ISSUE THREAD

**Issue by normesta** [MicrosoftDocs/azure-dev-docs#51]
As of the time of this comment, the article is titled "Deploy a static website to Azure from Visual Studio Code", but the article only contains guidance for how to sign in to Azure. This article contains no guidance for how to deploy a static site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28741df-a56f-1056-9b96-d98f5bcc3cad
* Version Independent ID: 4d5aebae-8e3c-5848-6dc8-905d5fa47efc
* Content: [Deploy a static Node.js website to Azure from Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-01?source=docs#feedback)
* Content Source: [javascript/tutorial-vscode-static-website-node-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-static-website-node-01.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
This is by design, as it's a multi-step tutorial. All of the tutorials on the dev center are like this. You can go to the next step using either the button at the end of the article or the TOC.

**Comment by normesta** [comment]
Not sure all are like that (example: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-upload-process-images?tabs=dotnet). That said, I see no other issues reported on the article, so there perhaps there is no pattern of confusion. It is a content/title mismatch though. I'd suggest text that sets expectation that this is a multi-part tutorial and that all that user will accomplish with this specific article is to install the extension and then log into Azure.  I'll go ahead and close this issue. Thx for listening.

**Comment by kraigb** [comment]
To be clear, I meant all the other four tutorials on this specific JS dev center, https://docs.microsoft.com/en-us/azure/javascript/, not all tutorials elsewhere on Azure. In any case, thanks for the issue, as it will help anyone else who lands here answer the same question.
