### ISSUE TITLE
Instruction to use ansible is not working

### ISSUE THREAD

**Issue by rajaniesh** [MicrosoftDocs/azure-dev-docs#515]
Hi,
I tried running the azure resource group creation playbook by following these steps given in the MS site:https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=ansible#file-credentials

but it is throwing this error

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'urllib3.packages.six'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (msrestazure) on ansible-controller's Python /usr/bin/python3.6. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

This issue is logged here:
https://github.com/ansible/ansible/issues/74758
Regards

Rajaniesh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ac6b7d-76dc-189b-4ce7-d5f2b4043162
* Version Independent ID: 5982bd9f-1339-3a62-75a4-35161e88368e
* Content: [Quickstart - Configure Ansible using Azure CLI](https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=ansible#file-credentials)
* Content Source: [articles/ansible/install-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/install-on-linux-vm.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @rajaniesh,

Are you running the playbook from within Azure Cloud Shell? If not, which version of Ansible are you using?

Thank you,

**Comment by rajaniesh** [comment]
I could make it work on CentOS 8 because on CentOS 7 it has a conflict with Python version because Python version required by Ansible is 3.5 or higher but by default the version on CentOS 7 is not more then 2.75 and if we upgrade it it has undesirable effects like yum is not working and this procedure is not written any where in your documentation. I have wasted so much time and energy on this finally I have taken fresh CentoS 8 machine and installed python 3.5 then it started working

**Comment by Duffney** [comment]
@rajaniesh I appreciate the reply. To confirm the issue is between the Python version and Ansible, not the az Ansible collection correct?

Do you have a requirement to use Ansible 2.10+? Another option might be to use Ansible 2.9 which doesn't have the same Python version requirement. It's not an ideal long-term solution, but might work in the short-term if that's what will work in your environment.

**Comment by Duffney** [comment]
You raise an excellent point @rajaniesh, I will update the doc noting the Python version requirements for ansible-core.

Sidenote:
Do you have a requirement to use Ansible 2.11+? Another option might be to use a lower ansible-core version which can use Python 2.75.

**Comment by Duffney** [comment]
I've added a note detailing the Python version requirements for the different Ansible versions. A PR has been submitted and the changed should be public within a few days.

Thank you for opening the issue @rajaniesh!
