### ISSUE TITLE
Environment variable is invalid. 

### ISSUE THREAD

**Issue by 7474** [MicrosoftDocs/azure-dev-docs#516]
`ARM_CLIENT_PASSWORD` was an invalid environment variable.
`ARM_CLIENT_SECRET` is correct.

Ref.
https://github.com/7474/azure-dev-docs/commit/f74e03e0db1994cf65fd70903bab30060d24644b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c31173-3e96-c871-5a2d-743a26522b4d
* Version Independent ID: 5b281d75-b37e-0301-e1fd-431e0344d0c7
* Content: [Quickstart - Configure Terraform using Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell)
* Content Source: [articles/terraform/get-started-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@7474 Good catch! I'm rewriting that article and it should be published by early next week.

**Comment by TomArcherMsft** [comment]
@7474 Rewriting the "Get Started" articles is taking longer than expected. However, this error is obviously confusing to users and needs to be fixed. Therefore, I've updated this article now and you should see the update in tomorrow's build. Thanks again for catching this and letting me know.

**Comment by 7474** [comment]
Thank you for the fix!

I think so can now proceed with the tutorial smoothly.
