### ISSUE TITLE
Java to Azure RedHat OpenShift migration strategy

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#518]
Could you please add a section "Java to Azure RedHat OpenShift migration strategy" ?

That could include SpringBoot Apps. or Java/Tomcat  Java/WildFly App to ARO migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f7f8f0-3ecb-c09c-8545-b0d98e5396df
* Version Independent ID: fc186d62-3f1f-c8a2-2a27-8f13a6dcd817
* Content: [Migrate Java applications to Azure](https://docs.microsoft.com/en-us/azure/developer/java/migration/migration-overview)
* Content Source: [articles/java/migration/migration-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/migration/migration-overview.md)
* Service: **azure-java**
* GitHub Login: @yevster
* Microsoft Alias: **yebronsh**

**Comment by KarlErickson** [comment]
+ @selvasingh @bmitchell287 for visibility
