### ISSUE TITLE
Inspec or Terraform

### ISSUE THREAD

**Issue by steve-parker-by** [MicrosoftDocs/azure-dev-docs#523]
The page https://docs.microsoft.com/en-us/azure/developer/chef/inspec-overview
implies this is about Chef Inspec - but all the links are for Terraform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31874f60-fbbb-5b60-7352-a7780dfebac2
* Version Independent ID: 6d81c340-c562-624a-3b3f-66444a2d190e
* Content: [Use InSpec for compliance automation of your Azure infrastructure](https://docs.microsoft.com/en-us/azure/developer/chef/inspec-overview?WT.mc_id=azureapril_devto-blog-cxa)
* Content Source: [articles/chef/inspec-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/chef/inspec-overview.md)
* Service: **chef**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@steve-parker-by Thanks for the feedback. Those links are driven by some automated process that is showing related content in terms of working with Azure (not necessarily with Chef). I'll email the PM to look into changing this. Thanks again.

**Comment by TomArcherMsft** [comment]
@steve-parker-by The PM just told me how to disable this feature for this page - since Chef Software content no longer hosted on our site. I'm making that update and it will be published in tomorrow's build.
