### ISSUE TITLE
Hope to deploy Azure resources more efficiently

### ISSUE THREAD

**Issue by moarychan** [MicrosoftDocs/azure-dev-docs#524]
When developers start to use Azure Spring Starter, they maybe want to create and deploy Azure resources more quickly. Currently, 
it is an interactive introduction to Azure CLI.

Hope there's a new template for all the docs under [spring-framework](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/)， specifically include the following:
For Azure resource deployment part:
- Provide resource operation Azure CLI version.
- Provide resource operation [Arm template](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/overview).
- Provide other automation tools, maybe the [Terraform ](https://docs.microsoft.com/en-us/azure/developer/terraform/overview) is a good choice.

At the same time, it's very necessary to have the repo to control the version.

Hi @stliu , @saragluna @backwind1233 ,  please feel free to discuss here, thanks.

**Comment by TomArcherMsft** [comment]
@moarychan Thanks for the feedback. However, GitHub Issues are for customers to report broken or outdated documentation issues; not for employees to request new articles. I'll email you offline to discuss your ideas further. Thanks again.
