### ISSUE TITLE
Azure function name should be same as of component name

### ISSUE THREAD

**Issue by Vipin-Sharma** [MicrosoftDocs/azure-dev-docs#528]
Azure function name in this document is hello. As per component name it should be "helloFunction".

**Comment by KarlErickson** [comment]
Hi @Vipin-Sharma - it looks like you've removed all the auto-generated content when you created this issue, so we can't identify which article or feature area this is for. Which topic are you referring to? Thanks!

**Comment by Vipin-Sharma** [comment]
Hi @KarlErickson , I used mobile app to create this issue and I was expecting this page information should be added automatically, did not remove anything. I should have check this after creating issue, my bad.
 
This is the link I am talking about here.

https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure

**Comment by KarlErickson** [comment]
@Vipin-Sharma - I didn't know that about the mobile app. Good to know. Thanks for the URL - we'll look into this!

**Comment by Vipin-Sharma** [comment]
You may also want to correct one other line that has @ before enable, i don't think there is anything like this annotation available in spring or azure libraries.

**Comment by moarychan** [comment]
Hi @Vipin-Sharma , this PR https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/1898 will update the doc, regarding `@Enable`, it refers to the annotations starting with the @Enable prefix, for example, @EnableCaching, @EnableAsync, you can use azure functions with these features, maybe it's better to change to @EnableXXX.
