### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rscottwatson** [MicrosoftDocs/azure-dev-docs#53]
This link is not working.   Azure SDK for Python package index [https://github.com/Azure/azure-sdk-for-python/blob/master/packages.md]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6044da4-64e4-09c8-81c8-653f43448121
* Version Independent ID: 621581bd-0b83-6458-863d-28e1dd026bfd
* Content: [Azure SDK for Python](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-overview)
* Content Source: [python/python-sdk-azure-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/python-sdk-azure-overview.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for pointing that out. It looks like the package.md file was removed, so the link should go to the SDK docs at https://azure.github.io/azure-sdk-for-python/. I'll make that fix.
