### ISSUE TITLE
Sample code Error in 'Create a pipeline job to upload build artifacts' section

### ISSUE THREAD

**Issue by eyoh5** [MicrosoftDocs/azure-dev-docs#534]
[Enter feedback here]
sample code in 'Create a pipeline job to upload build artifacts' section. 
there is 
               az storage blob upload-batch --destination ${JOB_NAME} --source ./text --auth-mode login

However, the above command complains missing credential to access storage service.
We need --account-name option. 
               az storage blob upload-batch --destination ${JOB_NAME} --source ./text --auth-mode login --account-name $AAZURE_STORAGE_ACCOUNT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2156af24-387c-e4c9-1326-226a7040eca5
* Version Independent ID: 53c8b381-419c-9dd9-2f60-d9e2fd897ae4
* Content: [Tutorial - Use Azure Storage for build artifacts](https://docs.microsoft.com/en-us/azure/developer/jenkins/azure-storage-blobs-as-build-artifact-repository)
* Content Source: [articles/jenkins/azure-storage-blobs-as-build-artifact-repository.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/azure-storage-blobs-as-build-artifact-repository.md)
* Service: **jenkins**
* GitHub Login: @Duffney
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @eyoh5,

I submitted a PR to resolve the issue in the article and I very much appreciated the correct syntax being listed the issue. :)

Changes to the article should be made available within a few days.

Thank you!
