### ISSUE TITLE
Change the localhost from the Angular demo

### ISSUE THREAD

**Issue by glaucia86** [MicrosoftDocs/azure-dev-docs#54]
In this part of the tutorial:

Link: **[https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-02?tabs=angular](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-02?tabs=angular)**

In the step 5, show us that we need to open the browser in the  **http://localhost:3000** to verify that the app is running. 
But actually must be: **http://localhost:4200**

Image
![image](https://user-images.githubusercontent.com/1631477/72770156-c65bc100-3bdb-11ea-9dd3-28c0b38dd97c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33a6d23c-3c05-4a22-8ffb-cd20d050f421
* Version Independent ID: d72dca0f-2c32-30b3-b330-51e5533f4e00
* Content: [Create the static Node.js app in Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-02?tabs=angular#feedback)
* Content Source: [javascript/tutorial-vscode-static-website-node-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-static-website-node-02.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **buhollan**

**Comment by kraigb** [comment]
Right you are...it even shows that way in the browser. I'll fix that.
