### ISSUE TITLE
missing spaces in command under "Authenticate via Azure service principal"

### ISSUE THREAD

**Issue by Jedoe830** [MicrosoftDocs/azure-dev-docs#540]
[Enter feedback here]
There are spaces missing in the chapter "Authenticate via Azure service principal" in the first Azure CLI command so this command fails when copy&paste it to the CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Jedoe830 

The first Azure CLI command in the subsection "Authenticate via Azure service principal" is "az ad sp create".

When I copy and paste that command, and then change the placeholder to my Azure subscription ID, it works. 

Is that the command you're talking about? What error are you getting?

**Comment by Jedoe830** [comment]
Well, it throw an error about that the parameter "--role" is kinda wrong, I don't know the exact error message. But when I run it now as it is documented, it works. So it seems like there is no issue with the Docs
