### ISSUE TITLE
Facing broker disconnected issue while establishing Kafka with Azure Event hubs in Spring boot application

### ISSUE THREAD

**Issue by Rajiya-Mulani** [MicrosoftDocs/azure-dev-docs#543]
1. Article link I followed to configure Event hub.
   https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quickstart-kafka-enabled-event-hubs    (TLS/SSL)

2. code  
Configurations in .properties file
     
###############################################################################################################
###############################################################################################################

kafkaConnectionUrl=******.servicebus.windows.net:9093
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://******.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=*************************";

     POM File : 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.****.iot</groupId>
		<artifactId>m2m-processor</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>m2m-processor-common</artifactId>
	<packaging>jar</packaging>
	<properties>
		<project.root.directory>${basedir}/..</project.root.directory>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.****.iot</groupId>
			<artifactId>m2m-processor-data</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>0.11.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-io</artifactId>
			<version>1.3.2</version>
		</dependency>
		<dependency>
			<groupId>commons-configuration</groupId>
			<artifactId>commons-configuration</artifactId>
			<version>1.10</version>
		</dependency>
	</dependencies>
</project>'

 Kafka producer Configurations : 
    @Bean
	public Producer<String, IndexMessage> IndexMessageKafkaProducer() {
		
		logger.info("BootStrap Server ");
		logger.info(new CommonUtility().getPropertyValue("kafkaConnectionUrl"));
		Map<String, Object> configProps = new HashMap();
		
		  configProps.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, new CommonUtility().getPropertyValue("kafkaConnectionUrl"));
		  configProps.put(ProducerConfig.ACKS_CONFIG, new CommonUtility().getPropertyValue("kafkaProducerAcks"));
		  configProps.put(ProducerConfig.RETRIES_CONFIG, new CommonUtility().getPropertyValue("kafkaProducerRetries"));
		  configProps.put(ProducerConfig.BATCH_SIZE_CONFIG, new CommonUtility().getPropertyValue("kafkaProducerBatchSize"));
		  configProps.put(ProducerConfig.LINGER_MS_CONFIG, new CommonUtility().getPropertyValue("kafkaProducerLingerMs"));
		  configProps.put(ProducerConfig.BUFFER_MEMORY_CONFIG, new CommonUtility().getPropertyValue("kafkaProducerBufferMemory"));
		  configProps.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,new CommonUtility().getPropertyValue("kafkaTopicKeySerializer"));
		  configProps.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,new CommonUtility().getPropertyValue("IndexMessageSerializer"));
		  configProps.put(ProducerConfig.COMPRESSION_TYPE_CONFIG, new CommonUtility().getPropertyValue("kafkaProducerCompressionType"));
		 

        return new KafkaProducer(configProps);
    }

 Kafka consumer Configurations:
   
  @Bean 
	public Consumer<String, IndexMessage>  IndexMessageKafkaConsumer() {
		
		Map<String, Object> configProps = new HashMap();
		configProps.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, new CommonUtility().getPropertyValue("kafkaConnectionUrl"));
		configProps.put(ConsumerConfig.GROUP_ID_CONFIG, new CommonUtility().getPropertyValue("indexConsumerGroupid"));
		configProps.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, new CommonUtility().getPropertyValue("offset"));
		configProps.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, new CommonUtility().getPropertyValue("autoCommit"));

		configProps.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, new CommonUtility().getPropertyValue("kafkaTopicKeyDeserializer"));
		configProps.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, new CommonUtility().getPropertyValue("IndexMessageDeserializer"));
		
		
		System.out.println("Inside Consumer Configuration");
		return new KafkaConsumer(configProps);
	}
	
3. Error : 
   2021-06-28 14:23:41.262  INFO 16940 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 9999 (http)
2021-06-28 14:23:41.270  INFO 16940 --- [           main] c.a.i.m.p.c.SpringBootWebApplication     : Started SpringBootWebApplication in 15.464 seconds (JVM running for 16.243)
2021-06-28 14:23:41.740  WARN 16940 --- [ad | producer-2] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-2] Bootstrap broker *********.servicebus.windows.net:9093 (id: -1 rack: null) disconnected

**Comment by Rajiya-Mulani** [comment]
Kindly update on this issue.

**Comment by Rajiya-Mulani** [comment]
can you please update on this

**Comment by Rajiya-Mulani** [comment]
Any update on this?

**Comment by chenrujun** [comment]
Hi, @yiliuTo Could you please take a look at this issue?

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
Hi @Rajiya-Mulani , from your KafkaProducer and KafkaConsumer beans, seems like your sasl related configs are not configured to them, could you check this? Besides, are you using the java Kafka producer/consumer clients instead of Spring Kafka apis? For spring kafka apis, I mean KafkaTemplate and KafkaListener.

**Comment by KarlErickson** [comment]
No response in 6 months, so I'm closing. @Rajiya-Mulani if this is still an issue for you, please reopen or create a new issue. Thanks!
