### ISSUE TITLE
many PSHELL commands not working in quick start.

### ISSUE THREAD

**Issue by benjamin-goldman** [MicrosoftDocs/azure-dev-docs#544]
[Enter feedback here]
so many of these commands are simply not available even though my computer is showing 7.1.3 powershell.

any chance this could be refreshed or checked by a peer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c31173-3e96-c871-5a2d-743a26522b4d
* Version Independent ID: 5b281d75-b37e-0301-e1fd-431e0344d0c7
* Content: [Quickstart - Configure Terraform using Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-powershell)
* Content Source: [articles/terraform/get-started-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@benjamin-goldman What section are you seeing problems with and what commands are you running that are producing the errors?

**Comment by TomArcherMsft** [comment]
@benjamin-goldman I believe these issues are resolved. If you're still finding issues, please let me know and I'll research further. Thank you.
