### ISSUE TITLE
Create tls_private_key Resource is Not Used

### ISSUE THREAD

**Issue by ItayPodhajcer** [MicrosoftDocs/azure-dev-docs#546]
The example has a `tls_private_key` resource created (to generate an SSH key), but it is not being used except for outputting the private key.
It makes sense that the generate key should be used in the `azurerm_linux_virtual_machine` resource under the `admin_ssh_key` section.

Issue appears in the examples of the following sections:
- [Create virtual machine](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#create-virtual-machine)
- [Complete Terraform script](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#complete-terraform-script)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Configure a Linux VM with infrastructure in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment]
Hey @ItayPodhajcer!

I'm reviewing the article now to make the appropriate changes.  I'll reply after a PR has been submitted

Thank you for submitting the issue,

Given that the MVP renewals and nominations just went out I hope it's safe to say congratulations!

**Comment by Duffney** [comment]
Just wanted to provide an update, I'm doing a full refresh pass on the article to update it to the latest provide syntax etc..

**Comment by TomArcherMsft** [comment]
@ItayPodhajcer Thanks for your feedback. I fixed this issue and you should see it published tomorrow.
