### ISSUE TITLE
Couple of clarifications would be helpful

### ISSUE THREAD

**Issue by kfilimon** [MicrosoftDocs/azure-dev-docs#549]
---
#### Details

the following command would fail if `.kube` does not exist, so it might be helpful to suggest `sudo mkdir var/lib/jenkins/.kube/`
`sudo cp ~/.kube/config /var/lib/jenkins/.kube/`

It's not clear what the purpose of running the following command.
When I see 777 it's usually a red flag from the security point of view.
```
sudo chmod 777 /var/lib/jenkins/   
sudo chmod 777 /var/lib/jenkins/config  
```

is the path correct `/var/lib/jenkins/config`? this file doesn't exist. Did you mean `/var/lib/jenkins/.kube/config`?

In the examples where the following placeholder is used `<Resource_Group>`  it can be better to include prefix for better clarity e.g. `<AKS__Resource_Group>` or `<ACR_Resource_Group>`

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c8677e-3fcd-56c0-fa71-64d758a02ca8
* Version Independent ID: ffb63abe-0c37-4c6c-0560-3e2df33e7e5b
* Content: [Tutorial - Deploy from GitHub to Azure Kubernetes Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-aks)
* Content Source: [articles/jenkins/deploy-from-github-to-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-aks.md)
* Service: **jenkins**
* GitHub Login: @Duffney
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@kfilimon  Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
