### ISSUE TITLE
[Feature request] - Create a code sample using Svelte Framework

### ISSUE THREAD

**Issue by glaucia86** [MicrosoftDocs/azure-dev-docs#55]
This is a suggestion to include a sample code using Svelte Framework in this 2 pages:

Link 1: https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-02?tabs=angular

Link 2: https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-04?tabs=angular

Since the Svelte Community has been growing every day among developers around the world. As you can see in the image below. 

Image
![image](https://user-images.githubusercontent.com/1631477/72772826-d7103500-3be3-11ea-867e-9b8ee6e065d0.png)

If you wish I can create a PR to help creating a Svelte code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 545a3d32-4b23-8a9e-afc4-e48b1783ce2e
* Version Independent ID: 183441d2-7809-36c3-eafb-0745fab9fa75
* Content: [Deploy the static Node.js app files to Azure Storage from Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-static-website-node-04?tabs=angular)
* Content Source: [javascript/tutorial-vscode-static-website-node-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-static-website-node-04.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **buhollan**

**Comment by kraigb** [comment]
Closing as resolved because there's an active PR and we don't need the issue tracking.
