### ISSUE TITLE
No option to select Region in which to create App Service

### ISSUE THREAD

**Issue by w5m** [MicrosoftDocs/azure-dev-docs#551]
Unfortunately, there was no option to select Region when creating the App Service, so I ended up with Central US when I wanted to target the UK. It would be useful if this was a selectable option during the creation process. The current creation wizard has 3 pages: (1) app name, (2) run-time (e.g. Python 3.7), (3) service plan (Free, Basic, Standard, etc.).

Many thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 741ba8e6-6f4c-65a3-d82d-c99e2bf82698
* Version Independent ID: 81acbdf1-f21a-7bbe-0944-b3bd0c2f4bfd
* Content: [Step 3: Create the App Service from Visual Studio Code](https://docs.microsoft.com/en-gb/azure/developer/python/tutorial-deploy-app-service-on-linux-03)
* Content Source: [articles/python/tutorial-deploy-app-service-on-linux-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-deploy-app-service-on-linux-03.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@w5m Thanks for filing the issue, and you bring up a good point that I'll remedy in the docs. The solution is to use the "Advanced" variant of the create web app UI. This option (that's suffixed with "(Advanced)" sometimes appears in the UI prompts, but if it doesn't, use the Command Palette (Ctrl+Shift+P) and select "Azure App Service: Create New Web App...(Advanced)". After entering the name for the web app, select "Create new resource group". The series of prompts that follow include the option to select the region.

**Comment by w5m** [comment]
Many thanks @kraigb
