### ISSUE TITLE
Flutter Azure Hub Notification - device installation not updated

### ISSUE THREAD

**Issue by isacmoura** [MicrosoftDocs/azure-dev-docs#553]
I think might be some update at Flutter and the return of String at some methods are now "dynamic", as the image below shows:
![image](https://user-images.githubusercontent.com/11962687/126179582-a541d88c-db9e-4fff-a70e-d5a5b72f2ecf.png)

I replace the String at the "<>" and worked fine, but I think the documentation should be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b0eeab-4627-9795-8d11-16187ea82d6c
* Version Independent ID: 963a4858-9631-c1a7-b4ef-e74f74bf95e6
* Content: [Send push notifications to Flutter apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-flutter)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-flutter.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-flutter.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
