### ISSUE TITLE
Missing example for creating a specialized image version with Ansible

### ISSUE THREAD

**Issue by seflue** [MicrosoftDocs/azure-dev-docs#555]
I really would appreciate an example how to create a specialized image version with Ansible. I'm trying that since two days without any success - but with Azure CLI it works.

Especially the following error message is not helpful:

> Error creating the GalleryImageVersion instance: Azure Error: InvalidParameter
> Message: The gallery artifact version source can only be specified either directly under storageProfile or within individual OS or data disks. One and only one source type (user image, snapshot, disk, virtual machine) can be provided.
> Target: galleryImageVersion.properties.storageProfile.source.id

And the documentation on that does not help at all:

> Message: The gallery artifact version source can only be specified either directly under storageProfile or within individual OS or data disks. One and only one source type (user image, snapshot, disk, virtual machine) can be provided.
> Cause: The source ID is missing.
> Workaround: Ensure that the source ID of the source is present.

The examples on that are outdated, because they're using "managed_image" which is depricated.

**Comment by TomArcherMsft** [comment]
@seflue What article are you referring to that you would like to see updated?

**Comment by TomArcherMsft** [comment]
From what I can tell, the quote is from the Ansible site, so please follow up with their doc team. Closing issue as this doesn't appear to be a doc error against the Ansible/Azure docs. I'm happy to discuss further if I'm misunderstanding.
