### ISSUE TITLE
Example of ansible playbook on azure fails

### ISSUE THREAD

**Issue by dometdemont** [MicrosoftDocs/azure-dev-docs#557]
Thank you for this nice page of valuable information and examples.
However, from my experiment using the cloud shell, the deployment fails with this error:
TASK [Create VM] *******************************************************************************************************************************************************************
[WARNING]: Module did not set no_log for ssh_password_enabled
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine myVM - Azure Error: InvalidParameter\nMessage: The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid.\nTarget: linuxConfiguration.ssh.publicKeys.keyData"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ab8eeb-df97-be60-ce0a-ed619748c43e
* Version Independent ID: 4dd052d8-808b-1761-526f-2d534322f0e1
* Content: [Quickstart - Configure Linux virtual machines in Azure using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible)
* Content Source: [articles/ansible/vm-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/vm-configure.md)
* Service: **ansible**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by dometdemont** [comment]
Sorry, I missed the instruction to replace the ssh key data :-/

**Comment by TomArcherMsft** [comment]
Hi, @dometdemont. Thanks for the feedback! I'm glad replacing the ssh key data resolved the issue.
