### ISSUE TITLE
error: no such host

### ISSUE THREAD

**Issue by torchy-newman** [MicrosoftDocs/azure-dev-docs#558]
I have tried the tutorial and successfully used the hcl to create the storage account, I can see the storage account in Azure Portal, all looks good,  
but when I try to use it as a backend I get this error:
`terraform init
Initializing the backend...
│ Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure sending request: StatusCode=0 -- Original Error: Get "https://tfbackendmne7fhxxg.blob.core.windows.net/terraform-backend-container?comp=list&prefix=terraform.tfstateenv%3A&restype=container": dial tcp: lookup tfbackendmne7fhxxg.blob.core.windows.net on 168.63.129.16:53:no such host`

What to do?

Regards

Stephen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Tutorial - Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=terraform)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
