### ISSUE TITLE
set environment variable in ps

### ISSUE THREAD

**Issue by austin2153** [MicrosoftDocs/azure-dev-docs#56]
set FLASK_APP=hello:myapp needs to be $env:FLASK_APP = "hello:myapp" in powershell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbae0ad-08bc-c084-0fe1-7fd9c5aeac39
* Version Independent ID: aacdf91a-34af-42f3-c04b-f5217bcbccec
* Content: [Tutorial: Prepare an app for deployment to Azure App Service on Linux from Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-app-service-on-linux-02#feedback)
* Content Source: [python/tutorial-deploy-app-service-on-linux-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-deploy-app-service-on-linux-02.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks, I'll fix that. In future, you can also use the "Edit" button on the upper right of the docs page to make the fix directly. I'll get the PR for review and you get the contribution credit.
