### ISSUE TITLE
acr login command syntax error

### ISSUE THREAD

**Issue by insankim** [MicrosoftDocs/azure-dev-docs#560]
[Enter feedback here]
Sign in to your Azure Container Instance.

az login -n <acrLoginServer>
Replace <acrLoginServer> with your ACR login server.

1. Command syntax error:  az "acr" login
2. Typo: Sign in to your Azure Container "Registry"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c8677e-3fcd-56c0-fa71-64d758a02ca8
* Version Independent ID: ffb63abe-0c37-4c6c-0560-3e2df33e7e5b
* Content: [Tutorial - Deploy from GitHub to Azure Kubernetes Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-aks)
* Content Source: [articles/jenkins/deploy-from-github-to-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-aks.md)
* Service: **jenkins**
* GitHub Login: @Duffney
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@insankim Thanks for the feedback. I've made the change with a slight difference. As the [Azure Container Registry](https://docs.microsoft.com/azure/container-registry/) page shows, the capitalization  is "Azure Container Registry" when referring to the brand that represents the technology. The capitalization is "Azure container registry" when referring to an instance. The change should be published tomorrow (PST).
