### ISSUE TITLE
How to automate the infrastructure creation using Azure Devops PIpeline

### ISSUE THREAD

**Issue by sb1975** [MicrosoftDocs/azure-dev-docs#564]
[Enter feedback here]

Can you provide another tutorial to do the same using Azure Devops Pipeline ?

Create an Application Gateway ingress controller in Azure Kubernetes Service using Azure Devops Pipelines 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sb1975 Thanks for the feedback. 

@Duffney Could you add this to your backlog?

As this is not a "bug" or something that needs fixing in the article, I'll close this GitHub Issue.
