### ISSUE TITLE
Please mention file format (.TF) in the Section - 'Create a base Terraform configuration file'

### ISSUE THREAD

**Issue by cloudysingh** [MicrosoftDocs/azure-dev-docs#566]
Please mention the file format to be created. Also, it will be good idea to suggest users to use Vim/Vi etc. to create a file with a .tf file extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@cloudysingh I have rewritten the "Get Started" article, which will go live next week. As part of those changes, we now recommend the file name. As for suggesting a specific editor, we decided against that as there are too many options - such as VI, the Cloud Shell implementation of VS Code, etc. Thanks again for your feedback.
