### ISSUE TITLE
Execution Policy Error func1.ps1

### ISSUE THREAD

**Issue by m-sterspace** [MicrosoftDocs/azure-dev-docs#57]
I ran into an execution policy error when trying to debug locally. I had to uninstall the azure-functions-core-tools@3 with npm, then install it using chocolatey and a terminal with admin priveleges to get it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca06dae8-9f56-748a-877e-d5e23f79eddc
* Version Independent ID: 05f0d483-4026-2b14-74de-5040ffb55e21
* Content: [Run the Azure Functions application locally in Visual Studio Code](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-03)
* Content Source: [javascript/tutorial-vscode-serverless-node-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-serverless-node-03.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Did that happen with step 1 in the process? I just want to include a small troubleshooting note with your experience and solution, and want to make sure it's in the place you encountered it.

**Comment by kraigb** [comment]
Closing due to no response for more information. Please reopen if providing the needed details.

**Comment by m-sterspace** [comment]
My apologies for the slow response, but yes, it was when I went to run it using the debugger that I ran into the policy error.

**Comment by kraigb** [comment]
Thanks. I'll reopen then so I remember to make the update.
