### ISSUE TITLE
Missing Terraform code snippet

### ISSUE THREAD

**Issue by hitman126** [MicrosoftDocs/azure-dev-docs#573]
[The Terraform code snippet expected below the line wording is missing:
 
"**_Run the following commands to get the storage access key and store it as an environment variable:_**"

Kindly provide the example.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Tutorial - Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=terraform)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@hitman126 

Thanks for your feedback. 

I'm assuming you're referring to code sections within the section "Configure terraform backend state"? 

If so, there is a comment after the empty code block:
"Terraform prevents sensitive information from being displayed within the terminal. It's recommended to use Azure CLI or Azure PowerShell to retrieve the access key."

I can see how this might appear to be a mistakenly empty code block. I'll move the code to a comment within the block.

Sorry about the confusion and thanks again for the feedback.
