### ISSUE TITLE
Authentication error when creating a custom VM image with GitHub Actions

### ISSUE THREAD

**Issue by chester-leung** [MicrosoftDocs/azure-dev-docs#575]
Hi, I'm trying to create a custom VM image with GitHub actions following this [tutorial](https://docs.microsoft.com/en-us/azure/developer/github/build-vm-image). However, I run into the following error

```
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:2a2c9bac-e01e-00ce-3254-8d2bc1000000 Time:2021-08-09T19:29:24.8381595Z</Message>
</Error>
```

I'm able to log in to Azure with my service principal secret, but during the actual image building process, I get this error. Can you please explain what is happening when running this action? Why is it trying to access a storage account?

I've found that running this action with create a new resource group that contains a storage account, but I'm not sure what this storage account is actually used for. I'm not creating an image with anything from Azure storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3382100a-d652-0579-115e-2b8a991e244b
* Version Independent ID: a47e1d15-ea94-f224-602d-b60e18d4bf7f
* Content: [Build custom virtual machine images with GitHub Actions and Azure](https://docs.microsoft.com/en-us/azure/developer/github/build-vm-image)
* Content Source: [articles/github/build-vm-image.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/github/build-vm-image.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
@chester-leung I apologize for the late response. I've added a note to make it clearer how to authenticate during the Create App Baked Image action. You'll need to verify that you have assigned the Image Creation Role to your user-managed identity.

**Comment by juliakm** [comment]
The update will deploy in the next day. 

#please-close
