### ISSUE TITLE
Public access to Azure Storage Account to store Terraform state

### ISSUE THREAD

**Issue by magic-happenz** [MicrosoftDocs/azure-dev-docs#577]
Hello,

I just setup up a Storage Account to store my Terraform state according to this example https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md. 

I am curious what is the reason to recommend all examples to setup the Storage Account for public access? Isn´t that rather a security risk and bad recommendation? Since I deploy resources to Azure I would be authenticated anyways so why activating public access on that account by default? Especially given that the state files can include very sensitive data I would propose to change all examples to deactivate public access unless it is required for whatever reason or add a reason to the documentation why this is proposed.

Best,
Mario

**Comment by scottyhq** [comment]
Also confused by this! I think the docs just need some clarification. Related: #568

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
