### ISSUE TITLE
Maven cargo plugin and version

### ISSUE THREAD

**Issue by gregbek** [MicrosoftDocs/azure-dev-docs#578]
Version of maven plugin for cargo needs to be:
```
                <artifactId>cargo-maven3-plugin</artifactId>
                <version>1.9.6</version>
```
 Most importantly "maven3" not "maven2".

Fails to deploy if not fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea34ef2-42ef-59b6-d7d9-e832aaf41dc1
* Version Independent ID: 9afefbb9-7108-8af3-1ce1-60a8b70c3c74
* Content: [Deploy a Spring/Tomcat app to App Service with Azure Database for MySQL](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-app-service-e2e?tabs=bash)
* Content Source: [articles/java/spring-framework/spring-app-service-e2e.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/spring-app-service-e2e.md)
* Service: **app-service**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@gregbek thanks for the feedback! We'll take a look and get that fixed.
