### ISSUE TITLE
Next Steps Aren't Useful

### ISSUE THREAD

**Issue by m-sterspace** [MicrosoftDocs/azure-dev-docs#58]
The Next Steps on this page make sense from how Microsoft groups it's products but it doesn't make sense from the perspective of a developer who might be following this guide. A developer is presumably trying to build a web app using Azure Functions so useful Next Steps would be stuff like properly configuring authentication, when to combine functions or leave them separate, how to use them to connect to a db, or how to managing routing with your api. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa1710c0-7d63-6375-c25a-b204898fe283
* Version Independent ID: c0e8cd44-abbb-e47a-3085-141c9f7af8ea
* Content: [Clean up resource after deploying the Azure Functions application to azure](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-serverless-node-05)
* Content Source: [javascript/tutorial-vscode-serverless-node-05.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/javascript/tutorial-vscode-serverless-node-05.md)
* Product: **azure-nodejs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Yes, I agree. :) In some cases we have gaps, meaning we don't yet have appropriate articles to link to. In any case, @btholt @burkeholland  I'm assigning to you to consider for the JavaScript backlog.

**Comment by diberry** [comment]
@m-sterspace I've added a more robust set of links for next steps. I'm closing this issue however if you feel more can be done, let me know which specific content links you wanted included. #please-close
