### ISSUE TITLE
Unable to find the integration tests in the article

### ISSUE THREAD

**Issue by ahmetsyildirim** [MicrosoftDocs/azure-dev-docs#580]
So, Checkov is a static code analysis tool and terraform validate is to validate the configuration files.
So both of them are "offline tests".
If I'm not mistaken, integration test terminology generally refers to tests done against deployed resources.

Is this article using the "integration test" terminology in a different context?

Also Martin Fowler has a very nice article about the blurred 'integration test' terminology over the years.
https://martinfowler.com/bliki/IntegrationTest.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1572ea-d197-2543-b3ea-07b5bf7e8483
* Version Independent ID: 6651e0a0-be7d-6a50-43ff-83760f9fa380
* Content: [Implement integration testing with Terraform and Azure](https://docs.microsoft.com/en-us/azure/developer/terraform/best-practices-integration-testing)
* Content Source: [articles/terraform/best-practices-integration-testing.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/best-practices-integration-testing.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by ahmetsyildirim** [comment]
I guess this article aligns with the integration test with my understanding. 
https://docs.microsoft.com/en-us/azure/developer/terraform/best-practices-end-to-end-testing
So may be the issue I raised could be invalid.

**Comment by TomArcherMsft** [comment]
@ahmetsyildirim Thanks for your feedback. I'm looping in the author for that article for his input.

@jcorioland Could you answer the questions posed in this GitHub Issue?

**Comment by jcorioland** [comment]
@ahmetsyildirim the 2 first steps (checkov and Terraform validate) are offline indeed. But the third one, terraform plan, actually connects to Azure and validate the new Terraform configuration can be deployed to the existing environment. This is in that sense that we call it "integration tests" in this article, because we ensure the new configuration integrates correctly with existing resource.

**Comment by TomArcherMsft** [comment]
@ahmetsyildirim It looks like @jcorioland answered your question, so I'm going to close the Issue. 

If you disagree or have more questions, I'll be happy to reopen the Issue for further discussion.

Also, if you feel there's a note or something we can add to the article to help people understand better, please let me know and we can talk about that.

**Comment by ahmetsyildirim** [comment]
@jcorioland I tend to agree with your explanation about terraform plan. Indeed it is an "online" command. Plan evaluates the proposed code using the stored state file and identifies that if any changes need to be reflected to the target cloud. Also it can create a binary out file as a kind of deployable artefact. And during that process it fail with an error if the proposed change is not compliant with the target vendor (Azure Cloud). But I'm not very convinced that it involves any integration testing.

Also if you can check this article from [Hashicorp's ](https://www.hashicorp.com/blog/testing-hashicorp-terraform)website, their diagram also does not identify "plan" command as an integration test.

![terraform_test](https://user-images.githubusercontent.com/1262423/130721491-8fbd045e-4d8c-44b9-a741-1547387e3cce.png)

May be just the terminology "integration test" is used in different a context there.

@TomArcherMsft  I think there is no need to reopen the issue. I hope that I was able to express my confusion about the article. Thanks :)

**Comment by jcorioland** [comment]
@ahmetsyildirim ok, now I got your point. I think there is a confusion between continuous integration and integration tests, indeed.  The article is about continuous integration, so it's actually integration tests for the code. All tests are made to ensure that new code that is pushed on the repository integrates correctly with the existing configuration, new changes pushed by other developers and existing resources on Azure (the Terraform plan step).
If you look for integration tests, you can have a look to [this article](https://docs.microsoft.com/en-us/azure/developer/terraform/best-practices-end-to-end-testing) about end-to-end testing. The Terratest framework that is used in this one allows to write integration tests, i.e. in this context, making sure that the Terraform module deploy and integrates correctly with other existing components, for example.

@TomArcherMsft to avoid confusion, maybe we could rename the article to "Implement **continuous** integration tests for Terraform projects in Azure" ? and also change the title of point number 5. to **Continuous integration using Azure Pipeline** ? I think it will remove any confusion.
