### ISSUE TITLE
tpm

### ISSUE THREAD

**Issue by mike1980-aca** [MicrosoftDocs/azure-dev-docs#581]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af1310e4-f7d3-1098-aae8-979a75abe19c
* Version Independent ID: 846b7186-6865-8ee4-785c-5f0ef6afaf25
* Content: [Troubleshoot networking issues when using the Azure SDK for Java](https://docs.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-network?view=azure-java-preview)
* Content Source: [articles/java/sdk/troubleshooting-network.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/sdk/troubleshooting-network.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **alzimmer**

**Comment by KarlErickson** [comment]
@mike1980-aca thanks for filing the issue, but you didn't provide any feedback. If you forgot to fill that part in, please reopen this issue or file a new one. Thanks!
