### ISSUE TITLE
container_name tstate

### ISSUE THREAD

**Issue by chris-edwards-pub** [MicrosoftDocs/azure-dev-docs#582]
In the **Create a Terraform configuration with a backend configuration block.** 

```
    backend "azurerm" {
        resource_group_name  = "tfstate"
        storage_account_name = "<storage_account_name>"
        container_name       = "tstate"
        key                  = "terraform.tfstate"
    }
```

container_name should be tfstate not tstate.

**Comment by TomArcherMsft** [comment]
@chris-edwards-pub Thanks for the catch! I've fixed the container name and the article should be republished tomorrow.
