### ISSUE TITLE
Feedback regarding the docs

### ISSUE THREAD

**Issue by JennyLJY** [MicrosoftDocs/azure-dev-docs#584]
[Enter feedback here]
It seems this docs is outdated as the kubernetes version shown in the picture is v1.9, however the kubernetes currently supported version is about v1.19 now. Please help to confirm if the same configuration could work for deploying the AKS integrate with AGIC currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@JennyLJY Thanks for contacting us. That article is out of date and being rewritten. As we already have many GitHub Issues open against that article, and this issue doesn't point to a specific problem, I'm going to close it. We should have the article updated within the next week.
