### ISSUE TITLE
Add warning regarding automatic schema generation

### ISSUE THREAD

**Issue by joergjo** [MicrosoftDocs/azure-dev-docs#59]
It might be worth pointing out that the sample code will recreate the database every time the application runs because of spring.jpa.hibernate.ddl-auto=create to avoid confusion when running the sample app multiple times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53ede65e-1ae2-0620-6c15-7433e8aa0c1f
* Version Independent ID: 3835e91b-cbb9-72ba-8be0-ff8c837f4ca6
* Content: [How to use Spring Data JPA with Azure PostgreSQL](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql#feedback)
* Content Source: [java/spring-framework/configure-spring-data-jpa-with-azure-postgresql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql.md)
* Service: **postgresql**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@joergjo thanks for the feedback! We'll investigate and update the topic.

**Comment by jdubois** [comment]
Thanks @joergjo - as discussed with @KarlErickson I will update that documentation (and probably also the ones on MySQL and MS SQL Server as they work the same way).

As explained in the [Hibernate documentation](https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html), using `create` will result in: "Database dropping will be generated followed by database creation".

So you are indeed correct, and I will add a warning note for users, as indeed this is a bit misleading.
