### ISSUE TITLE
Analyze image in http://localhost:3000/build not working

### ISSUE THREAD

**Issue by tpal72** [MicrosoftDocs/azure-dev-docs#592]
Unhandled Rejection (TypeError): Cannot read property 'filter' of undefined
includesText
C:/Users/tapal/source/devcode/azure/js-e2e-client-cognitive-services/src/azure-cognitiveservices-computervision.js:44
  41 | 
  42 | // Computer Vision detected Printed Text
  43 | const includesText = async (tags) => {
> 44 |   return tags.filter((el) => {
  45 |     return el.name.toLowerCase() === "text";
  46 |   });
  47 | };
View compiled
computerVision
C:/Users/tapal/source/devcode/azure/js-e2e-client-cognitive-services/src/azure-cognitiveservices-computervision.js:78
  75 |  });
  76 | 
  77 |  // text detected - what does it say and where is it
> 78 |  if (includesText(analysis.tags) || includesHandwriting(analysis.tags)) {
     | ^  79 |    analysis.text = await readTextFromURL(computerVisionClient, urlToAnalyze);
  80 |  }
  81 | 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01198bfe-0789-cf6f-0ede-f05d347596ba
* Version Independent ID: 0e4bd267-e323-8d8f-edb2-59fd25a35852
* Content: [Create Computer Vision resource - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/static-web-app/create-computer-vision-resource-use-in-code?tabs=bash)
* Content Source: [articles/javascript/tutorial/static-web-app/create-computer-vision-resource-use-in-code.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/static-web-app/create-computer-vision-resource-use-in-code.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@tpal72 - Thank you for reporting this. I'll take a look. #in-progress

**Comment by diberry** [comment]
@tpal72 - what operating system and node.js version are you using? I'm using Windows 10 and Node.js 14.17.1 and I don't get this error?

**Comment by diberry** [comment]
@tpal72 any update?

**Comment by diberry** [comment]
Closing due to lack of information. Feel free to reopen when you have time. #please-close
