### ISSUE TITLE
the reply URL specified in the request does not match the reply URLs configured for the application

### ISSUE THREAD

**Issue by romainiac** [MicrosoftDocs/azure-dev-docs#594]
Following the guide, I am receiving this error once signing in. 

Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'bc18d5db-06ae-4c36-8ff0-a224453daa86'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **brendm**

**Comment by saragluna** [comment]
@moarychan please take a look at it.

**Comment by moarychan** [comment]
Hi @romainiac , Sorry to keep you waiting. We have just released [library 4.0]( https://aka.ms/spring/docs/4.0.0), [samples for 4.0](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.0.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-web-application), you are welcome to upgrade. I just used the release version 3.9.0 in September 2021 and tested the sample of [aad-web-application](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/azure-spring-boot_3.9.0/aad/azure-spring-boot-starter-active-directory/aad-web-application). The result is normal. Can you confirm the reply-url you configured? Or can I use your demo project so I can quickly locate the problem?

**Comment by stliu** [comment]
shall we close this one?

**Comment by moarychan** [comment]
Hi @KarlErickson please help close this issue due to no updates for a long time. @romainiac any more updates are welcome, or you can open a new issue, thanks!
