### ISSUE TITLE
Backend storage account section doesn't support variables

### ISSUE THREAD

**Issue by assaf-grth** [MicrosoftDocs/azure-dev-docs#595]
The block at section 3.2 displays a backend.azurerm section using variables
```
  backend "azurerm" {
    resource_group_name = var.resource_group_name
    storage_account_name = var.storage_account_name
    container_name = "tfstate"
    key = "codelab.microsoft.tfstate"
  }
```

Executing terraform init fails with this error:
```
╷
│ Error: Variables not allowed
│
│   on main.tf line 12, in terraform:
│   12:     resource_group_name = var.state_resource_group
│
│ Variables may not be used here.
╵

╷
│ Error: Variables not allowed
│
│   on main.tf line 13, in terraform:
│   13:     storage_account_name = var.state_storage_account
│
│ Variables may not be used here.
```

Documentation should be updated to support current situation

(terraform version used is 1.0.6)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@assaf-grth Thanks for the feedback. We're aware of this issue (and others with this article) are in the process of rewriting it. I'll update this issue when it's done. Thanks again.

**Comment by TomArcherMsft** [comment]
@assaf-grth I've completely rewritten and tested this article. It should go live Monday.
