### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by vacuela** [MicrosoftDocs/azure-dev-docs#598]
In the page
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starters-for-azure

There is a link in the recommended content section
the firts option "Azure Spring Boot statrter cliente liberay for java" is broken
regards

**Comment by KarlErickson** [comment]
The recommended content section is autogenerated, and driven by machine learning. The broken link is no longer appearing.
