### ISSUE TITLE
Q: Using @autowired requires compile-time knowledge about the instrumentation key, right?

### ISSUE THREAD

**Issue by jochenvanwylick** [MicrosoftDocs/azure-dev-docs#60]
Quick question - I've used the @Autowired annotation on the Telemetryclient but commented out the instrumentation key from the application.properties - because I don't want to check in my instrumentation key into source control and - don't know the instrumentation key compile-time as I would like to have multiple app insights instances for different DTA environments.
However - that seems to break the build because apparently compile-time it tries to instantiate an instance of the Telemetryclient but cannot since the key is missing. So I'm now newwing-up an instance of TelemetryClient in the class which - I hope - will look for the instrumentation key in the environment variables. Did I do this correctly? No way I can use @Autowired without specifying the key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0847a17d-8f32-d22e-e8f9-e2604c8d34bb
* Version Independent ID: d0056593-615e-0147-fa0e-9633ad590b66
* Content: [Configure a Spring Boot Initializer app to use Azure Application Insights SpringBoot Starter](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-java-applicationinsights)
* Content Source: [java/spring-framework/configure-spring-boot-java-applicationinsights.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-java-applicationinsights.md)
* Service: **azure-monitor**
* GitHub Login: @dhaval24
* Microsoft Alias: **dhdoshi**

**Comment by KarlErickson** [comment]
@dhaval24 can you provide input here? @selvasingh @bmitchell287 for awareness

**Comment by KarlErickson** [comment]
Topic has been removed and redirected to current recommended approach.
