### ISSUE TITLE
 @azure/ms-rest-nodeauth and @azure/ms-rest-browserauth packages need not be mentioned anymore

### ISSUE THREAD

**Issue by ramya-rao-a** [MicrosoftDocs/azure-dev-docs#603]
The section on `Classic programmatic authentication` mentions the use of `@azure/ms-rest-nodeauth` and `@azure/ms-rest-browserauth` packages for auth. This applied to all of the arm packages and a handful of data plane packages.

The latest versions of all arm packages now support `@azure/identity` as well.
This leaves only a handful of data plane packages that still need `@azure/ms-rest-nodeauth` or `@azure/ms-rest-browserauth`

- @azure/applicationinsights-query (will be deprecated later in the year or early next year in favor of Monitor Query)
- @azure/batch 
- @azure/graph  (will be deprecated later in the year or early next year in favor of Microsoft Graph)
- @azure/loganalytics  (will be deprecated later in the year or early next year in favor of Monitor Query)
- @azure/servicefabric (no active development in the past 2 years)
- @azure/storage-datalake (no active development in the past 2 years)

With this, I think it is safe enough to not mention either of these 2 packages in this page.

Moreover, we have the below line before showing a code sample that uses a cognitive service package

> The following example demonstrates how to authenticate with a service provided key and endpoint.

I would preface this with the note that not all services support auth via AAD in which case `@azure/identity` cannot be used. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108cfe63-679d-4820-23d5-a42bd38ff328
* Version Independent ID: 935b0817-b960-9872-93bb-60c45d5175a3
* Content: [Authentication and Authorization - JavaScript - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/concepts/identity-authentication-users)
* Content Source: [articles/javascript/concepts/identity-authentication-users.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/concepts/identity-authentication-users.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
I believe I have this fixed by removing this article and letting the Identity team's content cover this. I will also keep a watch for any other content in my area covering this info. Feel free to reopen if needed. 

#please-close
