### ISSUE TITLE
usage and securing ssh_key should be mentioned

### ISSUE THREAD

**Issue by sb1975** [MicrosoftDocs/azure-dev-docs#605]
[Enter feedback here]

The linux_profile record allows you to configure the settings that enable signing into the worker nodes using SSH.
This description is very minimal and needs to be elaborated with details as suggested below :

1. Links and explanation on how to use the SSH keys to connect to the worker nodes. There are some unofficial ways to inject the ssh into the debug pods and then execute it, however official details from Microsoft would be more useful.

2. There should be some explanation on how to secure the ssh_keys, they should not be passed as simply readable variables and must be secured. Maybe details on how it would be secured in Azure Devops , Terraform and also how it would be secured if terraform is used in Azure Devops Pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sb1975 Thanks for the feedback. Those 2 subjects are advanced topics that are outside the scope of the article, which is intended to get people started. However, I'll add your ideas to our backlog for possible future articles. Thanks again.
