### ISSUE TITLE
Configure Ansible in Azure Government doc is needed

### ISSUE THREAD

**Issue by Psichomofo** [MicrosoftDocs/azure-dev-docs#606]
[Enter feedback here]
Could we get a snippet or help some where when trying to do this in the azure Government cloudshell ?
Documentation for azure gov is poor to non-existent.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf34277-7542-1451-31c7-a41aeabca49d
* Version Independent ID: b8a2871c-6ddf-4106-70f6-905684c329ef
* Content: [Get Started - Configure Ansible using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?bc=%2Fazure%2Fbread%2Ftoc.json&toc=%2Fazure%2Fcloud-shell%2Ftoc.json&tabs=ansible)
* Content Source: [articles/ansible/getting-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/getting-started-cloud-shell.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Psichomofo Thanks for the feedback. I've added this to our backlog for future consideration.
