### ISSUE TITLE
Wrong title to the installation link

### ISSUE THREAD

**Issue by niajthat** [MicrosoftDocs/azure-dev-docs#607]
The troubleshooting section says "refer to the Cloudbees Jenkins installation page" with a hyperlink pointing to https://www.jenkins.io/doc/book/installing/. This link is not related to Cloudbees. Either title should be updated or the link be updated appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Get Started - Install Jenkins on an Azure Linux VM](https://docs.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@niajthat Thanks for the feedback. The link text has been corrected.
