### ISSUE TITLE
Typescript/JavaScript confusion

### ISSUE THREAD

**Issue by CrazyRobMiles** [MicrosoftDocs/azure-dev-docs#609]
Nice tutorial. However, I got confused over whether you are using JavaScript or TypeScript. On the Create the local Functions app with the Visual Studio Code Functions extension page step 3 says select JavaScript and step 4 says select TypeScript. Then the two code samples are labelled JavaScript and TypeScript (and one seems to include the other).It would be best to pick one or the other, or explain why the two languages are used. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6b8af9c-5a33-a4c9-706e-02b6257754b7
* Version Independent ID: ba88d675-f23a-6565-d59c-fcfa07b77f11
* Content: [Create the Azure Functions 3.x application from Visual Studio Code - Azure](https://docs.microsoft.com/en-gb/azure/developer/javascript/tutorial/vscode-function-app-http-trigger/tutorial-vscode-serverless-node-create-local)
* Content Source: [articles/javascript/tutorial/vscode-function-app-http-trigger/tutorial-vscode-serverless-node-create-local.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/vscode-function-app-http-trigger/tutorial-vscode-serverless-node-create-local.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
Thank you for reporting this. I believe this issue has been resolved. #please-close
