### ISSUE TITLE
Should include an end-to-end overview

### ISSUE THREAD

**Issue by Qythyx** [MicrosoftDocs/azure-dev-docs#610]
This tutorial is useful, but it is also very hard to understand exactly what is happening, when, and why.

For me the biggest unexplained part is when you should call `RegisterDeviceAsync` in a real app. In this sample app it is done via button to Register or Deregister, but in most real apps they just turn on notifications when you first launch (and possibly have settings to turn them off later). In this sample app calling `RegisterDeviceAsync` must be done after other things occur, and it is hard to understand when it is ok. Furthermore, you should only call `RegisterDeviceAsync` once, but it isn't clear how to determine if you called it already (do you need to keep track of this yourself, or is there some way within the existing infrastructure?).

Another example is the instructions for Android say to create a `PushNotificationFirebaseMessagingService` class with `[IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]` decoration on it. But there is no explanation of what this magical decoration does. After doing some searching it seems the main this it does is cause the `OnNewToken` and `OnMessageReceived` methods to automagically get called by the Firebase system. That's great, but it would be great if it was explained. Furthermore, it seems that `OnNewToken` is only called once when the app is run the first time it is installed. This can be very confusing and frustrating when trying to debug if you don't know that and expect it to be called each time the app launches.

So, I feel a diagram or something that shows the timeline of all the push related events and calls would help explain this significantly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
