### ISSUE TITLE
Java Spring boot Kafka cloud

### ISSUE THREAD

**Issue by Tockra** [MicrosoftDocs/azure-dev-docs#615]
Hi Guys,

I have an event stream in azure and want to consume events from there in my java application. 
So I read:
https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md

For now it seems to work well. Everything I configured there is shown in the terminal. 
But I find no way to change the scope of the azure authentication. At the moment it is on its default value: https://management.core.windows.net//.default

I found no property to change it. But I just brute forced it :p . I don't know where I find a list of all properties.

T

**Comment by stliu** [comment]
I don't think this is an issue anymore since we already update the doc with password less support and reference doc, @KarlErickson  do you think we can close this one?
