### ISSUE TITLE
ERROR: features is not a directory.

### ISSUE THREAD

**Issue by michaelspinks** [MicrosoftDocs/azure-dev-docs#630]
When I ran this command I got an error

docker run --rm -v $PWD:/target -it eerkunt/terraform-comnce -f ./features -p main.tfplan.json
terraform-compliance v1.3.30 initiated

ERROR: features is not a directory.

I can see features is a directory containing tagging.feature for the cucumber tests, it came as part of the downloaded source files as a directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289ec1fa-65bf-099d-302c-1ecb57e164ed
* Version Independent ID: 0ec86998-3ecc-47fe-0b12-741c6b7f153d
* Content: [Implement compliance testing with Terraform and Azure](https://docs.microsoft.com/en-us/azure/developer/terraform/best-practices-compliance-testing)
* Content Source: [articles/terraform/best-practices-compliance-testing.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/best-practices-compliance-testing.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@michaelspinks Are you running the docker command in the "features" parent directory?

**Comment by TomArcherMsft** [comment]
@michaelspinks You never replied, so I'm going to close the issue. Please let me know if you're still having problems and I'll reopen the issue and contact the author of the article to help out.
