### ISSUE TITLE
Missing sample Service Principal ID

### ISSUE THREAD

**Issue by ringoc** [MicrosoftDocs/azure-dev-docs#631]
It is better to put in a dummy App ID as e.g. 

```
$ az ad sp --id <app-id>
```
Otherwise it throws out an error 

```
argument --id: expected one argument

TRY THIS:
az ad sp create --id 00000000-0000-0000-0000-000000000000
Create a service principal. (autogenerated)
```

![image](https://user-images.githubusercontent.com/202669/139428229-85541f18-d1d1-4ace-b4a4-9326edc05bd8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#use-the-azure-login-action-with-openid-connect)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by cveld** [comment]
Same counts for the next step:
Currently:
`az role assignment create --role contributor --subscription --assignee-object-id`

Suggested:
`az role assignment create --role contributor --subscription <subscription-id> --assignee-object-id <service-principal-object-id>`

I guess it would be even more preferred to provide the outputs to the next steps programmatically.

**Comment by juliakm** [comment]
Thanks, this has been addressed. 

#please-close
