### ISSUE TITLE
this lab breaks here: Select the ellipsis next to Environment 1. Select Add deployment group phase.

### ISSUE THREAD

**Issue by smoms** [MicrosoftDocs/azure-dev-docs#632]
this lab breaks here: Select the ellipsis next to Environment 1. Select Add deployment group phase.

There is no such option in Azuree DevOps. Please fix it asap.

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba5c28a5-b211-e95d-f145-06898f60ef2c
* Version Independent ID: 49ee2033-65c8-e36c-3c67-057fc253efe0
* Content: [Deploy to Linux virtual machine using Jenkins and Azure DevOps Services](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-to-linux-vm-using-azure-devops-services)
* Content Source: [articles/jenkins/deploy-to-linux-vm-using-azure-devops-services.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-to-linux-vm-using-azure-devops-services.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@smoms  Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
