### ISSUE TITLE
Tutorial does not run successfully 

### ISSUE THREAD

**Issue by shreyaaithal** [MicrosoftDocs/azure-dev-docs#633]
Project ID and name in the sample does not match the rest of the tutorial. 
Need to update project artifact ID in pom.xml file under "complete" folder:

\<groupId\>com.example\</groupId\>
\<artifactId\>gs-spring-boot-docker\</artifactId\>
\<version\>0.0.1-SNAPSHOT\</version\>
\<name\>gs-spring-boot-docker\</name\>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200ae7a0-87fe-9d4d-db79-12495746fbd8
* Version Independent ID: 0aaa8a60-4aec-ac05-a9bc-7d9a4883c637
* Content: [Deploy Spring Boot Application to the Azure Kubernetes Service - Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @KarlErickson
* Microsoft Alias: **brendm**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @fangjian0423 ?

**Comment by fangjian0423** [comment]
#assign:chenrujun

**Comment by fangjian0423** [comment]
hi @shreyaaithal , thanks for reaching out.

I think everywhere about `gs-spring-boot-docker` in "Deploy the image to your Kubernetes cluster" section change to `spring-boot-docker-complete` is better. 

We will update it ASAP.
