### ISSUE TITLE
Update Track 2 Go documentation based on recent changes

### ISSUE THREAD

**Issue by nickzhums** [MicrosoftDocs/azure-dev-docs#634]
We recently made a few changes to the Go SDK and need to update the following page:

https://docs.microsoft.com/en-us/azure/developer/go/management-libraries

- Module path and dependencies update:

There is no ‘armcore’ library.
Module path change:  github.com/Azure/azure-sdk-for-go/sdk/resoucemanager/compute/armcompute
     github.com/Azure/azure-sdk-for-go/sdk/azcore/to

- API change of the constructor so the sample code needs to be updated.

There is no connection object now.

con := armcore.NewDefaultConnection(cred, nil)

use the below way to create a client.

rgClient := armresources.NewResourceGroupsClient(subscriptionID, credential, options)

**Comment by nickzhums** [comment]
@Duffney please take a look

**Comment by lirenhe** [comment]
One more questions related to https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-tools#dependency-management-with-dep, from https://github.com/golang/dep, it mentioned 'Dep is deprecated and archived in favor of Go modules'
Do we still need this?

**Comment by nickzhums** [comment]
Good question, I think we will remove it and mention Go modules instead

**Comment by Duffney** [comment]
I apologize, I missed the notification. Looking into this now. :)

**Comment by Duffney** [comment]
Pull request submitted with revision. :)

**Comment by lirenhe** [comment]
@Duffney, could you share the link of the PR?

**Comment by Duffney** [comment]
> @Duffney, could you share the link of the PR?

The changes have just been merged. It was created on an internal repo and it didn't appear you were inside the organization for the repo and I wasn't able to add you @lirenhe. Changes should be merged and made public within 48 hours. If they don't fully address your concerns please be sure to let me know. :)

Thanks!

**Comment by Duffney** [comment]
Closing this issue, but please reopen if the changes do not fully address the concerns discussed here.

**Comment by Duffney** [comment]
@nickzhums when you've got a moment, please review the changes, and close the issue if it's been resolved, thank you. :)

**Comment by nickzhums** [comment]
@Duffney thanks! looks good to me, I will let @lirenhe double confirm

**Comment by lirenhe** [comment]
@Duffney  thanks, overall it looks good.
A small comment:
typo in:  poller, err := client.BeginCreate(ctx, "resource_identifier", "additonal_parameter")
