### ISSUE TITLE
Terratest Doc- Dep is deprecated and not maintained anymore

### ISSUE THREAD

**Issue by cyprienruelle** [MicrosoftDocs/azure-dev-docs#636]
In the github page of [Dep](https://github.com/golang/dep#installation), (linked in this page too), it is said Dep is now deprecated. Moreover, no commit have been done since september 2020.
It is said Dep is now part of Go since 1.11.

Can you please update this tutorial to match state of art ?
Update should include:
- Removal of Dep installation instructions.
- Shell commands updates.

Thanks.

(I'm totally newbie with Go and I can't provide equivalent commands).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a16eed4-6a1c-7bf5-1ce8-bef512ba3c43
* Version Independent ID: c44ea309-2614-62d4-da5b-3ad1ec086866
* Content: [Test Terraform modules in Azure using Terratest](https://docs.microsoft.com/en-us/azure/developer/terraform/test-modules-using-terratest)
* Content Source: [articles/terraform/test-modules-using-terratest.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/test-modules-using-terratest.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@cyprienruelle Thanks for your feedback. As you noted, this article is very out of date. As a result, it is no longer in the TOC and is in our backlog to rewrite.
