### ISSUE TITLE
Is the sample code runnable?

### ISSUE THREAD

**Issue by benchwang** [MicrosoftDocs/azure-dev-docs#638]
Could not find where `ctx` is declared in following code:
	// Call your function to create an Azure resource group.
	resourceGroup, err := createResourceGroup(ctx, conn)

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842c31dc-7df1-9052-cdcf-c5e03fae0766
* Version Independent ID: e3a655d2-ac7a-1d23-16d5-3d0d50fc673e
* Content: [Manage resource groups with the Azure SDK for Go](https://docs.microsoft.com/en-us/azure/developer/go/manage-resource-groups?tabs=windows%2Cazure-portal)
* Content Source: [articles/go/manage-resource-groups.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/go/manage-resource-groups.md)
* Service: **azure**
* GitHub Login: @barbkess
* Microsoft Alias: **barbkess**

**Comment by Duffney** [comment]
Hey @benchwang,

I've likely updated the code since you file the issue, but the `ctx` is declared in the `var` block and is set to the value `context.Background()`. Please let me know if you have any other comments or concerns.

Thank you for taking the time to file this issue, have a great day. :)

**Comment by Duffney** [comment]
#please-close
