### ISSUE TITLE
The --sdk-auth argument is being deprecated

### ISSUE THREAD

**Issue by johndowns** [MicrosoftDocs/azure-dev-docs#639]
In step 2 in [this section](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#create-a-service-principal-and-add-it-as-a-github-secret) of the document, it advises using the `--sdk-auth` argument to create a JSON-formatted object with the credentials for the service principal.

The Azure CLI team is deprecating the `--sdk-auth` switch. The deprecation notice appeared in v2.30.0 and is also [listed in the release notes](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#role).

Can you please update the document with the latest guidance to follow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks, we've since addressed this issue. 

#please-close
