### ISSUE TITLE
How to setup the redirectURI

### ISSUE THREAD

**Issue by tenzin-ravi** [MicrosoftDocs/azure-dev-docs#642]
Wonderful article. I need your help. The redirect URI is set to the value of default of http://localhost:8080/login/oauth2/code. How do I change it?

Thank you in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@edburns can you answer? Thanks!

**Comment by KarlErickson** [comment]
@edburns ping

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by chenrujun** [comment]
Hi, @tenzin-ravi 

Please try **spring.cloud.azure.active-directory.b2c.reply-url**.

Refs: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-appendix#azure-active-directory-b2c-properties
