### ISSUE TITLE
Dynamic inventory may not be working with newer versions of Ansible

### ISSUE THREAD

**Issue by lasertown** [MicrosoftDocs/azure-dev-docs#645]
The Ansible dynamic inventory seems like it is not working in the latest version of ansible:
$ ansible --version
ansible [core 2.11.6]
  config file = /home/x/throughput_test/ansible.cfg
  configured module search path = ['/home/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/x/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True

The dynamic inventory has stopped working without any changes to my ansible and terraform code projects.  I am using terraform to create my resources, which may be relevant.  My inventory shows:
@all:
  |--@ungrouped:

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059a1972-09ee-02a7-8159-07ba04a2c763
* Version Independent ID: 4323aa16-062c-1b11-fb73-11777c34f88e
* Content: [Tutorial - Configure dynamic inventories for Azure Virtual Machines using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/dynamic-inventory-configure?tabs=azure-cli)
* Content Source: [articles/ansible/dynamic-inventory-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/dynamic-inventory-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
The Dynamic Inventory script has a known bug that throws an error if the resource is in update or delete state. This bug is being worked on.
