### ISSUE TITLE
Formatting error in Jenkins deployment tutorial

### ISSUE THREAD

**Issue by joncooke** [MicrosoftDocs/azure-dev-docs#647]
![image](https://user-images.githubusercontent.com/6512280/143428884-b6e8c59f-0914-4e14-a0b6-d5f8588764e9.png)

I'm pretty sure the 'as' should be outside the credential name highlighting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8984381e-8bfd-776c-c2f7-cc0f608c756d
* Version Independent ID: 73f51811-5f38-a96a-58c6-0683c0242ee4
* Content: [Tutorial - Deploy to Azure Functions using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-to-azure-functions)
* Content Source: [articles/jenkins/deploy-to-azure-functions.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-to-azure-functions.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@joncooke Thanks. The article has been updated and will publish tomorrow.
