### ISSUE TITLE
Can't get the Xamarin Forms Todo App to work with ASP.NET Core backend service

### ISSUE THREAD

**Issue by khambley** [MicrosoftDocs/azure-dev-docs#654]
So, I created my own ASP.NET Core 6.0 Data Sync backend service, deployed it to Azure with a public endpoint. I initially got the "API-VERSION missing" error but then I appended the ZUMO-API-VERSION=2.0.0 to my query string and got back a 200 OK response along with data from my Azure SQL database in Postman. I very closely followed your instructions to wire up the sample Todo Azure Mobile App in Xamarin.Forms and I can't get it to work. I get a "Request cannot be completed. (Not Found)" error in both Android and iOS simulators. What am I missing? I'm about to pull my hair out! This would be a great tool if I can prove it works! Help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbf00e2a-56e1-3da7-859a-a7563dd9148b
* Version Independent ID: 2866c1ea-6a4e-27e5-ce7f-34153eaf6c94
* Content: [Build a Xamarin.Forms app with Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/index.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/index.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Without seeing code, I don't think I can answer this.  Can you post a link to a GitHub repo with your .NET Core service code in it?

**Comment by adrianhall** [comment]
Also, please skip over to the discussions and issues at azure/azure-mobile-apps - that's where I am providing support for the code.  Thanks!

**Comment by khambley** [comment]
Thanks for the quick reply! I moved my question over to the discussions here, https://github.com/Azure/azure-mobile-apps/discussions/270 and I included my public Github repo with the code like you asked. Thanks in advance for any help you can provide! Katherine.

**Comment by adrianhall** [comment]
#close
