### ISSUE TITLE
Where do you configure the connection string?

### ISSUE THREAD

**Issue by khambley** [MicrosoftDocs/azure-dev-docs#655]
You don't explain how to configure the connection string for the database in your instructions. Also, you don't explain how to redeploy the node.js service if you want to add or modify the tables in the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffeddd9-6452-14b1-e6e7-e1185edcb686
* Version Independent ID: 71ce9e1b-fdee-be3f-ca87-3df2d1a7f7a3
* Content: [How to use the Node.js SDK for Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/server/nodejs)
* Content Source: [articles/mobile-apps/azure-mobile-apps/howto/server/nodejs.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/azure-mobile-apps/howto/server/nodejs.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Hello,

The docs include this statement:

**Comment by adrianhall** [comment]
#close

**Comment by adrianhall** [comment]
This is no longer relevant as the document has been unlinked and the NodeJS version has been retired.

#please-close
