### ISSUE TITLE
Documentation bug in the configurable properties

### ISSUE THREAD

**Issue by PbALpi7xEX** [MicrosoftDocs/azure-dev-docs#658]
Documentation bug on the configurable properties.

**azure.activedirectory.user-group.allowed-groups** should read **azure.activedirectory.user-group.allowed-group-names**

Using the former produces a warning in stacktrace to update to new config value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba254924-0fee-04dd-6db0-f7588106a3c1
* Version Independent ID: b689c92c-8fdd-a3de-d13e-889934dbb734
* Content: [Spring Boot Starter for Azure Active Directory developer's guide](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide)
* Content Source: [articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **shaozliu**

**Comment by KarlErickson** [comment]
@stliu can you validate this? I will update the article if you approve. Thanks!

**Comment by KarlErickson** [comment]
@stliu ping
