### ISSUE TITLE
The code for creating a service principal with PowerShell is wrong

### ISSUE THREAD

**Issue by bernd-spieth** [MicrosoftDocs/azure-dev-docs#660]
The service principal object has no attribute ApplicationID instead it has AppId. Also the code for retrieving the secret does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cbb8da-d7df-723f-c7a5-5872381bb4aa
* Version Independent ID: fbd4f2e5-d160-236e-8cc0-ea58ac18a1d0
* Content: [Get Started - Install Terraform on Windows with Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-windows-powershell?tabs=azure-powershell)
* Content Source: [articles/terraform/get-started-windows-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-windows-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@bernd-spieth Thank you for your feedback and patience. This article has been updated and will publish tomorrow.
