### ISSUE TITLE
Documentation is incorrect and incomplete

### ISSUE THREAD

**Issue by webpwnized** [MicrosoftDocs/azure-dev-docs#665]
It is not possible to log into the VM using the example provided because the example does not include the SSH key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 769cffa1-15de-54d1-3ddc-84e67972b44e
* Version Independent ID: 41340ea6-9fbe-45f5-e4e7-4194cab9fb76
* Content: [SSH to virtual machine - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/nodejs-virtual-machine-vm/connect-linux-virtual-machine-ssh)
* Content Source: [articles/javascript/tutorial/nodejs-virtual-machine-vm/connect-linux-virtual-machine-ssh.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/nodejs-virtual-machine-vm/connect-linux-virtual-machine-ssh.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@webpwnized Hi Jeremy, The SSH keys are supposed to be placed on your machine when you [created the VM](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/nodejs-virtual-machine-vm/create-linux-virtual-machine-azure-cli#create-a-virtual-machine-resource). The command should have displayed where the keys were stored. Can you verify you don't have any SSH keys on your computer in the default location?

#in-progress

**Comment by diberry** [comment]
@webpwnized - I'm going to close this now. If you find that your SSH keys were not on your local computer after you created the VM, please let us know what steps you took to debug that so we can pass that information along. #please-close
