### ISSUE TITLE
restart the cloud shell for updated terraform binary

### ISSUE THREAD

**Issue by thomasknowles** [MicrosoftDocs/azure-dev-docs#666]
If you needed to create the bin directory and move the updated Terraform binary into it, the user may need to "restart" their close shell session for the command "terraform version" to properly work with the updated binary. I experienced this in the bash shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89ec2c-6792-5fda-8838-e4b4aac79960
* Version Independent ID: 357320a3-8d02-d834-6553-d183584e8639
* Content: [Get Started - Configure Terraform in Azure Cloud Shell with Bash](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-bash?tabs=bash)
* Content Source: [articles/terraform/get-started-cloud-shell-bash.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell-bash.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@thomasknowles Thanks for the feedback on your experience. I've added a step to the instructions to restart Cloud Shell after copying the Terraform executable into the bin directory. The article should republish tomorrow.
