### ISSUE TITLE
Appreciate this page!

### ISSUE THREAD

**Issue by abhidotnet** [MicrosoftDocs/azure-dev-docs#667]
The examples on this page worked flawlessly and I am glad for this.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbf00e2a-56e1-3da7-859a-a7563dd9148b
* Version Independent ID: 2866c1ea-6a4e-27e5-ce7f-34153eaf6c94
* Content: [Build a Xamarin.Forms app with Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/index.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/index.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by KarlErickson** [comment]
@abhidotnet thanks for the feedback! Glad that it's helping you.

CC @adrianhall
