### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by adanaher** [MicrosoftDocs/azure-dev-docs#668]
I believe there is an error in the code provided on this screen. When running locally or deploying to Azure with the code as written, I'm getting the following error: "None of [Index(['Segment', 'Country', 'Units Sold', 'Gross Sales', 'Date'], dtype='object')] are in the [columns]" 

I believe the line of code that creates the cols list should be:
cols = ['segment', 'country', 'units_sold', 'gross_sales', 'date']

This is because the column names have already been converted to lowercase and had spaces replaced with underscores by the time this variable is used to filter the columns in the processed dataframe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d2c9309-2af1-7e36-ecb9-a092224e2355
* Version Independent ID: 47dfbb72-e141-486d-a645-2ec8d5c41bbf
* Content: [Transform relational data with Pandas and Azure Function Apps](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-serverless-cloud-etl-04)
* Content Source: [articles/python/tutorial-deploy-serverless-cloud-etl-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-deploy-serverless-cloud-etl-04.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by diberry** [comment]
#self-assign

**Comment by diberry** [comment]
This article needs to be updated as part of the event release this month.

**Comment by diberry** [comment]
@adanaher Thank you for this fix. It will be in the next publishing cycle within 24 hours.
