### ISSUE TITLE
A section of this page is not accurate.

### ISSUE THREAD

**Issue by abhidotnet** [MicrosoftDocs/azure-dev-docs#669]
There is no Authentication / Authorization link. There is an Authentication link.
That link brings you up to a page that says "Add Identity Provider".
There are 2 tabs. Basics and Permissions.

In the Basics tab you need to select the Identity Provider as Microsoft.
Then you need to add the issuer URL.

There is no tab  or link titled "Advanced". Am I missing something or this page is not right?

There are 12 steps in the section. Copied the section below.

>Configure Azure App Service Authentication and Authorization
>In the Azure portal, select All Resources, then your App Service.
>Select Settings > Authentication / Authorization.
>Ensure that App Service Authentication is On.
>Under Authentication Providers, select Azure Active Directory.
>Select Advanced under Management mode.
>Paste the Application (client) ID that you obtained earlier.
>Enter https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0 into the Issuer Url field. This URL is the "magic tenant url" for Microsoft logins.
>Press Show secret. Paste the client secret value into the field that appears.
>Select OK.
>Set Action to take when request is not authenticated to Log in with Azure Active Directory.
>In the Allowed External Redirect URLs, enter zumoquickstart://easyauth.callback.
>Select Save.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5316c2b4-4da6-e294-f8d5-caa49dc3ab1c
* Version Independent ID: 2947c751-f42c-001b-b1d2-c512aec7cdea
* Content: [Add authentication to your Xamarin.Forms app](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Looks like App Service has just updated their side-bar and functionality for Authentication / Authorization.  This is a good thing (since you have a lot more options and it's a simpler flow), but it's completely changed this section of the tutorial.  

the initial part is:

* Select Settings > Authentication
* Press Add Identity Provider
* Select "Microsoft" from the drop-down as the identity provider.
* Fill in the form (appliction ID, client secret, and issuer URL)
* Select "HTTP 401" for unauthenticated requests
* Click Add

Once it's been linked, the "allowed external redirect URLs" list is available and you can enter the value there.

I'll need to update the tutorial accordingly. 

(Triage: Assign to me)

**Comment by abhidotnet** [comment]
Thanks for replying to me! Most of my posts are simply getting ignored. I also try to give positive feedback when things work seamlessly.

**Comment by abhidotnet** [comment]
Also, is it possible to show (preferably a screenshot) where is the field that will take the client secret?

**Comment by abhidotnet** [comment]
This is the error I get when I run the app. Is there something I am missing?

![zumo_error](https://user-images.githubusercontent.com/164457/146278183-cc08eca7-5839-494e-aec2-6934f44302b3.png)
.

**Comment by adrianhall** [comment]
The client secret is entered when you configure the identity provider.  I have not played with the new authentication configuration yet, so I want to ensure I'm giving the correct advice.

I need to walk through the entire tutorial with the new settings and work out what is wrong.  I'll update the tutorial this week (probably Friday - that's when I normally have time to work on this stuff).  I will then post here to say I've updated it and you can re-try.

**Comment by abhidotnet** [comment]
@adrianhall I am getting the same error as before. This is the URL my app hits.
https://zumo-exk7wo5vca7wq.azurewebsites.net/.auth/login/aad?post_login_redirect_url=zumoquickstart%3A%2F%2Feasyauth.callback%2F&code_challenge=v7bv76kDZLSDL8CWumu0LwUx%2FLAaA1SLaNU3rnz%2FGBg%3D&code_challenge_method=S256&session_mode=token

and then it shows a message stating "This page is not working right now".

**Comment by adrianhall** [comment]
There is something else going on with your configuration then.  I walked through the specific instructions for each tutorial to ensure working knowledge.  I'd back out the changes (including the AAD configuration), and start over.

**Comment by adrianhall** [comment]
The value (as it says).

**Comment by abhidotnet** [comment]
The error has changed. Instead of prompting me to a login screen, I am now getting this message in the emulator.

![androidEmulatorError](https://user-images.githubusercontent.com/164457/146977533-1e93a53f-b64a-4224-afd8-4b466636263a.png)

**Comment by adrianhall** [comment]
You did not properly follow the instructions for setting up the AAD application registration.

Explicitly, it says:

**Comment by abhidotnet** [comment]
You're correct. I deleted the group and recreated the app registration. I believe I have followed all the instructions as I am able to see a login screen in the Android Emulator. 

However once I have logged in, it doesn't navigate to the app. Instead, it just stays on a blank page in the webview. 
The attached screen recording will give you an idea.

https://user-images.githubusercontent.com/164457/147130623-2aac5251-1b2e-4cf4-8a01-2a683dc3306f.mp4

.

**Comment by abhidotnet** [comment]
When I worked on the UWP project, there is some progress. I am able to see the TODO list, but as soon as I add an item, I get a runtime error. I don't know if this is related to the documentation or the samples that are being maintained in Github. 

https://user-images.githubusercontent.com/164457/147144693-21506587-4cdb-4776-8398-710fa05b78e7.mp4

**Comment by adrianhall** [comment]
This has moved beyond a documentation problem at this point, and into the realm of diagnosing issues with your environment, code, and so on.  I'm happy to continue working with you (although I am taking the christmas period off, so it will be the new year).  However, I do not do prodct support here.  Product support is done over on the azure/azure-mobile-apps github repository (there is a discussion board for this sort of thing).  This will allow the community to assist as well.

I look forward to seeing you over there!

**Comment by abhidotnet** [comment]
Thanks for pointing me in the right direction. I will raise an issue with the community you've mentioned.

**Comment by adrianhall** [comment]
This is complete now.

#please-close
