### ISSUE TITLE
Wrong TOC for Express.js on Linux VM tutorial

### ISSUE THREAD

**Issue by ItalyPaleAle** [MicrosoftDocs/azure-dev-docs#670]
On the page linked below, the TOC seems not to match the contetn:
![image](https://user-images.githubusercontent.com/43508/146269912-94c23f69-bafd-47fc-8bb4-33c2b61b467a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b287689c-78b2-f375-b266-169a7a0b020a
* Version Independent ID: 778902dd-ade9-050b-b400-acb2238944dd
* Content: [Azure CLI Linux virtual machine - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/nodejs-virtual-machine-vm/introduction)
* Content Source: [articles/javascript/tutorial/nodejs-virtual-machine-vm/introduction.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/nodejs-virtual-machine-vm/introduction.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
#in-progress Thank you for reporting this.

**Comment by diberry** [comment]
This has been fixed in the TOC. #please-close
