### ISSUE TITLE
Issues with Node.js VM tutorial

### ISSUE THREAD

**Issue by ItalyPaleAle** [MicrosoftDocs/azure-dev-docs#671]
In the page linked below, there are a few issues:

1. The tutorial recommends using Node.js 12, which is an old version currently in maintenance mode. Will reach EOL in April. Suggest updating to a more recent build, such as Node.js 16 (current LTS)
2. The app is started by the cloud-init script with this command: `cd myapp && npm install && npm start'`. Because the app is started by cloud-init, and the cloud-init scripts only run on first boot, on a reboot of the VM the app would not be started automatically. I recommend setting up a process manager, which could simply be systemd.
3. `service nginx restart` -> `systemctl restart nginx` to use the modern systemctl commands

This may be helpful: https://withblue.ink/2018/12/02/node-js-web-apps-in-ubuntu-production-ready.html it's a bit outdated because it uses Ubuntu 18.04 and an older version of Node.js, but the same setup should work with Ubuntu 20.04 (current LTS) and Node.js 16 too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ecaed2-8f8e-f03e-235d-e3de39d3b217
* Version Independent ID: e70134e2-4930-96ea-cfe8-c66146fce3ef
* Content: [Create Linux virtual machine - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/nodejs-virtual-machine-vm/create-linux-virtual-machine-azure-cli)
* Content Source: [articles/javascript/tutorial/nodejs-virtual-machine-vm/create-linux-virtual-machine-azure-cli.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/tutorial/nodejs-virtual-machine-vm/create-linux-virtual-machine-azure-cli.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
#in-progress
