### ISSUE TITLE
If the storage account is not global azure, will get 'no such host is known' error

### ISSUE THREAD

**Issue by arrebnac** [MicrosoftDocs/azure-dev-docs#672]
We are using Azure Mooncake.
When using the spring boot sample code for eventhub, we got 'no such host is known' error for storage.
In the error message it says can't find xxx.blob.core.windows.net, but actually the blob storage on mooncake is xxx.blob.core.chinacloudapi.cn.
How to set the azure china in the code?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [How to create a Spring Cloud Stream Binder application with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **brendm**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by KarlErickson** [comment]
@chenrujun will do. You can also do it yourself like this:

#assign:@yiliuTo

**Comment by KarlErickson** [comment]
#assign:yiliuTo

**Comment by KarlErickson** [comment]
@chenrujun normally this works, but apparently there's a problem at the moment, so I'll go ahead and make all the requested assignments using the admin UI.

**Comment by chenrujun** [comment]
@KarlErickson 

I got it. Thank you.

**Comment by yiliuTo** [comment]
Hi @canberra2002 , if you are using the access key as credentials, then to connect to Storage blob in Azure China cloud, please add anther property on the basis of contain name, account name and account key, which should be `spring.cloud.azure.eventhubs.processor.checkpoint-store.endpoint=https://<your-account-name>.blob.core.chinacloudapi.cn`. This suggestion works on version 4.x of library `spring-cloud-azure-stream-binder-eventhubs`. Let me know if you are using another version or other credentials.
