### ISSUE TITLE
Add Go mgmt page to ToC

### ISSUE THREAD

**Issue by kimprice** [MicrosoftDocs/azure-dev-docs#675]
Add the Go management SDK page (https://docs.microsoft.com/en-us/azure/developer/go/management-libraries) as a subpage on the ToC under either "Use the Azure SDK for Go" or "What is the Azure SDK for Go?"

**Comment by KarlErickson** [comment]
Hi @kimprice - thanks for filing the issue! For internal work items, please work with the content publisher (in this case, @Duffney) to track work items internally using Azure DevOps, rather than using the GitHub issues list. We want to reserve the issues list for customer issues. Thanks!
