### ISSUE TITLE
The container image

### ISSUE THREAD

**Issue by cenzwong** [MicrosoftDocs/azure-dev-docs#676]
The Container Image should changed 

from 
image  = "microsoft/azure-vote-front:cosmosdb"
to
image  = "mcr.microsoft.com/azuredocs/azure-vote-front:cosmosdb"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e206df2-ca76-283a-0689-4aa90229a5c2
* Version Independent ID: d7475eda-b72a-7799-7942-fb2010e56f66
* Content: [Deploy an Azure Cosmos DB to Azure Container Instances](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-azure-cosmos-db-to-azure-container-instances)
* Content Source: [articles/terraform/deploy-azure-cosmos-db-to-azure-container-instances.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/deploy-azure-cosmos-db-to-azure-container-instances.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@cenzwong Thanks for the update. The image location value has been updated and the article will republish later today or tomorrow.
