### ISSUE TITLE
yaml field initialization value not specified

### ISSUE THREAD

**Issue by datasmithadvtech** [MicrosoftDocs/azure-dev-docs#677]
on https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc , it says, be sure to properly configure user-name-attribute-name in the application.yml file

however, how should this field be initialized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by datasmithadvtech** [comment]
It says, "When creating the user workflow, for User attributes and claims, be sure to choose attributes and claims for Display Name. Also, be sure to properly configure user-name-attribute-name in the application.yml file."

user-name-attribute-name: <your-user-name-attribute-name> 

I am returning Display Name in user flows, it is not clear what value i should use for user-name-attribute-name:

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by KarlErickson** [comment]
#assign:chenrujun

**Comment by chenrujun** [comment]
Hi, @datasmithadvtech 

Thanks for reaching out.
The **user-name-attribute-name** can be **name**.

Refer to [Troubleshooting/Missing attribute name in attributes](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc#missing-attribute-name-in-attributes) to get more information if you face problem about **Missing attribute 'name' in attributes**.
