### ISSUE TITLE
Static Web Apps sample not work

### ISSUE THREAD

**Issue by georgeOsdDev** [MicrosoftDocs/azure-dev-docs#684]
[Enter feedback here]

`npm start` command defined in `package.json` file's scripts section not work correctly.
Also I made patch for sample app repository.
https://github.com/Azure-Samples/js-e2e-static-web-app-with-cli/pull/6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75fe702d-5a31-b7f7-4f58-d90d691da79a
* Version Independent ID: d2d978b5-c834-c188-bc42-a4e0172d3930
* Content: [6-Integration: Connect app to API - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/how-to/with-web-app/static-web-app-with-swa-cli/connect-client-to-api)
* Content Source: [articles/javascript/how-to/with-web-app/static-web-app-with-swa-cli/connect-client-to-api.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/javascript/how-to/with-web-app/static-web-app-with-swa-cli/connect-client-to-api.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
#in-progress

**Comment by diberry** [comment]
@georgeOsdDev Can you tell me more about what isn't working? What operating system and version of node, what is the error you are seeing, or other expected behavior you didn't see?

**Comment by georgeOsdDev** [comment]
Hi @diberry 
Examples in package.json is not working.
I tried it on Ubuntu 20.04.1 LTS
```
node -v
v14.17.6
$ npm -v
6.14.15
```
But I think is not related to OS, version, etc. It is simply wrong in `npm start`. 
`npm start` could not start Azure Static Web Apps emulator sat http://localhost:4280

- swa-up is not defined in package.json. use start-swa instead.
- Also && will wait success exit of previous command. so that we should use &

<img width="464" alt="image" src="https://user-images.githubusercontent.com/1381907/151326625-78b349ce-17e1-4be7-a117-5245606198e0.png">

See:
Azure-Samples/js-e2e-static-web-app-with-cli#6

**Comment by diberry** [comment]
@georgeOsdDev - I updated the package.json. Please try it now. I would love to learn more about how you came to this sample and your experience with it. If you have time for a call or email, let me know.

**Comment by diberry** [comment]
#please-close
