### ISSUE TITLE
FirebaseInstanceId is deprecated - please update documentation.

### ISSUE THREAD

**Issue by M-Rostock** [MicrosoftDocs/azure-dev-docs#685]
The FireBaseInstanceId class is deprecated and have been replaced with the FirebaseInstallations class - see https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.

As far as I can tell, the code example below must be updated:

Old:
```
if(DeviceInstallationService.NotificationsSupported)
{
	FirebaseInstanceId.GetInstance(Firebase.FirebaseApp.Instance)
			.GetInstanceId()
			.AddOnSuccessListener(this);
}
```
New:
```
if(DeviceInstallationService.NotificationsSupported)
{
	FirebaseInstallations.GetInstance(Firebase.FirebaseApp.Instance)
		.GetId()
		.AddOnSuccessListener(???);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by aosyatnik** [comment]
@mikeparker104  any updates on this?

**Comment by aosyatnik** [comment]
For those, who follow article, these changes need to be made.
You need to make `MainActivity` implement `IOnSuccessListener`, like this:
```C#
public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity, IOnSuccessListener
```

Also you need update code like this:
```C#
if (DeviceInstallationService.NotificationsSupported)
{            
    FirebaseInstallations.GetInstance(Firebase.FirebaseApp.Instance)
                     .GetId()
                     .AddOnSuccessListener(this);
}
```

And you need to update `OnSuccess` like this:
```C#
public void OnSuccess(Java.Lang.Object result)
{ 
    DeviceInstallationService.Token = result.ToString();
}
```

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
