### ISSUE TITLE
Somehow confusing document

### ISSUE THREAD

**Issue by vgirnet** [MicrosoftDocs/azure-dev-docs#689]
[Enter feedback here]

Tried all steps as described, but didn't work. 

Steps like how to get IDs of application/tenant are confusing. 

Please review it, and adjust. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux#use-the-azure-login-action-with-openid-connect)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks, we've since updated the document for clarity. 

#please-close
