### ISSUE TITLE
Url does not having enough information.

### ISSUE THREAD

**Issue by sarathraj-coder** [MicrosoftDocs/azure-dev-docs#691]
[Enter feedback here]

Url does not having enough information. [url for habitat is wrong in page](https://docs.microsoft.com/en-us/azure/developer/chef/habitat-overview)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115807e-01cf-9b92-01e0-6a55ee86a4d4
* Version Independent ID: a23dc1b4-7559-5aea-267e-742f6f5dd74b
* Content: [Use Habitat to deploy your application to Azure](https://docs.microsoft.com/en-us/azure/developer/chef/habitat-overview)
* Content Source: [articles/chef/habitat-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/chef/habitat-overview.md)
* Service: **chef**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sarathraj-coder Thanks for your feedback. However, we no longer document Chef on Azure. Chef Software provided that URL as the one they want us to use in forwarding Chef users to their site. Please follow up with Chef Software via their site if something needs to be changed regarding the URL being used.
