### ISSUE TITLE
Url does not having enough information

### ISSUE THREAD

**Issue by sarathraj-coder** [MicrosoftDocs/azure-dev-docs#692]
[url for InSpec](https://docs.microsoft.com/en-us/azure/developer/chef/inspec-overview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31874f60-fbbb-5b60-7352-a7780dfebac2
* Version Independent ID: 6d81c340-c562-624a-3b3f-66444a2d190e
* Content: [Use InSpec for compliance automation of your Azure infrastructure](https://docs.microsoft.com/en-us/azure/developer/chef/inspec-overview)
* Content Source: [articles/chef/inspec-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/chef/inspec-overview.md)
* Service: **chef**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sarathraj-coder Thanks for your feedback. As noted in Issue #691, we no longer document Chef on Azure. Chef Software provided that URL as the one they want us to use in forwarding Chef users to their site. Please follow up with Chef Software via their site if something needs to be changed regarding the URL being used.
