### ISSUE TITLE
parse-multipart   has some bugs not fixed by author

### ISSUE THREAD

**Issue by aclottan** [MicrosoftDocs/azure-dev-docs#696]
[Enter feedback here]

the package that you use 'parse-multipart' have many flaws that are not fixed/merged by the author for a couple of years now.
it caused me to spend hours try to figure our the errors i get in the function.

i used a forked and fixed version of that package: 'parse-multipart-data'
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fccbc7c0-7c8f-f796-5412-56c1ea5d660e
* Version Independent ID: 41a2325e-3363-d173-7779-d2517e624e7a
* Content: [Upload file to Storage - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/how-to/with-web-app/azure-function-file-upload)
* Content Source: [articles/javascript/how-to/with-web-app/azure-function-file-upload.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/how-to/with-web-app/azure-function-file-upload.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@aclottan - Thank you for letting us know. We'll review and fix. #in-progress.

**Comment by diberry** [comment]
@aclottan - I've tested this on both Windows and Mac with Node 14 and it works for me. I've also tested on a Linux DevContainer with Node 14. Can you tell me more about your setup, hardware, os, node version, function version, etc?

**Comment by diberry** [comment]
Without more information, I'll close this issue. Please reopen when you can tell me more about it. #please-close

**Comment by aclottan** [comment]
please reopen.
here are the details of my sample:

 the call is from an angular application:
 
 
 
  const formData = new FormData();
//report and singleFile are application objects
  const fileDTO: FileDTO = {reportDetails: report, file: singleFile};
  formData.append( 'fileDto', JSON.stringify( fileDTO ) )
   
 this.httpClient.post( `${url}/uploadFile`, formData ).subscribe();
         
  ---------------------
  the code in the function
  
  
  
  import { AzureFunction, Context, HttpRequest } from '@azure/functions';
import * as multipart from 'parse-multipart';
import { FileDTO, FileToUpload, ReportDetails } from '../../api-interfaces/';
const httpTrigger: AzureFunction = async function (
  context: Context,
  req: HttpRequest
): Promise<any> {
  context.log('HTTP trigger function processed a request.');

  if (!req.body || !req.body.length) {
    context.res.body = `Request body is not defined`;
    context.res.status = 500;
    return context.res;
  }

  const bodyBuffer = Buffer.from(req.body);
  const boundary = multipart.getBoundary(req.headers['content-type']);
  const parts = multipart.Parse(bodyBuffer, boundary);

  const fileDTO: FileDTO = JSON.parse(parts[0].data.toString());


////
the error received:

System.Private.CoreLib: Exception while executing function: Functions.uploadFile. System.Private.CoreLib: Result: Failure        
Exception: TypeError: Cannot read properties of undefined (reading 'split')   
Stack: TypeError: Cannot read properties of undefined (reading 'split')  

//////////
the issue is documented in the repo

https://github.com/freesoftwarefactory/parse-multipart/issues/4
and
https://github.com/freesoftwarefactory/parse-multipart/issues/2

but never resolved for a couple of years

**Comment by diberry** [comment]
@aclottan And you get the same error if you make the request from curl?

**Comment by aclottan** [comment]
thanks for your prompt reply.
when i switch to the forked and fixed version "parse-multipart-data" everything works ok with the exact same code (except for the Parse function that is now in lowercase "parse".
i send a json object that includes a base64 encoding of an image. the size is approx 56K

**Comment by diberry** [comment]
@aclottan - thank you for working through this. I've updated the code to check for the required properties, and added notes in the sample repo.
