### ISSUE TITLE
uses depricated packages, example code doesn't work as is (without modification to use the new packages)

### ISSUE THREAD

**Issue by ealasgarov** [MicrosoftDocs/azure-dev-docs#697]
These are the new packages (new URLs) which should be quoted in examples:
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc812f1-5c2e-f614-50a8-240851237ce6
* Version Independent ID: f84a275e-df66-5225-b5dd-b3e0cfbd15c4
* Content: [Azure SDK for Go authentication with a service principal](https://docs.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication-service-principal?tabs=azure-cli)
* Content Source: [articles/go/azure-sdk-authentication-service-principal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/azure-sdk-authentication-service-principal.md)
* Service: **azure**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by Duffney** [comment]
Hi @ealasgarov,

I've updated the article with a different sample that uses the latest packages, resolving the deprecation warnings. Please let me know if this doesn't resolve the issue for you.

Thank you filing this issue, have a great day! :)

**Comment by Duffney** [comment]
#please-close
