### ISSUE TITLE
Manage resource groups with the Azure SDK for Go - Deprecation warnings and errors

### ISSUE THREAD

**Issue by rvben** [MicrosoftDocs/azure-dev-docs#698]
Trying to follow the example in the page results in deprecation warnings and errors.
Following the advise printed in the console to 'use this instead', does not result in a working example.
This is very unfortunate for a 'simple example' that should get you started.

Kind regards,

Ruben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842c31dc-7df1-9052-cdcf-c5e03fae0766
* Version Independent ID: e3a655d2-ac7a-1d23-16d5-3d0d50fc673e
* Content: [Manage resource groups with the Azure SDK for Go](https://docs.microsoft.com/en-us/azure/developer/go/manage-resource-groups?tabs=windows%2Cazure-portal#feedback)
* Content Source: [articles/go/manage-resource-groups.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/manage-resource-groups.md)
* Service: **azure**
* GitHub Login: @Duffney
* Microsoft Alias: **jduffney**

**Comment by Duffney** [comment]
Hey @rvben,

I've updated the docs to use the latest packages for resource manager, which is [armresources](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armresources). You shoud no longer receive the deprecation warnings and errors that you did previously.

Thank you for filing this issue, have a wonderful day! :)
