### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by saugusto** [MicrosoftDocs/azure-dev-docs#7]
"with … azure function core tools..." https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local.md#v2 broken 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6a3f99-4725-7f93-301e-da4ba69d4986
* Version Independent ID: 3477aa24-7135-e6e9-3791-17d66052589e
* Content: [Create and deploy serverless Azure Functions in Python with Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-vs-code-serverless-python-01#feedback)
* Content Source: [python/tutorial-vs-code-serverless-python-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-vs-code-serverless-python-01.md)
* Service: **azure-functions**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@saugusto Thanks for catching that...the ".md" shouldn't be in the link. I'll get that corrected.

**Comment by kraigb** [comment]
The fix should be published later today. Please close this issue once you've confirmed. Thanks.
