### ISSUE TITLE
Authenticating using AzureDefaultCredential

### ISSUE THREAD

**Issue by IngridAtMicrosoft** [MicrosoftDocs/azure-dev-docs#701]
Hi there,
I am writing Python code samples for Azure Media Services.  The AzureDefaultCredential in azure.identity is not documented here and probably should be.  Please see 

https://docs.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#authenticate-with-defaultazurecredential

Ingrid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb3e07-c6f8-efc3-2fba-d87ea4ce3e17
* Version Independent ID: 8da49a57-9830-998c-d93d-c3b0df683583
* Content: [How to authenticate Python applications with Azure services (alternate methods)](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-development-environments)
* Content Source: [articles/python/azure-sdk-authenticate-development-environments.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/azure-sdk-authenticate-development-environments.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by DavidCBerry13** [comment]
#assign: DavoidCBerry13

**Comment by KarlErickson** [comment]
#assign:@DavidCBerry13

**Comment by DavidCBerry13** [comment]
@IngridAtMicrosoft - I just rewrote all of the Azure Python SDK auth content to cover DefaultAzureCredential and how this works going from local development to server environments.  I think that solves the problem you were highlighting here, so I am going to close this out.

#please-close
