### ISSUE TITLE
[ANDROID] Intent extras lost

### ISSUE THREAD

**Issue by MattePozzy** [MicrosoftDocs/azure-dev-docs#702]
Hi,
I have follow [this](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#option-2-creating-a-p8-certificate-that-can-be-used-for-token-based-authentication) guide to setup push notification in my Xamarin Forms app.

I have an app with two activity,
one splash activity
```
Activity(Theme = "@style/SplashTheme",
        MainLauncher = true, ScreenOrientation = ScreenOrientation.Portrait, NoHistory = true)]
    public class SplashAct: Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            StartActivity(typeof(MainActivity));
            Finish();
        }
    }
```
and the MainActivity

```
 [Activity(
        ClearTaskOnLaunch = false,
        FinishOnTaskLaunch = false,
        Theme = "@style/MainTheme",
        LaunchMode = LaunchMode.SingleTask,
        ScreenOrientation = ScreenOrientation.Portrait,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public partial class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity, Android.Gms.Tasks.IOnSuccessListener
```

in the main activity I have override the OnNewIntent method
```
     protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            ProcessNotificationActions(intent);
        }
```
and I have tried to send a notification using a web api published on Azure with this body:
```
{
    "text": "Test msg",
    "action": "action_a"
}
```

on device the text is correctly shown, but when the code reach the `OnNewIntent` method the intent has not extras so I lost the "action" value.

How can I solve this?

NB. I can't use `LaunchMode = LaunchMode.SingleTop` otherwise the `OnNewIntent` is not called, the `OnCreate` is called and the app shows a blank screen.
This happens only if the application is in background or closed. If it is in foreground all works fine.

Thank you.

EDIT: Attached a sample, a video and info to make the POSTMAN\RESTER request.
[Archive.zip](https://github.com/MicrosoftDocs/azure-dev-docs/files/7969438/Archive.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#option-2-creating-a-p8-certificate-that-can-be-used-for-token-based-authentication)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by Raystorm7** [comment]
Hi, any news about this? We need to release an application soon.
Thank you.

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
