### ISSUE TITLE
Inaccurate ToC label

### ISSUE THREAD

**Issue by ArLucaID** [MicrosoftDocs/azure-dev-docs#704]
toc label for this page reads: "Authenticate from Azure to GitHub"
Based on the content, shouldn't it be: "Authenticate from GitHub to azure" or "Authenticate to Azure from Github"?

Apologies if I'm missing something here. 

Thanks,
-Arturo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks @ArLucaID! I think you're right, we want to allow GitHub Actions workflows to access resources in Azure. I'll look at updating the ToC.
