### ISSUE TITLE
Can not use ansible on cloudshell

### ISSUE THREAD

**Issue by hisasima** [MicrosoftDocs/azure-dev-docs#708]
I can not use ansible on cloudshell now. I confirmed that I could use it 2 month ago. Is it bug or is the installation of this document wrong ? I think you can easily reproduce this error.

user@Azure:~$ cat test.yaml 
- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group - "{{ rgname }}"
      azure_rm_resourcegroup:
        name: "{{ rgname }}"
        location: "{{ region }}"
      register: rg
    - debug:
        var: rg
user@Azure:~$ ansible-playbook test.yaml --extra-vars "region=japaneast rgname=NVA-rg1" -vvv

TASK [Creating resource group - "NVA-rg1"] **************************************************************************************************************************************************************************************************
task path: /home/user/test.yaml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314 `" && echo ansible-tmp-1643768887.0003822-321-180849448652314="` echo /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.azure_rm_resourcegroup to azure.azcollection.azure_rm_resourcegroup
Using module file /opt/ansible/lib/python3.7/site-packages/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-183pi8outr1/tmp0hei8xpa TO /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314/AnsiballZ_azure_rm_resourcegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314/ /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/opt/ansible/bin/python /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1643768887.0003822-321-180849448652314/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_resourcegroup_payload_9r_l3p_o/ansible_azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 225, in <module>
    from azure.mgmt.monitor.version import VERSION as monitor_client_version
ModuleNotFoundError: No module named 'azure.mgmt.monitor.version'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "msi",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "force_delete_nonempty": false,
            "location": "japaneast",
            "name": "NVA-rg1",
            "password": null,
            "profile": null,
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on cc-3737ef1b-78ccc458c-xl98n's Python /opt/ansible/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf34277-7542-1451-31c7-a41aeabca49d
* Version Independent ID: b8a2871c-6ddf-4106-70f6-905684c329ef
* Content: [Get Started - Configure Ansible using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?tabs=ansible)
* Content Source: [articles/ansible/getting-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/getting-started-cloud-shell.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by DavidLievrouw** [comment]
I am experiencing this too.

A temporary workaround, is to install a newer version.
- Check the current version with `ansible-playbook --version`
- Run:
  ```
  pip3 install 'ansible[azure]'
  curl -O https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
  pip3 install -r requirements-azure.txt
  ansible-galaxy collection install azure.azcollection
  ```
- Then close the cloud shell, and reopen it. 
- Confirm with `ansible-playbook --version`

Most of it works, but sometimes, I get the following error: `Failed to authenticate with provided credentials. Some attributes were missing. Credentials must include client_id, secret and tenant or ad_user and password, or ad_user, password, client_id, tenant and adfs_authority_url(optional) for ADFS authentication, or be logged in using AzureCLI.`

Did not get around that one. Yet...

Replay:
- `mkdir TestApp`
- `cd TestApp`
- `dotnet new console`
- Program.cs:
```
using System;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;

namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {            
            var p1=Process.Start("ansible-playbook", "--version");
            p1.WaitForExit();
            var p2=Process.Start("/home/david/.local/bin/ansible-playbook", "--version");
            p2.WaitForExit();
            var processStartInfo = new ProcessStartInfo {
                FileName = "/home/david/.local/bin/ansible-playbook",
                Arguments = "azure_create_vm.yml",
                CreateNoWindow = true,
                RedirectStandardOutput = true,
                RedirectStandardInput = true,
                UseShellExecute = false,
                WorkingDirectory = "/home/david/TestApp"
            };         
            var ansibleProcess = new Process();
            ansibleProcess.StartInfo = processStartInfo;
            ansibleProcess.Start();
            ansibleProcess.WaitForExit();
        }
    }
}
```
- `dotnet run`

**Comment by hisasima** [comment]
I tried your work around but it failed. I also tried to run dotnet. Do you have another work around ?

```
ansible-playbook --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]. This feature will be removed from ansible-core in version 2.12.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible-playbook [core 2.11.8]
  config file = None

  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
  jinja version = 3.0.3
  libyaml = False
```

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": "auto",
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "force_delete_nonempty": false,
            "location": "japaneast",
            "log_mode": null,
            "log_path": null,
            "name": "NVA-rg1",
            "password": null,
            "profile": null,
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Failed to authenticate with provided credentials. Some attributes were missing. Credentials must include client_id, secret and tenant or ad_user and password, or ad_user, password, client_id, tenant and adfs_authority_url(optional) for ADFS authentication, or be logged in using AzureCLI."
}
```

**Comment by DavidLievrouw** [comment]
No, I do not, unfortunately.

In my case, it works when I run `ansible-playbook azure_create_vm.yml`, directly in cloud shell (bash).

However, it does not work when I run the program using `dotnet run`. In that case, I get the same error as you (`Failed to authenticate with provided credentials...`). 
I am trying to run `ansible-playbook` through a dotnet tool using `Process.Start()`.

It seems that the newly installed v2.11.8 of Ansible is not properly configured to use the "az" login context, when you run it as a new process, started from a dotnet application. Don't know exactly why.

**Comment by hisasima** [comment]
I think many people encounter this issue now. It this bug ?

**Comment by hisasima** [comment]
I tried bellow operation and it works well. Thanks.

pip3 install 'ansible[azure]'
curl -O https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
pip3 install -r requirements-azure.txt

reopen cloudshell

ansible-galaxy collection install azure.azcollection

**Comment by hisasima** [comment]
When I exported my Subscription ID in advance, the credential error happened. I added it as the extra-vars and it was successful.

export AZURE_SUBSCRIPTION_ID=xxxxx-xxx

**Comment by hisasima** [comment]
When I used below command to use my subscription, the credential error happened. I think "az account set" command is also fine.

export AZURE_SUBSCRIPTION_ID=xxxxx-xxx

**Comment by TomArcherMsft** [comment]
@hisasima @DavidLievrouw 

I am able reproduce similar errors when attempting to run a very simple Ansible playbook.

This is not a doc Issue, so I'm closing this GitHub Issue.

I've opened a [GitHub Issue](https://github.com/Azure/Ansible/issues/24) in the Azure/Ansible repo on your behalf.

I've also emailed the PM who manages that product.

Thank you,
Tom
