### ISSUE TITLE
example code missing .storage in package line

### ISSUE THREAD

**Issue by asherk-kxs** [MicrosoftDocs/azure-dev-docs#711]
I think

```
package com.<your-resource-group>.<your-artifact-name>;
```
should be
```
package com.<your-resource-group>.<your-artifact-name>.storage;
```
given that BlobController.java is placed within a new subfolder "storage"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac19ce1b-2184-5487-67c9-22c4ff97336d
* Version Independent ID: ecc6b6cf-73e4-1575-add0-cb44d7aa4fcf
* Content: [How to use the Spring Boot Starter for Azure Storage](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage.md)
* Service: **storage**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @backwind1233 ?

**Comment by fangjian0423** [comment]
@asherk-kxs thanks for reaching out.

Below code snippets show all package names of Spring Cloud Azure docs:

```bash
package com.contoso.ssltest;
package com.wingtiptoys.servicebus;
package com.<your-resource-group>.<your-artifact-name>;
package com.example.demo;
package yourGroupId.yourGroupId.controller;
package com.wingtiptoys.security;
package com.contoso.eventhubs.sample;
package com.example.servicebus;
....
```

We will discuss how to improve it.
