### ISSUE TITLE
Add artifact coordinates for all azure-core-http implementations

### ISSUE THREAD

**Issue by zavyrylin** [MicrosoftDocs/azure-dev-docs#713]
The doc is great, but It could be much better if it had all artifact names listed in "Replace the default HTTP client" section.

The text claims there is an http client implementation using JDK's HttpClient, but it seems that the artifact is missing (at least on Maven Central). Googling for `JdkAsyncHttpClientBuilder` referred in text gives a couple of links to javadocs, but https://search.maven.org can't find any artifact containing this class.

Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3433a5-66ef-795f-f46a-1611e38e1813
* Version Independent ID: 061b4cd5-e949-f072-9538-cb7d655fb9c8
* Content: [HTTP clients and pipelines in the Azure SDK for Java](https://docs.microsoft.com/en-gb/azure/developer/java/sdk/http-client-pipeline)
* Content Source: [articles/java/sdk/http-client-pipeline.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/sdk/http-client-pipeline.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **srnagar**

**Comment by JonathanGiles** [comment]
Good suggestion @zavyrylin - I'll work on making this change ASAP.

**Comment by srnagar** [comment]
Moved this issue to https://github.com/Azure/azure-sdk-for-java/issues/39239

**Comment by srnagar** [comment]
#please-close
