### ISSUE TITLE
client Id unknown

### ISSUE THREAD

**Issue by pfgarvey** [MicrosoftDocs/azure-dev-docs#714]
[Enter feedback here]

When running this, I get a pause on the client id. In vars, it is empty. I see TFVARS env vars but is this supposed to be imported for the client id? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@pfgarvey Thanks for the question and patience. I'm working on rewriting this article and will have feedback in the coming days.

**Comment by TomArcherMsft** [comment]
@pfgarvey I've updated and tested the article. It will publish around 10 AM (PST) tomorrow. Thanks again for posting your feedback.
