### ISSUE TITLE
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by liuyukuai** [MicrosoftDocs/azure-dev-docs#715]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by nmanandhar** [comment]
I am getting the same issue after following the tutorial. Any suggestion on what could be wrong would be great

**Comment by KarlErickson** [comment]
Thanks for the input, @nmanandhar!

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by chenrujun** [comment]
Hi, @liuyukuai , could you please provide more detail about how does this error happen?

**Comment by chenrujun** [comment]
Hi, @KarlErickson .
Please help to close this issue, because it's not updated for a long time.
