### ISSUE TITLE
 authorization.RoleAssignmentsClient#Create: Failure responding to request : Principals of type Application cannot validly be used in role assignments.

### ISSUE THREAD

**Issue by logcorner** [MicrosoftDocs/azure-dev-docs#717]
Hi
![terraform error](https://user-images.githubusercontent.com/5066547/154677310-9b3cc1d8-969d-4d57-8211-f0b26f9286a2.png)

I got the following error when running the terraform files (**NB** i'm owner of the azure subscription):
 
 _Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments."
│
│   with azurerm_role_assignment.ra1,
│   on resources.tf line 133, in resource "azurerm_role_assignment" "ra1":
│  133: resource "azurerm_role_assignment" "ra1" {
│
╵
╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalTypeNotSupported" Message="Principals of type Application cannot validly be used in role assignments."
│
│   with azurerm_role_assignment.ra2,
│   on resources.tf line 141, in resource "azurerm_role_assignment" "ra2":
│  141: resource "azurerm_role_assignment" "ra2" {_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway ingress controller in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@logcorner Thanks for your feedback. I've completely rewritten and tested this article. It should go live Monday.
