### ISSUE TITLE
async, await and handleRedirectPromise is missing in the azure-authentication-context.ts code

### ISSUE THREAD

**Issue by P47K0** [MicrosoftDocs/azure-dev-docs#718]
Dear,

I couldn't sign in again after signing out (only once I could sign in).
The error code in the javascript console was: `Interaction_in_progress`
I went to the page that was suggested in the error message:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#interaction_in_progress

After reading the details about the problem I added some code to the azure-authentication-context.ts file:
First I added `await `to all (except getAllAccounts) the myMSALObj calls (and the `async `keyword to the function that contains the await call).
Second I added:
`await this.myMSALObj.handleRedirectPromise();`
On the first line of the `getAccount()` method and at the first line of the `login()` method.

Now it works!
Maybe you can correct the code that is listed in this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c627aaef-62e5-1aeb-f034-72790dff714a
* Version Independent ID: ad9d621b-bb91-9d21-2a2e-45183a48c709
* Content: [Tutorial: Add Microsoft login button to React SPA - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/single-page-application-azure-login-button-sdk-msal)
* Content Source: [articles/javascript/tutorial/single-page-application-azure-login-button-sdk-msal.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/tutorial/single-page-application-azure-login-button-sdk-msal.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
Thanks for letting us know. I'll review the doc and fix. #in-progress.

**Comment by P47K0** [comment]
The actual page of the article I mentioned is:
https://docs.microsoft.com/en-us/azure/developer/javascript/tutorial/single-page-application-azure-login-button-sdk-msal

**Comment by diberry** [comment]
@P47K0 - after looking at this sample code and looking at the Identity team's doc and sample, I'm going to retire this sample and point the content to the doc/sample from Identity. 

* [Documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react)
* [Sample](https://github.com/Azure-Samples/ms-identity-javascript-react-spa)

**Comment by diberry** [comment]
#please-close
