### ISSUE TITLE
Azure PostgreSQL connection setup using Managed Identity in Spring Boot JPA

### ISSUE THREAD

**Issue by vtapadia** [MicrosoftDocs/azure-dev-docs#719]
As the title suggests, I am looking for a sample on how we can use Managed Identity in Spring Boot JPA to connect to a PostgreSQL database.

The setup on the database and linking is all done, but the connection setup is not clear and the suggestions on using API calls sounds not polished for production usage. Is there abstraction and azure provided sdks available for this use case. Would be really helpful.

I guess you are already using this in the Azure Spring Cloud setup, so it might just be missing documentation. Any help would be greatly appreciated.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d7ffb1-3e05-a916-8133-0ba300ec46b9
* Version Independent ID: b8d7ffb1-3e05-a916-8133-0ba300ec46b9
* Content: [Java libraries, drivers, and Spring modules for Azure](https://docs.microsoft.com/en-gb/azure/developer/java/sdk/libraries-drivers-modules)
* Content Source: [articles/java/sdk/libraries-drivers-modules.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/sdk/libraries-drivers-modules.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@selvasingh can you comment here? Thanks.

**Comment by janchristian-haddorp** [comment]
@vtapadia: Is this what you are looking for?
https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/migrate-postgresql-to-passwordless-connection.md

**Comment by KarlErickson** [comment]
No reply - closing
