### ISSUE TITLE
Location brazilsoutheast is not available for resource group

### ISSUE THREAD

**Issue by trferreira-BR** [MicrosoftDocs/azure-dev-docs#720]
Hi everyone,

I just try to create asimple web app using 'brazilsoutheast' as location but it's not available and cause an error. So, I don't exactly why this location is not available, but why this option is showing in the list when a deploy a webapp on Azure using IntelliJ if it isn't possible?

![image](https://user-images.githubusercontent.com/34104414/155171826-bae7c459-20fb-4bc8-8d83-48d2d4eebb98.png)

![image](https://user-images.githubusercontent.com/34104414/155171176-2caa7ae0-33e2-4898-a2d8-5f17c1af0335.png)

Thanks a lot,
Thiago

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5ac22c-2840-a25d-2194-3b6b995cbfce
* Version Independent ID: 621793ae-d1f5-cac5-bedd-36e9fea015a7
* Content: [Create a Hello World web app for Azure App Service using IntelliJ](https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/create-hello-world-web-app)
* Content Source: [articles/java/toolkit-for-intellij/create-hello-world-web-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/toolkit-for-intellij/create-hello-world-web-app.md)
* Service: **app-service**
* GitHub Login: @KarlErickson
* Microsoft Alias: **yucwan**

**Comment by KarlErickson** [comment]
@yucwan can you comment here? Thanks.
