### ISSUE TITLE
Error "Account Requires HTTPS" occurs when trying to handle request

### ISSUE THREAD

**Issue by stevencl** [MicrosoftDocs/azure-dev-docs#721]
I followed the portal instructions on the page to create the storage account then added the BlobController class, built the project and ran.

When I executed the first curl request I got this error in the terminal: 
com.azure.storage.blob.models.BlobStorageException: Status code 400, "?<?xml version="1.0" encoding="utf-8"?><Error><Code>AccountRequiresHttps</Code><Message>The account being accessed does not support http.

I had to go back to the portal and set the storage account property "Secure transfer required" to disabled, in order for the request to be handled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac19ce1b-2184-5487-67c9-22c4ff97336d
* Version Independent ID: ecc6b6cf-73e4-1575-add0-cb44d7aa4fcf
* Content: [How to use the Spring Boot Starter for Azure Storage](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage#prerequisites)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage.md)
* Service: **storage**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @backwind1233 ?

**Comment by saragluna** [comment]
This issue has been resolved, the library will default to using https now. Closing this issue.

**Comment by saragluna** [comment]
#please-close
