### ISSUE TITLE
video  steps did not work in my environment.

### ISSUE THREAD

**Issue by derelih** [MicrosoftDocs/azure-dev-docs#723]
Following the steps in the mentioned video does not work in my environment, unless I did not update the Flask version in the requirements.txt. 

I was getting "cannot import name ‘json’ from itsdangerous" error until I updated the Flask version to >2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac023b-e576-7e00-ca13-9bfb4597e91e
* Version Independent ID: e7fe954e-c81a-f9e2-6bb5-5aba2ba03be7
* Content: [Tutorial: Deploy Python apps to Azure App Service on Linux from Visual Studio Code](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-01)
* Content Source: [articles/python/tutorial-deploy-app-service-on-linux-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-deploy-app-service-on-linux-01.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by jess-johnson-msft** [comment]
#assign:DavidCBerry13

**Comment by jess-johnson-msft** [comment]
Topic has been removed and we do not review to the video anymore.
