### ISSUE TITLE
Is READ_PHONE_STATE permission still required, and why?

### ISSUE THREAD

**Issue by dave-sampson13** [MicrosoftDocs/azure-dev-docs#726]
In the section [Validate package name and permissions](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#validate-package-name-and-permissions) it states that `READ_PHONE_STATE` permission is required. This permission grants a lot more access to the device than should be necessary for receiving push notifications, and is frequently a permission of concern, requiring explicit noting in the app's privacy policy. However, our experience is that this permission is not actually required for receiving push notifications to succeed.

If the permission is required, can the documentation be updated to reflect why & for what purpose it is required? And if it is no longer required, can it be removed from the documentation please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#validate-package-name-and-permissions)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
