### ISSUE TITLE
why is this still recommending Zulu and not the Microsoft openJDK build?

### ISSUE THREAD

**Issue by tacowan** [MicrosoftDocs/azure-dev-docs#729]
[Enter feedback here]
If the zulu JDK is no longer receiving updates and going out of support, and given we should use the Microsoft build of the JDK, why is this still guiding us to install  Zulu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 733d4a97-401b-afe5-cf02-325e5e7286ef
* Version Independent ID: f31fe3ee-ddba-5da3-e158-0da3c8af8cc7
* Content: [Install a JDK for Azure development](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-jdk-install)
* Content Source: [articles/java/fundamentals/java-jdk-install.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/fundamentals/java-jdk-install.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
Hi @tacowan - thanks for the feedback! We are planning to update this article soon.

**Comment by KarlErickson** [comment]
Doc has been updated.
