### ISSUE TITLE
add procedure for WEBSITES_PORT setting

### ISSUE THREAD

**Issue by hfujikawa77** [MicrosoftDocs/azure-dev-docs#730]
In the WEBSITES_PORT setting, it was necessary to enter the check box of the deployment slot in addition to entering the port number.
I would appreciate it if you could confirm it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14b4680-9c75-f97a-030c-f893d69daad3
* Version Independent ID: 06585e09-0a7c-d2f4-8229-726d85fff436
* Content: [Deploy a Spring Boot Web App to Linux on Azure App Service](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-linux)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-on-linux.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/deploy-spring-boot-java-app-on-linux.md)
* Service: **app-service**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@seanli1988 can you confirm? Thanks!

**Comment by KarlErickson** [comment]
@seanli1988 ping

**Comment by seanli1988** [comment]
@chenrujun can you have someone test this and confirm?

**Comment by chenrujun** [comment]
@seanli1988 .

OK, I'll take care of this.

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by fangjian0423** [comment]
hi @hfujikawa77 , it works good for me whether select or not the deployment slot setting.

And I find [App Service docs](https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots#which-settings-are-swapped) tells how deployment slot setting works, hope it could help you , thanks.

**Comment by Lisamcperez4love** [comment]
Let us know your opinion about this app
