### ISSUE TITLE
Please fix tutorial so it works

### ISSUE THREAD

**Issue by mattgillard** [MicrosoftDocs/azure-dev-docs#731]
You are missing this code to glue the NIC to the backend pool.

resource "azurerm_network_interface_backend_address_pool_association" "example" {
count = 2
network_interface_id = element(azurerm_network_interface.test.*.id,count.index)
ip_configuration_name = "testConfiguration"
backend_address_pool_id = azurerm_lb_backend_address_pool.test.id
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef91226-6c89-f8f1-3400-28d633cd1791
* Version Independent ID: 19ea3aee-2e71-0764-110c-fadf241c377f
* Content: [Create an Azure VM cluster with Terraform and HCL](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-with-infrastructure)
* Content Source: [articles/terraform/create-vm-cluster-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-cluster-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@mattgillard Thanks for this. I'll try to get to this in the next day or two.

**Comment by mattgillard** [comment]
All good. Thanks!

**Comment by TomArcherMsft** [comment]
@mattgillard Thanks again for following up on this issue. I've updated the article and tested the article. The article will publish by tomorrow afternoon (PST).

**Comment by mattgillard** [comment]
Thanks! Looks good.
