### ISSUE TITLE
Parameter substitution does not work for content.xml inside the web apps' META-INF folder

### ISSUE THREAD

**Issue by DaveFoxOpenGI** [MicrosoftDocs/azure-dev-docs#732]
Hi, 
good documentation here, however, does not make it clear that the e.g. ${db.url} substitution parameters do not work for a Java/Tomcat in an App Serevice when the context.xml is 'inside the .war' file in the META-INF folder.

Unless there is a way to get this to work?? 
I simply get errors such as 
`"Cannot create JDBC driver of class 'org.gjt.mm.mysql.Driver' for connect URL '${MYSQLCONNSTR_ecommerceDB}'`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f0940f3-b32a-cba8-3ff8-b30aec424b42
* Version Independent ID: 6d40912c-076c-91d8-84f0-bbe5b4b3182c
* Content: [Migrate Tomcat applications to Tomcat on Azure App Service](https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-tomcat-to-tomcat-app-service)
* Content Source: [articles/java/migration/migrate-tomcat-to-tomcat-app-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migrate-tomcat-to-tomcat-app-service.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@selvasingh or @mnriem can you comment here? Thanks!

**Comment by mnriem** [comment]
See https://tomcat.apache.org/tomcat-9.0-doc/config/index.html

**Comment by DaveFoxOpenGI** [comment]
Exactly my point. 
The server.xml and context.xml located in the **tomcat/conf** folder DOES get parameter substitution. as per the tomcat 9 docs.
However, your help page on migrating to Azure **incorrently** implies above that this will also occur for any context.xml file WITHIN the **META-INF** folder **inside** the deployed .war file. This is **not** correct.

**Comment by KarlErickson** [comment]
@DaveFoxOpenGI @mnriem thanks for the feedback and info! I will create a work item to address this in the article.

**Comment by KarlErickson** [comment]
Hi @DaveFoxOpenGI - @mnriem has tested, and has reproduced the error. He's determined that setting CATALINA_OPTS to "-Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource" makes it work. I will update the documentation with this information.

**Comment by DaveFoxOpenGI** [comment]
thank you.
