### ISSUE TITLE
Getting Consumer Binding Exception.

### ISSUE THREAD

**Issue by chhonker** [MicrosoftDocs/azure-dev-docs#734]
o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 

Caused by: com.azure.storage.blob.models.BlobStorageException: If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ea30f719-b01e-0051-0718-351daa000000
Time:2022-03-11T07:22:30.0501669Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'vWIr**********8c4r7S/dnDr******15s=' is not the same as any computed signature. Server used following string to sign: 'GET

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [How to create a Spring Cloud Stream Binder application with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
@chhonker this error indicates that your credential for storage blob is not valid. Could you share the version you are using and also detailed configuration of your storage blob checkpoint store?

**Comment by KarlErickson** [comment]
No reply - closing
