### ISSUE TITLE
OfflineDataSync Xamarin.forms 

### ISSUE THREAD

**Issue by hannibub** [MicrosoftDocs/azure-dev-docs#735]
Hi, 

I tried to implement offline data sync capabilities to my Xamarin.Forms application by following the documentation (https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/offline) but the nuget packages "WindowsAzure.MobileServices" are deprecated in favor of Azure Mobile Apps. However, the documentation and sample project found in docs sill refer to those old, deprecated packages. 

I could not find any updated information or documentation with the new packages on offline data sync. Is that even a functional feature as of now? Is there any updated documentation available? 

Best regards, 

Fabian  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ba1d7d0-b6d3-0258-1dc5-bcef1f7bfcfe
* Version Independent ID: c3876d2d-be57-53d9-6359-4bee0efaba80
* Content: [Add offline data sync to your Xamarin.Forms app](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/offline)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/offline.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-forms/offline.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
The Azure Mobile Apps packages are in beta.  The WindowsAzure.MobileServices packages that are referenced WILL BE deprecated in favor of the new ones when they are released to GA.  As a result, the documentation is still good at this point.

I will be updating the documentation to use the new packages once they are released as GA.

**Comment by adrianhall** [comment]
#please-close
