### ISSUE TITLE
Jenkins on Azure overview landing page references outdated material

### ISSUE THREAD

**Issue by Minreaux** [MicrosoftDocs/azure-dev-docs#737]
The [Jenkins on Azure overview landing page](https://docs.microsoft.com/en-us/azure/developer/jenkins/overview), which is the first page I looked at for learning how to use Jenkins on Azure, references the Azure VM Agents Jenkins plugin which is a plugin that will be deprecated in 2024.

This page should be updated to included the new recommended way to setup Jenkins on Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a437702-cc4c-86c4-25ba-2a0365737d82
* Version Independent ID: 318fc29a-87f6-784f-918b-6ec7ec7ed282
* Content: [Overview of Jenkins and Azure](https://docs.microsoft.com/en-us/azure/developer/jenkins/overview)
* Content Source: [articles/jenkins/overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/overview.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Minreaux Thanks for your feedback. Since the plugin you mention is supported for 2 more years, it is the recommended way. When the plugin gets closer to retirement, we'll have a transition path we'll document.
