### ISSUE TITLE
JBoss EAP on ARO doc should refer to the install guide

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#738]
How to install JBoss EAP on ARO ?
If the official guideline is [https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index) could you please add it to this doc ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1baed898-42c0-9b64-3f85-5c76d7ede093
* Version Independent ID: 9935d7eb-6f70-6baa-fa5a-544638c49faf
* Content: [JBoss EAP on Azure](https://docs.microsoft.com/en-us/azure/developer/java/ee/jboss-on-azure#jboss-eap-on-azure-red-hat-openshift-aro)
* Content Source: [articles/java/ee/jboss-on-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/ee/jboss-on-azure.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **jafreebe**

**Comment by ezYakaEagle442** [comment]
also JBoss EAP o nARO doc should refer to the [Wildfly Operator](https://github.com/wildfly/wildfly-operator)

**Comment by edburns** [comment]
Thanks for bringing this to my attention. I have filed internal issue [rh-603](https://dev.azure.com/azure-redhat-projects/azure-redhat-projects/_workitems/edit/603).
