### ISSUE TITLE
No mention of specifying the VM version

### ISSUE THREAD

**Issue by spongebob331** [MicrosoftDocs/azure-dev-docs#741]
There should be a method to specify the VM version created using the ansible module.  This should at least be discussed in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ab8eeb-df97-be60-ce0a-ed619748c43e
* Version Independent ID: 4dd052d8-808b-1761-526f-2d534322f0e1
* Content: [Create a Linux virtual machines in Azure using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible)
* Content Source: [articles/ansible/vm-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@spongebob331 Thanks for your feedback. The `azure_rm_virtualmachine` block details the attributes of the VM. Could you please explain exactly what you mean by way of example?

**Comment by spongebob331** [comment]
@TomArcherMsft When creating a VM or VM image using the CLI, you can specify the VM version using the  -HyperVGeneration option. I don't see where the current Ansible modules for creating a VM (azure_rm_virtualmachine) or creating a VM image (azure_rm_image) support this option. How do you use Ansible to create V2 VMs and images? The terraform provider for creating an image (azurerm_image) allows you to specify the VM version, but I don't see where this is possible in Ansible. Whether it's possible or not, this page (and probably others) should be updated to show how to specify the version desired when creating VMs and images since V2 is  becoming more popular than V1 VMs.  Thank you.

**Comment by TomArcherMsft** [comment]
@spongebob331 Thanks for the additional information. I've reached out to our Ansible plugins PM for guidance and will reply when I have more information.

**Comment by TomArcherMsft** [comment]
@spongebob331 The Ansible plugins do not currently support V2 VMs but it is something in development. If you want, you can open a GitHub Issue on the [azure/ansible repo](https://github.com/Azure/Ansible/issues) to let the engineering team know of this request and track progress. I'm going to close this Issue as it's not a doc issue.
