### ISSUE TITLE
Incorrect image name in kubectl run command

### ISSUE THREAD

**Issue by jihu** [MicrosoftDocs/azure-dev-docs#742]
This command is incorrect:

`kubectl run gs-spring-boot-docker --image=wingtiptoysregistry.azurecr.io/gs-spring-boot-docker:latest`

The image name is called "**spring-boot-docker-complete**", so the command should be:

`kubectl run gs-spring-boot-docker --image=wingtiptoysregistry.azurecr.io/spring-boot-docker-complete:latest`

As far as I can tell, the image name is the same as the artifactId of the maven project. And at least in the current version of this project, the pom file for the "complete" module has "spring-boot-docker-complete" as the artifact id. Using this, I got it all working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200ae7a0-87fe-9d4d-db79-12495746fbd8
* Version Independent ID: 0aaa8a60-4aec-ac05-a9bc-7d9a4883c637
* Content: [Deploy Spring Boot Application to the Azure Kubernetes Service - Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes)
* Content Source: [articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by fangjian0423** [comment]
Similar with https://github.com/MicrosoftDocs/azure-dev-docs/issues/633. 

hi @jihu , thanks for reaching out.

We will update to images name to `gs-spring-boot-docker`, thanks.

**Comment by KarlErickson** [comment]
Update merged.
