### ISSUE TITLE
sample YAML in "Use the Azure CLI action" uses incorrect indentation

### ISSUE THREAD

**Issue by roalexan** [MicrosoftDocs/azure-dev-docs#744]
Does the sample YAML in "Use the Azure CLI action" work for you? I tried pasting it in, and it failed. I flailed around a while, stumbled across [this bug](https://github.community/t/run-failing-invalid-workflow-file/127574), and came to the realization that the indentation is not correct as currently presented. It would be great if you could fix this and save some pain down the road.

This is what worked for me:

<pre>
on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account show
            az storage -h
</pre>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-in/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-cli-action)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
@roalexan Thank you! I'm updating the formatting now.

**Comment by roalexan** [comment]
[like]  Robert Alexander reacted to your message:
________________________________
