### ISSUE TITLE
Incorrect service principal credential format for azure/login GA in docs

### ISSUE THREAD

**Issue by gregsmi** [MicrosoftDocs/azure-dev-docs#745]
The fields described in [Create a service principal and add it as a GitHub secret](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#create-a-service-principal-and-add-it-as-a-github-secret) as the appropriate Json format for an `AZURE_CREDENTIALS` secret usable by the `azure/login@v1` action are incorrect, and will cause an authentication failure. This is the correct format (as defined [here](https://github.com/Azure/login#configure-a-service-principal-with-a-secret))

    {
        "clientId":"<GUID>",
        "clientSecret":"<secret>",
        "subscriptionId":"<GUID>",
        "tenantId":"<GUID>"
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks, I'm updating this now.
