### ISSUE TITLE
Many parameters are not easily available and understood. 

### ISSUE THREAD

**Issue by Vishwasrao1** [MicrosoftDocs/azure-dev-docs#746]
https://docs.microsoft.com/en-us/python/api/azure-iot-deviceupdate/azure.iot.deviceupdate.operations.devicemanagementoperations?view=azure-python-preview#azure-iot-deviceupdate-operations-devicemanagementoperations-create-or-update-deployment

I was going through this and unable to find any of the parameter given. For example

`deployment_id
Required
Deployment identifier.`

wow great! so deployment id means Deployment identifier , How knowledgeable this was!! Now tell me where can I find it?
what should I enter in this field?? You guys know that because you are working on it, not us. Stop using shortcuts.

So my sincere request is to please provide sample examples(which makes sense to others) not like below image
![image](https://user-images.githubusercontent.com/82839871/161047949-d8897bd4-9d42-4dc0-984d-2dbab24ba130.png)

in this example instanceID is given "blue" ? what do you mean by blue, can I write my favourite colour? I have invested 32 hours just to figure out where and how can i find these "top secret" parameters. 

So I kindly request you to give us example of each parameter, their location on azure portal. Waiting for your positive reply

**Comment by DavidCBerry13** [comment]
@lmazuel - Is there someone on your team that can help out with this?  I think this probably should have ended up in the SDK repo, but is here instead.  Do you know who could take a look?

**Comment by dpokluda** [comment]
Hi @Vishwasrao1, thank you for your feedback. I have created a task for the dev team to update the swagger documentation to contain more meaningful property and method descriptions.

**Comment by jessmjohnson** [comment]
Hello! I have discussed this issue with @dpokluda  and the issue/feedback has been published. I will close the issue.
