### ISSUE TITLE
how to configure with Spring data auto configuration ?

### ISSUE THREAD

**Issue by abhinav-jain09** [MicrosoftDocs/azure-dev-docs#748]
[Enter feedback here]
How about using spring Data? how to configure the mango db URL  with local azure emulator and also live Azure enviroment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d9dcaa-2461-164f-0b5e-1670807e5df5
* Version Independent ID: 43e1642b-64e1-a636-2763-aa459f3725ea
* Content: [How to use Spring Data MongoDB API with Azure Cosmos DB](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-mongodb-with-cosmos-db)
* Content Source: [articles/java/spring-framework/configure-spring-data-mongodb-with-cosmos-db.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-mongodb-with-cosmos-db.md)
* Service: **cosmos-db**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @backwind1233 ?

**Comment by KarlErickson** [comment]
@TheovanKraay according to https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-develop-emulator?tabs=docker-linux%2Ccsharp&pivots=api-mongodb Java is not supported. Can we close this issue? Can you assess whether your article should be updated? Thanks!

**Comment by KarlErickson** [comment]
@TheovanKraay ping. I need to close this issue soon, so please be sure to represent any necessary work in Azure DevOps. Thanks!

**Comment by KarlErickson** [comment]
Closing. Pinged @TheovanKraay via Teams to ensure awareness and potential future tracking.
