### ISSUE TITLE
Error: Cannot index a set value

### ISSUE THREAD

**Issue by danilpremgi** [MicrosoftDocs/azure-dev-docs#752]
Running `terraform plan -out main.tfplan` getting the following

>  Error: Cannot index a set value
>  on main.tf line 108, in resource "azurerm_network_interface_application_gateway_backend_address_pool_association" "nic-assoc01":
>  108:   backend_address_pool_id = azurerm_application_gateway.network.backend_address_pool[0].id
>  Block type "backend_address_pool" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria,   
> use a "for" expression with an "if" clause.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Version Independent ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Content: [Deploy an Azure Application Gateway v2 using Terraform to direct web traffic](https://docs.microsoft.com/en-gb/azure/developer/terraform/deploy-application-gateway-v2?toc=%2Fazure%2Fapplication-gateway%2Ftoc.json&bc=%2Fazure%2Fapplication-gateway%2Fbreadcrumb%2Ftoc.json)
* Content Source: [articles/terraform/deploy-application-gateway-v2.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-application-gateway-v2.md)
* Service: **terraform**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by TomArcherMsft** [comment]
@danilpremgi Thanks for bringing this to our attention. @vhorne Could you please take a look at this?

**Comment by johnastiles** [comment]
I get the same error. It appears to be a Terraform provider issue. If I use v2.99.0, it works fine. Using v3.50.0 gives the error.

**Comment by TomArcherMsft** [comment]
Thanks, @danilpremgi, @johnastiles. The code and article have been updated and tested. The article will republish tomorrow morning (PST). If you still see the problem, please comment here and I'll investigate further.
