### ISSUE TITLE
New Consumer Group Event Processor Reading Latest Events from Partitions

### ISSUE THREAD

**Issue by Chaitragandha** [MicrosoftDocs/azure-dev-docs#754]
**I created new conumer group in Eventhub. Eventhub has events event before creating the new conumer group. The Event processor is reading from latest event in the partition using new consumer group and not the oldest event in the partition. Is there any way I can change this by mentioning in application.properties file? Kindly find the logs below.** 

> 
> [2022-04-12 13:19:25.610] [prod] [bajaj-webhook-eventhub-consumer-service] [reactor-http-epoll-1] [INFO ] Started receiving on partition: 2

> [2022-04-12 13:19:25.611] [prod] [bajaj-webhook-eventhub-consumer-service] [reactor-http-epoll-1] [INFO ] Starting event processing from offset[@latest], sequenceNumber[null], enqueuedTime[null], isInclusive[false] for partition  

[spring-cloud-azure-stream-binder-eventhubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)

**Comment by KarlErickson** [comment]
Hi @Chaitragandha - Thank you for your feedback. Since this channel is more for driving improvements toward MS Docs, could you post on [MS Q&A channel](https://docs.microsoft.com/en-us/answers/index.html) instead for your question?

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
Hi @Chaitragandha , for specifying the starting position, you can use the property of `spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer.initial-partition-event-position`, for more details about this propery, you can refer to our [reference doc](https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#eventhubs-consumer-properties) which also contains a sample for this.

**Comment by Chaitragandha** [comment]
Hi @yiliuTo , Thanks a lot!! was looking for this since a very long time. I will definitely try this.

**Comment by chenrujun** [comment]
Hi, @Chaitragandha 

Thanks for your feedback.
Please close this issue if problem solved.
