### ISSUE TITLE
Custom port configuration setting name in Application Settings

### ISSUE THREAD

**Issue by gandhirajan** [MicrosoftDocs/azure-dev-docs#76]
Under 'Diagnose and solve problems' -> 'Availability and Performance' -> 'Application Logs ' section in App Services, it clearly states that the application settings for port change should be mentioned under setting named - 'WEBSITES_PORT' and not 'PORT'.

But under the note section in the following link - https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-on-linux#create-a-web-app-on-linux-on-azure-app-service-using-your-container-image , setting name for custom port is mentioned as 'PORT' instead of 'WEBSITES_PORT' which needs to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f50e3e9-904e-0ffd-1d18-2b7be7d15dd9
* Version Independent ID: 191f1eb6-dcab-3ec8-bbf3-1a8109116429
* Content: [Deploy a Spring Boot Web App on Azure App Service for Container](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-on-linux#feedback)
* Content Source: [java/spring-framework/deploy-spring-boot-java-app-on-linux.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/deploy-spring-boot-java-app-on-linux.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by gandhirajan** [comment]
PR# 75 - 'PORT should be changed as WEBSITES_PORT in Application settings' closes this issue. Please merge.

**Comment by MikeDodaro** [comment]
#sign-off

**Comment by gandhirajan** [comment]
@MikeDodaro  Hi Mike, I m not able to link the PR# 75 to this issue. If you can link it you can merge the PR I guess.

**Comment by bmitchell287** [comment]
#sign-off

**Comment by bmitchell287** [comment]
@gandhirajan @MikeDodaro - I merged PR #75, thanks for the submission.

**Comment by bmitchell287** [comment]
Merged

**Comment by gandhirajan** [comment]
> @gandhirajan @MikeDodaro - I merged PR #75, thanks for the submission.
Thanks a lot @MikeDodaro @bmitchell287
