### ISSUE TITLE
Code sample refers to incorrect credential

### ISSUE THREAD

**Issue by briglx** [MicrosoftDocs/azure-dev-docs#761]
Page show:

```
credential = DefaultAzureCredential()

blob_service_client = BlobServiceClient(
    account_url=storage_account_url,
    credential=token_credential)   <<<< Notice it has token_credential
```

Should be:

```
credential = DefaultAzureCredential()

blob_service_client = BlobServiceClient(
    account_url=storage_account_url,
    credential=credential )   <<<<<< Should be credential not token_credential
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4b3e86-5019-fd4e-e71d-a0694d5aa697
* Version Independent ID: 9a4b3e86-5019-fd4e-e71d-a0694d5aa697
* Content: [Overview: Authenticate Python apps to Azure using the Azure SDK](https://docs.microsoft.com/en-us/azure/developer/python/sdk/authentication-overview)
* Content Source: [articles/python/sdk/authentication-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/authentication-overview.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by DavidCBerry13** [comment]
Thanks @briglx - My bad there, I'll get this updated.

**Comment by DavidCBerry13** [comment]
This is the PR for the fix --> https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2978

Should publish around noon US Central time.

**Comment by DavidCBerry13** [comment]
#please-close
