### ISSUE TITLE
Rename AADWebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by THD-Thomas-Lang** [MicrosoftDocs/azure-dev-docs#763]
Please rename `AADWebSecurityConfigurerAdapter` to the right class name `AadWebSecurityConfigurerAdapter`
See: https://stackoverflow.com/questions/71966520/aadwebsecurityconfigureradapter-not-found

Maybe all `AAD*` classes need renaming to `Aad*`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba254924-0fee-04dd-6db0-f7588106a3c1
* Version Independent ID: b689c92c-8fdd-a3de-d13e-889934dbb734
* Content: [Spring Boot Starter for Azure Active Directory developer's guide](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide)
* Content Source: [articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **shaozliu**

**Comment by KarlErickson** [comment]
@stliu can you please validate, for the class mentioned and for all AAD* classes? Thanks!

**Comment by KarlErickson** [comment]
@stliu @chenrujun can you validate? See also #771.

**Comment by chenrujun** [comment]
@KarlErickson PR is creating.
