### ISSUE TITLE
Artifact if is different if i go to maven repo for version 4.0.0

### ISSUE THREAD

**Issue by rhyashu** [MicrosoftDocs/azure-dev-docs#764]
In the doc artifact name is mentioned as "spring-cloud-azure-stream-binder-eventhubs" but in maven repo is same as previous version 2.* which is 

<dependency>
    <groupId>com.azure.spring</groupId>
    <artifactId>azure-spring-cloud-stream-binder-eventhubs</artifactId>
    <version>4.0.0</version>
</dependency>

Are they both same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [How to create a Spring Cloud Stream Binder application with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub#feedback)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@stliu can you please validate? Thanks!

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
@rhyashu sorry for the late response. For version after 4.0.0, our artifact has been renamed to [com.azure.spring:spring-cloud-azure-stream-binder-eventhubs](https://search.maven.org/artifact/com.azure.spring/spring-cloud-azure-stream-binder-eventhubs), so please use the new one. And as for [com.azure.spring:azure-spring-cloud-stream-binder-eventhubs:4.0.0](https://search.maven.org/artifact/com.azure.spring/azure-spring-cloud-stream-binder-eventhubs/4.0.0/jar), that one is published for relocation.
