### ISSUE TITLE
Syntax broken for code block

### ISSUE THREAD

**Issue by bitdeft** [MicrosoftDocs/azure-dev-docs#766]
[Enter feedback here]

Code block is incorrect at the first paragraph, causing the part before the intended code block to be placed in code block mkrdwn :
"

Developing on Azure requires Python 3.6 or higher. Its assumed you already have Python 3.6 or higher installed on your local workstation. To verify the version of Python on your workstation, type the command python --version` in any console window.

"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c507d59-970e-feae-b034-8dc27f04d6b4
* Version Independent ID: 0c608a8f-a794-1f3e-6047-24dd2108633b
* Content: [Configure your local Python environment for Azure development](https://docs.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=windows%2Capt%2Cbash)
* Content Source: [articles/python/configure-local-development-environment.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/configure-local-development-environment.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by bitdeft** [comment]
Correction: Second paragraph. It's pretty easy to see, should be quick fix 👍

**Comment by DavidCBerry13** [comment]
Yes.  Wrong tick mark.  Switching to the other (correct) tick mark.  Thanks for letting me know.  The fix will publish out on Tuesday.

**Comment by DavidCBerry13** [comment]
This is the PR --> https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2990

**Comment by DavidCBerry13** [comment]
#pleas-close

**Comment by DavidCBerry13** [comment]
#please-close
