### ISSUE TITLE
Binding multiple topics

### ISSUE THREAD

**Issue by henryho062** [MicrosoftDocs/azure-dev-docs#767]
[Enter feedback here]

How to binding for multiple Service Bus topics and handle consume/supply messages from/to those topics?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25596474-8a16-dcf6-e9a9-09ca23c905a9
* Version Independent ID: 9c1525d4-c8fe-f585-8f27-667291a58fd0
* Content: [How to use Spring Cloud Azure Stream Binder for Azure Service Bus](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **seal**

**Comment by marcin-sikorski-circlek** [comment]
Can somebody answer in this issue? Is supplying two multiple queues possible?

**Comment by KarlErickson** [comment]
@seanli1988 can you comment here? Thanks.

**Comment by KarlErickson** [comment]
@marcin-sikorski-circlek you might want to also ask your question on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/index.html) site.

**Comment by yiliuTo** [comment]
Hi @henryho062 and @marcin-sikorski-circlek , to bind for multiple topics or queues of Service Bus, you can refer to [our sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.4.0/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders) for more details. The sample takes binding to one topic and queue in different namespaces as an example. It also applys if your topics or queues are in the same namespace, to do so you only need to remove all the configuration of [the second binder definition](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/3f71bd7ae2521a1505110289a8835ad3405ebfe9/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/src/main/resources/application.yaml#L28) and [reference](https://github.com/Azure-Samples/azure-spring-boot-samples/blob/3f71bd7ae2521a1505110289a8835ad3405ebfe9/servicebus/spring-cloud-azure-stream-binder-servicebus/servicebus-multibinders/src/main/resources/application.yaml#L13).

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by chenrujun** [comment]
Hi, @yiliuTo
Please let Karl close this issue if you think this issue should be closed now.

**Comment by yiliuTo** [comment]
Hi @KarlErickson , I suppose this issue can be closed since there is no response from the customer for long.
