### ISSUE TITLE
Does the Python SDK work for  Canary environments ?

### ISSUE THREAD

**Issue by KumariSupriya** [MicrosoftDocs/azure-dev-docs#768]
We are seeing an issue when creating a resource group in CentralUSEUAP and the resource group creation fails with region is invalid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a664b6ce-32ab-17ab-9d96-2860a88bbf95
* Version Independent ID: a664b6ce-32ab-17ab-9d96-2860a88bbf95
* Content: [Use the Azure libraries (SDK) for Python](https://docs.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-overview)
* Content Source: [articles/python/sdk/azure-sdk-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/azure-sdk-overview.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by jess-johnson-msft** [comment]
@lmazuel are you or someone on your team able to help address this issue?

**Comment by jess-johnson-msft** [comment]
Yes the Python for Azure SDK can work in the Carnary Environment - if you need additional help setting up the sdk please reach out to @lmazuel
