### ISSUE TITLE
Any docs for JMS 1.1 ? JMS 2.0 is only available on premium subscription which is a NO-GO given our budget.

### ISSUE THREAD

**Issue by abouquet** [MicrosoftDocs/azure-dev-docs#769]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbecafd0-c6db-9cb0-c5a4-328946446ec6
* Version Independent ID: 40cea238-c2de-fd1d-fef7-c1a850b54158
* Content: [How to use the Spring Boot Starter for Azure Service Bus JMS](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus?msclkid=0af3ab30c61211ecaed5b44bcd85c8b8)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **seal**

**Comment by abouquet** [comment]
Probably related to https://github.com/MicrosoftDocs/azure-dev-docs/issues/762

**Comment by KarlErickson** [comment]
@seanli1988 can you comment here? Thanks!

**Comment by abouquet** [comment]
Hi ! Can we have a follow up to this question please ? :)

**Comment by KarlErickson** [comment]
@seanli1988 ping - Sean, could you loop in someone who could provide guidance here? Thanks.

**Comment by yiliuTo** [comment]
Hi @abouquet , the library `spring-cloud-azure-starter-servicebus-jms` supports the standard tier as well, but only for the limited JMS 1.1 functionalities. And for docs on JMS 1.1 support of Service Bus, we currently don't have such docs on the basis of `spring-cloud-azure-starter-servicebus-jms` , you may refer to the official [Azure Service Bus doc](https://docs.microsoft.com/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp).

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?
