### ISSUE TITLE
Azure SDK auth using an authenticated proxy

### ISSUE THREAD

**Issue by bg2132332** [MicrosoftDocs/azure-dev-docs#77]
I'm looking for an example of how to configure a proxy with Azure SDK for Java -- including proxy username and password.  The samples I find online that add "Proxy-Authorization" header don't seem to work for me -- the Authenticator is not getting called right for me and it would be nice to have an official sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b69839eb-e8c9-e071-54cd-004ced699ee1
* Version Independent ID: d7e0e990-c840-2975-3721-2169fc54650e
* Content: [Authenticate with the Azure management libraries for Java](https://docs.microsoft.com/en-us/azure/java/java-sdk-azure-authenticate)
* Content Source: [java/java-sdk-azure-authenticate.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/java-sdk-azure-authenticate.md)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@selvasingh can you provide input here? @bmitchell287 for awareness.

**Comment by KarlErickson** [comment]
Proxying is now covered at https://learn.microsoft.com/en-us/azure/developer/java/sdk/proxying.
