### ISSUE TITLE
There is an error in the main.tf file contents. I am sharing the feedback from testing it in terraform.

### ISSUE THREAD

**Issue by asukumar22** [MicrosoftDocs/azure-dev-docs#770]
There is an error in the main.tf file contents. I am sharing the feedback from testing it in terraform. 
It is given in the line like this:
backend_address_pool_id = azurerm_application_gateway.network.backend_address_pool[0].id

It threw an error in the plan stage.
╷
│ Error: Cannot index a set value
│
│   on main.tf line 108, in resource "azurerm_network_interface_application_gateway_backend_address_pool_association" "nic-assoc01":
│  108:   backend_address_pool_id = azurerm_application_gateway.network.backend_address_pool[0]
│
│ Block type "backend_address_pool" is represented by a set of objects, and set elements do not have addressable keys.
│ To find elements matching specific criteria, use a "for" expression with an "if" clause.
╵

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Version Independent ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Content: [Deploy an Azure Application Gateway v2 using Terraform to direct web traffic](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-application-gateway-v2?msclkid=43e14adbc67a11ec860a4cc0784fd100)
* Content Source: [articles/terraform/deploy-application-gateway-v2.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-application-gateway-v2.md)
* Service: **terraform**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by TomArcherMsft** [comment]
@asukumar22 I apologize for this not being responded to earlier. The code and article have been updated and tested. The article will republish tomorrow morning (PST). If you still see the problem, please comment here and I'll investigate further.
