### ISSUE TITLE
Support for AmqpWebSockets

### ISSUE THREAD

**Issue by joustine** [MicrosoftDocs/azure-dev-docs#773]
[Enter feedback here]
Is AMQP over web socket (TransportType=AmqpWebSockets) supported in Spring Cloud Stream Binder application for event hubs? How can I specify "TransportType=AmqpWebSockets" in my application, if it is supported? This will be helpful in the scenarios where  outbound connections to ports 5671 and 5672 are blocked in data center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f685fa4-079e-19b2-9926-7eec807e3f43
* Version Independent ID: 612f907e-2e5a-9188-8d10-1c54334c97ad
* Content: [How to create a Spring Cloud Stream Binder application with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@chenrujun can you comment here? Thanks!

**Comment by chenrujun** [comment]
Hi, @yiliuTo, please comment here.

**Comment by yiliuTo** [comment]
Hi @joustine , to configure the `TransportType` property, we support multiple ways for it.you can configure it using one of the below properties that fits your case:
- `spring.cloud.azure.client.transport-type` configures the transport type for all Spring Cloud Azure internal SDK clients which has the lowest priority of all supported properties
- `spring.cloud.azure.eventhubs.client.transport-type` configures the transport type for all Event Hubs clients and has higher priority, you can use this if you expect all the connections to different event hub entities have the same transport type.
- `spring.cloud.stream.eventhubs.bindings.<binding-name>.consumer.client.transport-type` or `spring.cloud.stream.eventhubs.bindings.<binding-name>.producer.client.transport-type` configures the transport type for a specific Event Hubs client using for a consumer / producer binding which has the highest proority, you can use this property if you want to configure different transport types for different bindings.

For more information about the configuration of Event Hubs Spring Cloud Stream Binder, you can refer to the [doc](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#eventhubs-connection-configuration).
