### ISSUE TITLE
Insufficient JUnit test principle.

### ISSUE THREAD

**Issue by ThomasAtAcerta** [MicrosoftDocs/azure-dev-docs#774]
- The Handler class extending FunctionInvoker has concerns that are not testable such as HttpStatus 200, 400, etc.

- Using HttpRequestMessage with queryParameters: this is unclear to me how to unit test this.

>        Map<String, String> queryParameters = request.getQueryParameters();
>        if(queryParameters == null){
>            logger.warning("No parameters found");
>            return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("No parameters found").build();
>        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Getting started with Spring Cloud Function in Azure](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
@jdubois can you reply here? Thanks!

**Comment by jdubois** [comment]
This is a sample code, with already has some test coverage: I don’t think you can expect much more from such a sample, which needs to stay very simple (people need to be able to follow this in 10-15 minutes). API concerns should go to the main project, not the sample code.

**Comment by ThomasAtAcerta** [comment]
> This is a sample code, with already has some test coverage: I don’t think you can expect much more from such a sample, which needs to stay very simple (people need to be able to follow this in 10-15 minutes). API concerns should go to the main project, not the sample code.

When deciding to either use or not use a library like this the testability of such a library should be a major concern (IMO).  I am having trouble finding more detailed test code anywhere.  Also, the production code in this sample is simple enough, all concerns should be easily testable and I do think this sample should show how to do that.  I am specifically talking about the concern of the http status code that is returned.  That's not a minor detail of such functionality.

I'll elaborate on what I did to get this tested.

- The class extending FunctionInvoker needs a constructur with configurationClass parameter, so one can instantiate the extended class instead of the abstraction in the test code:

`    public HelloHandler(Class<?> configurationClass) {
        super(configurationClass);
    }
`

- Depending on what sort of test you want here one can use a specific Spring context to initialize.  In this case it's a very small Spring context configuration class with its Function (or Supplier, Consumer) Bean(s) with mocked functionality. 

`
    public void setup(){
        helloHandler = new HelloHandler(HelloMockConfig.class);
    }
`

- Instead of calling the abstraction method (handleRequest) one can call the specific method of the HelloHandler class (execute).  With some mocking and a test implementation of ExecutionContext I was able to assert:

`HttpResponseMessage httpResponseMessage = helloHandler.execute(mockedHttpRequestMessage, testExecutionContext);
assertThat(httpResponseMessage.getStatus()).isEqualTo(HttpStatus.OK);
assertThat(httpResponseMessage.getBody()).isEqualTo(HelloMockConfig.mockedReturnMessage);
`

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @jdubois ?

Hi, @jdubois 
Could you please let Karl close this issue if you think this issue can be closed now?

**Comment by jdubois** [comment]
I believe this should be closed.
I had a look at the module again, the goal is to teach people about Functions in a very limited amount of time, and it already has some (limited) testing support as an example. More tests would be interesting in a module dedicated to testing, or in the sample application, but here this is just going to make the module too long.

**Comment by ThomasAtAcerta** [comment]
> 

I disagree.  The functionality shown here is already very limited.  Those limited concerns aren't even tested properly.  A showcase such as this should at least be able to demonstrate how to write a test for those concerns.  If that is too hard to do then all this showcase does is demonstrate its weakness.
