### ISSUE TITLE
Proposing some improvements

### ISSUE THREAD

**Issue by sokoloffmaks** [MicrosoftDocs/azure-dev-docs#775]
HI Jen, great work as usual!

couple of things on how this AVD terraform example doco can be improved 

1)Suggesting to add azure devops pipeline section/page showing on how to deploy codebase you are providing  via Azure Devops / yaml file

2) Atm, this code obviously allows only to deploy the single pool/workspace/app group into a single environment..
Potential Improvement is to allow to deploy different pools /workspaces based on input variables using the same codebase - 
ie , let say we have a couple of user personas each requires separate pool and workspace ( and obviously an app group) . So, this code should be able to deploy two different host pools using the same codebase/same Azure Devops pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0a97cf-1514-889c-edbc-9c10bd566231
* Version Independent ID: 3a0a97cf-1514-889c-edbc-9c10bd566231
* Content: [Configure Azure Virtual Desktop using Terraform - Azure](https://docs.microsoft.com/en-us/azure/developer/terraform/configure-azure-virtual-desktop)
* Content Source: [articles/terraform/configure-azure-virtual-desktop.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-azure-virtual-desktop.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@sokoloffmaks Thanks for your feedback. I've assigned the Issue to @jensheerin.
