### ISSUE TITLE
Example Tests

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/azure-dev-docs#776]
How about some springboot @webmvctest examples to go with it? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba254924-0fee-04dd-6db0-f7588106a3c1
* Version Independent ID: b689c92c-8fdd-a3de-d13e-889934dbb734
* Content: [Spring Boot Starter for Azure Active Directory developer's guide](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide)
* Content Source: [articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/spring-boot-starter-for-azure-active-directory-developer-guide.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **shaozliu**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by chenrujun** [comment]
HI, @ghost 

Thanks for reaching out.

This doc is just used to tell the features of spring-cloud-azure-starter-active-directory.
The @webmvctest is not related to this topic.
So, now I don't have plan to add it.
