### ISSUE TITLE
Image tag is not correct

### ISSUE THREAD

**Issue by JesseHoch** [MicrosoftDocs/azure-dev-docs#779]
The image tag is:
"mcr.microsoft.com/azuredocs/azure-vote-front:cosmosd"

Should be:
"mcr.microsoft.com/azuredocs/azure-vote-front:cosmosdb"

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e206df2-ca76-283a-0689-4aa90229a5c2
* Version Independent ID: d7475eda-b72a-7799-7942-fb2010e56f66
* Content: [Deploy an Azure Cosmos DB to Azure Container Instances](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-azure-cosmos-db-to-azure-container-instances)
* Content Source: [articles/terraform/deploy-azure-cosmos-db-to-azure-container-instances.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-azure-cosmos-db-to-azure-container-instances.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@JesseHoch Thanks for the catch! I've updated the article and it should publish sometime later this morning.
