### ISSUE TITLE
Ansible Tower changed names

### ISSUE THREAD

**Issue by lanicolas** [MicrosoftDocs/azure-dev-docs#780]
Ansible Tower by Red Hat is now called Red Hat Ansible Automation Platform, as they also reflect it in their marketplace offering. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88e2bae-a0d4-f918-4cfe-2c21656baca0
* Version Independent ID: 118ef161-46e8-1625-6972-524555aca8c0
* Content: [Using Ansible with Azure](https://docs.microsoft.com/en-us/azure/developer/ansible/overview)
* Content Source: [articles/ansible/overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/overview.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@lanicolas Did you forget the link? :)

**Comment by TomArcherMsft** [comment]
I found an article that talks about the name change. I'll take a look and comment back in a few minutes...

**Comment by TomArcherMsft** [comment]
@lanicolas I decided to remove the section entirely as it adds no value to the article. Thanks again for alerting us.
