### ISSUE TITLE
A managed resource "azurerm_resource_group" "k8s" has not been declared in the root module.

### ISSUE THREAD

**Issue by joeistyping** [MicrosoftDocs/azure-dev-docs#782]
Following the tutorial yields:
│ Error: Reference to undeclared resource
│
│   on main.tf line 19, in resource "azurerm_log_analytics_workspace" "test":
│   19:     resource_group_name = azurerm_resource_group.k8s.name
│
│ A managed resource "azurerm_resource_group" "k8s" has not been declared in
│ the root module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@joeistyping Thanks for the feedback. I'm looking into this now.

**Comment by TomArcherMsft** [comment]
@joeistyping  The code has been completely updated and tested. I'm awaiting engineering-team sign-off, and then the article will be republished. Thanks again for your feedback!

**Comment by TomArcherMsft** [comment]
The [updated article](https://docs.microsoft.com/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks) is now live.
