### ISSUE TITLE
Deprecated Action in Use Key Vault secrets in GitHub Actions workflows

### ISSUE THREAD

**Issue by ahmedig** [MicrosoftDocs/azure-dev-docs#784]
The Action "Azure/get-keyvault-secrets" is deprecated as per [the GitHub action](https://github.com/Azure/get-keyvault-secrets#deprecation-notice). We would love to have an example using the CLI as currently recommended in the docs, and show a way to read the values, and set and mask the environment variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae689e10-62a4-f724-7705-9273801217aa
* Version Independent ID: 2fa43bd0-223b-5f6e-1fca-e823d5b92ef5
* Content: [Quickstart -  Use Azure Key Vault secrets in GitHub Actions workflows](https://docs.microsoft.com/en-us/azure/developer/github/github-key-vault)
* Content Source: [articles/github/github-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-key-vault.md)
* Service: **key-vault**
* Sub-service: **secrets**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
#please-close

This article is no longer active.
