### ISSUE TITLE
Documentation is incomplete and difficult to follow

### ISSUE THREAD

**Issue by itsme300** [MicrosoftDocs/azure-dev-docs#786]
The login methods are shown and login logging options are given.

which method should I use to logon to the service? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f30ac0e-7650-9033-dae3-c96c6090312a
* Version Independent ID: 8c754945-f8d0-af20-7f37-4c2a8fc0cf59
* Content: [Walkthrough, Part 5: Authenticate Python apps with Azure services](https://docs.microsoft.com/en-us/azure/developer/python/walkthrough-tutorial-authentication-05)
* Content Source: [articles/python/walkthrough-tutorial-authentication-05.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/walkthrough-tutorial-authentication-05.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by jess-johnson-msft** [comment]
Thank you so much for reaching out with this feedback! This item has been added to our triage queue and will be investigated further.

**Comment by jess-johnson-msft** [comment]
These issue has been addressed by PRs #3126 and #3127
