### ISSUE TITLE
this doesnt work

### ISSUE THREAD

**Issue by ChristianMA19** [MicrosoftDocs/azure-dev-docs#788]
hello men how are you today,

ok so i have this error i have done everything you said in the page and it doesnt work
![image](https://user-images.githubusercontent.com/68516237/168403224-2e844ced-339f-464c-9969-0656063d88c2.png)
![image](https://user-images.githubusercontent.com/68516237/168403258-4705e4a7-df33-465a-8e47-e80b4653353a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26a6589-1419-0dfb-0afc-a87712dd006c
* Version Independent ID: 74ce4509-6344-ecdd-4738-a94e4df4dfb6
* Content: [Build a Xamarin.Android app with Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-android/#feedback)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-android/index.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/xamarin-android/index.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by sebaxe07** [comment]
Hello, I have the same issue here on my end. I already tried the process twice referred to in this article 
https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/xamarin-android/

**Comment by adrianhall** [comment]
Thank you for the report. We've recently updated the tutorial and code and are just awaiting a new publication of the docs site.  Once that is done, please retry the tutorial.

#please-close
