### ISSUE TITLE
How to set rule priority in routing rule while creating app gateway for multiple domains with terraform?

### ISSUE THREAD

**Issue by SudhirG85** [MicrosoftDocs/azure-dev-docs#789]
It seems with recent API update on azure application gateway, it is mandatory to set rule priority in routing rules. Due to which the existing setup with AGIC in AKS is not updating the App gateway configuration promptly. Instead it exits with an error: 
**error: network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePartialPriorityDefined" Message="Either all or no rule should have the priority specified." Details=[]
I0519 06:29:50.854292       1 mutate_app_gateway.go:174] END AppGateway deployment
E0519 06:29:50.854312       1 worker.go:62] Error mutating App Gateway config from k8s event. network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePartialPriorityDefined" Message="Either all or no rule should have the priority specified." Details=[]**

We have created app gateway with terraform and if we have to update the setup, please share how can we define priority(which supports integer value from 1-20000) on routing rules for app gateway which now supports multiple domains in our organization.

request_routing_rule {
    name                       = var.request_routing_rule_name
    priority                     = **value, when we deploy multiple domain in one app gateway**
    rule_type                  = "Basic"
    http_listener_name         = var.listener_name
    backend_address_pool_name  = var.backend_address_pool_name
    backend_http_settings_name = var.http_setting_name
  }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Version Independent ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Content: [Deploy an Azure Application Gateway v2 using Terraform to direct web traffic](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-application-gateway-v2)
* Content Source: [articles/terraform/deploy-application-gateway-v2.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-application-gateway-v2.md)
* Service: **terraform**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by SudhirG85** [comment]
@KarlErickson thanks for response. But please consider this feedback as more of an update in page based on the recent upgrade of Application Gateway and its API which made priority in routing rule as a mandatory field. It would be good if we have sections in this page to demonstrate how we create app gateway using terraform for both single domain and multi domain setup with rule priority defined.

**Comment by TomArcherMsft** [comment]
@SudhirG85 Thanks for the great feedback. I'll add this request to my backlog.
