### ISSUE TITLE
Java EE applications

### ISSUE THREAD

**Issue by ashoksuryap** [MicrosoftDocs/azure-dev-docs#79]
why we can not install websphere in VM directly? Any reason for keeping it in planning(in Java EE applications section)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e235d8-3078-72fd-e2ef-25796a9dd8d8
* Version Independent ID: fa1a6f25-9ca9-72e0-87bd-98f1f93e5e94
* Content: [Migrate Java applications to Azure](https://docs.microsoft.com/en-us/azure/java/migration-overview#feedback)
* Content Source: [java/migration-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/migration-overview.md)
* Service: **azure-java**
* GitHub Login: @yevster
* Microsoft Alias: **yebronsh**

**Comment by bmitchell287** [comment]
@yevster  - Would you please provide feedback or route to appropriate contact? Thanks.

**Comment by KarlErickson** [comment]
@ashoksuryap thanks for the feedback! I apologize for the miscommunication in this topic. You can install WebSphere in a VM directly. Where the topic says "planned", we're referring to guidance documentation that we're still working on. I will submit a pull request to change the topic to make that clear. (When the pull request is merged, it will close this issue automatically.) Thanks again!

**Comment by selvasingh** [comment]
Added @edburns and @m-reza-rahman

**Comment by m-reza-rahman** [comment]
Hello @ashoksuryap,

Would you mind sending me an email at reza dot rahman at microsoft dot com on this topic? In short, we can easily prioritize this work if we can identify a credible customer that would follow this migration path.

Thanks,
Reza
