### ISSUE TITLE
Input parameter 'redirect_uri' not valid

### ISSUE THREAD

**Issue by poochie89** [MicrosoftDocs/azure-dev-docs#791]
I am following the guide but when trying to login with the Microsoft account I am getting
"invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application."

I added `http://localhost` to the redirect URIs
The submitted url contains the correct uri
https://login.live.com/oauth20_authorize.srf?....&redirect_uri=http%3a%2f%2flocalhost%3a56183&....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485cc056-932a-2383-55b4-b93a223d22e7
* Version Independent ID: 814489ea-74c8-3e4b-6b1c-95afdc7e0476
* Content: [Add authentication to your Windows (WPF) app](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/wpf/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/wpf/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/wpf/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
The redirect_uri you are sending is wrong - it's `http://localhost:56183` instead of `http://localhost` - it needs to match exactly.

**Comment by adrianhall** [comment]
Closing off older issues with no feedback.  The instructions are verified correct.

#please-close
