### ISSUE TITLE
Error while deploying the hub-spoke deployment with Terraform

### ISSUE THREAD

**Issue by merwindz** [MicrosoftDocs/azure-dev-docs#795]
[Enter feedback here]

I am testing this deployment using terraform and get the below errors. Do you know if this has been addressed?

Thanks

Merwin

C:\learn-terraform-azure>terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v3.0.2

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

C:\learn-terraform-azure>terraform plan -out main.tfplan
var.password
  Password for Virtual Machines

  Enter a value: Password@2022

╷
│ Error: expected route.0.next_hop_type to be one of [VirtualNetworkGateway VnetLocal Internet VirtualAppliance None], got vnetlocal
│
│   with azurerm_route_table.spoke1-rt,
│   on hub-nva.tf line 129, in resource "azurerm_route_table" "spoke1-rt":
│  129: resource "azurerm_route_table" "spoke1-rt" {
│
╵
╷
│ Error: expected route.0.next_hop_type to be one of [VirtualNetworkGateway VnetLocal Internet VirtualAppliance None], got vnetlocal
│
│   with azurerm_route_table.spoke2-rt,
│   on hub-nva.tf line 165, in resource "azurerm_route_table" "spoke2-rt":
│  165: resource "azurerm_route_table" "spoke2-rt" {
│
╵
╷
│ Error: Reference to undeclared resource
│
│   on output.tf line 2, in output "resource_group_name":
│    2:     value = azurerm_resource_group.rg.name
│
│ A managed resource "azurerm_resource_group" "rg" has not been declared in the root module.
╵

C:\learn-terraform-azure>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e973d5-b117-99c6-f0a0-c7d779ea3ea0
* Version Independent ID: d4d46d49-d837-6d99-2f50-5578f67b1e89
* Content: [Validate a hub and spoke network in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/hub-spoke-validation)
* Content Source: [articles/terraform/hub-spoke-validation.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/hub-spoke-validation.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by JCP13** [comment]
Greetings, any update on this issue? because I am getting the same error.

**Comment by JCP13** [comment]
A quick Update, the error was right in front of me and I did not see it (I blame it at looking at code for too long). It is a case sensitive issue. must change  "vnetlocal" to "VnetLocal".

**Comment by TomArcherMsft** [comment]
@merwindz @JCP13 Thanks for the feedback and help debugging the issue. I'll get this article updated this week.

**Comment by JCP13** [comment]
Thank you @TomArcherMsft , and one more thing, please add a Resource Group to the update.
