### ISSUE TITLE
What will be the Login page credentials 

### ISSUE THREAD

**Issue by Khushali-DG** [MicrosoftDocs/azure-dev-docs#796]
[Enter feedback here]

As I run this command: "curl -X POST localhost:8080/messages?message=hello" it is taking me to a sign in page.
What should be the username-password for this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbecafd0-c6db-9cb0-c5a4-328946446ec6
* Version Independent ID: 40cea238-c2de-fd1d-fef7-c1a850b54158
* Content: [How to use the Spring Boot Starter for Azure Service Bus JMS](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-service-bus.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **seal**

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
Hi @Khushali-DG , could you share your application.properties and pom.xml to help me reproduce this issue? seems like the there are spring security related function getting triggered.

**Comment by KarlErickson** [comment]
No reply - closing
