### ISSUE TITLE
Unsupported function version

### ISSUE THREAD

**Issue by mafverargulla** [MicrosoftDocs/azure-dev-docs#797]
When creating the function, I receive this error:
Functions version 2 is not supported for runtime python with version 3.7 and os linux. Supported functions versions are ['4', '3']. Run 'az functionapp list-runtimes' for more details on supported runtimes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bbb5dd1-f7fa-5ebe-1c47-1eef3182db5b
* Version Independent ID: 97bc93df-959a-ffd6-a084-ffeb99a2d94c
* Content: [Create resources for a cloud-based, serverless ETL solution using Python on Azure](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-serverless-cloud-etl-02)
* Content Source: [articles/python/tutorial-deploy-serverless-cloud-etl-02.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-deploy-serverless-cloud-etl-02.md)
* Product: **azure-python**
* GitHub Login: @jess-johnson-msft
* Microsoft Alias: **jejohn**

**Comment by jessmjohnson** [comment]
Hello, Thank you for bringing this to our attention! This issue is currently being triaged and will be addressed in our next sprint roll out.

**Comment by diberry** [comment]
@mafverargulla This is an issue you your local environment have version 2 of azure-functions-core-tools. Please update your package: 

```
npm i -g azure-functions-core-tools@4 --unsafe-perm true
```
