### ISSUE TITLE
Terratest Documentation is not up to date

### ISSUE THREAD

**Issue by ASHR4** [MicrosoftDocs/azure-dev-docs#800]
The Unit Test Section no longer works. For the plan which uses the terraformCore.ReadPlan is no longer a a method and breaks the remaining code. 

The import for terraformCore is also wrong, as it now points to:

github.com/hashicorp/terraform-plugin-sdk/terraform

I’m keen to understand, following these docs, how to complete unit tests with go as I’m unfamiliar with the language and I’m relying heavily on these docs which don’t seem to be correct

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a16eed4-6a1c-7bf5-1ce8-bef512ba3c43
* Version Independent ID: c44ea309-2614-62d4-da5b-3ad1ec086866
* Content: [Test Terraform modules in Azure using Terratest](https://docs.microsoft.com/en-us/azure/developer/terraform/test-modules-using-terratest)
* Content Source: [articles/terraform/test-modules-using-terratest.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/test-modules-using-terratest.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by aiden-liu** [comment]
Hi,
I same am suffering from this doc, and hoping to be guided of best practices. Given the initial timestamp of this issue, wonder if there's any updates on doc updates please?

Thanks

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
