### ISSUE TITLE
Terraform code example requires "priority" argument in "request_routing_rule" block within Application Gateway resource

### ISSUE THREAD

**Issue by mgrlabs** [MicrosoftDocs/azure-dev-docs#801]
If you attempt to deploy the Terraform code in this example as is, it will fail due to the introduction of mandatory priorities in the `request_routing_rule` block within the `azurerm_application_gateway` resource. Introduced as a mandatory field in AzureRM provider 3.6.0.

Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#priority

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Version Independent ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Content: [Deploy an Azure Application Gateway v2 using Terraform to direct web traffic](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-application-gateway-v2?toc=%2Fazure%2Fapplication-gateway%2Ftoc.json&bc=%2Fazure%2Fapplication-gateway%2Fbreadcrumb%2Ftoc.json)
* Content Source: [articles/terraform/deploy-application-gateway-v2.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-application-gateway-v2.md)
* Service: **terraform**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
