### ISSUE TITLE
[Clarifications] Difference between @PartitionKey (Spring annotation) and partition_key_path (Container parameter)

### ISSUE THREAD

**Issue by aomegax** [MicrosoftDocs/azure-dev-docs#802]
Hi, 
I don't understand the difference between `partition_key_path` that I should set during container creation and the Spring annotation `@PartitionKey` used when I define an entity in my app.

Which is the relationship between the two modes?

In my case, I don't have nested keys, but I need to partition on a base field (ie. firstName), so I set it (ie /firstName) as `partition_key_path`. Then do I annotate firstName field with `@PartitionKey` in my code too? or is it unnecessary?

I read in [this article](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-data-cosmos-readme?view=azure-java-stable#nested-partition-key-support) that `@PartitionKey` annotation takes precedence versus `partitionKeyPath` defined in the `@Container`. Is it the same case of `partition_key_path` defined at Container definition context? If yes, in this case I could leave `/id` as `partition_key_path` and manage partitioning at applicative level.

Thank you for the support.

**Comment by KarlErickson** [comment]
@seanli1988 can you comment?
@aomegax this issues list is for documentation feedback, so you might want to ask your question on the [Q&A forum](https://docs.microsoft.com/en-us/answers/index.html) also. Thanks!

**Comment by saragluna** [comment]
@kushagraThapar could you help with this?

**Comment by aomegax** [comment]
[Here](https://docs.microsoft.com/en-us/answers/questions/885167/clarifications-difference-between.html) the question on the forum. 
Now it is clear for me. Probably, this should be written in the documentation, in order to clarify this case.
Thanks!

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @kushagraThapar ?

**Comment by kushagraThapar** [comment]
@aomegax if your partition key is part of the entity that represents the collection, then you can just annotate your field with `@PartitionKey` annotation, which in your case looks like the correct thing to do. 
`partition_key_path` is for nested partition keys and only works in case if the entity that represents the collection has a child entity which has a filed that represents the partition key, which doesn't look like your case.

**Comment by kushagraThapar** [comment]
@TheovanKraay - can you please follow up on this, thanks!

**Comment by kushagraThapar** [comment]
@KarlErickson can you please assign this to Theo?

**Comment by KarlErickson** [comment]
Feedback has been communicated to the correct owner. Closing.
