### ISSUE TITLE
yeoman cannot run in cloud shell

### ISSUE THREAD

**Issue by oldwatch** [MicrosoftDocs/azure-dev-docs#804]
in cloud shell
yeoman's version is 4.3.0 
nodejs version is 8.16.1

but
Yo@4 supports node >= 12.10.0
https://github.com/yeoman/yo/issues/665

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06e75bd-7854-f965-71b0-79fd29eb12fe
* Version Independent ID: 26cfa42b-f393-a62c-fb0b-37be423702ea
* Content: [Create a Terraform base template in Azure using Yeoman](https://docs.microsoft.com/en-us/azure/developer/terraform/create-base-template-using-yeoman#6-use-yeoman-generator-to-create-and-test-a-module)
* Content Source: [articles/terraform/create-base-template-using-yeoman.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-base-template-using-yeoman.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
