### ISSUE TITLE
Documentation for AMPLS

### ISSUE THREAD

**Issue by mmyers299** [MicrosoftDocs/azure-dev-docs#805]
This is a great starter document but I'd love to see more complicated scenarios documented such as how to use Terraform to implement Azure Monitor Private Link 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde74b44-d938-eb2e-884a-9321415bcb3e
* Version Independent ID: bde74b44-d938-eb2e-884a-9321415bcb3e
* Content: [Configure Log Analytics Workspace using Terraform - Azure](https://docs.microsoft.com/en-us/azure/developer/terraform/create-avd-log-analytics-workspace)
* Content Source: [articles/terraform/create-avd-log-analytics-workspace.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-avd-log-analytics-workspace.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@mmyers299 Good news. I've been in contact with the Azure Monitor writers to publish several Terraform articles. ETA is unknown at the moment as we're upgrading all Terraform sample code to automatically test against each new version of Terraform. Once that task is complete, we'll work on the customer article-backlog (which includes the Monitor articles).
