### ISSUE TITLE
Actions to Azure via OIDC - unnecessarily secret?

### ISSUE THREAD

**Issue by johnterickson** [MicrosoftDocs/azure-dev-docs#807]
Is there a reason why we instruct folks to mark these variables as secrets?  It seems unnecessary and the point of the whole flow is that "you don't need secrets anymore!" 😁

```
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081be8c9-7871-db69-977c-9304daa6c870
* Version Independent ID: aa3e5074-a630-3756-be86-295d1a2d101f
* Content: [Connect GitHub and Azure](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-openid-connect)
* Content Source: [articles/github/connect-from-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/connect-from-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by juliakm** [comment]
Thanks, closing for now because we shared this feedback with the product team. 

#please-close
