### ISSUE TITLE
Incorrect instructions.

### ISSUE THREAD

**Issue by Erol-E** [MicrosoftDocs/azure-dev-docs#808]
https://docs.microsoft.com/en-au/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/uwp/offline#set-the-offline-database-location)
I think this part is copied from the instructions for TodoApp.WinWPF and need to be changed to TodoApp.WinUWP?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7934ed86-2493-cc38-c27a-6b2dd5ecb58e
* Version Independent ID: adfd8bf9-efa1-faf8-61f1-ba6abaed63a8
* Content: [Add offline data sync to your Windows (UWP) app](https://docs.microsoft.com/en-au/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/uwp/offline)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/uwp/offline.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/uwp/offline.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Thanks for the report - the UWP and WPF instructions share this piece.  I'll get it updated today.

**Comment by adrianhall** [comment]
Corrected instructions are updated and will be rolled out in the next publish cycle.

#please-close
