### ISSUE TITLE
Out of date resource

### ISSUE THREAD

**Issue by shermanyin** [MicrosoftDocs/azure-dev-docs#809]
The Terraform code seems to be a bit dated despite being updated a month ago.

e.g. 
- azure_lb_probe doesn't take a resource_group_name (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_probe)

- azurerm_virtual_machine_scale_set is deprecated https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set and I'd imagine Azure want to promote azurerm_orchestrated_virtual_machine_scale_set instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560d5902-d21c-a085-86a2-3189dde5d76c
* Version Independent ID: 7c19fad6-c65a-847d-a98c-0f9c9e4c6217
* Content: [Create an Azure virtual machine scale set using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-hcl)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-scaleset-network-disks-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
