### ISSUE TITLE
The following code is missing in main.tf

### ISSUE THREAD

**Issue by yukit7s** [MicrosoftDocs/azure-dev-docs#812]
[Enter feedback here]

I think the following code is missing in `main.tf`

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      # version = "=3.10.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14080c3b-027f-93e1-fd0f-4bea971f51b0
* Version Independent ID: 5894d6ec-4347-153c-fa9a-203d41275153
* Content: [Install the Azure Terraform Visual Studio Code extension](https://docs.microsoft.com/en-us/azure/developer/terraform/configure-vs-code-extension-for-terraform?tabs=azure-cli)
* Content Source: [articles/terraform/configure-vs-code-extension-for-terraform.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-vs-code-extension-for-terraform.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Tythos** [comment]
This should be defined in your *providers.tf* file; in this example, *main.tf* is primarily used to enumerate the specific resources/references in the infrastructure (as opposed to provider-specific dependencies).

**Comment by TomArcherMsft** [comment]
@yukit7s Apologies for responding to this so late. I've been out on some summer vacation. As @Tythos says, this information (the provider declaration) is in the providers.tf file.

**Comment by yukit7s** [comment]
@TomArcherMsft Thank you for your reply. If you can add the following code to this tutorial, I think that beginners will not get lost.

https://learn.microsoft.com/en-us/azure/developer/terraform/configure-vs-code-extension-for-terraform?tabs=azure-cli#3-implement-the-terraform-code

```
1. Create a file named `providers.tf` and insert the following code:

    [!code-terraform[master](../../terraform_samples/quickstart/101-resource-group/providers.tf)]

```
