### ISSUE TITLE
Need to specify managed identity if it is actually managed?

### ISSUE THREAD

**Issue by Trailbear** [MicrosoftDocs/azure-dev-docs#813]
Note says: "If you use client-id and client-secret, you shouldn't use managed-identity, and if you use managed-identity, you shouldn't use client-id and client-secret."

It seems like you would normally let the machine provide the object Id of its own managed identity unless it was specifically user provided.  Is this instruction meant for both situations or just the user provided scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 158dedb3-7c29-ddae-96b2-ec0b4f348094
* Version Independent ID: 158dedb3-7c29-ddae-96b2-ec0b4f348094
* Content: [Use Azure Key Vault to deliver TLS/SSL certificates to the JVM](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-azure-keyvault-ssl-integration-jvm#how-to-run-your-application)
* Content Source: [articles/java/fundamentals/java-azure-keyvault-ssl-integration-jvm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/fundamentals/java-azure-keyvault-ssl-integration-jvm.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **manriem**

**Comment by mnriem** [comment]
In principle it should not be much different than how our managed services operate, but I have not tested this particular scenario. @saragluna Can you test to see if an Azure VM with a managed identity works too and if so adjust the documentation to reflect how that is done?

**Comment by saragluna** [comment]
@moarychan please take a look at this.

**Comment by moarychan** [comment]
Hi all, I just tested through the following two scenarios in an Azure VM:

1. Use system-assigned identity, it's not necessary to append `-Dazure.keyvault.managed-identity=<xxx>`.
I check the source code, and there's a comment for this scenario:
![image](https://user-images.githubusercontent.com/19926623/177501832-3faa1141-7a3d-43ac-b8ac-80b0817e2411.png)

And another important comment is not working in Azure App Service.

2. Use user-managed identity, it must use the object id for the managed-identity value, `-Dazure.keyvault.managed-identity=<replace-with-the-object-id-of-your-user-managed-identify>`.

I will update the documentation to clarify both scenarios.

**Comment by mnriem** [comment]
@moarychan Thanks for validating!

**Comment by KarlErickson** [comment]
@moarychan thanks! Will you or @saragluna please create a PR to update the article? Thanks!

**Comment by saragluna** [comment]
Thanks, @KarlErickson. @moarychan will help create a PR to update the article. 

@moarychan please make sure we provide the guide on which properties to set when using different authentication methods and clarify the expected values of properties like the KV uri.
