### ISSUE TITLE
Please help check why the doc can't be run successfully.

### ISSUE THREAD

**Issue by ZHIXIN-SUN** [MicrosoftDocs/azure-dev-docs#815]
Dear Team,

Could you please help check why the doc is not working why I run "ansible-playbook aks-azure-cni.yml". I am totally using the yml file as   our template. 
![image](https://user-images.githubusercontent.com/58249056/176153173-01c43dde-7b13-40d5-9bdc-e3bf5be81a2f.png)

BR//Zhixin

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73fe5788-9351-668f-cca0-65060f4c6517
* Version Independent ID: 02f68fd7-b4f7-6e75-31d0-a28c71f768e8
* Content: [Tutorial - Configure Azure CNI networking in Azure Kubernetes Service (AKS) using Ansible](https://docs.microsoft.com/en-us/azure/developer/ansible/aks-configure-cni-networking?tabs=ansible)
* Content Source: [articles/ansible/aks-configure-cni-networking.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/aks-configure-cni-networking.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ZHIXIN-SUN The devs don't believe that this issue is related to the docs. Based on their feedback, I'm closing this issue. If you disagree, please let us know and we'll investigate further.
