### ISSUE TITLE
FCM Update for Send push notifications to React Native apps using Azure Notification Hubs via a backend service

### ISSUE THREAD

**Issue by MysteryAchievement** [MicrosoftDocs/azure-dev-docs#818]
The instructions for getting the FCM server key have changed.  In step 5 of the Create a Firebase project and enable Firebase Cloud Messaging for Android section, the tutorial instructs the reader to "Switch to the Cloud Messaging tab at the top. Copy and save the Server key for later use. "  Unfortunately, Google has changed this.  There is a new section titled "Cloud Messaging API (Legacy)" which is disabled by default.  The reader must first enable the legacy section by clicking on the verlipsis on the right side of the section, select the Manage API in Google Cloud Console popup menu item and enable Cloud Messaging.  Once complete, the user can navigate back to the Project settings and refresh the Cloud Messaging tab in order to see the Server key and its corresponding token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60458a66-21b6-1ace-2626-99faaa2e7fc6
* Version Independent ID: 9b339fcf-7c2f-b2e5-d9ca-00c0187f7062
* Content: [Send push notifications to React Native apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-react-native)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-react-native.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-react-native.md)
* Service: **mobile-services**
* GitHub Login: @alexeystrakh
* Microsoft Alias: **alstrakh**

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
