### ISSUE TITLE
Errors galore

### ISSUE THREAD

**Issue by martyt** [MicrosoftDocs/azure-dev-docs#819]
Did anyone actually test the Terraform scripts on this page? 

Nothing works out of the box - there are references to incorrect terraform object names, missing variables, etc. etc. - sure, I can eventually fight my way through the issues, but I wasn't looking to go on a bug-squashing expedition when I decided to use this how-to...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@martyt Update: We've shipped the new product I was working on, and I'm looking into this article and why it's broken. I'll respond as soon as I have something substantive to relay.

**Comment by TomArcherMsft** [comment]
@martyt The code has been completely updated and tested. I'm awaiting engineering-team sign-off, and then the article will be republished. Keep in mind that the nature of basing documentation on open-source and/or third-party products means that broken changes will occur in the future. Thanks to people such as yourself, we're able to learn of these breaks in our docs and fix them. The updated article should be live in the next couple of days.

**Comment by TomArcherMsft** [comment]
The [updated article](https://docs.microsoft.com/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks) is now live.
