### ISSUE TITLE
What command to use to connect azure devops PAT authentication

### ISSUE THREAD

**Issue by SarveshPandey** [MicrosoftDocs/azure-dev-docs#821]
Hi Team,

$az devops login --organization https://dev.azure.com/contoso
Token:

above command is used only in Azure CLI. what command should i use in PowerShell ISE.
In PowerShell, az is not recognizing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac17c09f-fe22-0eae-855f-dca9eb5b660e
* Version Independent ID: c3c47436-7e6b-7af2-03e8-ef05159813ba
* Content: [Quickstart - Choosing the right command-line tool for Azure](https://docs.microsoft.com/en-us/azure/developer/azure-cli/choose-the-right-azure-command-line-tool)
* Content Source: [articles/azure-cli/choose-the-right-azure-command-line-tool.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-cli/choose-the-right-azure-command-line-tool.md)
* Service: **azure**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by KarlErickson** [comment]
No response, closing.
