### ISSUE TITLE
wrong references and depricated blocks

### ISSUE THREAD

**Issue by sumansrivastava** [MicrosoftDocs/azure-dev-docs#823]
Morning Tom,

My name is Suman Srivastava, I was just running the codes with the new terraform azrerm providers =3.0.0 and found the below two blocks are not working.

1. azurerm_resource_group is referenced with rg and been called as k8s in subsequent resource blocks.
2. addon_profile is no more valid block and this needs to be corrected.
3. network_profile is pointing to SKU="Standard" whch is not valid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a750d14-2f87-914e-8715-fac805c8ba3b
* Version Independent ID: f8d16dbe-e594-408c-18d8-26fc95de6c65
* Content: [Create a Kubernetes cluster with Azure Kubernetes Service (AKS) using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks)
* Content Source: [articles/terraform/create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-tf-and-aks.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@tyadon The code has been completely updated and tested. I'm awaiting engineering-team sign-off, and then the article will be republished. Thanks again for your contribution!

**Comment by TomArcherMsft** [comment]
The [updated article](https://docs.microsoft.com/azure/developer/terraform/create-k8s-cluster-with-tf-and-aks) is now live.
