### ISSUE TITLE
Java to Azure migration doc should include JBoss EAP to ARO scenario

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#825]
Java to Azure migration doc should include JBoss EAP to ARO scenario

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3197694f-b089-2836-8d00-28d0cb994079
* Version Independent ID: fc99326c-665f-17b1-e2b2-2f4c9b3079d9
* Content: [Migrate JBoss EAP applications to JBoss EAP on Azure App Service](https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-jboss-eap-to-jboss-eap-on-azure-app-service)
* Content Source: [articles/java/migration/migrate-jboss-eap-to-jboss-eap-on-azure-app-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migrate-jboss-eap-to-jboss-eap-on-azure-app-service.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
+ @selvasingh for awareness
