### ISSUE TITLE
Java to Azure migration doc should include Spring Boot Apps migration to Azure Container Apps

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#826]
Java to Azure migration doc should include Spring Boot Apps migration to Azure Container Apps

See also [https://github.com/MicrosoftDocs/azure-dev-docs/issues/825](https://github.com/MicrosoftDocs/azure-dev-docs/issues/825)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3830ec12-c308-1d59-07c8-be295d8db7a3
* Version Independent ID: b4439660-4af0-12eb-408b-ec9a181ec505
* Content: [Migrate Spring Boot applications to run on Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-kubernetes-service)
* Content Source: [articles/java/migration/migrate-spring-boot-to-azure-kubernetes-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migrate-spring-boot-to-azure-kubernetes-service.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **manriem**

**Comment by KarlErickson** [comment]
The migration overview now includes coverage of Azure Container Apps. See <https://learn.microsoft.com/en-us/azure/developer/java/migration/migration-overview#migration-guidance>.
