### ISSUE TITLE
Java to Azure migration doc should include JBoss EAP to ARO with Quarkus

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#827]
Java to Azure migration doc should include JBoss EAP to ARO with Quarkus

See also [https://github.com/MicrosoftDocs/azure-dev-docs/issues/825](https://github.com/MicrosoftDocs/azure-dev-docs/issues/825)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b005cd61-1215-3f36-3a1a-bb738160b44f
* Version Independent ID: 41598425-9c7d-4a94-0be2-a588eafa6baf
* Content: [Migrate JBoss EAP applications to WildFly on Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-jboss-eap-to-wildfly-on-azure-kubernetes-service)
* Content Source: [articles/java/migration/migrate-jboss-eap-to-wildfly-on-azure-kubernetes-service.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migrate-jboss-eap-to-wildfly-on-azure-kubernetes-service.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **manriem**

**Comment by KarlErickson** [comment]
+@selvasingh for awareness
