### ISSUE TITLE
Package react-native-push-notification is no longer maintained.

### ISSUE THREAD

**Issue by ThugLifeAquatic** [MicrosoftDocs/azure-dev-docs#828]
This implementation is no longer working in our production app. Not sure what to recommend, but with the above package no longer being maintained, there is no longer a documented way to reliably implement cross platform react-native push notifications using Azure notification hubs.  Notifee seems to be the recommended replacement for the expired package, but it only supports notifications through FCM, and ANH doesn't seem to support iOS notifications for FCM.  If there's a way to use ANH without the dead package, I'd love to see this doc updated with that info.  Right now I'm considering replacing ANH with FCM, but that would be a ton of work both client and server side.

**Comment by KarlErickson** [comment]
@ThugLifeAquatic never mind, I see that you filed another issue with the information. Thanks!
