### ISSUE TITLE
Required package React-Native-Push-Notification is no longer maintained

### ISSUE THREAD

**Issue by ThugLifeAquatic** [MicrosoftDocs/azure-dev-docs#829]
This implementation is no longer working in our production app. Not sure what to recommend, but with the above package no longer being maintained, there is no longer a documented way to reliably implement cross platform react-native push notifications using Azure notification hubs. Notifee seems to be the recommended replacement for the expired package, but it only supports notifications through FCM, and ANH doesn't seem to support iOS notifications for FCM. If there's a way to use ANH without the dead package, I'd love to see this doc updated with that info. Right now I'm considering replacing ANH with FCM, but that would be a ton of work both client and server side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60458a66-21b6-1ace-2626-99faaa2e7fc6
* Version Independent ID: 9b339fcf-7c2f-b2e5-d9ca-00c0187f7062
* Content: [Send push notifications to React Native apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-react-native)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-react-native.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-react-native.md)
* Service: **mobile-services**
* GitHub Login: @alexeystrakh
* Microsoft Alias: **alstrakh**

**Comment by jLoven** [comment]
Having the same issue here. Thank you for looking into this!

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
