### ISSUE TITLE
Azure Python SDK doesn't support "sudo pip install"

### ISSUE THREAD

**Issue by jasonzio** [MicrosoftDocs/azure-dev-docs#83]
There's no way to install the Azure Python SDK one time on a Linux system such that it can be used by python code running under multiple uids on that system. Each user (e.g. each service account) must install the SDK separately (so that it appears under /home/<user>/.local

The documentation should be clear about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b440c3f1-e186-48e8-e98d-508f0d704f72
* Version Independent ID: c4dfd464-e21e-ac43-c355-d2e3f35d6f45
* Content: [Install the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-install)
* Content Source: [python/python-sdk-azure-install.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/python-sdk-azure-install.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for explaining the detail. I'll add a small note to that effect.
