### ISSUE TITLE
Update the hosting grid

### ISSUE THREAD

**Issue by harrchen88** [MicrosoftDocs/azure-dev-docs#834]
I would like to propose you to update the hosting grid:
1. Use the correct name for "Azure Spring Apps" instead of "Azure Spring Cloud"
2. Please add "Azure Container Apps" to the options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f7f8f0-3ecb-c09c-8545-b0d98e5396df
* Version Independent ID: fc186d62-3f1f-c8a2-2a27-8f13a6dcd817
* Content: [Migrate Java applications to Azure](https://docs.microsoft.com/en-us/azure/developer/java/migration/migration-overview)
* Content Source: [articles/java/migration/migration-overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/migration/migration-overview.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
Hi @harrchen88 - thanks for the feedback! I overlooked that instance of "Azure Spring Cloud". I'll fix that right away. Also, we have guidance for Azure Container Apps in progress, so we'll add that soon.

**Comment by KarlErickson** [comment]
Doc has been updated - closing
