### ISSUE TITLE
Clarify the Java on Azure support

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#835]
Could you please clarify the Java on Azure support at [https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-support-on-azure#customer-support](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-support-on-azure#customer-support), adding a FAQ or clear statements like : 

- A customer deployed to an on-prem VM, a Spring Boot App which uses Spring Cloud for Azure, will he get  "Java on Azure" support from MS ? ==> Yes

- A customer deployed a Spring Boot App to AKS which read secrets from Azure Key Vault using spring Cloud for Azure, will he get  "Java on Azure" support from MS ? ==> Yes

- A customer deployed to Azure Spring Apps a Spring Boot App and found a bug in Spring Security, will he get  "Spring Runtime" support ? Yes from VMWare choosing [Enterprise Tier](https://docs.microsoft.com/en-us/azure/spring-cloud/faq?pivots=programming-language-java#how-do-i-get-vmware-spring-runtime-support-enterprise-tier-only). 
  - See also [https://aka.ms/EnterpriseTierFAQ](https://aka.ms/EnterpriseTierFAQ)
  
- A customer deployed to an on-prem VM, a Spring Boot App which uses Azure Application Insights, will he get  "Application Insights" support from MS ? ==> Yes

- customer deployed a Java Quarkus App to Azure Container Apps, will he get  "Java on Azure" support from MS ?
  - No if there is there is no integration with Azure REST APIs
  - Customers requiring support on the Quarkus runtime itself can get support from [RedHat through Red Hat Middleware Subscriptions Bundles](https://access.redhat.com/articles/3666991) "Red Hat Runtimes" which includes Cloud Native Runtimes : Red Hat build of Quarkus, and Red Hat support for Spring Boot, Red Hat build of Thorntail, Red Hat build of Eclipse Vert.x, Red Hat build of Node.js

- Azure Service Bus / Java XA transactions support : see [https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp#unsupported-features-and-restrictions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp#unsupported-features-and-restrictions)

- [Spring Boot Reference Documentation](https://docs.spring.io/spring-boot/docs/2.7.4/reference/htmlsingle/#io.jta) : Spring Boot supports distributed JTA transactions across multiple XA resources by using an Atomikos embedded transaction manager. JTA transactions are also supported when deploying to a suitable Java EE Application Server. When a JTA environment is detected, Spring’s JtaTransactionManager is used to manage transactions. Auto-configured JMS, DataSource, and JPA beans are upgraded to support XA transactions. You can use standard Spring idioms, such as @Transactional, to participate in a distributed transaction. If you are within a JTA environment and still want to use local transactions, you can set the spring.jta.enabled property to false to disable the JTA auto-configuration.
  - [https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.transaction.spring.jta.enabled](https://docs.spring.io/spring-boot/docs/2.7.3/reference/html/application-properties.html#application-properties.transaction.spring.jta.enabled) : true by default
- About [Camel and XA support](https://camel.apache.org/components/3.18.x/eips/transactional-client.html) :
  - Transactions are supported by Spring Transactions and also with a JTA Transaction Manager.
 Traditionally a JTA Transaction Manager are included in JEE application servers. However, when running microservice applications with Spring Boot, or Quarkus, then a 3rd-party JTA transaction manager can be embedded and used.
 In Camel transactions are supported by JMS messaging components:

  - [ActiveMQ](https://camel.apache.org/components/3.18.x/activemq-component.html)
  - [JMS](https://camel.apache.org/components/3.18.x/jms-component.html)
  - [Simple JMS](https://camel.apache.org/components/3.18.x/sjms-component.html)
  - [Simple JMS 2.x](https://camel.apache.org/components/3.18.x/sjms2-component.html)

   And all the SQL database components, such as:
   - [JDBC](https://camel.apache.org/components/3.18.x/jdbc-component.html)
   - [JPA](https://camel.apache.org/components/3.18.x/jpa-component.html)
   - [SQL](https://camel.apache.org/components/3.18.x/sql-component.html)
   - [MyBatis](https://camel.apache.org/components/3.18.x/mybatis-component.html)

- ACR Fails to build my Dockerfile containing a Spring Boot App, see this [bug](https://github.com/moby/moby/issues/37965) ==> Java Dev. would hit it in 80% of cases

- GH Actions & Build how-to : 

  - [https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Microsoft](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Microsoft) 
  - [https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) 
  - [https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages) 
  - [https://github.com/marketplace/actions/generate-settings-xml-for-maven-builds](https://github.com/marketplace/actions/generate-settings-xml-for-maven-builds) 
  - [https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altDeploymentRepository](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altDeploymentRepository) 
  - 
  - ACR image build with Build Pack (Preview) : [https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-pack-build](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-tasks-pack-build )

@selvasingh 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b4b9c70-5ce2-1cd3-e6be-5e70717f4afe
* Version Independent ID: a794996e-8005-c4d9-03d0-fecb203ad701
* Content: [Java JDKs support for Azure development](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-support-on-azure)
* Content Source: [articles/java/fundamentals/java-support-on-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/fundamentals/java-support-on-azure.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**
*

**Comment by ezYakaEagle442** [comment]
@KarlErickson could you provide an update now it is end of Q1, that would help customers + the MS field ?

**Comment by KarlErickson** [comment]
@selvasingh @brunoborges can one of you comment here? Thanks.

**Comment by ezYakaEagle442** [comment]
@jdubois

**Comment by jdubois** [comment]
I believe those are valid points and answers, maybe they are limited to using the Microsoft Build of OpenJDK? @brunoborges will know.
For Quarkus, if he builds a native image, I have no idea if we can support this at all (for the moment).

**Comment by ezYakaEagle442** [comment]
can we get an update on this issue please ?

**Comment by KarlErickson** [comment]
@brunoborges @jdubois ping

**Comment by KarlErickson** [comment]
Closing. Please contact @selvasingh directly if you still have concerns here.
