### ISSUE TITLE
Azure Developer CLI (azd) _ Page not Found

### ISSUE THREAD

**Issue by rawatsudhir1** [MicrosoftDocs/azure-dev-docs#840]
The link on the page lands on "404 - Page not found" 

![image](https://user-images.githubusercontent.com/32550309/178673636-727dd942-81f3-436c-8634-23635834a4ea.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da63649f-5dd6-83c7-8d42-46b4b1291e47
* Version Independent ID: da63649f-5dd6-83c7-8d42-46b4b1291e47
* Content: [What is the Azure Developer CLI (azd) Preview?](https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/overview?tabs=csharp#azure-developer-cli-templates)
* Content Source: [articles/azure-developer-cli/overview.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/overview.md)
* Product: **azure**
* GitHub Login: @puicchan
* Microsoft Alias: **puichan**

**Comment by KarlErickson** [comment]
Fixed by #839
