### ISSUE TITLE
Wide umask can lead to ssh failure when quickstarting with terraform

### ISSUE THREAD

**Issue by filippog** [MicrosoftDocs/azure-dev-docs#841]
The instructions on the page mention writing the ssh key as such:

```
terraform output -raw tls_private_key > id_rsa
```

And subsequently connect via ssh on the public IP:

```
ssh -i id_rsa azureuser@...
```

However depending on user's current umask (e.g. `0022`) the `id_rsa` file can end up with permissions too open, thus ssh refusing to use the key, and ultimately fail to login:

```
The authenticity of host '...' can't be established.
ECDSA key fingerprint is SHA256:wLV5tlAgJIPOyJwJMwgj795UZ2UvsFvqKvP7UZqTouU.
No matching host key fingerprint found in DNS.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '...' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for 'id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "id_rsa": bad permissions
azureuser@...: Permission denied (publickey).
```

The easiest fix I think is to `chmod 600 id_rsa` after writing out the file, what do you think ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Quickstart - Configure a Linux virtual machine in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@filippog Thanks much for the feedback. I'm updating that article now and will incorporate your feedback as well.

**Comment by TomArcherMsft** [comment]
@filippog I added your recommended fix as a troubleshooting tip into the article. Thanks again!

**Comment by filippog** [comment]
Thank you @TomArcherMsft for your help! I checked https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure and https://docs.microsoft.com/en-us/azure/developer/terraform/troubleshoot just now though I'm not finding the troubleshooting step. What article(s) should I be looking at ?

**Comment by TomArcherMsft** [comment]
@filippog My apologies. I should have explained that we publish every weekday morning (PST). Therefore, you'll see the new version of the article around 11:00 AM (PST).

**Comment by TomArcherMsft** [comment]
@filippog The article is live: https://docs.microsoft.com/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure#verify-the-results

**Comment by filippog** [comment]
Thank you @TomArcherMsft for the link and following up! Appreciate it
