### ISSUE TITLE
Preqreqs need update: az and gh cli

### ISSUE THREAD

**Issue by paulyuk** [MicrosoftDocs/azure-dev-docs#842]
[Enter feedback here]
The prereqs have two issues I can see in this doc:
1) it does not list `az cli` but I believe you need it to do the az login, at least currently
2) it prereqs Github cli (not just git) and I don't think that's needed.  Maybe it's a soft dependency just for creating pipelines? an could be labeled this way?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Version Independent ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Content: [Get started using Azure Developer CLI (azd) Preview](https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=bare-metal%2Cwindows&pivots=programming-language-nodejs)
* Content Source: [articles/azure-developer-cli/get-started.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/get-started.md)
* Product: **azure**
* GitHub Login: @puicchan
* Microsoft Alias: **puichan**

**Comment by alexwolfmsft** [comment]
Thanks, this doc was updated but the issue wasn't closed.

**Comment by alexwolfmsft** [comment]
#please-close
