### ISSUE TITLE
Suggestion: I'd like to see a link to all `azd-template` tagged templates and not just the curated list

### ISSUE THREAD

**Issue by paulyuk** [MicrosoftDocs/azure-dev-docs#843]
[Enter feedback here]
The `pick a template` anchor link points to a curated table of templates, which is fine for now.

However there are more, like [Dapr](aka.ms/daprazd), that we'll keep adding and so I'd love a "See all templates.." link to catch these.  Thoughts?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Version Independent ID: d31e2f07-64ce-ae10-e15b-4bc52e1c2fd5
* Content: [Get started using Azure Developer CLI (azd) Preview](https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/get-started?tabs=bare-metal%2Cwindows&pivots=programming-language-nodejs)
* Content Source: [articles/azure-developer-cli/get-started.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/get-started.md)
* Product: **azure**
* GitHub Login: @puicchan
* Microsoft Alias: **puichan**

**Comment by alexwolfmsft** [comment]
Thanks for this feedback, there is an updated link to the new Awesome AZD template gallery. We are currently working on updating the Getting Started section and will further address this.

**Comment by alexwolfmsft** [comment]
#please-close
