### ISSUE TITLE
Wrong backend pool variable assignment

### ISSUE THREAD

**Issue by gh2132** [MicrosoftDocs/azure-dev-docs#848]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Version Independent ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Content: [Deploy an Azure Application Gateway v2 using Terraform to direct web traffic](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-application-gateway-v2?toc=%2Fazure%2Fapplication-gateway%2Ftoc.json&bc=%2Fazure%2Fapplication-gateway%2Fbreadcrumb%2Ftoc.json)
* Content Source: [articles/terraform/deploy-application-gateway-v2.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-application-gateway-v2.md)
* Service: **terraform**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by TomArcherMsft** [comment]
Thanks, @gh2132 . The code and article have been updated and tested. The article will republish tomorrow morning (PST). If you still see the problem, please comment here and I'll investigate further.
