### ISSUE TITLE
URL for AZD YAML schema is incorrect

### ISSUE THREAD

**Issue by Sealjay** [MicrosoftDocs/azure-dev-docs#850]
URL for AZD YAML schema is incorrect

Is
> For full details, refer to [azure.yaml.json](https://github.com/Azure/azure-dev/blob/main/schemas/v1.0/azure.yaml.json/).

Should be
> For full details, refer to [azure.yaml.json](https://azuresdkreleasepreview.blob.core.windows.net/azd/schema/azure.yaml.json).

Pull request:  #849
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e84b0a-122b-5884-a21f-9284036afdb7
* Version Independent ID: 45e84b0a-122b-5884-a21f-9284036afdb7
* Content: [Make your project compatible with Azure Developer CLI (azd) Preview](https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/make-azd-compatible?pivots=azd-create)
* Content Source: [articles/azure-developer-cli/make-azd-compatible.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/make-azd-compatible.md)
* Product: **azure**
* GitHub Login: @hhunter-ms
* Microsoft Alias: **hannahhunter**

**Comment by hhunter-ms** [comment]
Hi @Sealjay - According to the engineering team, the link originally provided is correct. They used the schema copy on an Azure blob store as a temporary measure before the project was publicly announced. Hopefully this helps!
