### ISSUE TITLE
Container nodes webAppestapp_0_2ab2aa8a didn't respond to HTTP pings on port: 3000, failing site start. 

### ISSUE THREAD

**Issue by xboxeer** [MicrosoftDocs/azure-dev-docs#851]
Route from https://github.com/Azure/azure-sdk-for-js/issues/21572, not an SDK issue but docs optimize suggestion.

**Comment by diberry** [comment]
#In-progress

**Comment by diberry** [comment]
Resolved in other thread #please-close
