### ISSUE TITLE
Incomplete non-working code examples

### ISSUE THREAD

**Issue by Sergong** [MicrosoftDocs/azure-dev-docs#852]
[Enter feedback here]
The code examples here don’t work as there is no resource group specified for starters. I suspect there is much more missing as there is also no indication of how many cluster nodes will be deployed and how.
The impression is given that the code presented here can be copied and pasted to end up with a working example. This is far from the case here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df42c6c6-f4e0-072f-3fca-e3d97ccfe261
* Version Independent ID: da6a6e53-0803-3692-85cb-9a77fc231946
* Content: [Configure an Azure VM cluster using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-module)
* Content Source: [articles/terraform/create-vm-cluster-module.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-cluster-module.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Sergong Thanks for the feedback! I've rewritten this sample and the article should publish early next week.
