### ISSUE TITLE
scope doesnt exist for resource '00000003-0000-0000-c000-000000000000'

### ISSUE THREAD

**Issue by LKujala** [MicrosoftDocs/azure-dev-docs#857]
Followed steps to add Authentication. Two issues (may be related or not)
- the authentication form is opening multiple times (looks like recursion issue)
- getting error message that Application X asked for scope 'access_as_user' that doesnt exist on resource '00000003-0000-0000-c000-000000000000'

Raises two questions about code:
1 - how to test / debug authentication errors
2 - is there a recursion issue when retrieving data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Version Independent ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Content: [Add authentication to your .NET MAUI app](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by LKujala** [comment]
fixed the first problem: I didnt understand that the scope id was a globally unique uri of the form "api://<appid>/<scope_name>"... I was just using <scope_name>.

still getting the multiple login prompts. my suspicion is this is being triggered by the call to system.linq.async tolistasync function which loops through the data request async to add to a list. so the login is prompted for each item in the list until the async login is completed... just a guess.

**Comment by adrianhall** [comment]
I'm going to need more information about how you have set things up, as it isn't obvious from the report.  Please join us on https://github.com/azure/azure-mobile-apps where we run this open-source project.  There is a specific issue around MAUI.

Thanks!

**Comment by LKujala** [comment]
I am out of town right now.
As an FYI I noticed the same problem with the Xbox win10 app, where the login prompt comes up repeatedly.


This makes me think the problem has nothing to do with the Maui demo app but has something to do with the production code for managing identity that the demo app uses.



Sent from my Bell Samsung device over Canada's largest network.



-------- Original message --------
From: Adrian Hall ***@***.***>
Date: 2022-08-08 3:16 p.m. (GMT-08:00)
To: MicrosoftDocs/azure-dev-docs ***@***.***>
Cc: Lance Kujala ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/azure-dev-docs] scope doesnt exist for resource '00000003-0000-0000-c000-000000000000' (Issue #857)


I'm going to need more information about how you have set things up, as it isn't obvious from the report. Please join us on https://github.com/azure/azure-mobile-apps where we run this open-source project. There is a specific issue around MAUI.

Thanks!

**Comment by adrianhall** [comment]
Got it.  I'll be running through the MAUI demo app again this weekend, so I'll look for any issues you describe and update docs accordingly if I find anything.

#please-close

**Comment by LKujala** [comment]
I will be trying out a lot of the Maui demos. I am shifting to using Maui from winform development (last 25 years). If there is a demo app you want feedback on let me know.



Sent from my Bell Samsung device over Canada's largest network.



-------- Original message --------
From: Adrian Hall ***@***.***>
Date: 2022-08-09 9:38 a.m. (GMT-08:00)
To: MicrosoftDocs/azure-dev-docs ***@***.***>
Cc: Lance Kujala ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/azure-dev-docs] scope doesnt exist for resource '00000003-0000-0000-c000-000000000000' (Issue #857)


Got it. I'll be running through the MAUI demo app again this weekend, so I'll look for any issues you describe and update docs accordingly if I find anything.

#please-close

**Comment by diberry** [comment]
@alexwolfmsft FYI - Maui
