### ISSUE TITLE
Fails compilation due to No SDK version specified for azure-cosmosdb-spring-boot-starter in this docs

### ISSUE THREAD

**Issue by jyotsnaravikumar** [MicrosoftDocs/azure-dev-docs#86]
This sample fails to compile with the following error :

[ERROR]   
[ERROR]   The project com.microsoft:wingtiptoys:0.0.1-SNAPSHOT (/Users/wingtiptoys/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for com.microsoft.azure:azure-cosmosdb-spring-boot-starter:jar is missing. @ line 24, column 15
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

Please provide correct SDK starter version in the dependancy here:

&lt;dependency&gt;
    &lt;groupId&gt;com.microsoft.azure&lt;/groupId&gt;
    &lt;artifactId&gt;azure-cosmosdb-spring-boot-starter&lt;/artifactId&gt;
&lt;/dependency&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94a4e2b-02fa-18b2-74e3-b8f2de14ce41
* Version Independent ID: c5c5534a-b181-8750-3f22-88613bfa6fac
* Content: [How to use the Spring Boot Starter with the Azure Cosmos DB SQL API](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-cosmos-db.md)
* Service: **cosmos-db**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
Thanks, @jyotsnaravikumar ! We'll investigate.

**Comment by KarlErickson** [comment]
I reverted the incorrect fix for this, so I'm reopening.
@saragluna can you provide a correct version number? Thanks!

**Comment by saragluna** [comment]
@KarlErickson the latest version we shipped for Spring Boot 2.2.x is `2.2.5`.

**Comment by KarlErickson** [comment]
Topic was updated on 9/8 to use 2.3.3.
