### ISSUE TITLE
Azure CLI command uses en dash instead of double dash

### ISSUE THREAD

**Issue by GreenpantsDeveloper** [MicrosoftDocs/azure-dev-docs#860]
In the table for "Set Subscription", the Azure CLI command contains an en dash (–) instead of a double dash (--):

`az account set –subscription <SubscriptionId>`

This should of course be:

`az account set --subscription <SubscriptionId>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac17c09f-fe22-0eae-855f-dca9eb5b660e
* Version Independent ID: c3c47436-7e6b-7af2-03e8-ef05159813ba
* Content: [Quickstart - Choosing the right command-line tool for Azure](https://docs.microsoft.com/en-us/azure/developer/azure-cli/choose-the-right-azure-command-line-tool)
* Content Source: [articles/azure-cli/choose-the-right-azure-command-line-tool.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-cli/choose-the-right-azure-command-line-tool.md)
* Service: **azure**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by dbradish-microsoft** [comment]
This typo has been fixed in [PR 3715](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3715).  Thank you @GreenpantsDeveloper  for bringing this to our attention.
