### ISSUE TITLE
Minor issues with terraform code

### ISSUE THREAD

**Issue by vanmash** [MicrosoftDocs/azure-dev-docs#861]
terraform complains about issues with terraform code.
I unable to fix them due to lack of access to
[master](https://github.com/MicrosoftDocs/azure-dev-docs/blob/bd3e54279b50f3622c1b1c4f50c457395bba5113/terraform_samples/quickstart/201-vmss-packer-jumpbox/main.tf)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4371abd-f9cc-1ee9-1ed3-a5f0488740ce
* Version Independent ID: 14c6cf0f-ec32-15ed-cb38-8eb5860d858e
* Content: [Create an Azure virtual machine scale set from a Packer custom image by using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-scaleset-network-disks-using-packer-hcl#feedback)
* Content Source: [articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-vm-scaleset-network-disks-using-packer-hcl.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@vanmash Apologies for us missing this issue. The code has been updated and should be working. If not, please let me know and I'll investigate.
