### ISSUE TITLE
mvn compile jib:build fails with error -  I/O error for image [registry-1.docker.io/library/openjdk]

### ISSUE THREAD

**Issue by jyotsnaravikumar** [MicrosoftDocs/azure-dev-docs#87]
Hello,

I am deploying this app as per instructions on this page from Mac.

Step(5)  : mvn compile jib:build fails with the following error:

[ERROR] I/O error for image [registry-1.docker.io/library/openjdk]:
[ERROR]     Socket closed
[INFO] Executing tasks:
[INFO] [=========                     ] 30.0% complete
[INFO] &gt; pulling base image manifest
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.8.0:build (default-cli) on project gs-spring-boot-docker: Build image failed, perhaps you should make sure your credentials for 'jyowingtiptoysregistry.azurecr.io/gs-spring-boot-docker' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help: Unauthorized for jyowingtiptoysregistry.azurecr.io/gs-spring-boot-docker: 401 Unauthorized -&gt; [Help 1]
[ERROR] 

Further I verified in 
docker login 
cd /Users/{user}/.docker/config.json 
The auth and token are set correctly

"jyowingtiptoysregistry.azurecr.io": {
			"auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
			"identitytoken": "{token_value}"
		}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1bc58a-332c-ccc9-edff-47b175858a85
* Version Independent ID: 143d9272-f610-dcce-d4cf-940e5b615369
* Content: [Deploy a Spring Boot app on Kubernetes - Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes)
* Content Source: [java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@selvasingh - Would you please route to the appropriate contact and/or provide feedback?

**Comment by selvasingh** [comment]
@yucwan should review and fix

**Comment by yucwan** [comment]
@jyotsnaravikumar please install acr credential helper first, see: https://github.com/Azure/acr-docker-credential-helper

@bmitchell287 I will submit a pr to fix this.

**Comment by KarlErickson** [comment]
I've verified that this is fixed, so I'm closing.
