### ISSUE TITLE
Legacy Cloud Messaging API has Been Disabled By Default in Firebase, Additional Steps Need to be Taken to Get Server Key for Notification Hub

### ISSUE THREAD

**Issue by JacobEmmersonStovall** [MicrosoftDocs/azure-dev-docs#874]
Hello,

When going through the setting up Xamarin.Forms push notifications tutorial, I noticed that the server key section was no longer available by default in Firebase. Since Azure has API Key as the input field and since the page has not been updated since 2021, I thought that the service has changed to use the API Key. It turns out it still uses the Server Key, you now just need to take extra steps in Firebase to get the server key.

Here is an example I found online for a different service which has the steps to get the server key for new projects that have the legacy service disabled:

https://documentation.onesignal.com/docs/generate-a-google-server-api-key

It may be helpful to also talk to the dev team to change the input field name in Notification Hub to Server Key for Google Cloud Platform / Firebase because what Google calls an API Key is actually not accepted in the Notification Hub (it gives back a bad credentials error).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by adrianhall** [comment]
This is no longer a part of Azure Mobile Apps.

#please-close
