### ISSUE TITLE
More Relevant content required

### ISSUE THREAD

**Issue by pjainan** [MicrosoftDocs/azure-dev-docs#875]
I was expecting some architecture guidance to implement, store & sync offline data for mobile apps and azure services. Somehow this article only talks about generic capabilities of Azure Cosmos and Azure SQL Databases. This is not essentially required under this section. Please update with more relevant information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0863cd21-1efc-a123-d8c3-c9b21873ca54
* Version Independent ID: 62fc3700-e827-29b7-f253-7bac94f80f47
* Content: [Store, manage, and persist application data in the cloud with Visual Studio App Center and Azure services](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/data-storage?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Farchitecture%2Fbread%2Ftoc.json)
* Content Source: [articles/mobile-apps/data-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/data-storage.md)
* Service: **mobile-services**
* GitHub Login: @codemillmatt
* Microsoft Alias: **masoucou**

**Comment by codemillmatt** [comment]
Thanks @pjainan - the entire section is currently being considered for redevelopment and we'll take your comments into consideration.
