### ISSUE TITLE
Please, add support for Azure DevOps

### ISSUE THREAD

**Issue by pachecolp** [MicrosoftDocs/azure-dev-docs#876]
Documentation only mentions support for GitHub. 
Please, add support for Azure DevOps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c0acc4-c861-1e33-9169-fb04aeabb7d1
* Version Independent ID: e2c0acc4-c861-1e33-9169-fb04aeabb7d1
* Content: [Azure Developer CLI Preview FAQ](https://docs.microsoft.com/en-us/azure/developer/azure-developer-cli/faq)
* Content Source: [articles/azure-developer-cli/faq.yml](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/azure-developer-cli/faq.yml)
* Product: **azure**
* GitHub Login: @puicchan
* Microsoft Alias: **puichan**

**Comment by puicchan** [comment]
We are actively working on adding the support of Azure DevOps in azd. Please stay tuned; we will make the announcement in https://github.com/azure/azure-dev/discussions.
