### ISSUE TITLE
Link to this page needs update

### ISSUE THREAD

**Issue by FeedTheHungry** [MicrosoftDocs/azure-dev-docs#878]
Link to this page needs update
and given the title, without an argument in the url, probably should default to powshell

How to see the issue:
From page at
https://docs.microsoft.com/en-us/azure/developer/terraform/create-vm-cluster-with-infrastructure
use link titled
Configure Terraform in Azure Cloud Shell with PowerShell
brought me to
Configure Terraform in Azure Cloud Shell with Azure PowerShell
https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-powershell?tabs=bash

1/2 way down the page finally there is an option to change the script examples from bash to powershell.

The original page link needs an update to default to powershell examples from the start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a29143-0d6f-8a49-8c19-e6a48c5f9ba5
* Version Independent ID: e3c8bcff-6ae2-79d0-92c9-18fb5cd58f5b
* Content: [Configure Terraform in Azure Cloud Shell with Azure PowerShell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-powershell?tabs=bash)
* Content Source: [articles/terraform/get-started-cloud-shell-powershell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/get-started-cloud-shell-powershell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@FeedTheHungry Thanks for the feedback. We are in the process of rewriting those "getting started" articles.
