### ISSUE TITLE
It is using service principal which is security risk in Azure

### ISSUE THREAD

**Issue by jlichwa** [MicrosoftDocs/azure-dev-docs#879]
Please follow quick starts which use local identity using Azure Identity Library:
Example for java here: 
https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-java?tabs=azure-cli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [Tutorial: Read a secret from Azure Key Vault in a Spring Boot application](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@edburns can you comment here? Thanks.

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @fangjian0423 ?

**Comment by hui1110** [comment]
@KarlErickson The changes are done in [PR](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/4039), can you help close this issue?
