### ISSUE TITLE
Error:  Load key "id_rsa": invalid format

### ISSUE THREAD

**Issue by FeedTheHungry** [MicrosoftDocs/azure-dev-docs#881]
Following this tutorial worked well until the last step of connecting to the VM.  Final steps with the outputs shown:

PS C:\Users\shawn\OneDrive\documents\Projects\linux vm qs> terraform output -raw tls_private_key > id_rsa
PS C:\Users\shawn\OneDrive\documents\Projects\linux vm qs> terraform output public_ip_address
"20.232.167.55"
PS C:\Users\shawn\OneDrive\documents\Projects\linux vm qs> ssh -i id_rsa azureuser@20.232.167.55
The authenticity of host '20.232.167.55 (20.232.167.55)' can't be established.
ECDSA key fingerprint is SHA256:fAmKfkfJNaeAKkWFqhbMk2w8k0NQ5eIt4nuui18nFms.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '20.232.167.55' (ECDSA) to the list of known hosts.
Load key "id_rsa": invalid format
azureuser@20.232.167.55: Permission denied (publickey).
PS C:\Users\shawn\OneDrive\documents\Projects\linux vm qs>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3a8a34-f0f0-7aba-b45b-2c59d722b7de
* Version Independent ID: 667d19a1-ff34-3979-105c-c0a918d29707
* Content: [Quickstart - Configure a Linux virtual machine in Azure using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/create-linux-virtual-machine-with-infrastructure)
* Content Source: [articles/terraform/create-linux-virtual-machine-with-infrastructure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-linux-virtual-machine-with-infrastructure.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@FeedTheHungry Thanks for the feedback. I'm testing this now.

**Comment by TomArcherMsft** [comment]
@FeedTheHungry I've updated the article and it will be live tomorrow.
