### ISSUE TITLE
Failed to configure KeyVault property source

### ISSUE THREAD

**Issue by Lesrac** [MicrosoftDocs/azure-dev-docs#883]
The Step in "Redeploy to Azure App Service and use managed identities for Azure resources" Doesn't seem to work.[direct link](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#redeploy-to-azure-app-service-and-use-managed-identities-for-azure-resources).

Connection between the demo application and keyvault through client-id and client-secret worked fine locally and in Azure.
After the steps where a managed identity is created and should be used, the service doesn't start anymore.

Inside the keyvaults "Access policies" I can see the permission for my demo application.
The defined client-id matches the identity (principal ID) of my application.

My properties are looking like described:
spring.cloud.azure.keyvault.secret.property-source-enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].credential.client-id=<principal-id>
spring.cloud.azure.keyvault.secret.property-sources[0].credential.managed-identity-enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].profile.tenant-id=<tenant-id>
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=<keyvault-url>

Error (removed IDs):
java.lang.IllegalStateException: Failed to configure KeyVault property source
...
Caused by: reactor.core.Exceptions$ReactiveException: java.io.IOException: Server returned HTTP response code: 400 for URL: http://169.254.129.2:8081/msi/token?resource=https%3A%2F%2Fvault.azure.net&api-version=2019-08-01&client_id=<principal-id>
...
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://169.254.129.2:8081/msi/token?resource=https%3A%2F%2Fvault.azure.net&api-version=2019-08-01&client_id=<principal-id> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e25b58-811b-ec83-0251-7a641d4a7670
* Version Independent ID: 55deb14a-7feb-fcf3-95e7-5e947f5fb061
* Content: [Tutorial: Read a secret from Azure Key Vault in a Spring Boot application](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault.md)
* Service: **key-vault**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by moarychan** [comment]
Hi @Lesrac , thanks for using Spring Cloud Azure Starter KeyVault Secret!

The doc you mentioned is targeted to Service principal Authentication, you may refer to this doc [Tutorial: Use a managed identity to connect Key Vault to an Azure Spring Apps app](https://docs.microsoft.com/en-us/azure/spring-apps/tutorial-managed-identities-key-vault).

**Comment by KarlErickson** [comment]
@edburns can you take a look? Thanks.

**Comment by moarychan** [comment]
Hi @KarlErickson , I am updating this doc, PR is coming.

**Comment by moarychan** [comment]
Hi @Lesrac , Thanks for using this feature!

I have created a PR to correct this doc, please check the update in this PR https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3540 if you are in a hurry.

**Comment by Lesrac** [comment]
Hello @moarychan, Thanks for working on this.
When clicking on your link, I'm presented with the 404 Github page

**Comment by moarychan** [comment]
Hi @Lesrac , Sorry for that, I see, because this is a private repo for azure doc updates, you will see the update if the pr merged, it will be soon. @KarlErickson please help to review, thanks!.
