### ISSUE TITLE
log4j config locations

### ISSUE THREAD

**Issue by paulaustin-automutatio** [MicrosoftDocs/azure-dev-docs#885]
[Enter feedback here]
The convention for Java resources in maven is 

src/main/resources

not

src/main/resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73ba552-dd43-2d6a-77d7-a09d302f09ba
* Version Independent ID: c6d2ebf7-9223-a148-71b7-92767a9a6ac9
* Content: [Log with the Azure SDK for Java and Log4j](https://docs.microsoft.com/en-us/azure/developer/java/sdk/logging-log4j)
* Content Source: [articles/java/sdk/logging-log4j.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/sdk/logging-log4j.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **srnagar**

**Comment by KarlErickson** [comment]
@paulaustin-automutatio thanks for pointing that out! I'll get that fixed.
