### ISSUE TITLE
Server app meaning

### ISSUE THREAD

**Issue by kanilZ** [MicrosoftDocs/azure-dev-docs#887]
In Caution section of the document there is a word **server app**. Could you please help me with understanding what is mean?
Is this specific PaaS on Azure or it mean backend service? Thanks in advance for answer.
![image](https://user-images.githubusercontent.com/43847461/188116021-df9467fb-b50b-4a1b-8757-11822e283345.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fccbc7c0-7c8f-f796-5412-56c1ea5d660e
* Version Independent ID: 41a2325e-3363-d173-7779-d2517e624e7a
* Content: [Upload file to Storage - Azure](https://docs.microsoft.com/en-us/azure/developer/javascript/how-to/with-web-app/azure-function-file-upload)
* Content Source: [articles/javascript/how-to/with-web-app/azure-function-file-upload.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/javascript/how-to/with-web-app/azure-function-file-upload.md)
* Product: **azure-nodejs**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
This note has been updated and will be published today. 

```
While you can replace the _out_ binding with more code to upload the file to Blob storage, you can't replace the SDK with any _out_ binding to generate the SAS token URL. As you move from beginning code for this functionality to more complex code, you'll replace the _out_ binding with [SDK upload calls](/azure/storage/blobs/storage-blob-upload-javascript#upload-by-blob-client).
```

#please-close
