### ISSUE TITLE
az container create wrongly written

### ISSUE THREAD

**Issue by fabio-castas** [MicrosoftDocs/azure-dev-docs#890]
In the **Create Azure Container Instance with CLI** section, point 2. of [this](https://docs.microsoft.com/en-us/azure/developer/jenkins/azure-container-instances-as-jenkins-build-agent?source=recommendations) tutorial you provide an _az container create_ command which is wrong :
`az container create \
  --name my-dock \
  --resource-group my-resourcegroup \
  --ip-address Public --image jenkins/inbound-agent:latest \
  --os-type linux \
  --ports 80 \
  --command-line "jenkins-agent -url http://jenkinsserver:port <JENKINS_SECRET> <AGENT_NAME>"`

The line **`--ip-address Public --image jenkins/inbound-agent:latest \`** should be changed to **`--ip-address Public \
--image jenkins/inbound-agent:latest \`**

**Comment by TomArcherMsft** [comment]
@fabio-castas What article does this Issue pertain to?

**Comment by TomArcherMsft** [comment]
@fabio-castas  Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
