### ISSUE TITLE
Create Jenkins work agent image outdated

### ISSUE THREAD

**Issue by fabio-castas** [MicrosoftDocs/azure-dev-docs#891]
In section **Create Jenkins work agent** point 11. of [this](https://docs.microsoft.com/en-us/azure/developer/jenkins/azure-container-instances-as-jenkins-build-agent?source=recommendations) tutorial we have a preview image with the configuration requested in previous steps. 

In the **Launch method** field of that image we have the option: **Launch agent by connecting to the master. This option is no longer available in Jenkins**, we have the options: Launch agent by connecting it to the controller; Launch agent via execution of command on controller; Launch agents via SSH

The image needs to be updated.

**Comment by TomArcherMsft** [comment]
@fabio-castas What article does this Issue pertain to?

**Comment by TomArcherMsft** [comment]
@fabio-castas  Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
