### ISSUE TITLE
Is this action available? Can not find it in github marketplace

### ISSUE THREAD

**Issue by pradorodriguez** [MicrosoftDocs/azure-dev-docs#892]
Is this action available? Can not find it in github marketplace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f48a84-dcf9-e852-3f3c-703382971875
* Version Independent ID: ffe51d31-19c8-f4c3-0d31-dc154e414a59
* Content: [Use variable substitution with GitHub Actions for Azure](https://docs.microsoft.com/en-us/azure/developer/github/github-variable-substitution)
* Content Source: [articles/github/github-variable-substitution.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-variable-substitution.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Unfortunately, there's no alternative action currently. I'll work on retiring the article.
