### ISSUE TITLE
backend address pool association

### ISSUE THREAD

**Issue by RamaInfraOps** [MicrosoftDocs/azure-dev-docs#894]
[Enter feedback here]

backend address pool association
  on app_gateway/main.tf line 108, in resource "azurerm_network_interface_application_gateway_backend_address_pool_association" "nic-assoc01":
 108:   backend_address_pool_id = azurerm_application_gateway.network.backend_address_pool[0].id

Block type "backend_address_pool" is represented by a set of objects, and set
elements do not have addressable keys. To find elements matching specific
criteria, use a "for" expression with an "if" clause.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Version Independent ID: 56eb6358-d924-6565-0d8e-9229d11c30e0
* Content: [Deploy an Azure Application Gateway v2 using Terraform to direct web traffic](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-application-gateway-v2?toc=%2Fazure%2Fapplication-gateway%2Ftoc.json&bc=%2Fazure%2Fapplication-gateway%2Fbreadcrumb%2Ftoc.json)
* Content Source: [articles/terraform/deploy-application-gateway-v2.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-application-gateway-v2.md)
* Service: **terraform**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by ahipe** [comment]
I have the same issue; it happens when there are two path routes for the app.

Example app1 and app2, and if you have 2 components on TF locals. The trigger or call is in array such [0] and [1] but on the source it is not on the array form.

Conclusion the source should be in for loop with if else condition.

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
