### ISSUE TITLE
Clarification on the example code for retrieving remote data please ?

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/azure-dev-docs#896]
The documentation isn't clear on this ... 

In the code you have the following to retrieve the ToDoItems ...
![image](https://user-images.githubusercontent.com/12648793/189642426-80015b5f-1fd5-4ff8-9671-a5990b9f3ebb.png)

I wrote this and it works but ... where is the data "filtered" .. on the server or on the client after all items are retrieved ?
![image](https://user-images.githubusercontent.com/12648793/189642553-686b6332-f5a3-44dd-bc9c-0d17dd616173.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd09c5f-3fe9-e58c-69d0-fa55157524f0
* Version Independent ID: 6d02e799-215b-6d05-8c43-edde20f68280
* Content: [How to use the .NET SDK for Azure Mobile Apps](https://docs.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet?source=recommendations#query-data-from-a-remote-server)
* Content Source: [articles/mobile-apps/azure-mobile-apps/howto/client/dotnet.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/howto/client/dotnet.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by stephenhauck** [comment]
Anyone ?
I need to know if all the data is pulled and filtered on the client before I continue building my app / system.

**Comment by IEvangelist** [comment]
Hi @stephenhauck, thanks for posting this issue. It looks like this source code is open source for the SDK, so I'm taking a look to see what I can figure out. Which exact NuGet package are you using?

**Comment by stephenhauck** [comment]
The code is from the examples ... 
In the RemoteToDoService.cs it has this private variable ...
![image](https://user-images.githubusercontent.com/12648793/190199852-59a44edc-571f-48c9-a598-a48b47f9712b.png)

Then in the constructor it has the following ...
![image](https://user-images.githubusercontent.com/12648793/190200123-f7aea23a-c262-454f-9c34-f1a2a0d5dc36.png)


Then the actual call ...
![image](https://user-images.githubusercontent.com/12648793/190200293-9ccaba1d-6955-47c4-a2c8-1cc837fa8491.png)


if the "local store" is empty .. what happens ..  does it pull all of them then filter the local store ?
Does it pass only parameters to pull only the incomplete items ?

it's not clear how and when the local talks to the remote and such and how do I know the local data is stale and cannot be refreshed ?

**Comment by IEvangelist** [comment]
Hi again @stephenhauck, I think I found the answer you're looking for. There is a `QueryTranslator`, so this would mean it passes the query to the server, runs the query there (including filtering) and then returns the results to the client.

https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/src/Microsoft.Datasync.Client/Query/Linq/QueryTranslator.cs

As for answering how data is synchronized, and how to determine if things are stale. I'm not sure, and the lead dev is out for a month I heard. With that said, "offline synchronization" is most commonly opaque to the author, meaning, that you would only have stale data when the client is unable to connect to the server. Otherwise, it is always the latest data. Does that make sense?

**Comment by adrianhall** [comment]
To pile on here, there is a lot of information on this in the client HOW TO area.  The tutorial really does not go into detail - it's enough to get you to a working app.  Feel free to join us in the discussions on https://github.com/azure/azure-mobile-apps as well, where we often answer these sorts of questions.

#please-close
