### ISSUE TITLE
Is it really a good idea to store service principal credentials in the `.bashrc`?

### ISSUE THREAD

**Issue by ltalirz** [MicrosoftDocs/azure-dev-docs#898]
The default guidance for using a service principal with terraform https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-bash?tabs=bash#specify-service-principal-credentials-in-environment-variables is to place the credentials in the `~/.bashrc` startup script of the user.

I am not a security expert, so I am happy to be educated on this topic, but this recommendation looks concerning to me. 

By default, service principal credentials will be valid for 12 months. From the point of adding these lines to the `~/.bashrc` onwards, the user will thus be "logged in" as this service principal for one year. Not only can any program that knows the `ARM_...` environment variables read those credentials, it also means the user could accidentally deploy resources using this service principal when they forget that they are logged in.

It seems to me users should be warned about this, and perhaps be given a pointer to a documentation of an alternative, safer method for handling these credentials.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89ec2c-6792-5fda-8838-e4b4aac79960
* Version Independent ID: 357320a3-8d02-d834-6553-d183584e8639
* Content: [Configure Terraform in Azure Cloud Shell with Bash](https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell-bash?tabs=bash#specify-service-principal-credentials-in-environment-variables)
* Content Source: [articles/terraform/get-started-cloud-shell-bash.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/get-started-cloud-shell-bash.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@ltalirz This article (and the other "config/install" articles lists the most popular, accepted ways of authenticating. However, there are some areas that are confusing. As a result, we are rewriting the "config/install" articles to be clearer, cover best-practices, and include warnings where appropriate.

**Comment by ltalirz** [comment]
Cheers, thanks for following up in this Tom!
