### ISSUE TITLE
No pricing about Websphere on AKS

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-dev-docs#899]
There is no NO pricing about Websphere on AKS, on the [Market place](https://azuremarketplace.microsoft.com/marketplace/apps/ibm-usa-ny-armonk-hq-6275750-ibmcloud-aiops.2021-02-17_websphere_offerings_contact_me?tab=PlansAndPrice) neither.

Is it aBring-Your-Own-License offer ? ==> It assumes you have already procured the appropriate licenses with IBM and are properly licensed to run offers in Microsoft Azure ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84bd85d8-bb75-170c-d9ff-241e5b43127b
* Version Independent ID: 8c5e1eef-5ed7-ebe7-8619-1808e5936977
* Content: [What are solutions to run the IBM WebSphere family of products on Azure](https://learn.microsoft.com/en-us/azure/developer/java/ee/websphere-family)
* Content Source: [articles/java/ee/websphere-family.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/ee/websphere-family.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **rezar**

**Comment by KarlErickson** [comment]
@m-reza-rahman @edburns can you comment here? Thanks!
