### ISSUE TITLE
Broken Url

### ISSUE THREAD

**Issue by anujkarn002** [MicrosoftDocs/azure-dev-docs#9]
Update link for **Create a Container** in Prerequisites section from _https://code.visualstudio.com/python/tutorial-create-containers_ to _https://code.visualstudio.com/docs/python/tutorial-create-containers_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d72cee17-0971-1029-870f-648c4a872a4b
* Version Independent ID: a41521cd-ba6c-7609-8cb2-65942ccd38f7
* Content: [Deploy Docker containers to Azure App Service with Visual Studio Code](https://docs.microsoft.com/en-us/azure/python/tutorial-deploy-containers-01)
* Content Source: [python/tutorial-deploy-containers-01.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/tutorial-deploy-containers-01.md)
* Service: **app-service**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@anujkarn002 Thanks, I'll get that link fixed.
