### ISSUE TITLE
Good idea - what about supporting it in Functions...

### ISSUE THREAD

**Issue by Krijger** [MicrosoftDocs/azure-dev-docs#90]
Jolly good idea. Java 11 has been LTE for some time now. However, Azure Functions still only supports Java 8: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java. What is the planning for fixing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2daa25-49b5-6747-431c-0a11e4330034
* Version Independent ID: a06dd236-5f8a-8885-a5c5-83001b929ccc
* Content: [Reasons to move to Java 11 - Azure](https://docs.microsoft.com/en-us/azure/java/jdk/reasons-to-move-to-java-11#feedback)
* Content Source: [java/jdk/reasons-to-move-to-java-11.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/jdk/reasons-to-move-to-java-11.md)
* Service: **azure-java**
* GitHub Login: @dsgrieve
* Microsoft Alias: **dagrieve**

**Comment by KarlErickson** [comment]
@selvasingh can you comment? @bmitchell287 for awareness

**Comment by KarlErickson** [comment]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-java now describes support up to Java 17.
