### ISSUE TITLE
go-dep is deprecated and it should be replaced in tutorials by using modules

### ISSUE THREAD

**Issue by tuxerrante** [MicrosoftDocs/azure-dev-docs#901]
Tutorials like this one still referenced an obsolete plugin, could they be updated with a more recent tool?

https://learn.microsoft.com/en-us/azure/developer/terraform/test-modules-using-terratest#1-configure-your-environment

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a16eed4-6a1c-7bf5-1ce8-bef512ba3c43
* Version Independent ID: c44ea309-2614-62d4-da5b-3ad1ec086866
* Content: [Test Terraform modules in Azure using Terratest](https://learn.microsoft.com/en-us/azure/developer/terraform/test-modules-using-terratest)
* Content Source: [articles/terraform/test-modules-using-terratest.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/test-modules-using-terratest.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@tuxerrante Thanks for the feedback. As you mention, the article is out of date, which is why it's not in the TOC and has the version disclaimer at the top. Rewriting this article is in our backlog.

**Comment by tuxerrante** [comment]
Sorry I've seen the last update date as 05/27/2022 and I've thought it was
already under a review process.
This is a great article and I hope it won't get forgotten! :)

Il giorno lun 26 set 2022 alle ore 16:14 Tom Archer <
***@***.***> ha scritto:
