### ISSUE TITLE
documentation does not match what azure portal has

### ISSUE THREAD

**Issue by bradyguyc** [MicrosoftDocs/azure-dev-docs#902]
When registering an app the documentation has fields called user description etc... however the azure portal only shows admin description etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Version Independent ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Content: [Add authentication to your .NET MAUI app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Thanks for the feedback.  The fields do correspond, but the UI has been updated.  I'll update the wording when I next update the tutorial.  Will leave this issue open until then.

**Comment by adrianhall** [comment]
Docs have now been updated.

#please-close
