### ISSUE TITLE
Terraform Azure Virtual Desktop Incomplete

### ISSUE THREAD

**Issue by nhalstead** [MicrosoftDocs/azure-dev-docs#904]
Hello,

While going through the docs, it seems as if the Terraform example provided was incomplete.

The terraform file `main.tf` has everything set fine but the `output.tf` file has two errors.

Errors are `output "location"` and `output "AVD_user_groupname"`. They have invalid values referenced, this TF config does not provide any resource to `azurerm_resource_group.rg` (assumed to be `sh`) nor `azuread_group`. 

https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/configure-azure-virtual-desktop.md

Thanks

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
