### ISSUE TITLE
Spring cloud other then HTTP 

### ISSUE THREAD

**Issue by abhinav-jain09** [MicrosoftDocs/azure-dev-docs#905]
[Enter feedback here]

Is it possible to use the spring cloud function with other kind of trigger like 
 @ServiceBusQueueTrigger(
                    name = "usageCollector",
                    queueName = "usage.collector",
                    connection = "springCloudAzureServiceBusConnectionString") Event event,
            final ExecutionContext context) {

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59f2ae26-8728-c449-ba2d-6f870080f07e
* Version Independent ID: 9d7345f9-d9be-1056-b293-18c16e524d3e
* Content: [Getting started with Spring Cloud Function in Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure)
* Content Source: [articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/getting-started-with-spring-cloud-function-in-azure.md)
* Service: **azure-functions**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment]
@jdubois can you comment here?
@abhinav-jain09 you might want to ask your question at the [Q&A](https://learn.microsoft.com/en-us/answers/index.html) site as well.

**Comment by jdubois** [comment]
As far as I know they only provide a HTTP invoker, see https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-adapters/spring-cloud-function-adapter-azure/src/main/java/org/springframework/cloud/function/adapter/azure

**Comment by yiliuTo** [comment]
Hi @fangjian0423 please help to take a look.

**Comment by chenrujun** [comment]
Hi, @abhinav-jain09 

Can [this sample](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.4.1/aad/spring-cloud-azure-starter-active-directory-b2c/aad-b2c-resource-server) satisfy your requirement?

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @fangjian0423?
