### ISSUE TITLE
How can I query all data in my Azure Confidential Ledger?

### ISSUE THREAD

**Issue by AminAvan** [MicrosoftDocs/azure-dev-docs#907]
Hi friends,

I have a "Azure Confidential Ledger", but there is a spike on its cost, and I want to know how much data & when & by who is added to my ACL, would you please guide me how can I get this information from my ACL?

Thanks,
Amin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c507d59-970e-feae-b034-8dc27f04d6b4
* Version Independent ID: 0c608a8f-a794-1f3e-6047-24dd2108633b
* Content: [Configure your local Python environment for Azure development](https://learn.microsoft.com/en-us/azure/developer/python/configure-local-development-environment?tabs=windows%2Capt%2Ccmd#use-python-virtual-environments)
* Content Source: [articles/python/configure-local-development-environment.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/configure-local-development-environment.md)
* Product: **azure-python**
* GitHub Login: @jessmjohnson
* Microsoft Alias: **jejohn**

**Comment by AminAvan** [comment]
Hi again,

Is there any update?

Thanks

**Comment by AminAvan** [comment]
Something equivalent to "query the INFORMATION_SCHEMA" in the database, I want to know what is stored in my Azure Confidential Ledger.

Thanks

**Comment by diberry** [comment]
@AminAvan I'm looking for the correct repo to move this issue to - to get it closer to the correct service team to answer - #in-progress

**Comment by sumitis14** [comment]
@AminAvan: Could you share the name of Azure confidential ledger resource?

**Comment by diberry** [comment]
@AminAvan I believe you need to open an issue against this [FAQ](https://learn.microsoft.com/en-us/azure/confidential-ledger/faq#does-acl-offers-querying-on-attributes-other-than-the-receipt-transaction-id-) @msmbaldwin Can you help open this issue?

**Comment by msmbaldwin** [comment]
Hi, @Aminavan.  The Azure Confidential Ledger team can help you obtain this information. Please go to the Azure portal and create a support request from here: https://ms.portal.azure.com/#view/Microsoft_Azure_Support/HelpAndSupportBlade/~/overview.  ACL will contact you if they need information beyond what you provide in your ticket.  Thanks! #please-close
