### ISSUE TITLE
No support for Java 11 yet in Azure Functions...

### ISSUE THREAD

**Issue by Krijger** [MicrosoftDocs/azure-dev-docs#91]
Should be mentioned on this page. Or better - fixed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a352957d-7f26-dfe0-adaa-3541bb4ec6f6
* Version Independent ID: 9e72eaf4-d3bc-3f2a-15ee-3affde80a8d1
* Content: [Java JDKs and long-term support for Azure development](https://docs.microsoft.com/en-us/azure/java/jdk/)
* Content Source: [java/jdk/index.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/jdk/index.md)
* Service: **azure-java**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@KarlErickson - Karl would you please follow up on this one? Thanks.

**Comment by selvasingh** [comment]
@kulkarnisonia16 - please review this entry

**Comment by bmitchell287** [comment]
@kulkarnisonia16 - would you please update this open issue? Thanks
