### ISSUE TITLE
cloud-init-jenkins.txt needs updating

### ISSUE THREAD

**Issue by nj358** [MicrosoftDocs/azure-dev-docs#911]
Initially I was having issues getting Jenkins running in the VM however after investigating the issue and updated the cloud-init-jenkins.txt file as follows, all was well again.

Changes are
 - switched to _openjdk-11-jre_ from _openjdk-8-jdk_
 - added sudo to _sh -c_ command

```
#cloud-config
package_upgrade: true
runcmd:
  - sudo apt install openjdk-11-jre -y
  - wget -qO - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  - sh -c 'sudo echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - sudo apt-get update && sudo apt-get install jenkins -y
  - sudo service jenkins restart
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115cdf49-6a35-aa52-de86-3cd8d0b2e3b9
* Version Independent ID: 40a3d5ca-157b-151f-a5e7-66fe71e41104
* Content: [Get Started - Install Jenkins on an Azure Linux VM](https://learn.microsoft.com/en-us/azure/developer/jenkins/configure-on-linux-vm#feedback)
* Content Source: [articles/jenkins/configure-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/configure-on-linux-vm.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@nj358  Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
