### ISSUE TITLE
wrong info related to managed identity

### ISSUE THREAD

**Issue by rufathpe** [MicrosoftDocs/azure-dev-docs#913]
Managed identity does not utilize environmental variables. when running your code inside an instance which utilize managed identity it should invoke web request to something like http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f486180b-8851-6bf0-c3a6-8d3823312c23
* Version Independent ID: f486180b-8851-6bf0-c3a6-8d3823312c23
* Content: [Authenticating Azure-hosted apps to Azure resources with the Azure SDK for Python](https://learn.microsoft.com/en-us/azure/developer/python/sdk/authentication-azure-hosted-apps?view=azure-python&tabs=azure-portal%2Cazure-app-service)
* Content Source: [articles/python/sdk/authentication-azure-hosted-apps.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/authentication-azure-hosted-apps.md)
* Product: **azure-python**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment]
@scottaddie I'll defer to you on this. Whatever you decide should be across all lang-MI docs.

**Comment by scottaddie** [comment]
@rufathpe Are you referring to the following sentence at the bottom of the doc? 

> When the above code is run on your local workstation during local development, it will look in the environment variables...

In this context, "it" refers to the `DefaultAzureCredential`. @diberry, Can you please update the doc accordingly?

**Comment by diberry** [comment]
Content merged - will publish later today.
