### ISSUE TITLE
IsAuthenticated is always false

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-dev-docs#914]
```c#
result = await identityClient
                    .AcquireTokenSilent(Constants.Scopes, accounts.FirstOrDefault())
                    .ExecuteAsync();
```
always yields an `AuthenticationResult` with a `ClaimsPrincipal` where the `IsAuthenticated` property returns `false`.

Is this expected?

We have added the following logic to enforce `IsAuthenticated` to `true`:

```c#
var claimsIdentity = new ClaimsIdentity(claims: authenticationResult.ClaimsPrincipal.Claims, authenticationType: "nativeapp");
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
```

The documentation of `ClaimsPrincipal`'s `IsAuthenticated` property states:
true if the `AuthenticationType` property is not null or an empty string.

Reference: https://learn.microsoft.com/en-us/dotnet/api/system.security.claims.claimsidentity.isauthenticated?view=net-6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 711bca8f-ae02-ba38-c6cf-c8fac4357c57
* Version Independent ID: 711bca8f-ae02-ba38-c6cf-c8fac4357c57
* Content: [Add authentication to your Windows (WinUI3) app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/winui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
I feel that this may be a debugging situation - beyond what I can do in the dev-docs area.  Please open an issue on github.com/azure/azure-mobile-apps and we can walk through the debugging and figure out what is going on.

FWIW, each tutorial is walked through from beginning to end repeatedly for each release (something that takes me the better part of two days) to ensure that the instructions still match.  However, the frameworks also do releases and sometimes they change things that cause us to change which we can't predict.

#please-close
