### ISSUE TITLE
Error when following the instructions on this page

### ISSUE THREAD

**Issue by madmalkav** [MicrosoftDocs/azure-dev-docs#915]
Following the instructions on this page and launching the first playbook throws the following error:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on cc-9beeda7-75c987bcd7-fznn5's Python /opt/ansible/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf34277-7542-1451-31c7-a41aeabca49d
* Version Independent ID: b8a2871c-6ddf-4106-70f6-905684c329ef
* Content: [Get Started - Configure Ansible using Azure Cloud Shell](https://learn.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?tabs=ansible)
* Content Source: [articles/ansible/getting-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/getting-started-cloud-shell.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@madmalkav This issue is the result of a cloud shell bug that has been fixed.
