### ISSUE TITLE
Azure CLI example not working

### ISSUE THREAD

**Issue by briansaxbergMSFT** [MicrosoftDocs/azure-dev-docs#916]
[Enter feedback here]
when attempting this Azure CLI from Cloud Shell in a new subscription.

appName="myApp"
    az ad app create \
    --display-name $appName \
    --homepage "http://localhost/$appName" \
    --identifier-uris http://localhost/$appName

PS /home/brian> az ad app create --display-name myApp --homepage http://localhost/myApp --identifier-uris http://localhost/myApp

unrecognized arguements: --homepage http://localhost/myApp

when looking at the document https://learn.microsoft.com/en-us/cli/azure/ad/app?view=azure-cli-latest#az-ad-app-create

It shows --web-home-page-url as an optional parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3382100a-d652-0579-115e-2b8a991e244b
* Version Independent ID: a47e1d15-ea94-f224-602d-b60e18d4bf7f
* Content: [Build custom virtual machine images with GitHub Actions and Azure](https://learn.microsoft.com/en-us/azure/developer/github/build-vm-image?tabs=principal#feedback)
* Content Source: [articles/github/build-vm-image.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/build-vm-image.md)
* Service: **virtual-machines**
* Sub-service: **imaging**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
I'm sorry for the late reply but I think that this is for a different article. I'm not seeing the commands in this one. 

#please-close
