### ISSUE TITLE
Centos:7 is deprecated. Please update base image.

### ISSUE THREAD

**Issue by AndyTwiss** [MicrosoftDocs/azure-dev-docs#917]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51db2faf-908c-8022-fe37-693a800ce42a
* Version Independent ID: 41e60749-b1bb-ba0b-1b2a-100a3da5a277
* Content: [Get Started - Configure Ansible in a Docker container](https://learn.microsoft.com/en-us/azure/developer/ansible/configure-in-docker-container?tabs=azure-cli)
* Content Source: [articles/ansible/configure-in-docker-container.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/configure-in-docker-container.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@AndyTwiss Thanks for the feedback. Centos 7 is still supported until mid-2024, so I'm going to close this issue for now. However, we'll update the article shortly to reflect the correct current configuration.
