### ISSUE TITLE
Missing `.` in `docker build` command

### ISSUE THREAD

**Issue by vonWojtas** [MicrosoftDocs/azure-dev-docs#919]
Hey - there is the `.` missing at the end of the line for the docker build command.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8981cd21-b358-5fb3-0b93-f39372e5045e
* Version Independent ID: 8981cd21-b358-5fb3-0b93-f39372e5045e
* Content: [Deploy a Go web app to Azure Container Apps](https://learn.microsoft.com/en-us/azure/developer/go/deploy-container-apps)
* Content Source: [articles/go/deploy-container-apps.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/deploy-container-apps.md)
* Service: **azure**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by bobtabor-msft** [comment]
Duplicate #1300
