### ISSUE TITLE
The Github action get-keyvault-secrets is deprecated

### ISSUE THREAD

**Issue by kjellegafvelin** [MicrosoftDocs/azure-dev-docs#920]
According to https://github.com/Azure/get-keyvault-secrets the action has been deprecated and now it is recommended to use 'azure@cli' instead. A new sample describing how to get secrets from Azure Key Vault with that action would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae689e10-62a4-f724-7705-9273801217aa
* Version Independent ID: 2fa43bd0-223b-5f6e-1fca-e823d5b92ef5
* Content: [Quickstart -  Use Azure Key Vault secrets in GitHub Actions workflows](https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault)
* Content Source: [articles/github/github-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-key-vault.md)
* Service: **key-vault**
* Sub-service: **secrets**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by fleed** [comment]
The deprecated action ensured that the secrets were hidden in the logs.
Using the Azure CLI action, the user should be aware of the risk that the secrets are show in the logs.

[This blob post](https://www.aaron-powell.com/posts/2022-07-14-working-with-add-mask-and-github-actions/) describes the problem and provides a solution.

**Comment by juliakm** [comment]
#please-close

This article is no longer active.
