### ISSUE TITLE
microsoft/variable-substitution being deprecated

### ISSUE THREAD

**Issue by groxana** [MicrosoftDocs/azure-dev-docs#921]
According to the repository of the microsoft/variable-substitution this is a deprecated feature and will not be updated to use a newer version of node , github now throws deprecation notices as they will soon drop support for node v12

In short this page it will soon be useless 

https://github.com/microsoft/variable-substitution

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f48a84-dcf9-e852-3f3c-703382971875
* Version Independent ID: ffe51d31-19c8-f4c3-0d31-dc154e414a59
* Content: [Use variable substitution with GitHub Actions for Azure](https://learn.microsoft.com/en-us/azure/developer/github/github-variable-substitution)
* Content Source: [articles/github/github-variable-substitution.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-variable-substitution.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Omzig** [comment]
I created a bug to get v2 created because of the node upgrade issue.
- https://github.com/microsoft/variable-substitution/issues/43

However, i think that it is still valuable and that microsoft or github needs to consider keeping it alive.

**Comment by juliakm** [comment]
Thank you for reporting this and creating the bug. Unfortunately there's no alternative action currently. I'll work on retiring the article.

**Comment by Omzig** [comment]
@groxana, do we need to move it out into open source and figure out how the community can keep this alive?
