### ISSUE TITLE
how to read every file in a blob storage

### ISSUE THREAD

**Issue by javiermtl** [MicrosoftDocs/azure-dev-docs#923]
[Enter feedback here]

this document shows how to read a single file into a dataframe, but is possible to read every file in blob storage like /path/**?

def read_csv_to_dataframe(container_client, filename, file_delimiter= ','):
    blob_client = container_client.get_blob_client(blob=filename) # instead to read a single file, read every file inside the path

    # Retrieve extract blob file
    blob_download = blob_client.download_blob()

    # Read blob file into DataFrame
    blob_data = StringIO(blob_download.content_as_text())
    df = pd.read_csv(blob_data,delimiter=file_delimiter)
    return df
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dca29af5-577f-f189-ccc9-fba5f94542d0
* Version Independent ID: 2795772f-3648-7e0a-6eb2-9995c37e981e
* Content: [Securely ingest Azure Blob Storage data using Azure Key Vault with a Python Azure Function](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-serverless-cloud-etl-03)
* Content Source: [articles/python/tutorial-deploy-serverless-cloud-etl-03.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/tutorial-deploy-serverless-cloud-etl-03.md)
* Product: **azure-python**
* GitHub Login: @jessmjohnson
* Microsoft Alias: **jejohn**

**Comment by diberry** [comment]
@vmagelo Can you provide a link to the GitHub repo show this code even if it isn't using an Azure Function?

**Comment by vmagelo** [comment]
@diberry  - I don't know where the repo is. I'll look around. 

I believe there is partial answer just looking at the [article](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-serverless-cloud-etl-02) and the code in it. The particular function that is highlighted is in the "read_csv_to_dataframe" function that reads one blob. The "read_csv_to_dataframe" is called by the "ingest_relational_data" that work on a list of blob files and calls the "read_csv_to_dataframew" for each blob file in the list. So, a list of blobs is processed.

To control the exact path, look at the "main function" which defines the criteria for the list of blob files worked on and passed to "ingest_relational_data".

**Comment by diberry** [comment]
@tamram @normesta Can you look at this issue?

**Comment by pauljewellmsft** [comment]
@diberry I agree with @vmagelo above. The code snippet in [step 3 of this section](https://learn.microsoft.com/en-us/azure/developer/python/tutorial-deploy-serverless-cloud-etl-03#3-ingest-data-from-azure-blob-storage-with-a-serverless-function) performs a list_blobs() operation on a specified container and stores the resulting blob names in an array. Then the code iterates over that array of blob names, reads in the data from each blob and appends it to the dataframe.

So we're iterating over a given container, reading in each blob from that container, and appending it to the dataframe.

**Comment by diberry** [comment]
@javiermtl The code in the article shows how to read all blobs in a loop:

```
def return_blob_files(container_client, arg_date, std_date_format):
    start_date = datetime.strptime(arg_date, std_date_format).date() - timedelta(days=1)

    blob_files = [blob for blob in container_client.list_blobs() if blob.creation_time.date() >= start_date]

    return blob_files
```

Another example is in the [Blob Storage quickstart for python](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python?tabs=managed-identity%2Croles-azure-portal%2Csign-in-azure-cli#list-the-blobs-in-a-container): 

```
print("\nListing blobs...")

# List the blobs in the container
blob_list = container_client.list_blobs()
for blob in blob_list:
    print("\t" + blob.name)
```

Notice the [list_blobs](https://learn.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.containerclient?view=azure-python#azure-storage-blob-containerclient-list-blobs) method's first param allows you to filter on blob name. and restrict to certain blob types. 

Closing this - feel free to reopen if there is an issue with the document.

#please-close
