### ISSUE TITLE
Add authentication: OnActivityResult has moved for Android

### ISSUE THREAD

**Issue by TrueGeek** [MicrosoftDocs/azure-dev-docs#924]
In the 'Add authentication' page it says to add this code to Platforms\Android\MainActivity.cs:

```
protected override void OnActivityResult(int requestCode, [GeneratedEnum] Result resultCode, Intent data)
{
    base.OnActivityResult(requestCode, resultCode, data);
    // Return control to MSAL
    AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
}
```

OnActivityResult is no longer available as an override. I believe it should now be done as part of CreateMauiApp in MauiProgram.cs, like this:

```
		builder
			.UseMauiApp<App>()
			.UseMauiCommunityToolkit()
            .ConfigureLifecycleEvents(events =>
            {

#if ANDROID

                events.AddAndroid(android => android
                    .OnActivityResult((activity, requestCode, resultCode, data) =>
                    {

                        AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);

                    }));
#endif

            })
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Version Independent ID: 0df49cfd-7591-447c-8ec6-c97285ba93e8
* Content: [Add authentication to your .NET MAUI app](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication)
* Content Source: [articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication.md)
* Service: **mobile-services**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Thanks for the report.  The MAUI tutorials are a work in progress.  I had done the Android versions from beginning to end, but it sounds like there has been some drift.  As a result, I'll take this feedback and run it through from beginning to end again and do any updates required.

#assign "adrianhall"

**Comment by adrianhall** [comment]
... and please file an issue on github.com/azure/azure-mobile-apps for the code - I can take this into consideration as I do the tutorials.
