### ISSUE TITLE
getAccessToken is null exception

### ISSUE THREAD

**Issue by EricFunk** [MicrosoftDocs/azure-dev-docs#925]
When I try to run through the "Secure a Java web app using the Spring Boot Starter for Azure Active Directory" tutorial. I get the following exception after logging in as a user and I am not too sure why.

java.lang.NullPointerException: Cannot invoke "org.springframework.security.oauth2.core.OAuth2AccessToken.getScopes()" because the return value of "org.springframework.security.oauth2.core.endpoint.OAuth2AccessTokenResponse.getAccessToken()" is null
	at org.springframework.security.oauth2.client.endpoint.DefaultAuthorizationCodeTokenResponseClient.getTokenResponse(DefaultAuthorizationCodeTokenResponseClient.java:80) ~[spring-security-oauth2-client-5.7.3.jar:5.7.3]
...

I am also getting the same error when running through other similar tutorials such as the following one:

https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_4.4.0/aad/spring-cloud-azure-starter-active-directory/web-client-access-resource-server/aad-web-application

This ends up resulting in the following screen

![image](https://user-images.githubusercontent.com/37702478/196297082-8bca8e1b-c09c-4728-a9ae-7c546461971e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?source=recommendations)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@seanli1988 can you comment here? Thanks!

**Comment by EricFunk** [comment]
Thanks, using 4.3 resolved the the issue.
