### ISSUE TITLE
Create route table spoke1-rt in resource group spoke1-vnet-rg

### ISSUE THREAD

**Issue by felixzieger** [MicrosoftDocs/azure-dev-docs#926]
The route table `spoke1-rt` is currently being created in the resource group `hub-nva-rg`.

I would expect it to be created under resource group `spoke1-vnet-rg` because the route table is associated to the subnets `spoke1-mgmt` and `spoke1-workload` which are created under `spoke1-vnet-rg`. 

This has the advantage that creating the spokes in a different subscription becomes a matter of moving everything beneath `spoke1-vnet-rg` to the subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b701b1c8-1b00-f16d-36eb-781c3ce062e8
* Version Independent ID: 9c43b7f0-2d05-c946-7ffe-c3599b99958e
* Content: [Create a hub virtual network appliance in Azure using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/hub-spoke-hub-nva)
* Content Source: [articles/terraform/hub-spoke-hub-nva.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/hub-spoke-hub-nva.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
