### ISSUE TITLE
Feedback to the example

### ISSUE THREAD

**Issue by fratschi** [MicrosoftDocs/azure-dev-docs#928]
Hi,

first of all: This example works!

But for a reader that hasn't a deep understanding of Azure this may not work and the reader also will not understand why this example works.

In this example you use azidentity.NewDefaultAzureCredential(nil)  as credentials.
This requires a former installation, a login with az login and the creation of a service principal which hidden in the portal as app registration...

When you instead used this:

cred, err := azidentity.NewClientSecretCredential("<tenant-id>", "<client-id>", "<client-secret>", nil)  

The reader would immediatly understand that you need some kind of login to Azure to perform such an operation.

best regars
frank

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2920c493-44bd-e966-6cbc-0ea0dfc28f6e
* Version Independent ID: 2920c493-44bd-e966-6cbc-0ea0dfc28f6e
* Content: [Deploy an Azure Resource Manage Template with the Azure SDK for Go](https://learn.microsoft.com/en-us/azure/developer/go/deploy-azure-resource-manager-template)
* Content Source: [articles/go/deploy-azure-resource-manager-template.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/deploy-azure-resource-manager-template.md)
* Service: **azure**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by JimacoMS4** [comment]
Thanks! Added a section to sign in with Azure CLI to mitigate any possibility of confusion. Should publish on Monday.
