### ISSUE TITLE
Documentation Uses Outdated Firebase Code (solution provided)

### ISSUE THREAD

**Issue by Rob97** [MicrosoftDocs/azure-dev-docs#929]
The documentation shows this on step 12 of the android implementation:
```

    FirebaseInstanceId.GetInstance(Firebase.FirebaseApp.Instance)
        .GetInstanceId()
        .AddOnSuccessListener(this);

```
It should be changed to:

` FirebaseInstallations.GetInstance(Firebase.FirebaseApp.Instance).GetId().AddOnSuccessListener(this);`

They may also need to upgrade Xamarin.AndroidX.Core to the latest nuget package

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b97ae-ec64-6de9-8f02-16f91f5f9519
* Version Independent ID: d9748b97-4afb-fc97-9598-188bd460cc13
* Content: [Send push notifications to Xamarin.Forms apps using Azure Notification Hubs via a backend service](https://learn.microsoft.com/en-us/azure/developer/mobile-apps/notification-hubs-backend-service-xamarin-forms#creating-a-certificate-for-notification-hubs)
* Content Source: [articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/mobile-apps/notification-hubs-backend-service-xamarin-forms.md)
* Service: **mobile-services**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by Rob97** [comment]
PROOF:
      
      1.  https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId
      2.  https://firebase.google.com/docs/reference/android/com/google/firebase/installations/FirebaseInstallations

**Comment by Rob97** [comment]
Hello,

Unfortunately my solution compiles the program but it crashes on deployment.
I get the following issue:
Java.Lang.IllegalStateException
  Message=Default FirebaseApp is not initialized in this process com.[companyName].[App]. Make sure to call FirebaseApp.initializeApp(Context) first.

I initialize it in my code, so not quite sure why its failing:
`LoadApplication(new App());
            //
            //In the same method, conditionally call GetInstanceId on the FirebaseApp instance, right after the
            //call to Bootstrap.Begin, adding MainActivity as the IOnSuccessListener.
            if (DeviceInstallationService.NotificationsSupported)
            {
                FirebaseApp.InitializeApp(this);
                FirebaseInstallations.GetInstance(Firebase.FirebaseApp.Instance).GetId().AddOnSuccessListener(this);

            }`
            
            I can't find any logs so don't know if its a package issue or not. These are my versions:
`
    <PackageReference Include="Xamarin.AndroidX.Core">
      <Version>1.7.0.2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.MediaRouter">
      <Version>1.3.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Palette">
      <Version>1.0.0.13</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.RecyclerView">
      <Version>1.2.1.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.7.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Messaging">
      <Version>123.0.8</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2515" />
<PackageReference Include="Xamarin.GooglePlayServices.Base">
      <Version>118.1.0</Version>`
            
        
 I can't add notifications to my android app unless this is figured out :/
             
P.S. I also get this issue where it no longer automatically adds "andriod:exported = false" to the autogenerated AndriodManifest.xml for the Firebase and MSAL authentication. I have to manually type it. 

Error: android:exported needs to be explicitly specified for element <service#crc649c7568c296a16966.PushNotificationFirebaseMessagingService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by Rob97** [comment]
Hello,

I figured out the issue.

First, The code needs to be updated to this:

     if (DeviceInstallationService.NotificationsSupported)
            {
                FirebaseMessaging.Instance.GetToken().AddOnSuccessListener(this);
            
            }

And need to update the onListner Code to this:


        //Implement the IOnSuccessListener interface to retrieve and store the Firebase token.
        public void OnSuccess(Java.Lang.Object result)
       => DeviceInstallationService.Token = result.ToString();
        // OLD: result.Class.GetMethod("getToken").Invoke(result).ToString();

Also Please explicitly explain the steps on how to set the BUILD ACTION for the google-services.json file and how to make sure it is added in the project cs code as well properly. 

Finally, setting to target sdk 33 causes issues during run time of the Andriod Manifest. It doesn't add the Andriod:export = false properly to the push notifications pacakges. As a workaround, target it to sdk 30 and you shall be fine. 

Sources:
Build Action: https://stackoverflow.com/questions/44437005/xamarin-firebase-default-firebaseapp-is-not-initialized-in-this-process-t AND https://stackoverflow.com/questions/42677766/cant-set-build-action-to-googleservicejson

Andriod Export issue: https://stackoverflow.com/questions/68554294/androidexported-needs-to-be-explicitly-specified-for-activity-apps-targeting


Andriod Code Updates: https://github.com/xamcat/mobcat-samples/issues/37

**Comment by KarlErickson** [comment]
Closing this issue due to staleness. We apologize for the delayed response. If you are still encountering the problem you've described, please re-open the issue within 2 weeks and we'll take a look. Thanks!

#label:"UUF-Stale-Not Planned"
