### ISSUE TITLE
Please provide examples for connecting Azure Devops without UI steps

### ISSUE THREAD

**Issue by fardarter** [MicrosoftDocs/azure-dev-docs#931]
Please provide examples for connecting Azure Devops without UI steps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c994a242-058b-28f5-54aa-bec2484e84eb
* Version Independent ID: 2c8a21d3-8c26-0c26-a2c6-b51e7ac8db20
* Content: [Provision infrastructure with Azure deployment slots using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/provision-infrastructure-using-azure-deployment-slots)
* Content Source: [articles/terraform/provision-infrastructure-using-azure-deployment-slots.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/provision-infrastructure-using-azure-deployment-slots.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@fardarter Thanks for the feedback! I'll add this idea to our article backlog. As GitHub Issues are used to track broken articles, I'm closing this issue. However, I'll still get email notifications when you comment, so please feel free to provide any further info on what you'd like to see in the proposed article. Thanks!

**Comment by fardarter** [comment]
@TomArcherMsft What the turn around on the backlog?
