### ISSUE TITLE
The request is not properly formatted. The parameter 'scope' is duplicated.

### ISSUE THREAD

**Issue by ehogeweg** [MicrosoftDocs/azure-dev-docs#934]
Hello,

I followed the instructions to the letter but I keep getting this error message. Not sure if it is a documentation or a code issue.

`[invalid_request] AADSTS9000411: The request is not properly formatted. The parameter 'scope' is duplicated. Trace ID: 08b48c71-34aa-45a5-8cfe-cb1a042c2b00 Correlation ID: 227ada7d-3d70-423e-a033-a759a8bc9467 Timestamp: 2022-10-26 01:48:47Z`

When inspect the request in the debugger there indeed is a lot of duplication:

"<POST [https://login.microsoftonline.com/9a389f02-1111-2222-3333-6731502edb22/oauth2/v2.0/token,{grant_type=[authorization_code]](https://login.microsoftonline.com/9a389f02-1111-2222-3333-6731502edb22/oauth2/v2.0/token,%7Bgrant_type=%5Bauthorization_code%5D), code=[0.ATgAAp84mnlg102ca2cxU

gatk7bcA], redirect_uri=[http://localhost:8080/login/oauth2/code/], scope=[**openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read, openid profile offline_access https://graph.microsoft.com/User.Read]**},[Accept:"application/json;charset=UTF-8", Content-Type:"application/x-www-form-urlencoded;charset=UTF-8", Authorization:"Basic NGI0ODNiODctNWMwNS00ZjQ4LTkyNzItYmZkZmE1MWVmZWMzOjdWczhRJTdFMGVfYUZ3OVNCYk9RUVRxNHdxMGdsTzVHbkxPUGdlT2E3eQ==", x-client-SKU:"**az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", "az-sp-aad", x-client-VER:"4.4.0", "4.4.0", "4.4.0", "4.4.0", "4.4.0", "4.4.0", "4.4.0", client-request-id:"d65adf28-6f54-405c-b8f7-697ba2eee9a5", "9fd23afb-451f-4dc1-8828-27dd8dffcef0", "4e2d85bb-6e7f-4f5c-bda4-0f57d053db5d", "0b57f544-df33-42bf-9572-54e95c0861e4", "3f4131b5-96e2-4552-a17d-3001c626fc07", "b8f95157-f805-414c-98ff-87cc3ca2bdd4", "5906ca56-fbb6-44c3-a39f-07b3b91b05dc"**]>"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@saragluna @chenrujun can you take a look at this please? Thanks!

**Comment by chenrujun** [comment]
Hi, @ehogeweg 

Thanks for reaching out.
This problem is a known issue, and is tracked here: https://github.com/Azure/azure-sdk-for-java/issues/31191
It will be fixed in version **4.4.1**. 
**4.4.1** is planned to be released before **2022-11-01**.

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
The problem has been fixed. Could you please close this issue?
