### ISSUE TITLE
[demo app] - Would be nice to implement some basic error handling.

### ISSUE THREAD

**Issue by ehogeweg** [MicrosoftDocs/azure-dev-docs#940]
With the fix in spring-cloud-azure-starter-active-directory-4.5.0-beta.2 this demo app now works correctly.

It would be nice to implement some basic error handling because any error results in a non-descriptive 404. It looks like some required libraries are missing.

Thanks for the fix.

Regards,

Erwin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment]
@seanli @saragluna can you take a look? Thanks.

**Comment by yiliuTo** [comment]
Hi @chenrujun please help to take a look, thanks.

**Comment by chenrujun** [comment]
Hi, @ehogeweg 

Thank you for your suggestion.

> It would be nice to implement some basic error handling because any error results in a non-descriptive 404.

Do you mean use methods like this: https://www.baeldung.com/exception-handling-for-rest-with-spring

My current plan is to add more debug level logs. Because these errors are unexpected at development time., even if we catch these errors, it should display in logs or return to web page. 

> It looks like some required libraries are missing.

What library do you mean?

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by KarlErickson** [comment]
Sorry for the spam, folks. The "thank you" message and spurious assignment is due to a bit of incorrect configuration that I've fixed in the private repo. This will stop happening when that config change gets sync'ed to the public repo.

**Comment by saragluna** [comment]
We've added more debug logs, please reopen this issue if the logs are enough.

**Comment by saragluna** [comment]
#please-close
