### ISSUE TITLE
it is nice to see tf code for app gateway, but how do you solve this for multiple backend pools and backend settings?

### ISSUE THREAD

**Issue by vamshisiram** [MicrosoftDocs/azure-dev-docs#942]
[Enter feedback here]

it is nice to see tf code for app gateway, but how do you solve this for multiple backend pools and backend settings?

We have a need to create a app gateway with multiple backend address pools, backend settings, etc.... there are not any details or examples to this at all anywhere.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 549713ae-8a7b-270a-a758-3a439d5518fe
* Version Independent ID: a46c18ff-0092-0384-b1ed-3ec076516da4
* Content: [Create an Application Gateway Ingress Controller in Azure Kubernetes Service using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress)
* Content Source: [articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-k8s-cluster-with-aks-applicationgateway-ingress.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
Hi, @vamshisiram 

Have you had a chance to look at the samples on the [Azure Terraform GitHub samples repo(https://github.com/Azure/terraform/tree/master/quickstart)? 

Let me know if one of those works for you. 

If none of those samples helps, I'll work with the engineering team to get this article idea on our backlog to write. 

I'm going to close this issue as it's not a documentation bug on this article. However, we can both continue to communicate via the comments.

**Comment by vamshisiram** [comment]
Hi @TomArcherMsft 

I assume you are referring to https://github.com/Azure/terraform/tree/master/quickstart/101-application-gateway

I referred that and even this one just has details to create just one backend pool, but I am wanting to create multiple backend pools in a single app gateway. 

I hope they get some examples for this soon.

I see there are a lot of other resources too here, but most examples only talk about a single instance. But it is complex when it comes to creating multiple instances of a resources or multiple settings for a resource. Just like how complicated app gateway is.

Thanks for looking into this.

**Comment by TomArcherMsft** [comment]
@vamshisiram I see 3 "app gateway" articles but as you say, none seems to address the scenario you're bringing up. I'll bring this idea up and reply back here with more info in the next day or two.

**Comment by vamshisiram** [comment]
Awesome, I appreciate it.

Have a good day.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TomArcherMsft** [comment]
@vamshisiram The Terraform PM doesn't have anything planned. I emailed the App Gateway team. The PM is on vacation but should be back Monday. I'll follow up with them and get back to you.

**Comment by vamshisiram** [comment]
Thanks so much, looking forward to hearing some positive updates from them. Thanks for the follow up, much appreciated.
