### ISSUE TITLE
Terraform will fail if storage account is set to no pubic access

### ISSUE THREAD

**Issue by dunluo** [MicrosoftDocs/azure-dev-docs#944]
I noticed that when storage account public access setting is set to disabled or "From selected virtual networks and IP addresses" terraform will fail with OIDC connection. Is there any way to allow OIDC connection to access the storage account via system managed identity? I have tested with granting OIDC spn storage blob owner to the storage account, but it failed.

**Comment by KarlErickson** [comment]
Hi @luodun2020 - this issues list is intended for feedback on the documentation. You might want to ask your question on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/index.html) forum. Thanks!

**Comment by TomArcherMsft** [comment]
Closing Issue per comment from @KarlErickson and lack of comments since.
