### ISSUE TITLE
Use Key Vault secrets documentation references a deprecated github action

### ISSUE THREAD

**Issue by tomhuang12** [MicrosoftDocs/azure-dev-docs#945]
Is this document out of date? It was last updated on Oct 26 but the [get-keyvault-secrets action](https://github.com/Azure/get-keyvault-secrets) it uses is deprecated and last released 2 years ago. Which one should I follow?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae689e10-62a4-f724-7705-9273801217aa
* Version Independent ID: 2fa43bd0-223b-5f6e-1fca-e823d5b92ef5
* Content: [Quickstart -  Use Azure Key Vault secrets in GitHub Actions workflows](https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault)
* Content Source: [articles/github/github-key-vault.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-key-vault.md)
* Service: **key-vault**
* Sub-service: **secrets**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by gkohen** [comment]
It's worth mentioning that it's still not clear why:
1. We are pointing from the official Microsoft documentation to a 3rd party action supposed replacement which is supported by an individual maintainer.
2. The original action has been deprecated considering the gap and the overhead of an [alternative which is not clear](https://github.com/Azure/get-keyvault-secrets/issues/33). Could not comment on the original thread as the original repo has been archived.
3. We can't update the original as a software is never quite frozen in time and now it spews warnings: `#[warning]The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

FYI: @BALAGA-GAYATRI , @microsoftopensource, @msftgits, @rakku-ms, @romil07

**Comment by juliakm** [comment]
#please-close

This article is no longer active.
