### ISSUE TITLE
Create a Terraform configuration with a backend configuration block : Missing code ?

### ISSUE THREAD

**Issue by lojacao** [MicrosoftDocs/azure-dev-docs#946]
[Enter feedback here]

Hi 
Missing tenent, subscription, sp, and secret info in the backend section. Without it my job fail. Referenced Terraform documentation for fix.

Create a Terraform configuration with a backend configuration block 

Example:

    backend "azurerm" {
        resource_group_name  = "tfstate"
        storage_account_name = "tfstate8b07123"
        container_name       = "tfstate"
        key                  = "terraform.tfstate"
        use_azuread_auth = true
        tenant_id = "tenant_id"
        subscription_id = "subscription_id"
        client_id = "id"
        client_secret = "secret"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Store Terraform state in Azure Storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by iamNoah1** [comment]
@karl-ernstzen according to [this doc](https://developer.hashicorp.com/terraform/language/settings/backends/azurerm), it depends on the way how you authenticate against Azure. If you follow this article correctly it links to the different ways to configure terraform for authentication. However, what would probably be helpful tough, would a quick note under which circumstances you don't need to add tenent, subscription, sp, and secret info in the backend section (i.e. when using az cli to authenticate).

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
