### ISSUE TITLE
CloudBlob...

### ISSUE THREAD

**Issue by sehaswell** [MicrosoftDocs/azure-dev-docs#95]
Please could you slap a warning on this page that CloudX has been removed in newer versions of the API? It seems I've just wasted some time following this article :(
Source for removal assertion: https://github.com/Azure/azure-storage-java/issues/487
It'd be great to have some sample code for using the new version with Spring too - there's some unofficial stuff to work from on the page linked above.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5faf500d-b6e5-1059-6dc5-a87d7578bb73
* Version Independent ID: 6e522a89-82b0-6a6e-4c59-e68db879a5cf
* Content: [How to use the Spring Boot Starter with the Azure Storage API](https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage-api#feedback)
* Content Source: [java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage-api.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage-api.md)
* Service: **storage**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by KarlErickson** [comment]
@sehaswell thanks for the feedback! We'll investigate and update the topic.

**Comment by wujack778** [comment]
The new version of spring initializr has not integrated Azure Storage module, if you want start a new Azure Storage application we suggest you look this 
[link](https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage#create-an-azure-storage-account-and- blob-container-for-your-application) @sehaswell

**Comment by tamram** [comment]
@KarlErickson - can we close out this issue, since the PR has been merged?
