### ISSUE TITLE
project1

### ISSUE THREAD

**Issue by srilakshmi2506** [MicrosoftDocs/azure-dev-docs#957]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7940a432-42d4-38d1-c2eb-67500cd4b5c6
* Version Independent ID: b751c9ca-2f68-f03e-82cf-0ad529ccafd8
* Content: [Deploy apps from GitHub to Azure](https://learn.microsoft.com/en-us/azure/developer/github/deploy-to-azure)
* Content Source: [articles/github/deploy-to-azure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/deploy-to-azure.md)
* Service: **azure**
* GitHub Login: @N-Usha
* Microsoft Alias: **ushan**

**Comment by KarlErickson** [comment]
@srilakshmi2506 there's no information in this issue, so I'm closing. If you encountered a problem, please open a new issue. Thanks!
