### ISSUE TITLE
az ad sp create-for-rbac does not have a --password parameter

### ISSUE THREAD

**Issue by MikeBazMSFT** [MicrosoftDocs/azure-dev-docs#96]
The first command in the document - to create a service principal - doesn't work as the --password parameter does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a30d24-e429-8543-0ae6-5a2178a2f205
* Version Independent ID: f74c22e5-9d3a-8fbd-800e-6eda0916b2e5
* Content: [Get started with the Azure SDK for Java](https://docs.microsoft.com/en-us/azure/java/java-sdk-azure-get-started?source=docs#feedback)
* Content Source: [java/java-sdk-azure-get-started.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/java-sdk-azure-get-started.md)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **brendm**

**Comment by selvasingh** [comment]
@yaohaizh (Yaohai Zhang) should able to help

**Comment by KarlErickson** [comment]
Topic has been updated.
