### ISSUE TITLE
permissions/RBAC for using AzAPI terraform provider

### ISSUE THREAD

**Issue by Equalitism** [MicrosoftDocs/azure-dev-docs#960]
Hi,
may i know what is the permissions/rbac required to run the provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 027fca70-797d-1605-34ab-63df7f422da3
* Version Independent ID: 027fca70-797d-1605-34ab-63df7f422da3
* Content: [Overview of the Terraform AzAPI provider](https://learn.microsoft.com/en-us/azure/developer/terraform/overview-azapi-provider?source=recommendations)
* Content Source: [articles/terraform/overview-azapi-provider.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/overview-azapi-provider.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by KarlErickson** [comment]
Hi @Equalitism - you might want to ask your question on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/index.html) site as well. Thanks!

**Comment by TomArcherMsft** [comment]
@Equalitism Thanks for your feedback. The Quickstarts for AzAPI:

- [Quickstart: Deploy your first Azure resource with the AzAPI Terraform provider](https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-azapi-resource)
- [Quickstart: Deploy your first Azure update resource with the AzAPI Terraform provider](https://learn.microsoft.com/en-us/azure/developer/terraform/get-started-azapi-update-resource?tabs=azure-cli)

If these links aren't sufficient, please open an issue against the product. 

Thanks!
