### ISSUE TITLE
azurerm error on terraform script.

### ISSUE THREAD

**Issue by zeesyed** [MicrosoftDocs/azure-dev-docs#963]
I encountered this error when I was testing the Terraform Quickstart steps. 
https://github.com/hashicorp/terraform-provider-azurerm/issues/17563 
Apparently, it has been going on for a while. Maybe we can add it to the page as a pre-requisite to login using az login (see the highest voted comment on the issue for work around) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e484981e-329b-b702-070c-d36e80b9fd49
* Version Independent ID: 7e56f5c2-1e6d-d3df-5722-4c53bdf26820
* Content: [Quickstart - Create an Azure resource group using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-resource-group?tabs=azure-cli)
* Content Source: [articles/terraform/create-resource-group.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-resource-group.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@zeesyed Thanks for your feedback. All articles have now been updated to have links in the Prerequisites section to configure Terraform (including authentication).
