### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by otabz** [MicrosoftDocs/azure-dev-docs#971]
[Enter feedback here]
com.azure.security.keyvault.jca.KeyVaultLoadStoreParameter its needs explicit dependency com.azure.security.keyvault.jca thats not mentioned 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7f76c16f-4898-d212-cec3-463f1d5a3912
* Version Independent ID: 10e24fd2-aa87-b300-d4ce-1a4377f4f2fc
* Content: [Tutorial: Secure Spring Boot apps using Azure Key Vault certificates](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.md)
* Service: **key-vault**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by KarlErickson** [comment]
@edburns can you comment?

**Comment by fangjian0423** [comment]
hi @otabz 

Description is very simple, could you pls provide more details about your issue?
