### ISSUE TITLE
How to stop/reduce verbose Service Bus logs?

### ISSUE THREAD

**Issue by Lesrac** [MicrosoftDocs/azure-dev-docs#972]
Hello

Is there a way to reduce the amount of logs that are generated if I use a "@ServiceBusQueueTrigger" inside a Azure function with Spring Cloud?
e.g. I have this configured:
@ServiceBusQueueTrigger(
            name = "message",
            queueName = "handle-queue",
            connection = "serviceBusConnection"
        ) message: String

And then even before my Spring Context is loaded, the logs are hammered with such entries:
[2022-11-23T15:44:21.450Z] handle-queue-988b8f3f-da1b-4c0a-aeaa-2fd5c61f1f84-Receiver: ReceiveBatchAsync start. MessageCount = 1

Setting the root logger in logback-spring.xml to ERROR has no effect (as those logs are not happening in the Spring context).
Setting inside local.settings.json "AzureFunctionsJobHost__logging__logLevel__default": "Warning" stops those messages, but also stops all my own info logs, that I would like to have. So that can't be used.
And I haven't found any other way to affect this.

If this is the wrong place to ask this, then I'm sorry and would appreciate if you could point me to the right place, as I was unable to find a more appropriate github repo.

Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25596474-8a16-dcf6-e9a9-09ca23c905a9
* Version Independent ID: 9c1525d4-c8fe-f585-8f27-667291a58fd0
* Content: [How to use Spring Cloud Azure Stream Binder for Azure Service Bus](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus.md)
* Service: **azure-java**
* GitHub Login: @KarlErickson
* Microsoft Alias: **seal**

**Comment by KarlErickson** [comment]
Hi @Lesrac - thanks for the comment. Because this is a product question, you might want to also post it at the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/index.html) site.

**Comment by KarlErickson** [comment]
@seanli1988 can you comment?

**Comment by yiliuTo** [comment]
Hi @Lesrac how do you run the doc [How to use Spring Cloud Azure Stream Binder for Azure Service Bus](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-with-service-bus) on Azure Funtions and see the mentioned logs?

**Comment by Lesrac** [comment]
Hello @yiliuTo it's more a combination of that page and the [Azure functions](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/getting-started-with-spring-cloud-function-in-azure) one.
As @KarlErickson mentioned, I have also created a [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/1102819/azure-function-spring-cloud-how-to-stopreduce-verb.html). So if that is rather the way to go, we could also close this ticket (as it isn't specifically about a single docs page)

**Comment by yiliuTo** [comment]
Hi @Lesrac thanks for the information, and since the logs are from Azure Functions API and are not controlled by Spring as you mentioned, I think that Azure Functions team can give the answer. 
@KarlErickson , could we have a way to tag Azure Functions friends here for this question?

**Comment by Lesrac** [comment]
@yiliuTo I don't think that this is necessary. As in the linked Q&A it isn't possible to configure a specific set of logs. I'm closing this ticket.
