### ISSUE TITLE
Consume from eventhub at constant speed

### ISSUE THREAD

**Issue by Chaitragandha** [MicrosoftDocs/azure-dev-docs#977]
**I am consuming events from eventhub and sending those events to a microservice having REST API. I want to put constant tps on the API which I am hitting even though there are lot of events pending to be consumed in eventhub. 
Even if I consume in BATCH I am not achieving this as its is either size or time based and not both at a time.**

Eg. I want to send events to another API by consuming 5 events per second from each partition.

Using spring-cloud-stream-binder.
[spring-cloud-azure-stream-binder-eventhubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)

**Comment by KarlErickson** [comment]
Hi @Chaitragandha - thank you for filing this issue. You might want to also post your question to the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers) site.

**Comment by chenrujun** [comment]
#assign:@yiliuTo

**Comment by Chaitragandha** [comment]
Thanks @yiliuTo 
Created [feature request 32633](https://github.com/Azure/azure-sdk-for-java/issues/32633)

**Comment by yiliuTo** [comment]
@Chaitragandha Thanks, and could you close this issue and track your request via https://github.com/Azure/azure-sdk-for-java/issues/32633?
