### ISSUE TITLE
Typo on Terraform AVD Session Host deployment

### ISSUE THREAD

**Issue by dpantaz** [MicrosoftDocs/azure-dev-docs#978]
The code in the main.tf file at https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host fails at the line that says:

    private_ip_address_allocation = "dynamic"

It should be updated to

    private_ip_address_allocation = "Dynamic"

The values are case-sensitive.

**Comment by TomArcherMsft** [comment]
Thanks @dpantaz. I'll get this corrected.

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
