### ISSUE TITLE
[BUG] The application can't work by following the MySQL JDBC passwordless doc

### ISSUE THREAD

**Issue by saragluna** [MicrosoftDocs/azure-dev-docs#979]
By following the doc, the generated dependencies are 

```groovy
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'com.azure.spring:spring-cloud-azure-starter'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

The passwordless scenario can't work, because it requires this dependency:

```
	implementation 'com.azure.spring:spring-cloud-azure-starter-jdbc-mysql'
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d253625-4caa-d771-7bee-fee6efe49bb8
* Version Independent ID: 342215bb-0060-4702-cb78-e1821a133242
* Content: [Use Spring Data JDBC with Azure Database for MySQL](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql?tabs=passwordless&toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json#create-a-mysql-server-and-set-up-admin-user)
* Content Source: [articles/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql.md)
* Service: **mysql**
* GitHub Login: @KarlErickson
* Microsoft Alias: **bbenz**

**Comment by fangjian0423** [comment]
Waiting 6.0 GA and add dependency on Spring Initializr: https://github.com/Azure/azure-sdk-for-java/issues/30768

**Comment by fangjian0423** [comment]
Add tips for now.

Remove tips when Spring Initializr support adding `com.azure.spring:spring-cloud-azure-starter-jdbc-mysql`.

**Comment by hui1110** [comment]
The [issue](https://github.com/Azure/azure-sdk-for-java/issues/30768) is completed in [9d2e80c](https://github.com/spring-io/start.spring.io/commit/9d2e80c35a46dd92d093133aa3ecba90bd2a3828),  `com.azure.spring:spring-cloud-azure-starter-jdbc-mysql` and `com.azure.spring:spring-cloud-azure-starter-jdbc-postgresql` can be added automatically using [Spring Initializr](https://start.spring.io/).

The tip added in the [PR](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3941) has been removed.

**Comment by hui1110** [comment]
This issue has been fixed, but I can't close this issue, @KarlErickson  @saragluna  can you help?

**Comment by saragluna** [comment]
Closing this issue now.
