### ISSUE TITLE
Tutorial pipeline will fail second run

### ISSUE THREAD

**Issue by Rulqu** [MicrosoftDocs/azure-dev-docs#980]
The pipeline here will fail after first run as it creates the container on the first run but fails on the second try as it has already been created. The container create command should be put into Prerequisites section instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2156af24-387c-e4c9-1326-226a7040eca5
* Version Independent ID: 53c8b381-419c-9dd9-2f60-d9e2fd897ae4
* Content: [Tutorial - Use Azure Storage for build artifacts](https://learn.microsoft.com/en-us/azure/developer/jenkins/azure-storage-blobs-as-build-artifact-repository)
* Content Source: [articles/jenkins/azure-storage-blobs-as-build-artifact-repository.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/jenkins/azure-storage-blobs-as-build-artifact-repository.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@Rulqu  Thank you for your feedback. As our current Jenkins support is limited to security fixes, we're closing this Issue.
