### ISSUE TITLE
Error Deploying

### ISSUE THREAD

**Issue by fatpacket** [MicrosoftDocs/azure-dev-docs#981]
Cut and pasted this code exactly and get errors deploying 100% reproduceable 

Message="Operations on a server group in dropping 
state are not allowed."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f2368d54-fdac-5b21-d467-f2e47be75061
* Version Independent ID: f2368d54-fdac-5b21-d467-f2e47be75061
* Content: [Deploy a PostgreSQL Flexible Server Database using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/deploy-postgresql-flexible-server-database?tabs=azure-cli)
* Content Source: [articles/terraform/deploy-postgresql-flexible-server-database.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-postgresql-flexible-server-database.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@fatpacket I apologize for not replying to this earlier. I'm able to copy/paste directly into VS Code and run the steps without a problem. Your situation might be environmental and/or involve a bug in the product. I'm closing this Issue as the doc is corrrect so this isn't a doc bug. However, if you continue to experience this problem, please open an Issue against the product. Thanks!
