### ISSUE TITLE
AVD terraform does not work

### ISSUE THREAD

**Issue by vegarjb** [MicrosoftDocs/azure-dev-docs#982]
[Enter feedback here]
The examples for AVD simply do not work. Terraform Plan will not work because there are many undeclared variables. The tfvars is the problem

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 954f37c7-64b8-759a-6f67-20d7847a9a85
* Version Independent ID: 954f37c7-64b8-759a-6f67-20d7847a9a85
* Content: [Configure Azure Virtual Desktop Session Hosts using Terraform](https://learn.microsoft.com/en-us/azure/developer/terraform/create-avd-session-host)
* Content Source: [articles/terraform/create-avd-session-host.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/create-avd-session-host.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by vegarjb** [comment]
The Terraform code still does not run. I will work with anybody on this to recreate the issues and show what is going on.

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
