### ISSUE TITLE
Unsecure guidance

### ISSUE THREAD

**Issue by gopher194** [MicrosoftDocs/azure-dev-docs#984]
[Enter feedback here]
Hello,

When following this step in the article:
https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli#3-configure-terraform-backend-state

- 2 elements make it potentially insecure:
  1. The use of hard-coded name for
          ```
          container_name = "tfstate"
          key                     = "terraform.tfstate"
          ```
      It should be mentioned that these names can be any names compatible with the containers and blobs names. Leaving it like that can lead to a pattern scan to capture `terraform.tfstate` files from an attacker. These files contain sensitive information.
  2. The article should be updated to use secured Blob practices:
      - Azure RBAC access instead of SAS key
      - container access type = "private"
      - locked storage firewall to limited set of IPs

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Store Terraform state in Azure Storage](https://learn.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment]
@gopher194 Thanks much for the feedback. I'm currently updating that article.

**Comment by TomArcherMsft** [comment]
Unfortunately, we have not been able to review this issue in a timely manner. We sincerely apologize for the delayed response. We are closing this issue. If you feel that the problem persists, please respond to this issue with any additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.

#please-close
