### ISSUE TITLE
Need improvement of the authentication part sample code

### ISSUE THREAD

**Issue by xboxeer** [MicrosoftDocs/azure-dev-docs#988]
We interviewed couple customer and we realized that they cannot quickly understand how the azidentity works, especially where it gets the credential, what environment variable it reads to get the credential, although we provided a link to [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity) package it is still difficult for customer to quickly get the information they want
We should improve our authentication part docs in this document to quickly tell customer they can set what environment to get their application authenticated, or they can login to CLI to automatically enable authentication in their local environment

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95d28050-0839-a6c2-c37b-7d43cfbd8770
* Version Independent ID: 20e0aeb4-1141-54aa-f472-7ceb27b55ea7
* Content: [Working with the Azure SDK for Go management libraries](https://learn.microsoft.com/en-us/azure/developer/go/management-libraries)
* Content Source: [articles/go/management-libraries.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/management-libraries.md)
* Service: **azure**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by xboxeer** [comment]
cc @tadelesh @lirenhe @ArcturusZhang

**Comment by lfraleigh** [comment]
cc @scottaddie

**Comment by bobtabor-msft** [comment]
@xboxeer Hi, the Skilling org is eliminating GitHub Issues as a means of taking bug reports with docs and content requests. If this is still something we should keep on the backlog, I would absolutely love to take it on as a new project, but I need to hear that from you. It's been on the backlog a long time and no one has acted on it. Please contact me via MSFT email. Thank you!
