### ISSUE TITLE
Is there a way to use gradle?

### ISSUE THREAD

**Issue by jaimodha** [MicrosoftDocs/azure-dev-docs#99]

**Comment by KarlErickson** [comment]
@yucwan can you comment here? Thanks.

**Comment by yucwan** [comment]
Hi @jaimodha, we are mostly supporting Azure PaaS with Maven plugins at: https://github.com/microsoft/azure-maven-plugins

We just initiated a [similar project for Gradle](https://github.com/microsoft/azure-gradle-plugins), but it only [support Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-java-gradle) for now. Could you share more about what kind of gradle support you would like to see?

**Comment by KarlErickson** [comment]
@jaimodha I'm closing this but you can still reply here. Thanks!
