### ISSUE TITLE
Optimize our document to include a cheat sheet 

### ISSUE THREAD

**Issue by xboxeer** [MicrosoftDocs/azure-dev-docs#991]
This document does not tell customer how to quickly CRUD his/her azure resources, customer need to go through lot of conceptual content before they can really start CRUD their azure resources. We shall provide a cheat sheet to customers so they don't need to look for samples every where
We should also tell customer the naming patterns of our track 2 SDK so that customer won't get confused with our track 1 SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95d28050-0839-a6c2-c37b-7d43cfbd8770
* Version Independent ID: 20e0aeb4-1141-54aa-f472-7ceb27b55ea7
* Content: [Working with the Azure SDK for Go management libraries](https://learn.microsoft.com/en-us/azure/developer/go/management-libraries)
* Content Source: [articles/go/management-libraries.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/go/management-libraries.md)
* Service: **azure**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by xboxeer** [comment]
CC: @scottaddie @sandeep-sen @lfraleigh @tadelesh @lirenhe @ArcturusZhang

**Comment by xboxeer** [comment]
We shall also tell customer how to find the correct module following track 2 SDK naming pattern, feel free to contact SDK team for more details

**Comment by tadelesh** [comment]
The doc shall also tell customers distinguish data plane modules and control plane modules which always are confusing for new customers.

**Comment by bobtabor-msft** [comment]
@xboxeer @tadelesh Hi, the Skilling org is eliminating GitHub Issues as a means of taking bug reports with docs and content requests. If this is still something we should keep on the backlog, I would absolutely love to take it on as a new project, but I need to hear that from you. It's been on the backlog a long time and no one has acted on it. Please contact me via MSFT email. Thank you!
