### ISSUE TITLE
Play boook fails with the error-No module named 'azure.storage.cloudstorageaccount'

### ISSUE THREAD

**Issue by ajmalhinas** [MicrosoftDocs/azure-dev-docs#994]
The playbook given in this tutorial failed in Azure Cloud Shell. The error message was

ModuleNotFoundError: No module named 'azure.storage.cloudstorageaccount'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2ab8eeb-df97-be60-ce0a-ed619748c43e
* Version Independent ID: 4dd052d8-808b-1761-526f-2d534322f0e1
* Content: [Create a Linux virtual machines in Azure using Ansible](https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure?tabs=ansible)
* Content Source: [articles/ansible/vm-configure.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/vm-configure.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by xuzhang3** [comment]
@ajmalhinas Which ansible version and azcollection are you using. From the error message the required dependenceies are not installed or the installed path does not have the permissions.

**Comment by TomArcherMsft** [comment]
@ajmalhinas Per the dev, this issue does not appear to be documentation-related. Therefore, I'm closing the issue for now. If you continue to experience problems, please open and issue against the product.
