### ISSUE TITLE
This article points to a deprecated github action (variable substitution action)

### ISSUE THREAD

**Issue by Nikkelmann** [MicrosoftDocs/azure-dev-docs#995]
The [variable substitution action](https://github.com/microsoft/variable-substitution) has been deprecated, with no alternative given.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 31f48a84-dcf9-e852-3f3c-703382971875
* Version Independent ID: ffe51d31-19c8-f4c3-0d31-dc154e414a59
* Content: [Use variable substitution with GitHub Actions for Azure](https://learn.microsoft.com/en-us/azure/developer/github/github-variable-substitution)
* Content Source: [articles/github/github-variable-substitution.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/github/github-variable-substitution.md)
* Service: **azure**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by juliakm** [comment]
Thank you for reporting this. Unfortunately there's no alternative action currently. I'll work on retiring the article.
